### ISSUE TITLE
Genshin Impact doesn't 'remember' the status of 'using gamepad'

### ISSUE THREAD

**Issue by HuayuZhangJager** [PlayCover/PlayCover#100]
Hey~ Thanks for the great codes!

I met a little problem may need yours guys' helps:
I have to re-select the gamepad as the control method once quit and re-enter the game.

Is there any way to make the control setting in-game persistently?

**Comment by Candygoblen123** [comment]
I don't believe that there is, no. That's something that Genshin's devs would have to implement, so we can't do much on that front

**Comment by Depal1** [comment]
This is not a Playcover issue, but a Genshin issue. It has the same behaviour as in IOS.

**Comment by Depal1** [comment]
I mean to say that the same issue is present while using the app on IOS devices.

**Comment by Candygoblen123** [comment]
Issue 100 🎉
