### ISSUE TITLE
[Bug]: PlayCover is immune to settings set in GUI or editing plist file

### ISSUE THREAD

**Issue by mavethee** [PlayCover/PlayCover#1003]
### Describe the bug

Trying to change settings of any app, back-frames all my changes, that's known issue so I re-open settings to make sure certain settings were set, trying launch the game will keep previous settings (e.g when reset to the default and want to change aspect ratio to 16:10 again).

### Steps to reproduce

Use PlayCover 3.0 beta1 on macOS 14 Sonoma Beta 1 (23A5257q)
Preferably reset app settings to default, try switching back to 16:10 again or high res.

### Expected behaviour

Applied settings working correctly.

### What version of PlayCover are you using?

Nightly/beta

### What version of macOS are you using?

macOS beta (please state the specific version)

### Issue Language

- [X] Yes my issue is written in English

**Comment by MEMORIEmusic** [comment]
This is (most probably) a macOS Sonoma issue. It doesn’t occur on Ventura and below.

**Comment by mavethee** [comment]
> This is (most probably) a macOS Sonoma issue. It doesn’t occur on Ventura and below.

Well that's I've mentioned in issue description I assume, question is if it's an issue more like for Sonoma stable release to check out on or can be looked on at current state.

**Comment by mavethee** [comment]
Any ideas on potential fix or we will have to wait for official release?

**Comment by TheMoonThatRises** [comment]
Fixed in later Sonoma beta.
