### ISSUE TITLE
[Bug]：

### ISSUE THREAD

**Issue by 18621009051** [PlayCover/PlayCover#1004]
### Describe the bug

The Key Mapping editor should be able to modify the key mapping but not after upgrading to macOS14

### Steps to reproduce

<img width="84" alt="截屏2023-06-17 下午4 34 50" src="https://github.com/PlayCover/PlayCover/assets/117356777/4eba49ba-b227-4d61-97e0-ac7aaef79920">

### Expected behaviour

I want to change the key mapping

### What version of PlayCover are you using?

Nightly/beta

### What version of macOS are you using?

macOS beta (please state the specific version)

### Issue Language

- [X] Yes my issue is written in English

**Comment by yeejian-tan** [comment]
Please enter a title and state explicitly the version of your MacOS.

**Comment by Oblivious27** [comment]
Same problem happened on Macbook air M2 16GB , 
System: Mac OS 14.0 Sonoma Developer beta
version of PlayCover : Nightly/Beta, 3.0
Bug : Command + K to call the key mapping is fine, but any key input from keyboard fails , while the left and right click of mouse is ok to key map.
Others: While input keys for key mapping ,I heard the system sound of key input. This sound is often heard when the key is not inputting in the active window.

**Comment by TheMoonThatRises** [comment]
Closing in favour of #1048.
