### ISSUE TITLE
[Bug]: Custom resolution issue for portrait apps (Ventura)

### ISSUE THREAD

**Issue by a4840639** [PlayCover/PlayCover#1006]
### Describe the bug

I was able to use custom resolution for portrait apps on Monterey.
However, after upgrading to Ventura today, I found out specifying any custom portrait resolution (like 720*1280) would make the actual content offset. The  only thing that seems to be working for these apps is to choose the app original resolution and tick the "fix windows issues" box.
<img width="703" alt="Screenshot 2023-06-18 at 1 14 54 AM" src="https://github.com/PlayCover/PlayCover/assets/12200912/737f9128-21f7-4b3d-a43e-4bbda1d68dc2">
<img width="666" alt="Screenshot 2023-06-18 at 1 15 06 AM" src="https://github.com/PlayCover/PlayCover/assets/12200912/4deb36aa-f134-4530-82bc-9a7bb6446474">
<img width="666" alt="Screenshot 2023-06-18 at 1 15 28 AM" src="https://github.com/PlayCover/PlayCover/assets/12200912/f1f53e4f-96cb-49b3-99fc-c7aa14ec75ec">

### Steps to reproduce

install any apps that is intended to work in portrait mode and set a custom resolution

### Expected behaviour

App should display correctly, like on Montrey

### What version of PlayCover are you using?

2.0.4

### What version of macOS are you using?

Ventura (macOS 13)

### Issue Language

- [X] Yes my issue is written in English

**Comment by a4840639** [comment]
I tried 1.1.1 and found out it actually handles portrait apps reasonably
The only issue is it is trying to display an extremely oversized window on my external display
<img width="1920" alt="Screenshot 2023-06-18 at 1 27 22 AM (2)" src="https://github.com/PlayCover/PlayCover/assets/12200912/4eb0dab0-67f2-4fae-b2cb-139e8373312e">

**Comment by TheMoonThatRises** [comment]
Update to the latest version (stale).

**Comment by crowdigit** [comment]
@TheMoonThatRises I can reproduce this issue on latest version (3.0.0-beta, 2.0.5) and only 1.1.1 handles portrait app well.

**Comment by crowdigit** [comment]
Launching app on 1.1.1 works well as described, but on 2 and 3-beta, it displays as such
<img width="959" alt="Screenshot 2023-10-21 at 4 28 18 AM" src="https://github.com/PlayCover/PlayCover/assets/87285844/9049c9b6-75e6-4fbf-8c42-fb36125d924f">

With custom portrait resolution
<img width="959" alt="Screenshot 2023-10-21 at 4 30 06 AM" src="https://github.com/PlayCover/PlayCover/assets/87285844/fccef408-18ea-495b-9757-37de8f70bd41">

Tested with/without "fix window display issues" but has no effect. I'm using Ventura too.
