### ISSUE TITLE
[Bug]：MacOS 13 Display Error

### ISSUE THREAD

**Issue by HotSharkkkk** [PlayCover/PlayCover#1008]
### Describe the bug

The system window of MacOS 13 and later versions cannot be displayed normally, the length and width are reversed, and the window cannot be scaled normally to display all

### Steps to reproduce

normal operation

### Expected behaviour

Window orientation and scaling are normal

### What version of PlayCover are you using?

Nightly/beta

### What version of macOS are you using?

Ventura (macOS 13)

### Issue Language

- [X] Yes my issue is written in English

**Comment by TheMoonThatRises** [comment]
Update to the latest version.
