### ISSUE TITLE
[Bug]: Crash on playing with DualSense 5 (Honkai Star Rail)

### ISSUE THREAD

**Issue by Disinterpreter** [PlayCover/PlayCover#1011]
### Describe the bug

Honkai Star Rail crash on playing with DualSense 5.
I installed Honkai Star Rail, connected my DS5, in setting change sensor mode to GamePad. The game reopened and crashed.
PlayCover version: 3.0.0-beta
MacOS version: 13.4

### Steps to reproduce

1. Install the game (Honkai Star Rail in my case)
2. Connect the DualSense 5
3. Launch the game and log in into the world
4. Open the settings -> last tab of settings -> first tab change type.
5. The game will reloading
6. After reloading try to login, you've get crash.

### Expected behaviour

Comfy gaming with gamepad in-game gamepad feature.

### Crash log

```shell
https://pastebin.com/Bxu6kUPf
```

### What version of PlayCover are you using?

Nightly/beta

### What version of macOS are you using?

Monterey (macOS 12)

### Issue Language

- [X] Yes my issue is written in English

**Comment by TAY0123** [comment]
disable keymapping in playcover seem bypassed the issue

**Comment by TheMoonThatRises** [comment]
Should be fixed with PR https://github.com/PlayCover/PlayTools/pull/120 by @XuYicong.
