### ISSUE TITLE
Sharing a single Genshin Impact installation between multiple macOS users

### ISSUE THREAD

**Issue by taupter** [PlayCover/PlayCover#102]
### Discussed in https://github.com/PlayCover/PlayCover/discussions/101

<div type='discussions-op-text'>

<sup>Originally posted by **taupter** July 26, 2022</sup>
Hello. I have a question. I have a Macbook Air M1, with PlayCover 1.0.7 installed and Genshin Impact 2.8.0 running on it. I play the game, but my daughter wants to play too on the same Mac. Due to the problems we already know, we need to do all that reboot magic to log in GI, but every time we need to change the GI user it needs to go through the reboot/safety mode cycle. One alternative I was contemplating was to make her use GI on her Mac's user account, but it would imply reinstalling and redownloading everything, making two copies of the full GI data on the space-starving internal SSD (each one in its own /Users/<user>/Library/Containers/com.miHoYo.GenshinImpact). Is there a way to download/install GI to a shared folder, so two different users could enjoy playing GI on their respective user accounts, without doubling the download and storage?</div>

**Comment by JoseMoreville** [comment]
This was already answered on discussion...
