### ISSUE TITLE
[Feature]: Custom controller keymapping

### ISSUE THREAD

**Issue by PaleNeutron** [PlayCover/PlayCover#1021]
### Is your feature request related to a problem?

I found current controller mode will use a fixed key mapping（Q=> X button, Space => A button, etc)

### Describe the solution you'd like

Change this keyboard to controller mapping by schema file，or I think it is possible now but undocumented？

### Anything else?

Nothing

### Issue Language

- [X] Yes my issue is written in English

**Comment by TheMoonThatRises** [comment]
These features should be implemented in newer PlayCover versions.
