### ISSUE TITLE
[Bug]: Github Actions has been failing to notarize DMG since nightly build #393

### ISSUE THREAD

**Issue by yeejian-tan** [PlayCover/PlayCover#1028]
### Describe the bug

As the title.

### Steps to reproduce

Check builds from https://github.com/PlayCover/PlayCover/actions/runs/5315526120 onwards. Still exists in yesterday's build.

### Expected behaviour

Signs the package properly for running.

### Crash log

NA

### What version of PlayCover are you using?

Nightly

### What version of macOS are you using?

NA

### Issue Language

- [X] Yes my issue is written in English

**Comment by TheMoonThatRises** [comment]
Yeah, we need to update the signing account.
