### ISSUE TITLE
[Bug]: Popup dialog is empty on MacOS 14

### ISSUE THREAD

**Issue by yeejian-tan** [PlayCover/PlayCover#1029]
### Describe the bug

The following screenshot was taken while installing a new IPA (namely Genshin Impact 3.8.0, might be irrelevant):

![image](https://github.com/PlayCover/PlayCover/assets/17807016/f57049eb-00e6-4d78-af9e-aeae821d7ab6)

The popup was weirdly sized and contains no text at all. The installation completed successfully, nonetheless.

I am not sure if it is a compatibility issue with MacOS 14.0. Run on nightly build 392 (the latest I could run without facing the notarization problem #1028 .

### Steps to reproduce

Perform a version update to an existing app.

### Expected behaviour

Dialog showing progress or whatever it should.

### What version of PlayCover are you using?

Nightly/beta

### What version of macOS are you using?

macOS beta (please state the specific version)

### Issue Language

- [X] Yes my issue is written in English

**Comment by Saibejjani** [comment]
same happend to me as well. But it's gone when i installed more than 3 apps

**Comment by TheMoonThatRises** [comment]
Can't reproduce this issue on the latest developer beta (23A5337a).
