### ISSUE TITLE
[Bug]: Resolution 2560x1080 appears part of the picture is not displayed!

### ISSUE THREAD

**Issue by zhugunick** [PlayCover/PlayCover#1031]
### Describe the bug

When I adjust the genshin screen to 2560x1080, part of the screen character information is completely black, how to solve this problem, (the normal resolution does not have this situation, what is the reason) I asked my friends who also use playcover to play genshin , he also adjusted to 2560x1080 and this did not happen!（2.04&3.0beta&night）

### Steps to reproduce

If you change the default resolution to 2560x1080, there is a probability that the screen will not be displayed.

### Expected behaviour

none

### Crash log

```shell
none
```

### What version of PlayCover are you using?

Nightly/beta

### What version of macOS are you using?

Monterey (macOS 12)

### Issue Language

- [X] Yes my issue is written in English

**Comment by TheMoonThatRises** [comment]
Update to the MacOS Ventura. MacOS Monterey is known to have some bugs with PlayCover.

**Comment by zhugunick** [comment]
![Uploading 95H[[TW@J)TLI@M595TNATH.png…]()
