### ISSUE TITLE
[Bug]: Genshin - Parameter error - Macbook m1 - playcover 2.0.5

### ISSUE THREAD

**Issue by Doan1312** [PlayCover/PlayCover#1033]
### Describe the bug

Describe the bug
Parameter error

### Steps to reproduce

Try to login in account

### Expected behaviour

Expected behaviour
 it's giving a "Parameter error" while logging in with another account

### What version of PlayCover are you using?

2.0.4

### What version of macOS are you using?

Ventura (macOS 13)

### Issue Language

- [X] Yes my issue is written in English

**Comment by amirsaam** [comment]
Read the docs
https://docs.playcover.io/getting_started/troubleshoot_login
