### ISSUE TITLE
[App Support]: 

### ISSUE THREAD

**Issue by sawak0** [PlayCover/PlayCover#1049]
### App Store link

playcover genshin impact

### Current issues

- [ ] App fails to install
- [X] App fails to open
- [ ] App crashes randomly during usage
- [ ] App experiences graphical issues or broken UI
- [ ] App fails to connect to servers
- [ ] Other

### More details

it says Genshin Impact quit unexpectedly.

### Issue Language

- [X] Yes my issue is written in English

**Comment by TheMoonThatRises** [comment]
Lower the resolution of Genshin Impact in PlayCover (left click Genshin in PlayCover->Graphics->change it to 1080p). Also, next time add more information please.
