### ISSUE TITLE
Octopath crashes at loading data

### ISSUE THREAD

**Issue by lordfriky** [PlayCover/PlayCover#105]
I'm not really sure how am I supposed to submit this issue, but judging by the other ones with the `game-support` tag I'm just gonna paste the report here. Lmk if you need something else (I have SIP enabled btw).

[octopath-report.txt](https://github.com/PlayCover/PlayCover/files/9205286/octopath-report.txt)

**Comment by IsaacMarovitz** [comment]
Please try again in PlayCover 1.1.1 and with SIP disabled

**Comment by Dong-Lin** [comment]
> Please try again in PlayCover 1.1.1 and with SIP disabled

Try with no luck, maybe due to their special game protection

**Comment by IsaacMarovitz** [comment]
Stale/Old PlayCover Version
