### ISSUE TITLE
[Game Support]: Arena Breakout

### ISSUE THREAD

**Issue by gajosadrian** [PlayCover/PlayCover#1051]
### App Store link

https://apps.apple.com/us/app/arena-breakout/id1560765304

### Current issues

- [ ] Game fails to install
- [X] Game fails to open
- [ ] Game crashes randomly during gameplay
- [ ] Game does not work with keymapping
- [ ] Game experiences graphical issues or broken UI
- [X] Game fails to connect to servers or complete download

### More details

The game freezes at the login menu after launching. I did the steps in https://docs.playcover.io/getting_started/troubleshoot_login and it still doesn't work.

Mac mini
Apple M2
OS 13.4.1

### Issue Language

- [X] Yes my issue is written in English

**Comment by lakarpusky** [comment]
Same the login form never shows up, it stays forever with the background cinematic

Mac Pro M1
OS 13.4.1 
PlayCover 2.0.5 (291)

**Comment by lukaswis** [comment]
> Same the login form never shows up, it stays forever with the background cinematic
> 
> Mac Pro M1 OS 13.4.1 PlayCover 2.0.5 (291)

This happens to me too is there any ways to fix it?

**Comment by TheMoonThatRises** [comment]
Closing in favour of #1201.

**Comment by sazidrayhan0** [comment]
has this issue been solved?
