### ISSUE TITLE
[Bug]: Keymap cannot map keys on the keyboard

### ISSUE THREAD

**Issue by violetweir** [PlayCover/PlayCover#1054]
### Describe the bug

I just played Genshin Impact today because there is a new key position that needs to be mapped. After opening the mapping and creating a key mapping result, there is no way to enter keys such as q and c.

### Steps to reproduce

NO

### Expected behaviour

NO

### What version of PlayCover are you using?

Nightly/beta

### What version of macOS are you using?

Monterey (macOS 12)

### Issue Language

- [X] Yes my issue is written in English

**Comment by MEMORIEmusic** [comment]
Try updating to macOS Ventura. Keymapping problems were fixed with the release of macOS 13.1, so try updating to the latest version of macOS.

Also, make sure you are using [latest nightly build](https://github.com/PlayCover/PlayCover/actions/runs/5638250354)

**Comment by xiaokang00010** [comment]
> 

I met the same problem on macOS Sonoma 14 Beta 3 with PlayCover version 3.0.0(427).
Maybe it's not a matter of macOS version ;-)

**Comment by MEMORIEmusic** [comment]
> I met the same problem on macOS Sonoma 14 Beta 3 with PlayCover version 3.0.0(427).
> Maybe it's not a matter of macOS version ;-)

Yes. macOS Sonoma beta has broken key mapping, but we won’t be fixing it until Sonoma’s official release.

**Comment by TheMoonThatRises** [comment]
Update to MacOS Ventura.
