### ISSUE TITLE
[Bug]: WASD not working in BATTLEGROUNDS MOBILE INDIA

### ISSUE THREAD

**Issue by virendra531** [PlayCover/PlayCover#1063]
### Describe the bug

WASD used for movement is not working
you have to press two key to make it work (like if you press w and d than d movement works)

i am using MacOS 14.0 Beta (23A5301g) and playcover Version 3.0.0 (378)

### Steps to reproduce

Install IPA for [BATTLEGROUNDS MOBILE INDIA ](https://decrypt.day/integrated/playcover/ddc67d9d-c86d-47ee-83da-1ca604adf8d4)
Open App

### Expected behaviour

WASD should work without pressing two key

### What version of PlayCover are you using?

Nightly/beta

### What version of macOS are you using?

macOS beta (please state the specific version)

### Issue Language

- [X] Yes my issue is written in English

**Comment by MEMORIEmusic** [comment]
Keymapping is broken on macOS Sonoma Beta.
Please downgrade to macOS Ventura.

**Comment by TheMoonThatRises** [comment]
First, try updating to the latest MacOS Beta. Then, make sure that the WASD pad covers the movement controls properly, with the correct size and position.

**Comment by saurabhnemade** [comment]
@TheMoonThatRises 

Here is how it is with latest MacOS 14.2.1 (23C71). 

Definitely something is off. I have only 1 assignment for w key but it never gets pressed as standalone. You can see the behaviour in the video below. it sometimes work but only when pressed with another key. 

Cannot upload more than 10 mb so uploading it to another video sharing 

https://filebin.net/mifeki8i1tvsv5zg

**Comment by arjunmeena344** [comment]
bhai mero ko ipa file dal de pls
