### ISSUE TITLE
[Feature]: GPS location support

### ISSUE THREAD

**Issue by ponponben** [PlayCover/PlayCover#1064]
### Is your feature request related to a problem?

When I first run the Gsland app, a popup window shows GPS permission request. When I select "allow", but the GPS function not working. At second time running, the popup not showing anymore, and GPS function still not working.

### Describe the solution you'd like

If yes, add the GPS support, Thank you.

### Anything else?

<img width="375" alt="截圖 2023-08-02 下午2 18 25" src="https://github.com/PlayCover/PlayCover/assets/57739522/6041285e-e1fd-44dc-9e0c-803b4199a894">

### Issue Language

- [x] Yes my issue is written in English

**Comment by ohaiibuzzle** [comment]
It makes total sense. Your Mac doesn't have GPS hardware. The only reason it knows your location is through nearby devices

**Comment by ponponben** [comment]
> It makes total sense. Your Mac doesn't have GPS hardware. The only reason it knows your location is through nearby devices

Seems macOS Ventura 13.5 broke location services. Waitting for 13.5.1 version to check this problem.

**Comment by Depal1** [comment]
Closed in favour of https://github.com/PlayCover/PlayCover/issues/1373.
