### ISSUE TITLE
[Game Support]: How to customize my Key Mapping?

### ISSUE THREAD

**Issue by DexterDreeeam** [PlayCover/PlayCover#1065]
### App Store link

NA

### Current issues

- [ ] Game fails to install
- [ ] Game fails to open
- [ ] Game crashes randomly during gameplay
- [ ] Game does not work with keymapping
- [ ] Game experiences graphical issues or broken UI
- [ ] Game fails to connect to servers or complete download

### More details

Hi, there,

So gald there is a project like this. I think it is what I am looking for.

But I have to play my favorite game with my custom Key Mapping settings (I know some normal default Key Mapping won't meet my requirements)

Since I see Play-Tool is out of maintain. Just want to confirm,

I think you don't plan to add some powerful 'Script' key into PlayCover, right?

### Issue Language

- [X] Yes my issue is written in English

**Comment by DexterDreeeam** [comment]
Actually I wanna try to do Script key function.
Just want to confirm there is no this plan from your side.
(Don't want to pay repeat effort ^ ^# )

**Comment by TheMoonThatRises** [comment]
No. See #687 and #378.
