### ISSUE TITLE
[Bug]: WASD bad working in Last Day on Earth

### ISSUE THREAD

**Issue by yar0m4** [PlayCover/PlayCover#1067]
### Describe the bug

WASD used for movement is not working. But I can press, for example, button "d" and after it press button "a", and then my character will go to the left. It's the same with the rest of the WASD.

### Steps to reproduce

- Install IPA Last Day on Earth: https://decrypt.day/app/id1241932094
- Open App
- Making Keymaps
- Play

### Expected behaviour

Press only button "d" = move my person right, press only button "a" = move my person left. It's the same with the rest of the WASD.

### Crash log

```shell
No response
```

### What version of PlayCover are you using?

Nightly/beta

### What version of macOS are you using?

Ventura (macOS 13)

### Issue Language

- [X] Yes my issue is written in English

**Comment by MEMORIEmusic** [comment]
Increase the size of WASD until required (select the D-Pad and then press `command +`)

**Comment by yar0m4** [comment]
> Increase the size of WASD until required (select the D-Pad and then press `command +`)

Does not help. Tried increasing and decreasing the size of the joystick

**Comment by MEMORIEmusic** [comment]
> > Increase the size of WASD until required (select the D-Pad and then press `command +`)
> 
> Does not help. Tried increasing and decreasing the size of the joystick

try making it like half of the screen(i forgot what exactly, but making it that big enables another feature)

edit: something like this:

<img width="1577" alt="Screenshot 2023-08-05 at 20 07 44" src="https://github.com/PlayCover/PlayCover/assets/79436281/37f68104-be48-430f-89ca-4725d76d9063">

**Comment by yar0m4** [comment]
> > > Increase the size of WASD until required (select the D-Pad and then press `command +`)
> > 
> > 
> > Does not help. Tried increasing and decreasing the size of the joystick
> 
> try making it like half of the screen(i forgot what exactly, but making it that big enables another feature)
> 
> edit: something like this:
> 
> <img alt="Screenshot 2023-08-05 at 20 07 44" width="1577" src="https://user-images.githubusercontent.com/79436281/258591035-37f68104-be48-430f-89ca-4725d76d9063.png">

Wow, that really helped. Thank you very much!
