### ISSUE TITLE
[Bug]: Controller crashing Games with inputs

### ISSUE THREAD

**Issue by Max529Khk** [PlayCover/PlayCover#1068]
### Describe the bug

System: Mac OS Ventura, 13.5 (22G74)
PlayCover build: 3.0.0 Beta

I'm using a DualSense Controller.

Any controller input  _**in the menu**_ of any game crashes the game.
Tested with Azur Lane (for the sake of testing) and Honkai Star Rail.
Update: However, after trying 5-10 times, it doesn't crash with every instance now. Really weird. It seems like the beta builds still have issues with controllers.

### Steps to reproduce

(most) Examples for Star Rail:

in the menu

Press any button  -> Game crashes
Move a stick -> Game crashes

in-game

pressing touchpad can also crash the game

### Expected behaviour

Controller should be detected and working as intended. I have to manually select the controller settings in HSR.

### What version of PlayCover are you using?

Nightly/beta

### What version of macOS are you using?

Ventura (macOS 13)

### Issue Language

- [X] Yes my issue is written in English

**Comment by MEMORIEmusic** [comment]
Right click the game -> settings -> disable/uncheck keymapping 
That’ll fix the issue

**Comment by Max529Khk** [comment]
Thanks! I'll test it asap.

**Comment by Boomspring** [comment]
Same behaviour on a different game (HI3), disabling keymapping fixed it.

**Comment by SeverusBlack** [comment]
> Right click the game -> settings -> disable/uncheck keymapping
> That’ll fix the issue

Works like a charm. Thank you!
