### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by WiktorOlf** [PlayCover/PlayCover#1073]
### Describe the bug

When I log into Genshin Impact 4.0.0 after disabling SIP and then re enable it, the logged in account disappears. If I disable SIP again it reappears making the game unplayable with SIP enabled.

[My Playcover version shows 2.0.5 but the selection only has version 2.0.4]

### Steps to reproduce

1. Log into Genshin Impact 4.0.0 after disabling SIP.
2. Quit the game and re-enable SIP.
3. Reopen the game and the account login screen appears and the logged-in account has disappeared.
4. Disable SIP again and reopen.
5. Logged-in account reappears.

### Expected behaviour

Before 4.0.0 the account used to stay available after re-enabling SIP.

### What version of PlayCover are you using?

2.0.4

### What version of macOS are you using?

Monterey (macOS 12)

### Issue Language

- [X] Yes my issue is written in English

**Comment by ohaiibuzzle** [comment]
@WiktorOlf Just use the 3.0 beta, it is *mostly* stable and doesn't require SIP trickery to login
