### ISSUE TITLE
[Bug]: can not change window size

### ISSUE THREAD

**Issue by yue-yin** [PlayCover/PlayCover#1075]
### Describe the bug

try to change setting -> graphics, but window size did not change
application is: https://decrypt.day/app/id982115698
I used playcover: Version 2.0.5 (291)
macOS: 13.3.1 (ventura) 

### Steps to reproduce

when open it

### Expected behaviour

it blocked by wrong window size, can not login

### What version of PlayCover are you using?

2.0.4

### What version of macOS are you using?

Ventura (macOS 13)

### Issue Language

- [X] Yes my issue is written in English

**Comment by yue-yin** [comment]
I have tested application: https://decrypt.day/app/id741292507
this one can work, even it can not set windows right, but I can modify it manually.
I also tried rotate display area, it does not work.

**Comment by ohaiibuzzle** [comment]
@yue-yin Makes sense. Dynamic window resize (App Default mode) is only possible if the app itself is built expecting it (eg. iPadOS apps with resizable window)

**Comment by TheMoonThatRises** [comment]
You don't need to manually resize the window. You can fix the window size and login by changing the resolution to app default and enabling `Fix window display issues`.
