### ISSUE TITLE
[Game Support]: Garena Undawn

### ISSUE THREAD

**Issue by oojw** [PlayCover/PlayCover#1076]
### App Store link

https://apps.apple.com/sg/app/garena-undawn/id1538722240

### Current issues

- [ ] Game fails to install
- [ ] Game fails to open
- [ ] Game crashes randomly during gameplay
- [X] Game does not work with keymapping
- [X] Game experiences graphical issues or broken UI
- [ ] Game fails to connect to servers or complete download

### More details

Hi I am able to install and run Garena Undawn on Playcover, however there are some issues with the key mapping (I suppose)

The WASD does not register efficiently making it hard to navigate, is this an issue with the game-keymapping or is it the play cover build? Thank you in advance

### Issue Language

- [X] Yes my issue is written in English

**Comment by ohaiibuzzle** [comment]
This is silly but just make the WASD obscenely big (even bigger than the actual area).

**Comment by MEMORIEmusic** [comment]
make the WASD half the size of the screen like...super massive

**Comment by oojw** [comment]
Yup I tried, but seems like the movement only triggers if two (of the WASD) are keyed
For example, if I want to move forward, I had to hold down either one of ASD, then key W 
Is this normal for key mapping?

**Comment by oojw** [comment]
Ok thank you it works
