### ISSUE TITLE
[Feature]: Multi-Touch Toggle

### ISSUE THREAD

**Issue by rlarhsid** [PlayCover/PlayCover#1078]
### Is your feature request related to a problem?

When I play games on my mac, clicking the screen via mouse was too cumbersome. So I always turned on the multi-touch feature, but the touch feature only seems to work when the option key is pressed.

### Describe the solution you'd like

I'd like to give two options to the multi-touch feature:
1. the legacy (it works only when option key is pressed)
2. new one (you can toggle the feature by pressing the option key)

### Anything else?

<img width="831" alt="image" src="https://github.com/PlayCover/PlayCover/assets/131584438/09388321-9a4a-450c-8492-0102475ce419">

### Issue Language

- [X] Yes my issue is written in English

**Comment by ohaiibuzzle** [comment]
@rlarhsid Unfortunately this is a macOS feature and not PlayCover's, so the only thing you can do is literally just deal with it or beg Apple to fix it
