### ISSUE TITLE
[Bug]: Clicking the image in Details of Wish in Genshin makes the screen go blank

### ISSUE THREAD

**Issue by bbajr** [PlayCover/PlayCover#1080]
### Describe the bug

In Genshin Impact Event Wish 'Conjuring Chiaroscuro' details page, I clicked on Lyney's image.
The screen went blank and I could not return back. 
Rotating the page did not help. I had to quit the game and go back.

### Steps to reproduce

In Genshin Impact,
1. Select wish icon
2. Click on Details Button
3. Click the 5 star character's image or 4 star character's image
4. The screen goes blank. 

### Expected behaviour

Nothing should happen.

### What version of PlayCover are you using?

Nightly/beta

### What version of macOS are you using?

Ventura (macOS 13)

### Issue Language

- [X] Yes my issue is written in English

**Comment by TheMoonThatRises** [comment]
Try lowering the resolution in PlayCover's settings (left click the app in PlayCover->Settings->Graphics).
