### ISSUE TITLE
[App Support]: congstar

### ISSUE THREAD

**Issue by wohfab** [PlayCover/PlayCover#1082]
### App Store link

https://apps.apple.com/de/app/congstar/id917314686

### Current issues

- [ ] App fails to install
- [ ] App fails to open
- [ ] App crashes randomly during usage
- [X] App experiences graphical issues or broken UI
- [ ] App fails to connect to servers
- [ ] Other

### More details

Installing works fine. Opening works fine, with settings `Graphics > Resolution > App Default` and `Graphics > Fix window issues > checked`. But the window is really small. Going to the menu `Window > Zoom` makes the window SMALLER not bigger. When I take the App Default resolution and multiply by 2 and then use `Graphics > Resolution > Custom` and set the resolution to double size, the content breaks out of the screen. The only aspect ratio that is working, is 1:1. So Custom Resolution `1000x1000` shows the content correctly. BUT it obviously is not a correct mobile phone aspect ratio. I would like to use double the size of the App Default and keep a phone aspect ratio.

### Screenshots

App Default:

![Screenshot 2023-08-31 at 20 07 33](https://github.com/PlayCover/PlayCover/assets/4539234/83e7e8c5-991c-43da-b093-1d42279664a6)

App Default + Zoom:

![Screenshot 2023-08-31 at 20 08 29](https://github.com/PlayCover/PlayCover/assets/4539234/0e68fb60-219e-4fa5-bc83-df5631d5ad96)

Custom 1000x1000:

![Screenshot 2023-08-31 at 20 09 17](https://github.com/PlayCover/PlayCover/assets/4539234/1db4829d-d05e-4f6b-89a1-019cb8d23fe0)

Wanted Custom 645x1398

![Screenshot 2023-08-31 at 20 10 24](https://github.com/PlayCover/PlayCover/assets/4539234/e41a786f-1d33-4c9e-822a-a60d3d002511)

### Issue Language

- [X] Yes my issue is written in English

**Comment by ohaiibuzzle** [comment]
@wohfab That is because this app only supports iPhone and not iPad display size, so it basically cannot be resized properly whatsoever

**Comment by wohfab** [comment]
Thanks for the quick reply, @ohaiibuzzle. What a shame... I mean, I do not need iPad display size, just the iPhone size but a little bigger. Is the "Window > Zoom" function supposed to make it bigger?

**Comment by ohaiibuzzle** [comment]
No, that feature is actually to cause the app to conform to either iOS or macOS pixel scaling
The former is roughly 77% of the other
