### ISSUE TITLE
[Feature]: Game Mode support

### ISSUE THREAD

**Issue by FlyMeToTheMoonAndLetMePlayAmongTheStars** [PlayCover/PlayCover#1085]
### Is your feature request related to a problem?

No

### Describe the solution you'd like

It would be nice to have support for the new Game Mode feature in macOS Sonoma. As far as I am aware it turns on automatically and can't be manually enabled otherwise. I assume macOS auto-detects if a game is using Metal API and is set to launch in fullscreen, if these two conditions are met then it automatically turns on Game Mode which can be seen as a notification and icon in the top menu bar. 

iPhone and iPad games compatible on macOS can use Game Mode so I don't see why games launched from PlayCover can't also use it. 

![image](https://github.com/PlayCover/PlayCover/assets/78054566/c186e01e-ccf0-46d8-bee9-6f59cd78ff14)

### Anything else?

![image](https://github.com/PlayCover/PlayCover/assets/78054566/1cb1d8f6-7b02-429b-80ba-e2712fd2fd4c)

![image](https://github.com/PlayCover/PlayCover/assets/78054566/3cd2b4aa-05a6-4dad-9ea0-585c99936867)

### Issue Language

- [X] Yes my issue is written in English

**Comment by TheMoonThatRises** [comment]
I will look into this. This seems to be easy to solve, and I would assume it would benefit a lot of people.
