### ISSUE TITLE
[Bug]: Smart Keymap is broken

### ISSUE THREAD

**Issue by FlyMeToTheMoonAndLetMePlayAmongTheStars** [PlayCover/PlayCover#1086]
### Describe the bug

Smart Keymap does not work properly and prevents in-game text field entry. This problem occurs on both 3.0.0 release and nightly (472).

With Smart Keymap disabled, you can click on a text field like the chat in Genshin Impact or Honkai Impact and type without issue. However, enabling it causes the text entry to "lose focus" when you try to type a certain letter that corresponds to an existing keymap button. 

Not sure if this has anything to do with the version of macOS I am on, I'm currently using macOS 14.0 Sonoma beta (23A5337a).

### Steps to reproduce

1. Enable Smart Keymap from the app settings
2. Try typing in an in-game text field like the chat box in Genshin Impact 

### Expected behaviour

Smart Keymap not breaking in-game text fields/chat entries. 

### Crash log

```shell
No crash
```

### What version of PlayCover are you using?

Nightly/beta

### What version of macOS are you using?

macOS beta (please state the specific version)

### Issue Language

- [X] Yes my issue is written in English

**Comment by TheMoonThatRises** [comment]
Fix implemented in https://github.com/PlayCover/PlayTools/pull/131.

**Comment by XuYicong** [comment]
Should have been fixed with the said PR
