### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by Retreller** [PlayCover/PlayCover#1089]
### Describe the bug

The keymapping is not working correctly on macOS Sonoma developer beta7, only mouse scroll, rmb and lmb work.

### Steps to reproduce

I don't know how to reduce problem, but I am assuming that it should not be that hard to fix .

### Expected behaviour

Everything work fine.

### What version of PlayCover are you using?

Nightly/beta

### What version of macOS are you using?

macOS beta (please state the specific version)

### Issue Language

- [X] Yes my issue is written in English

**Comment by TheMoonThatRises** [comment]
You need to create a keymapping (which can be learnt by [reading the docs](https://docs.playcover.io/settings/keymapping)). And since you are on MacOS Sonoma beta, you won't be able to make a keymap due to the problem in #1048.
