### ISSUE TITLE
[Bug]: XBox Series X Controller Triggers not identified

### ISSUE THREAD

**Issue by Kyanoxia** [PlayCover/PlayCover#1095]
### Describe the bug

XBox Series X Controller connected through bluetooth works flawlessly, aside from the triggers not doing anything.  In Genshin Impact, when I press the trigger, nothing happens.  This could easily be a genshin problem, but seeing as though it has dedicated controller support, I doubt it.

### Steps to reproduce

Install PlayCover
Install Genshin Impact (from any source)
Turn on Controller Support
Fail to use triggers

### Expected behaviour

Be able to use controller triggers

### What version of PlayCover are you using?

Nightly/beta

### What version of macOS are you using?

Ventura (macOS 13)

### Issue Language

- [X] Yes my issue is written in English

**Comment by zanderp25** [comment]
Unfortunately, we have received several reports about Xbox controllers not working properly but as far as I know, nobody has found out why or any solution.

**Comment by Kyanoxia** [comment]
Seems like the issue was fixed out of the blue.  Only thing I did on my side was install the latest Xcode tools package.
