### ISSUE TITLE
[Feature]: Is there any way to change the installation postions of apps?

### ISSUE THREAD

**Issue by zsMoonshine** [PlayCover/PlayCover#1096]
### Is your feature request related to a problem?

I'd like to install apps in postions choosed by myself to manage files in a better way and save space on Mac. However, I find no way to change the installation/unpack position of apps, and apps are installed in 'user/username/Library/Containers/PlayCover/***' by default. 

### Describe the solution you'd like

Is there a function to change the installation path? If so, please tell me how to change it.

### Anything else?

Actually I install PlayCover in an external disk, but the installation path is still in Macintosh HD.

### Issue Language

- [X] Yes my issue is written in English

**Comment by zanderp25** [comment]
As far as I know, there is no official way to change the installation path. However, symlinks might work, although I haven't tried it.

``` sh
ln -s /Volumes/externalpathto.app/ /Users/user/Library/Containers/<whatever the PlayCover folder is>/nameof.app
```

**Comment by zsMoonshine** [comment]
> As far as I know, there is no official way to change the installation path. However, symlinks might work, although I haven't tried it.
> 
> ```shell
> ln -s /Volumes/externalpathto.app/ /Users/user/Library/Containers/<whatever the PlayCover folder is>/nameof.app
> ```
Thanks a lot. Looking forward to an official way if possible.

**Comment by TheMoonThatRises** [comment]
This pull request #1100 will consider adding it. I just need to dedicate a lot of time into the pr.

**Comment by DaftDogeee** [comment]
@TheMoonThatRises Is there plan to offer the feature that user can move `Container` data of an app to an external disk?

**Comment by ghost** [comment]
I'm not sure if that's possible, as I've never seen a way to change the `/Application Support` or `/Containers` folders to a non-system disk.

**Comment by TheMoonThatRises** [comment]
Take a look through this issue: https://github.com/PlayCover/PlayCover/discussions/473. In short, no, you can't change the location of the app's container, but you can change the app's own location with symlinks.
