### ISSUE TITLE
Keyboard can’t be used in the app

### ISSUE THREAD

**Issue by MoeNyanSakura** [PlayCover/PlayCover#1098]
### Describe the bug

My laptop is Macbookair Sonoma14.0(bata) 

PLAYCOVER 3.00,2.0.5

In the game I can’t use the keyboard to control the characters in the game(yuanshen) Although I have set up the keyboard map,but it still doesn’t work
I have let the system allow the keyboard using of playcover.

### Steps to reproduce

As the passage below(My laptop is Macbookair Sonoma14.0(bata) 

PLAYCOVER 3.00,2.0.5

In the game I can’t use the keyboard to control the characters in the game(yuanshen) Although I have set up the keyboard map,but it still doesn’t work
I have let the system allow the keyboard using of playcover.)

The bug that let me almost can’t do everything with the game,It just like the keyboard doesn’t’t give me any response at all

The keyboard map setting that I can’t change the wasd into any other buttons

### Expected behaviour

I just want you to fix the bug,so that I can you the keyboard to control the character ,thank you 

### What version of PlayCover are you using?

Nightly/beta

### What version of macOS are you using?

macOS beta (please state the specific version)

### Issue Language

- [X] Yes my issue is written in English

**Comment by MEMORIEmusic** [comment]
Same as #1048. Read [my comment](https://github.com/PlayCover/PlayCover/issues/1098)
