### ISSUE TITLE
You do not have permission to store the file "Frameworks" into the folder "Library."

### ISSUE THREAD

**Issue by GHMike** [PlayCover/PlayCover#110]
You do not have permission to store the file "Frameworks" into the folder "Library."
Why is this only happening to my MAC Book Pro M1 Pro?

**Comment by Depal1** [comment]
This has to do with your writing permissions for ~/Library. You should enable writing permissions. It has nothing to do with PlayCover.

**Comment by Sunkisot** [comment]
I also have this problem. Please ask me how to solve it.
