### ISSUE TITLE
[App Support]: Vertical app help

### ISSUE THREAD

**Issue by ELE5tru** [PlayCover/PlayCover#1101]
### App Store link

i wanna play vertical app in play cover but all vertical app be like this. 
whats should i do this 

ps i also want to know how to allow tracking
<img width="903" alt="スクリーンショット 2023-09-21 20 25 08" src="https://github.com/PlayCover/PlayCover/assets/145682624/7861e08d-b06e-4c06-b20f-af7ecc101369">

### Current issues

- [ ] App fails to install
- [X] App fails to open
- [ ] App crashes randomly during usage
- [ ] App experiences graphical issues or broken UI
- [ ] App fails to connect to servers
- [ ] Other

### More details

playcover

### Issue Language

- [X] Yes my issue is written in English

**Comment by TheMoonThatRises** [comment]
Set the app resolution to `App Default` and tick `Fix display window issues`.
