### ISSUE TITLE
[Bug]: Auto mode investigation

### ISSUE THREAD

**Issue by CutieToyHeart** [PlayCover/PlayCover#1103]
### Describe the bug

Don't know if this happens to other people, but the objects in auto mode either are out of frame or don't even load

### Steps to reproduce

Entering auto mode

### Expected behaviour

The object should load in the center of the screen

### What version of PlayCover are you using?

2.0.4

### What version of macOS are you using?

Monterey (macOS 12)

### Issue Language

- [X] Yes my issue is written in English

**Comment by zanderp25** [comment]
Please elaborate:

- Are you referring to the "Auto" display mode?
- Which app or game are you trying to run?
- Could you provide a screenshot?

**Comment by zanderp25** [comment]
Does #1110 solve your problem?

**Comment by TheMoonThatRises** [comment]
Please provide more information. Some ways to fix the issue is to:
- Upgrade your PlayCover version to either the nightly build or 3.0 beta (2.0.4 is an old version)
- Upgrade your operating system to (Monterey is 2 major versions behind)

**Comment by CutieToyHeart** [comment]
Hi, I meant to say that in Life Makeover, one item you investigate in 10-8
was bugged for me, but as of now it's no longer an issue

Have a good day!
