### ISSUE TITLE
[Bug]: Keymapping option key not working

### ISSUE THREAD

**Issue by kazumaasa2** [PlayCover/PlayCover#1107]
### Describe the bug

I tried playing HSR today after updating my game, and the option key to switch to my kepmapping did not work. Then afterwards when trying to manually off and on keymapping, I could only do simple attack and my mouse dissapear.

### Steps to reproduce

Forcefully do CMD+K, then use the macOS finder function to off keyammping, and then you cannot play the game.

### Expected behaviour

Supposed to switch to keymapping, but it did not work.

### What version of PlayCover are you using?

Nightly/beta

### What version of macOS are you using?

Ventura (macOS 13)

### Issue Language

- [X] Yes my issue is written in English

**Comment by hendersonyang** [comment]
I am having the same issue, after updating to sonoma.

The options key stopped responding, and I am unable to close keymapping with cmd+k after opening it with cmd+k. Issue persists after restarting computer.

PlayCover version: Version 2.0.5 (291)
macOS version: Sonoma 14.0

**Comment by kazumaasa2** [comment]
Glad I am no tthe only one with this issue.

**Comment by kazumaasa2** [comment]
Also, might I add, I did not update to sonoma yet and already have this bug. Updating did not solve anythng.

**Comment by MEMORIEmusic** [comment]
Try restarting your Mac.

**Comment by bopen100** [comment]
me too, after updating to sonoma
options key does not working

**Comment by kazumaasa2** [comment]
I will restart my Mac after updating Xcode, and inform about the results.

**Comment by kazumaasa2** [comment]
Restarted, now I don't think the screen is supposed to be like this.
<img width="853" alt="Screenshot 2023-09-28 at 1 31 37 PM" src="https://github.com/PlayCover/PlayCover/assets/109513385/b21499e5-da49-43c7-b05f-7d8bb2fdfe4f">

**Comment by kazumaasa2** [comment]
I am trying to reinstall playcover, will update

**Comment by kazumaasa2** [comment]
I reinstalled playcover and HSR, and after reinstalling the playmap, it now works. Very weird, but at least its fixed.
