### ISSUE TITLE
Fixed

### ISSUE THREAD

**Issue by Sedret1234** [PlayCover/PlayCover#1109]
### Describe the bug

Once you open genshin impact the key mapping toggle keys(command k and option)dont work after saving the key mapping.
This issue started after updating my os to Sonoma (macOS). It wont let me put os as Sonoma.If you tab to key mapping on the menu bar you can open and close key mapping.But the shortcuts don't work and its very hard to do the above as your cursor is generally locked.

### Steps to reproduce

1)Update to Mac OS Sonoma
2)open genshin impact
3)press command k once
now option and command k stops working

### Expected behaviour

whenever you play a game you can easily toggle key mapping using option and command k.This however has stopped working.

### What version of PlayCover are you using?

2.0.4

### What version of macOS are you using?

macOS beta (please state the specific version)

### Issue Language

- [X] Yes my issue is written in English

**Comment by sseno** [comment]
me too, facing the same issue on MacOS Sonoma 14.0 and PlayCover 2.0.5

**Comment by TobyZT** [comment]
same issue, also on MacOS Sonoma 14.0 and PlayCover 2.0.5

**Comment by XuYicong** [comment]
For anyone having any issue on 2.0.x: there will not be any more 2.x.x versions. The next version of 2.0.5 is 3.0.0. Please upgrade to 3.0.0 before submitting issues. Especially those on Sonoma: 2.0.5 and earlier versions will NOT work on Sonoma.

**Comment by sseno** [comment]
> For anyone having any issue on 2.0.x: there will not be any more 2.x.x versions. The next version of 2.0.5 is 3.0.0. Please upgrade to 3.0.0 before submitting issues. Especially those on Sonoma: 2.0.5 and earlier versions will NOT work on Sonoma.

thanks, it works using v3.0.0

**Comment by Sedret1234** [comment]
it works. Thank you so much guys, the play cover community is amazing

**Comment by Sedret1234** [comment]
ill leave this issue open just in case someone else gets the same problem
