### ISSUE TITLE
[Feature]: Set Application type for certain games by default

### ISSUE THREAD

**Issue by MEMORIEmusic** [PlayCover/PlayCover#1111]
### Is your feature request related to a problem?

As of right now, games like Genshin Impact and Honkai: Star Rail may start to crash[macOS Sonoma 14.0] if their application type is set to `public.app-category.none`. 

### Describe the solution you'd like

It would be nice if application type of these games were set to `public.app-category.games` by default/upon install. 

### Anything else?

Using the latest nightly build. 

### Issue Language

- [X] Yes my issue is written in English

**Comment by Depal1** [comment]
This feature is available in PlayCover 3.0.0.
