### ISSUE TITLE
[Bug]: Keyboard not working but mouse clicks are

### ISSUE THREAD

**Issue by DevanshRangan** [PlayCover/PlayCover#1115]
### Describe the bug

Keyboard not working in any game. Mouse clicks are working fine but not keyboard.
Mac Version - MacOS Sonoma 14.0 (Stable)
Playcover version - Latest Beta

### Steps to reproduce

-

### Expected behaviour

Keyboard must be working

### What version of PlayCover are you using?

Nightly/beta

### What version of macOS are you using?

macOS beta (please state the specific version)

### Issue Language

- [x] Yes my issue is written in English

**Comment by chaos1023** [comment]
I have the same problem, and if I open the key mapping, and exit it the cursor disappears, but the keyboard is still not working.

**Comment by DevanshRangan** [comment]
> I have the same problem, and if I open the key mapping, and exit it the cursor disappears, but the keyboard is still not working.

Yes I can't even type on any game. So if I type something and then press the tab, text appears else no way my keyboard is working.

**Comment by MEMORIEmusic** [comment]
Try using the latest [nightly build](https://nightly.link/PlayCover/PlayCover/workflows/2.nightly_release/develop/PlayCover_nightly_497.dmg)

**Comment by DevanshRangan** [comment]
> Try using the latest [nightly build](https://nightly.link/PlayCover/PlayCover/workflows/2.nightly_release/develop/PlayCover_nightly_497.dmg)

Thanks for this. But I just upgraded my mac to Sonoma 14.1 beta and now games aren't even opening. So will this nightly build fix it?

**Comment by MEMORIEmusic** [comment]
> > Try using the latest [nightly build](https://nightly.link/PlayCover/PlayCover/workflows/2.nightly_release/develop/PlayCover_nightly_497.dmg)
> 
> Thanks for this. But I just upgraded my mac to Sonoma 14.1 beta and now games aren't even opening. So will this nightly build fix it?

Known issue(#1108). Probably won’t be fix until macOS 14.1 is officially released. Either downgrade or wait until it’s officially released.

**Comment by chaos1023** [comment]
But I'm using macOS 14.0, I'm not using the beta version of 14.1.

**Comment by chaos1023** [comment]
So I just took a look at the playcover discord channel and someone had brought up the same issue. The solution was to upgrade to the 3.0.0 beta version of playcover and I just tried it out and it actually worked. 
Apparently 2.0.5 isn't compatible with the MacOS Sonoma
