### ISSUE TITLE
[App Support]: 墨墨背单词

### ISSUE THREAD

**Issue by h1096224896** [PlayCover/PlayCover#1119]
### App Store link

软件字体布局太小，可以自定义dpi就好了

### Current issues

- [ ] App fails to install
- [ ] App fails to open
- [ ] App crashes randomly during usage
- [ ] App experiences graphical issues or broken UI
- [ ] App fails to connect to servers
- [ ] Other

### More details

增加软件dpi调节

### Issue Language

- [X] Yes my issue is written in English

**Comment by Kricium** [comment]
哥们儿你要用英文写...

**Comment by zanderp25** [comment]
There is already a display scale / DPI adjustment in graphics settings, if you are referring to that.

Also, yes, please use English when creating issues here.
