### ISSUE TITLE
Hope to support importing already installed software

### ISSUE THREAD

**Issue by crane3200** [PlayCover/PlayCover#112]
I hope to be able to support importing installed software, I want to use playcover's keyboard and mouse mapping function, thank you

**Comment by Depal1** [comment]
What do you mean by installed software. Could you please be more specific?

**Comment by crane3200** [comment]
Some software playcover cannot be installed successfully. I installed it successfully through other methods, but I hope to be able to use the keymap function of playcover.

**Comment by Depal1** [comment]
There is a .ipa export with PlayCover functionalities for use on the likes of Sideloadly. Some apps won't run through PlayCover at the moment.

**Comment by Depal1** [comment]
The exported .ipa for Sideloadly are not guaranteed to work.

**Comment by crane3200** [comment]
Sideloadly has no keymap feature

**Comment by Depal1** [comment]
You can use the export to Sideloadly feature on PlayCover.

**Comment by crane3200** [comment]
What should I do please?

**Comment by crane3200** [comment]
After I click this button, the application icons inside are all gray

**Comment by crane3200** [comment]
I get it，thank you ！
