### ISSUE TITLE
[App Support]: Yandex Music 

### ISSUE THREAD

**Issue by geek0big** [PlayCover/PlayCover#1120]
### App Store link

https://apps.apple.com/ru/app/яндекс-музыка-книги-подкасты/id520797969

### Current issues

- [ ] App fails to install
- [ ] App fails to open
- [ ] App crashes randomly during usage
- [ ] App experiences graphical issues or broken UI
- [X] App fails to connect to servers
- [ ] Other

### More details

PlayCover - 3.0.0 (486)  // on a (499) - apps not working

Issue - on macOS Sonoma 14.1  the Yandex Music app  has a "connection error". App opens without crashes.  on a Ventura it worked fine. Also, if I install it with Sideloadly, there is no "connection error".

### Issue Language

- [X] Yes my issue is written in English

**Comment by zanderp25** [comment]
Sonoma 14.1 beta is currently not supported yet, see #1108.
