### ISSUE TITLE
[应用程序支持]：怎么自由调节窗口大小？

### ISSUE THREAD

**Issue by 569363087** [PlayCover/PlayCover#1128]
### App Store link

https://apps.apple.com/us/app/nintendo-switch-online/id1234806557

### Current issues

- [ ] App fails to install
- [ ] App fails to open
- [ ] App crashes randomly during usage
- [ ] App experiences graphical issues or broken UI
- [ ] App fails to connect to servers
- [ ] Other

### More details

怎么自由调节窗口大小？只能窗口模式和全屏？

### Issue Language

- [X] Yes my issue is written in English

**Comment by XuYicong** [comment]
Set window resolution to default, and you can freely change resolution. And please write in English when possible.

把窗口分辨率设置为默认分辨率就可以。
