### ISSUE TITLE
[App Support]: How to completely uninstall a game？（如何干净的卸载游戏？）

### ISSUE THREAD

**Issue by xingyue52077** [PlayCover/PlayCover#1133]
### App Store link

https://apps.apple.com/cn/app/%E5%8E%9F%E7%A5%9E-3%E5%91%A8%E5%B9%B4/id1467190251

### Current issues

- [ ] App fails to install
- [ ] App fails to open
- [ ] App crashes randomly during usage
- [ ] App experiences graphical issues or broken UI
- [ ] App fails to connect to servers
- [X] Other

### More details

After entering the game, the game downloaded 20+g of data. How can I uninstall it completely? Uninstall the game directly. The downloaded data is still there, but I can’t find it no matter how I look for it. Where is the downloaded and stored game data?Thanks to those who helped me! !

进入游戏后游戏下载了20+g 数据，如何彻底卸载，直接卸载游戏，下载数据还在，但是怎么找也找不到，游戏数据下载储存的位置在哪？
感谢帮助我的人！！

### Issue Language

- [X] Yes my issue is written in English

**Comment by XuYicong** [comment]
You can choose to remove data and preference files when uninstalling. There is a popup window that lets you choose whether to remove. If you don't see such popup, you need to upgrade your playcover.

**Comment by xingyue52077** [comment]
Thank you for your reply.I also chose to delete the data when there was a prompt box, but then a message that permissions were not supported was displayed. Where is the specific location of this data? Can it be deleted manually? I am using version 3.00bate and the os version is 14.

**Comment by xingyue52077** [comment]
> You can choose to remove data and preference files when uninstalling. There is a popup window that lets you choose whether to remove. If you don't see such popup, you need to upgrade your playcover.

**Comment by TheMoonThatRises** [comment]
You need to go into your system settings, and under privacy give PlayCover full disk access in order for PlayCover to fully delete the app.

**Comment by linselect** [comment]
I also have the same problem, and after the deletion failed, the game icon also disappeared.Now I want to know where the installation path is？
