### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by 954708775** [PlayCover/PlayCover#1134]
### Describe the bug

Unable to turn the view by clicking the command (Or option, I have tried the related buttons) button in MacOS latest version Sonoma 14.0 with playcover ver 2.0.5(291)

### Steps to reproduce

Update MacOS to the latest version, when I try to play Honkai Starrail, I find that I can click the command button to enter the mouse view turn function, but there is no view turning, it just freezes. And I can't quit this interface to pop my mouse out.

### Expected behaviour

To make it compatible with the latest macOS version.

### What version of PlayCover are you using?

Nightly/beta

### What version of macOS are you using?

Ventura (macOS 13)

### Issue Language

- [X] Yes my issue is written in English

**Comment by XuYicong** [comment]
Dupilicate of #1048. Upgrade PlayCover to 3.0.0.

升级到 playcover 3.0.0 版本解决
