### ISSUE TITLE
[Bug]: keyboard unresponsive

### ISSUE THREAD

**Issue by senpapii** [PlayCover/PlayCover#1137]
### Describe the bug

After opening genshin impact, only the touchpad cursor is responsive. Pressing the option key doesn't enable the keymapping. If I use my cursor to access the keymapping option on top of the window, I can't press any keys and when I leave it, my cursor disappears and is unresponsive and i have to press command+tab to exit the game. The keyboard and option key worked fine when I first downloaded PlayCover and genshin, but after a Mac update that restarted my computer, it stopped working. 

### Steps to reproduce

Restarting my computer

### Expected behaviour

I expected the keymapping to work fine and that my cursor would appear and disappear when i press the option key.

### What version of PlayCover are you using?

2.0.4

### What version of macOS are you using?

Ventura (macOS 13)

### Issue Language

- [X] Yes my issue is written in English

**Comment by TheMoonThatRises** [comment]
Update to PlayCover 3.0.0.

**Comment by senpapii** [comment]
> Update to PlayCover 3.0.0.

it is and its still not working

**Comment by senpapii** [comment]
> Update to PlayCover 3.0.0.



> Update to PlayCover 3.0.0.

i did and it still doesnt work

**Comment by TheMoonThatRises** [comment]
Oh wait my bad, the issue should be fixed in the nightly build, not the 3.0.0.

**Comment by senpapii** [comment]
> Oh wait my bad, the issue should be fixed in the nightly build, not the 3.0.0.

im sorry im new to playcover, how exactly do i get nightly build?

**Comment by TheMoonThatRises** [comment]
You can go here to get the nightly builds: https://github.com/PlayCover/PlayCover/actions/workflows/2.nightly_release.yml.
