### ISSUE TITLE
[Feature]: Genshin Impact can't start Game Mode on MacOS Sonoma

### ISSUE THREAD

**Issue by NEU20205988John** [PlayCover/PlayCover#1139]
### Is your feature request related to a problem?

It only takes one click on Fullscreen button to start game mode, but it seems that apps using playcover can't be detected.

### Describe the solution you'd like

It only takes one click on Fullscreen button to start game mode, but it seems that apps using playcover can't be detected.

### Anything else?

It only takes one click on Fullscreen button to start game mode, but it seems that apps using playcover can't be detected.

### Issue Language

- [X] Yes my issue is written in English

**Comment by MEMORIEmusic** [comment]
1. Use PlayCover Nightly
2. Right click Genshin -> settings -> misc -> change Application Type to `public.app-category.games`

**Comment by BuleFACE** [comment]
https://github.com/PlayCover/PlayCover/issues/1108#issuecomment-1749899299
I tried and it worked.

**Comment by NEU20205988John** [comment]
> 1. Use PlayCover Nightly
> 2. Right click Genshin -> settings -> misc -> change Application Type to `public.app-category.games`

Thank you so much, it worked.

**Comment by sosring** [comment]
https://github.com/PlayCover/PlayCover/issues/1108#issuecomment-1749899299

Can't seems to find application type ? 
<img width="533" alt="Screenshot 2023-12-04 at 1 43 23 PM" src="https://github.com/PlayCover/PlayCover/assets/108966935/65107341-e0f1-43e2-83bc-c7171a985165">

**Comment by NEU20205988John** [comment]
https://docs.playcover.io/getting_started/download_playcover<img width="828" alt="image" src="https://github.com/PlayCover/PlayCover/assets/80146486/9461bd74-90bd-4ceb-9edf-c47edbae7fba">
<img width="922" alt="image" src="https://github.com/PlayCover/PlayCover/assets/80146486/98c06789-a6c4-4f09-b32d-8b0ff695ce50">
https://nightly.link/PlayCover/PlayCover/workflows/2.nightly_release/develop/PlayCover_nightly_558.dmg
