### ISSUE TITLE
[Bug]: Vertical Orientation in Horizontal Orientation App

### ISSUE THREAD

**Issue by Wanja01YT** [PlayCover/PlayCover#1141]
### Describe the bug

![image](https://github.com/PlayCover/PlayCover/assets/62118688/40595d4f-b02d-4947-9e6d-e893898488a7)
When running the video game "Standoff 2" the screen incorrectly opens in some cut-off vertical orientation. This issue happens both in 3.0.0 and 2.0.5.

### Steps to reproduce

1. Install "Standoff 2"
2. Run "Standoff 2"

### Expected behaviour

Game should run in normal orientation and not vertically.

### What version of PlayCover are you using?

Nightly/beta

### What version of macOS are you using?

Ventura (macOS 13)

### Issue Language

- [X] Yes my issue is written in English

**Comment by MEMORIEmusic** [comment]
Right click the game -> settings -> change resolution to “App Default” and check “Fix window display issues”

**Comment by nnzo** [comment]
> Right click the game -> settings -> change resolution to “App Default” and check “Fix window display issues”

This doesn't seem to work

**Comment by Wanja01YT** [comment]
> > Right click the game -> settings -> change resolution to “App Default” and check “Fix window display issues”
> 
> 
> 
> This doesn't seem to work

Works for me, but can't get latest version of game (0.25.1) to run, most likely ipa has not been decrypted properly.

**Comment by TheMoonThatRises** [comment]
Fixed in https://github.com/Playcover/PlayTools/pull/129.
