### ISSUE TITLE
[Bug]: Cannot compile on Xcode 15.0 (15A240d) - PhaseScriptExecution failed with a nonzero exit code

### ISSUE THREAD

**Issue by FreedomLabsIO** [PlayCover/PlayCover#1142]
### Describe the bug

Cannot compile on Xcode 15.0 (15A240d) - PhaseScriptExecution failed with a nonzero exit code

### Steps to reproduce

Follow all the steps from [https://docs.playcover.io/building_from_source/index (https://docs.playcover.io/building_from_source/index)
on latest macOS Ventura 13.5.2 with Xcode 15.0 (15A240d)

When I press the Play button the building process starts and stops with this error

PhaseScriptExecution failed with a nonzero exit code

### Expected behaviour

Compile and run PlayCover

### Crash log

```
Users/myself/Library/Developer/Xcode/DerivedData/PlayCover-cyrrvtyncgqfbzfaylnkohuaqkoj/SourcePackages/artifacts/sparkle/Sparkle.xcframework/macos-arm64_x86_64/Sparkle.framework/Autoupdate: No such file or directory
Command PhaseScriptExecution failed with a nonzero exit code
```

### What version of PlayCover are you using?

Nightly/beta

### What version of macOS are you using?

Ventura (macOS 13)

### Issue Language

- [X] Yes my issue is written in English

**Comment by fuomag9** [comment]
This fails on 14.1 (23B74) as well

**Comment by Vortec4800** [comment]
Just wanted to comment and mention this is still happening on the develop branch today. I updated the script and that fixed the issue, maybe the shell script should be changed to find the Sparkle.xcframework directory instead of hardcoding the path, in case it moves for whatever reason?

**Comment by MhAmerian** [comment]
Same issue on sonoma. M1pro

**Comment by MhAmerian** [comment]
did you find any solution?

**Comment by Catta1997** [comment]
Hi all. I had the same issue and for me `Clan build folder` solved  the issue
