### ISSUE TITLE
[Bug]: Keymapping does not record Macbook keyboard

### ISSUE THREAD

**Issue by mlumobi** [PlayCover/PlayCover#1146]
### Describe the bug

When using keymapping feature, I can not use Keyboard of my mac to set desire key input. External devices such as mouse can be recorded.

Device: M1 Pro Macbook Pro
OS: macOS Sonoma 14.0 (23A344)

### Steps to reproduce

Open Keymapping while application/game is running.

### Expected behaviour

When a key is pressed the Keymapping should change to the key that is pressed.

### Crash log

```shell
No Crash
```

### What version of PlayCover are you using?

Nightly/beta

### What version of macOS are you using?

macOS beta (please state the specific version)

### Issue Language

- [X] Yes my issue is written in English

**Comment by TheMoonThatRises** [comment]
Which PlayCover nightly version are you using?

**Comment by mlumobi** [comment]
> Which PlayCover nightly version are you using?

I am using 3.0.0 Beta version of PlayCover

**Comment by TheMoonThatRises** [comment]
Which one of the nightly version (like from which date)? If you don't know, try again by downloading the newest one.

**Comment by cliffxzx** [comment]
I have the same issue on same device and os. I installed by `brew install playcover-community-beta`. 
<img width="293" alt="image" src="https://github.com/PlayCover/PlayCover/assets/44764053/891d6930-0375-4ef8-af90-73f8055c3570">

Update:
Fixed on latest nightly build:
https://github.com/PlayCover/PlayCover/actions/runs/6500111481
<img width="473" alt="image" src="https://github.com/PlayCover/PlayCover/assets/44764053/039f8a90-a324-475c-b199-d8d11293c481">
