### ISSUE TITLE
[Bug]: Invalid keyboard map

### ISSUE THREAD

**Issue by Xing-YaoLei** [PlayCover/PlayCover#1147]
### Describe the bug

Device：MacBook Pro For M1 Pro
MacOS：14.0 (23A344)
Game：Honkai: Star Rail
Software version：3.0.0 (233)
Bug：After keyboard mapping is enabled, key combinations can be used, but keys such as Q, W, E, and R cannot be added。The mapping can be deleted using Command + Del

### Steps to reproduce

<img width="170" alt="image" src="https://github.com/PlayCover/PlayCover/assets/45413253/c65ae391-2a34-40da-84da-df1071c027d5">

### Expected behaviour

It is expected that mappings should be added

### What version of PlayCover are you using?

Nightly/beta

### What version of macOS are you using?

macOS beta (please state the specific version)

### Issue Language

- [X] Yes my issue is written in English

**Comment by Xing-YaoLei** [comment]
Similar key combinations like Command can be used, but mapping keys such as Q, W, E, R, X, C, etc. alone cannot be implemented

**Comment by TheMoonThatRises** [comment]
Duplicate of #1048. Use the latest PlayCover nightly build.
