### ISSUE TITLE
[Bug]: Controller Identified but doesn't work

### ISSUE THREAD

**Issue by phuwn** [PlayCover/PlayCover#1149]
### Describe the bug

I'm playing Genshin Impact with a PS4 Dual Shock controller. This setup has been working for weeks. But today, It suddenly just stops working. My controller still works on other apps. Plug-in or remove controller still pops up a notice in Genshin, but none of the buttons work. I'm using Sonoma (macOS 14), I updated it 2 days ago and yesterday It was still working fine.

### Steps to reproduce

- Open Genshin Impact
- Connect PS4 Controller (via Bluetooth or cable)
- Update Genshin Impact control settings

### Expected behaviour

The controller still works the same as yesterday.

### What version of PlayCover are you using?

Nightly/beta

### What version of macOS are you using?

Ventura (macOS 13)

### Issue Language

- [X] Yes my issue is written in English

**Comment by phuwn** [comment]
This sounds stupid but restarting mac solves the case.

**Comment by Andromea7** [comment]
> This sounds stupid but restarting mac solves the case.

Thank you, you did solve my problem so I am happy you posted your solution.

**Comment by phuwn** [comment]
> > This sounds stupid but restarting mac solves the case.
> 
> Thank you, you did solve my problem so I am happy you posted your solution.

Glad I could help 😄
