### ISSUE TITLE
[Feature]: When will 3.0.0 stable be released?

### ISSUE THREAD

**Issue by JiuZ-Chn** [PlayCover/PlayCover#1152]
### Is your feature request related to a problem?

1. In the new version of Mac OS, 3.0.0 beta has some bugs and many people need to download PlayCover from the nightly version.
2. Some new features are released in PlayCover and PlayTools, we hope to enjoy it.
So I would like to ask if there is an ETA that will release the stable version of 3.0.0?

### Describe the solution you'd like

N/A

### Anything else?

N/A

### Issue Language

- [X] Yes my issue is written in English

**Comment by TheMoonThatRises** [comment]
No ETA. We are all generally pretty busy at the moment and don't really have a timeline. You can just use the nightly build for PlayCover, as it is at the moment stable enough to be used.
