### ISSUE TITLE
[Bug]: Honkai:Star Rail get low FPS(between 30~40)

### ISSUE THREAD

**Issue by jayyah** [PlayCover/PlayCover#1153]
### Describe the bug

When the game version update to 1.4, it's FPS got stuck in 30 to 40.

<img width="242" alt="Screenshot 2023-10-12 at 21 48 52" src="https://github.com/PlayCover/PlayCover/assets/20358686/fa9ef265-cd56-43db-a66d-651db32ab915">
<img width="1716" alt="Screenshot 2023-10-12 at 21 54 50" src="https://github.com/PlayCover/PlayCover/assets/20358686/6ab32210-539e-4b16-b1c0-b8e4b7cdc30e">

Even if I adjust the graphics quality to ver low, it is still the same.
<img width="1683" alt="Screenshot 2023-10-12 at 21 57 11" src="https://github.com/PlayCover/PlayCover/assets/20358686/96622be4-d9d0-4f2f-be0a-07dee695a431">

PlayCover : Version 3.0.0 (378)
MacOS : 14.0

### Steps to reproduce

1. Update the game to 1.4 version
2. Start the game

### Expected behaviour

Run the game in FPS about 60

### What version of PlayCover are you using?

Nightly/beta

### What version of macOS are you using?

macOS beta (please state the specific version)

### Issue Language

- [X] Yes my issue is written in English

**Comment by zanderp25** [comment]
What happens if you set the FPS to 60? Same thing? You might want to change the device model in the app settings in PlayCover and see what works best.

**Comment by jayyah** [comment]
> What happens if you set the FPS to 60? Same thing? You might want to change the device model in the app settings in PlayCover and see what works best.

Thanks a lot, I set the FPS to 60, it works great. Maybe something changed in the game's new version.
