### ISSUE TITLE
[Feature]: App clone

### ISSUE THREAD

**Issue by mm304321141** [PlayCover/PlayCover#1158]
### Is your feature request related to a problem?

game multiple launch for login different accounts

### Describe the solution you'd like

App clone support .
Although we can modify inentity to install the same app multiple times, but it is troublesome, and the application takes up multiple storage spaces.
If application supports clons, it can become very convenient and save storage space.

### Anything else?

nop

### Issue Language

- [X] Yes my issue is written in English

**Comment by ghost** [comment]
I don't think it's necessary to do this. It may just be better to implement some sort of easy switcher GUI for app data and login information on a per-app basis.

**Comment by TheMoonThatRises** [comment]
See https://github.com/PlayCover/PlayCover/issues/349#issuecomment-1250046948. Short answer: no.

**Comment by Doooomizz** [comment]
@mm304321141 Could u guide me on how did u clone apps plz ?
