### ISSUE TITLE
[Bug]: Minecraft LogIn Not Possible

### ISSUE THREAD

**Issue by iMonZ** [PlayCover/PlayCover#1159]
### Describe the bug

Hey so I installed Minecraft But I cant login
![Screenshot 2023-10-16 at 14 57 49](https://github.com/PlayCover/PlayCover/assets/11319871/bbb22ec8-2041-4ba2-8b8a-10d120aa7ab3)
Is there any way to fix it?
Maybe It's because it cant verify its authenticity.
Is it possible to add App Store Verification Support so the app will work ( Since I really bought it ) (Or at least one of the people in the family sharing)

### Steps to reproduce

Open Minecraft
Press login

### Expected behaviour

A login prompt should appear
 (Using macOS Sonoma)

### What version of PlayCover are you using?

Nightly/beta

### What version of macOS are you using?

macOS beta (please state the specific version)

### Issue Language

- [X] Yes my issue is written in English

**Comment by TheMoonThatRises** [comment]
See https://github.com/PlayCover/PlayCover/issues/537#issuecomment-1420138619. If you really want to get MPE working, you can take a look at https://github.com/minecraft-linux/mcpelauncher-manifest or check the discord.

**Comment by daltonbr** [comment]
I have this issue too. Even though the ticket is closed it could be nice to get this to work someday, as the game seems to work fine.
