### ISSUE TITLE
Keyboard and mouse mapping fails when playing Genshin Impact under high load

### ISSUE THREAD

**Issue by lushuyu** [PlayCover/PlayCover#116]
Device: MacBook Pro 14' with 10 core M1 Pro and 16GB RAM

Even when playing Genshin Impact in 120hz and highest quality in Liyue, all works nice.

In some higher load scene, such as Tatarasuna（踏鞴砂）, or 4 Players (especially Yelan Q, Ganyu Q, Kazuha Q), game is still smooth, but keyboard and mouse operation failed. Often there is a large delay. I don't think it hit machine limit, because the game doesn't drop frames. Maybe the mouse and keyboard mapping needs a higher priority in macOS?

**Comment by lushuyu** [comment]
After adjusting the minimum quality, the problem of Tatarasuna is alleviated, but the problem of 4Players still exists

**Comment by hayatofujii** [comment]
Is it something along #28? But instead of "freezing keypresses", it's freezing at "no inputs" and does nothing for a while till you "fix it".

**Comment by lushuyu** [comment]
> Is it something along #28? But instead of "freezing keypresses", it's freezing at "no inputs" and does nothing for a while till you "fix it".

Only when the load is high, any key press and mouse rotation will have a delay of more than 3s...This kind of problem has always occurred when there are multiple teams, I think the process priority of the keyboard and mouse mapping is not high enough, or the playcover should not maintain the 120hz of Genshin when the load is very high. I guess the 120hz mode of playcover is mandatory, because the load will not drop frames no matter how high the load is.

**Comment by 47thforce** [comment]
> Device: MacBook Pro 14' with 10 core M1 Pro and 16GB RAM
> 
> Even when playing Genshin Impact in 120hz and highest quality in Liyue, all works nice.
> 
> In some higher load scene, such as Tatarasuna（踏鞴砂）, or 4 Players (especially Yelan Q, Ganyu Q, Kazuha Q), game is still smooth, but keyboard and mouse operation failed. Often there is a large delay. I don't think it hit machine limit, because the game doesn't drop frames. Maybe the mouse and keyboard mapping needs a higher priority in macOS?

I somehow didn't face that problem in the base version of M1 Macbook Air (of course I overclocked the screen to 80Hz and fps counter shows the FPS is about 65 to 74), EXCEPT when I turned on motion blur.

**Comment by IsaacMarovitz** [comment]
Does this issue persist in PlayCover 1.1.1?

**Comment by Iridescent-Moon** [comment]
I have also been facing this issue. I've just updated to PlayCover 1.1.1 earlier today, and it seems that I am still experiencing the issue where I lose control of the inputs and my character continues the previous input. I have not experienced the other issue where there is a large delay in processing my controls yet, but I did experience it prior to updating to 1.1.1. But it may be that not enough time has passed since updating for the other issue to occur.

I am playing on a M1 Macbook Air with 8 CPU cores and 7 GPU cores.

**Comment by XuYicong** [comment]
Hi friends if you are willing to test whether the fix works or not before it gets into nightly builds, follow these steps:

1. Download playTools binary from https://cdn.discordapp.com/attachments/918278843830272000/1013351348663754822/PlayTools
2. Replace the file `/Users/USERNAME/Library/Frameworks/PlayTools.framework/PlayTools` with the downloaded file (you could backup the original file)
3. Run genshin as normal

I have a confidence of like, 80% it solves the problem, and 95% it won't break existing things. But can't say for sure without testing.

In the worst case it messes up with something and you don't have a backup of the original file, do some changes to the APP preference and your original playTools will be back.

In even more worst case that doesn't help either, reinstalling the APP saves you.

**Comment by Iridescent-Moon** [comment]
I have played for a bit using the fix. Unfortunately, it doesn't seem to fix the problem where the inputs freeze and the previous input continues. Additionally, it seems that the option key no longer works either (this had also happened prior to updating to version 1.1.1, but I'm not sure whether it did happen after updating to version 1.1.1). I have to command+tab out to a different application and go back to fix the issue.

However, I have still not run into the other issue where there is a large delay in processing inputs.

**Comment by XuYicong** [comment]
> I have played for a bit using the fix. Unfortunately, it doesn't seem to fix the problem where the inputs freeze and the previous input continues. Additionally, it seems that the option key no longer works either (this had also happened prior to updating to version 1.1.1, but I'm not sure whether it did happen after updating to version 1.1.1). I have to command+tab out to a different application and go back to fix the issue.
> 
> However, I have still not run into the other issue where there is a large delay in processing inputs.

Thank you for the feedback. It seems the issue you encounter may have a different cause from the one here, since you're not having input delay issue or only encounter it under high load. Does it have something to do with https://github.com/PlayCover/PlayCover/issues/28 ?

**Comment by Iridescent-Moon** [comment]
The issue may be different, but I believe it's possible it could be related. When I play at 60fps, I run into the issue, but upon turning it down to 30fps, the issue doesn't come up. 

Someone else seems to have commented to #28 with a similar issue as mine, but it seems unrelated to the initial commenter's issue that was caused by pressing a key frequently.

If you would like, I could submit a new issue with the details regarding this issue I have been facing.

**Comment by lushuyu** [comment]
So how to install latest Playtools? Hope it can be merged into a new Playcover release.
