### ISSUE TITLE
[Feature]: allow PlayCover run in vm

### ISSUE THREAD

**Issue by d9j** [PlayCover/PlayCover#1162]
### Is your feature request related to a problem?

related to closed 
https://github.com/PlayCover/PlayCover/issues/1160

### Describe the solution you'd like

as mentioned there.the PlayCover refuses to launch "malicious" app on host. my suggestion now to allow just to run PlayCover in the virtual machine.. . i believe there is not much modification is needed

### Anything else?

---

### Issue Language

- [X] Yes my issue is written in English

**Comment by XuYicong** [comment]
As far as I and most other contributors can tell, there is no easy way to achieve this. If you find it easy, you're welcome to contribute. But if you want something like Qemu, which has a lot of performance overhead, you may want to try UTM. That's a more suitable software than PlayCover for this purpose.

**Comment by uprprc777** [comment]
With the new UTM (4.4.4) and macOS 14, I can launch some games through PlayCover inside a macOS UTM while some games looks OK and some have serious issues.
However, previously with UTM 4.3.5 and macOS 13, I was never able to launch any games. They crashed immediately.

I tried Genshin and Arknights with UTM 4.4.4 and macOS 14.1. 
Genshin now works fine. The graphic looks OK and I have not yet see any crash and error.
Arknight is able to launch but has serious graphic errors. Many graphics, models, pictures and even texts are not shown or not shown correctly.
