### ISSUE TITLE
[App Support]: 

### ISSUE THREAD

**Issue by tuncerbap09** [PlayCover/PlayCover#1166]
### App Store link

.

### Current issues

- [X] App fails to install
- [ ] App fails to open
- [ ] App crashes randomly during usage
- [ ] App experiences graphical issues or broken UI
- [ ] App fails to connect to servers
- [ ] Other

### More details

its said that my Mac doesnt support this application

### Crash log

```shell
.
```

### Issue Language

- [X] Yes my issue is written in English

**Comment by TheMoonThatRises** [comment]
PlayCover only runs on Apple Silicon Macs. Won't work on Intel Macs.
