### ISSUE TITLE
[Bug]: Update prompt appear to promote a older version

### ISSUE THREAD

**Issue by FxmousKid** [PlayCover/PlayCover#1169]
### Describe the bug

I downloaded the version 3.0.0 and as soon as i opened it i got a prompt to update to version 2.0.5, which doesn't make much sense since 3.0.0 > 2.0.5 but does make sense in the sense that 3.0.0 is beta where as 2.0.5 isn't, but i dont this is the intended use of the prompt (since it isn't mentioned in it anywhere), so i guess this counts as a bug

### Steps to reproduce

1. Download playcover 3.0.0 (the dmg, i have a Macbook pro m1 8gb ram 512gb Storage, Sonoma 14.0)
2. Launch the .dmg
3. open the app after moving it to /Applications 

### Expected behaviour

No such prompt

### Crash log

```shell
None
```

### What version of PlayCover are you using?

Nightly/beta

### What version of macOS are you using?

macOS beta (please state the specific version)

### Issue Language

- [X] Yes my issue is written in English

**Comment by MEMORIEmusic** [comment]
Application updater doesn’t recognise Nightlies and Betas/Pre-releases as latest release(since these are test versions, normal people won’t use it) so it shows that. Hence it doesn’t exactly count as a bug.
