### ISSUE TITLE
[Feature]: 能否加个多开功能呀Can you add a multi-open function?

### ISSUE THREAD

**Issue by star8618** [PlayCover/PlayCover#1171]
### Is your feature request related to a problem?

 能否加个多开功能呀+
Can you add a multi-open function?

### Describe the solution you'd like

 能否加个多开功能呀
Can you add a multi-open function?

### Anything else?

 能否加个多开功能呀
Can you add a multi-open function?

### Issue Language

- [X] Yes my issue is written in English

**Comment by TheMoonThatRises** [comment]
Duplicate of #1158.
