### ISSUE TITLE
[Feature]: Option to temporarily disable all keymapping

### ISSUE THREAD

**Issue by gedehari** [PlayCover/PlayCover#1173]
### Is your feature request related to a problem?

In Honkai: Star Rail, right when I was to enter a character name, keyboard keys that are mapped cannot be used to type, and only the ones that doesn't get mapped can be used. I had to delete all of the keymapping to proceed, then re-import it. This probably affects all in-game textfields but I have not experimented with them yet. I will update it when I do.

### Describe the solution you'd like

Just a toggle somewhere (preferrably in the menubar) to temporarily disable all keymapping.

### Anything else?

None as I have forgotten to record it. I will update with further information soon.

### Issue Language

- [X] Yes my issue is written in English

**Comment by MEMORIEmusic** [comment]
This is a bug with macOS Sonoma and smart keymapping. Use [PlayCover Nightly](https://nightly.link/playcover/playcover/workflows/2.nightly_release/develop). After that, right click honkai star rail -> settings -> disable smart keymapping & misc -> change application type to `public.app-category.games`.
