### ISSUE TITLE
[Bug]: Wrong orientation when playing Hearthstone with PlayTool

### ISSUE THREAD

**Issue by wlupus** [PlayCover/PlayCover#1189]
### Describe the bug

If I start Hearthstone with PlayTool installed, the game keeps vertical. I think that's a display bug because the button's position in game is correct (not identical to the display).

### Steps to reproduce

Install Hearthstone (version 27.2.185054) in PlayCover and install PlayTool for this game, which is default on my laptop.

Start the game with graphics settings below.
<img width="532" alt="image" src="https://github.com/PlayCover/PlayTools/assets/55167921/d0d3b9d2-7273-433a-b415-a24977d9747d">

And the game will be displayed with wrong orientation. However, the click seems still right. For example, if I want to open friends menu, I need to click bottom left, not the display position.

<img width="1260" alt="image" src="https://github.com/PlayCover/PlayTools/assets/55167921/61cbf6ef-b04f-4fe4-98ba-66505f5476a8">

### Expected behaviour
The game works well if started without PlayTool.
<img width="1164" alt="image" src="https://github.com/PlayCover/PlayTools/assets/55167921/bc3d5374-deaa-4609-bc57-9a32c2daff6e">

### Crash log
There is no crash.

### What version of PlayCover are you using
Version 3.0.0 (378) (Latest beta version)

### What version of macos are you using
macOS Ventura 13.5.1

**Comment by TheMoonThatRises** [comment]
Press Cmd+R to rotate the screen with PlayTools injected.
