### ISSUE TITLE
[Bug]: Camera stops moving mid game.

### ISSUE THREAD

**Issue by ridamarya2005** [PlayCover/PlayCover#1192]
### Describe the bug

MacOS : 14.1
bug : when I play genshin everything works fine but suddenly mid fight camera stops moving, To make it move again I have to press option twice. But after that It happens again mid fight.

### Steps to reproduce

I don't know how to reproduce it.It just happened after I updated my MacOS from 14.0 to 14.1 . Coz I just started using the nightly version and after that I'm having this issue. It suddenly happens mid fight.

### Expected behaviour

The camera stops moving. The rest button and things works fine. Just the camera gets stuck.

### What version of PlayCover are you using?

Nightly/beta

### What version of macOS are you using?

macOS beta (please state the specific version)

### Issue Language

- [X] Yes my issue is written in English

**Comment by JiuZX** [comment]
Same issue. But this bug seems to occur in the latest nightly (>528?), and the older ones are much better.

**Comment by ridamarya2005** [comment]
> Same issue. But this bug seems to occur in the latest nightly (>528?), and the older ones are much better.

Older version are better , But in The latest 14.1 MacOS sonoma you can only launch genshin via nightly. thru original you can't launch the game

**Comment by JiuZX** [comment]
You are right, but not need the latest nightly. In the playtools repo, the commit on Oct 27th helps fix the launch issue in MacOS 14.
<img width="1254" alt="image" src="https://github.com/PlayCover/PlayCover/assets/21299239/2b231d98-3ee1-459b-b465-d5b7e43c8e19">

Maybe you can try the version after that. https://github.com/PlayCover/PlayCover/actions/workflows/2.nightly_release.yml
On the workflow, and then you can download it here:
<img width="1599" alt="image" src="https://github.com/PlayCover/PlayCover/assets/21299239/49863a3e-7d6a-4c7f-9553-0695cc45f5b1">

**Comment by ridamarya2005** [comment]
> You are right, but not need the latest nightly. In the playtools repo, the commit on Oct 27th helps fix the launch issue in MacOS 14. <img alt="image" width="1254" src="https://user-images.githubusercontent.com/21299239/280372686-2b231d98-3ee1-459b-b465-d5b7e43c8e19.png">
> 
> Maybe you can try the version after that. https://github.com/PlayCover/PlayCover/actions/workflows/2.nightly_release.yml On the workflow, and then you can download it here: <img alt="image" width="1599" src="https://user-images.githubusercontent.com/21299239/280373206-49863a3e-7d6a-4c7f-9553-0695cc45f5b1.png">

I can't understand what is playtools repo and where to find it. And I can't run the game without nightly So can you please elaborate a bit.

**Comment by ridamarya2005** [comment]
> Same issue. But this bug seems to occur in the latest nightly (>528?), and the older ones are much better.

Thanks At first I couldn't understand what you were saying , but now I downloaded the older version of nightly and it works fine. thanks so muchh.
