### ISSUE TITLE
[Bug]: Golden Shovel Quits

### ISSUE THREAD

**Issue by riven-blade** [PlayCover/PlayCover#1197]
### Describe the bug

The Golden Shovel game will exit

### Steps to reproduce

The Golden Shovel game will exit

### Expected behaviour

The Golden Shovel game will exit

### What version of PlayCover are you using?

Nightly/beta

### What version of macOS are you using?

macOS beta (please state the specific version)

### Issue Language

- [X] Yes my issue is written in English

**Comment by TheMoonThatRises** [comment]
Duplicate of #1104.
