### ISSUE TITLE
[Bug]: Nikke Display Issue

### ISSUE THREAD

**Issue by Bwainy** [PlayCover/PlayCover#1203]
### Describe the bug

I've seen people with an issue like this before, but I tried all the things that they said to do and it did not work. I've changed the resolution to each possible setting. I ticked the box that says fix display issues. Any possible fixes or things that I can try?
This also happens for Blue Archive. But for Nikke: Goddess of Victory, I do not have this issue.
<img width="1526" alt="Screenshot 2023-11-07 at 10 29 16 AM" src="https://github.com/PlayCover/PlayCover/assets/150180611/87e07f6b-a558-4ddb-b406-56db7b5ea118">

### Steps to reproduce

I open the game and it looks like this. 
<img width="1495" alt="Screenshot 2023-11-07 at 10 18 16 AM" src="https://github.com/PlayCover/PlayCover/assets/150180611/03b0dc1d-6d5b-4b69-8d53-e1e9fbd5fd0e">

### Expected behaviour

Be able to see the game fully.

### What version of PlayCover are you using?

2.0.4

### What version of macOS are you using?

macOS beta (please state the specific version)

### Issue Language

- [X] Yes my issue is written in English

**Comment by TheMoonThatRises** [comment]
First, use the latest nightly version of PlayCover. Then, if the resolution is still off, set the resolution to `App Default`, as the `Fix window display issues` only works on that setting.

**Comment by GardieM** [comment]
i have the same issue 
<img width="528" alt="image" src="https://github.com/PlayCover/PlayCover/assets/171927022/15e94bbc-44f0-4c89-a712-42f3447ef68f">
<img width="1501" alt="image" src="https://github.com/PlayCover/PlayCover/assets/171927022/5d1c9401-7438-4f12-b458-07cb962ee030">
and cannot do or touch anything 
help me plz
