### ISSUE TITLE
[Bug]: Genshin Impact quit unexpectedly

### ISSUE THREAD

**Issue by K5031** [PlayCover/PlayCover#1212]
### Describe the bug

Genshin Impact crashes when opened and shows this message:
<img width="254" alt="Screenshot 2023-11-11 at 20 38 52" src="https://github.com/PlayCover/PlayCover/assets/110524712/3eac14f6-0fbd-48d8-9b52-09ab7eda12ea">

This issue appeared right after I upgraded to Sonoma 14.1.1.. Before it was working perfectly.

### Steps to reproduce

1. Import Genshin IPA from decrypt.day
2. Update to Sonoma 14.1.1
3. Click on Genshin in app library

### Expected behaviour

A window shows up saying "hoyoverse"

### Crash log
The problem report macOS gave me:
```shell
https://pastebin.com/vCveJmtj
```

### What version of PlayCover are you using?

Nightly/beta

### What version of macOS are you using?

Monterey (macOS 12)

### Issue Language

- [X] Yes my issue is written in English

**Comment by austinatose** [comment]
experiencing this issue too

**Comment by Eternal9eu** [comment]
Hope to have a solution! Same problem!

**Comment by laterre39** [comment]
fix bugs setting -> misc -> CategoryType changes -> games

**Comment by kang49** [comment]
I hope to have a solution of this issue too.

**Comment by kang49** [comment]
> fix bugs setting -> misc -> CategoryType changes -> games

Okay I know how to fix this bug. Actually you need to let's me know it's need (Playcover nightly version) to use that step.

Here's Nightly version link: https://nightly.link/PlayCover/PlayCover/workflows/2.nightly_release/develop/PlayCover_nightly_539.dmg

**Comment by laterre39** [comment]
> > fix bugs setting -> misc -> CategoryType changes -> games
> 
> Okay I know how to fix this bug. Actually you need to know it's need (Playcover lightly version) to use that step.
> 
> Here's Lightly version link: https://nightly.link/PlayCover/PlayCover/workflows/2.nightly_release/develop/PlayCover_nightly_539.dmg

Yea gj bro

**Comment by K5031** [comment]
> > fix bugs setting -> misc -> CategoryType changes -> games
> 
> Okay I know how to fix this bug. Actually you need to let's me know it's need (Playcover lightly version) to use that step.
> 
> Here's Lightly version link: https://nightly.link/PlayCover/PlayCover/workflows/2.nightly_release/develop/PlayCover_nightly_539.dmg

I installed the nightly version and it now launches. Thanks alot!
