### ISSUE TITLE
[Game Support]: Issue with updating Genshin Impact

### ISSUE THREAD

**Issue by AdvaitMalviya** [PlayCover/PlayCover#1220]
### Describe the bug

App not working, when i try to reopen it, it still shows the same thing, when i try to uninstall genshin impact it shows that i don't have the permission to do it.

### Steps to reproduce

I had genshin impact on my playcover before and haven't played it in a long time now when i downloaded the new update for it and installed the ipa, i tried to open it but it doesn't work. When i try to uninstall it, it shows that i don't have permission to do it, and then i uninstalled playcover and reinstalled it, it still didn't work.

### Expected behaviour

A window pops up and shows the app is not opening and when i click reopen it still shows the same window .

### What version of PlayCover are you using?

Nightly/beta

### What version of macOS are you using?

Ventura (macOS 13)

### Issue Language

- [X] Yes my issue is written in English

**Comment by TheMoonThatRises** [comment]
What do you mean updating it doesn't work? Can you provide more detail about that, as updating simply requires you to install the updated IPA without needing to mess with the app already installed.

**Comment by MEMORIEmusic** [comment]
Are you on macOS Sonoma or Ventura?

**Comment by AdvaitMalviya** [comment]
The latest one, I guess it is ventura

**Comment by AdvaitMalviya** [comment]
@TheMoonThatRises I downloaded the new update for genshin impact and installed it but it didn't work so I tried to uninstall the game but it shows I don't have permission for it and then when I tried to uninstall in reinstall the whole thing ( playcover and genshin impact ) it still showed the same thing .

**Comment by kong36088** [comment]
I have met the same problem. The latest version of genshin impact will crash.
Here's my version of macOS(Apple M2 Pro):
<img width="472" alt="image" src="https://github.com/PlayCover/PlayCover/assets/11497913/19bcfe78-ff6d-495e-aedd-6879440dece6">

**Comment by TheMoonThatRises** [comment]
First, make sure you are on the latest nightly version of PlayCover. Then, make sure you download the latest IPA of the Genshin and install it through PlayCover. Also can you elaborate on "when i try to reopen it, it still shows the same thing"?

**Comment by NightSkies07** [comment]
![Screenshot 2023-12-20 at 12 09 49 PM](https://github.com/PlayCover/PlayCover/assets/154414533/5a07836a-a6c0-4391-a83e-c5e4c713de32)

I followed all the steps ad then when I tried to open genshin it would pop this up, I tried restarting and everything

**Comment by kong36088** [comment]
> ![Screenshot 2023-12-20 at 12 09 49 PM](https://private-user-images.githubusercontent.com/154414533/291825042-5a07836a-a6c0-4391-a83e-c5e4c713de32.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDMwNjAxNzgsIm5iZiI6MTcwMzA1OTg3OCwicGF0aCI6Ii8xNTQ0MTQ1MzMvMjkxODI1MDQyLTVhMDc4MzZhLWE2YzAtNDM5MS1hODNlLWM1ZTRjNzEzZGUzMi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjIwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIyMFQwODExMThaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xMTE3Y2RhM2ZjZjIyMjJmZDM2YjdjZGE1MWM4MTQ5MTdjYmFiNGI3NWUwMTY4NGQyNzIxYjhkMGJmMmIxOGI1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.kOPtgnDx7RVdE6N0xOX9E3ESg7CcpRmSvBTlA5wS53s)
> 
> I followed all the steps ad then when I tried to open genshin it would pop this up, I tried restarting and everything

yes, the same.

**Comment by Kenneth-Privaldos** [comment]
Currently encountering this issue.

**Comment by NightSkies07** [comment]
I found a way to solve this, instead use the Playcover nightly version
https://github.com/PlayCover/PlayCover/actions/runs/7279978483#artifacts
through this link, youll find a file for the playcover night version

Genshin worked for me through this app

**Comment by TheMoonThatRises** [comment]
> ![Screenshot 2023-12-20 at 12 09 49 PM](https://private-user-images.githubusercontent.com/154414533/291825042-5a07836a-a6c0-4391-a83e-c5e4c713de32.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDMxOTgxODcsIm5iZiI6MTcwMzE5Nzg4NywicGF0aCI6Ii8xNTQ0MTQ1MzMvMjkxODI1MDQyLTVhMDc4MzZhLWE2YzAtNDM5MS1hODNlLWM1ZTRjNzEzZGUzMi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjIxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIyMVQyMjMxMjdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iMzQwYjFjM2M5OGFjOWFhMDJkNjVkMzE4ZDIzZTE2MGUyNDU4NDc2OGJjM2YyNTMxYzM1YWVkNWMyMzY2YjMxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.pnlYgFVsgmpaoKMN9iscBMp3dEs5FqxKIFpjpJF3Hww)
> 
> I followed all the steps ad then when I tried to open genshin it would pop this up, I tried restarting and everything

Set the `Application Type` of Genshin to something other than what it currently is (e.g. `public.app-category.games`). You can do this by opening PlayCover, left-clicking Genshin Impact, click `Settings`, click `Misc`, and it should be the first item.
