### ISSUE TITLE
[Bug]: Genshin Impact does not open

### ISSUE THREAD

**Issue by Sedret1234** [PlayCover/PlayCover#1224]
### Describe the bug

After updating to Sonoma 14.1.1 genshin impact does not open.(play cover version 3.0.0)
<img width="1440" alt="Screenshot 2023-11-18 at 12 31 33 PM" src="https://github.com/PlayCover/PlayCover/assets/146323598/6e319249-787c-46fc-afe8-fbd7845b319e">

### Steps to reproduce

Update to Sonoma 14.1.1 and open genshin impact through play cover.

### Expected behaviour

Genshin impact should open normally.

### What version of PlayCover are you using?

Nightly/beta

### What version of macOS are you using?

Ventura (macOS 13)

### Issue Language

- [X] Yes my issue is written in English

**Comment by FulanXisen** [comment]
@Sedret1234 I met the same problem. Did you solve it?

**Comment by MEMORIEmusic** [comment]
Same as #1108

**Comment by seemanth-raju** [comment]
same can anyone solve this
