### ISSUE TITLE
[Game Support]: Blue Archive JP "不明なアプリが検出されたため、終了します。" on nightly versions

### ISSUE THREAD

**Issue by Wzxxxsxxxx** [PlayCover/PlayCover#1230]
### App Store link

https://apps.apple.com/jp/app/%E3%83%96%E3%83%AB%E3%83%BC%E3%82%A2%E3%83%BC%E3%82%AB%E3%82%A4%E3%83%96/id1515877221

### Current issues

- [ ] Game fails to install
- [X] Game fails to open
- [ ] Game crashes randomly during gameplay
- [ ] Game does not work with keymapping
- [ ] Game experiences graphical issues or broken UI
- [ ] Game fails to connect to servers or complete download

### More details

![799F2CA7-068E-40ED-AE46-17454340B1E2](https://github.com/PlayCover/PlayCover/assets/123379865/f58d89fd-5fa9-45c9-a75c-7b98ec827503)
game version 1.38
![E128579A-D74F-4E02-9ADF-E7774277E449](https://github.com/PlayCover/PlayCover/assets/123379865/d5201373-0ae4-442c-a55e-78b1dad85d43)

### Issue Language

- [X] Yes my issue is written in English

**Comment by barutann** [comment]
https://www.bilibili.com/read/cv25700894/?spm_id_from=333.1007.0.0

**Comment by Wzxxxsxxxx** [comment]
> https://www.bilibili.com/read/cv25700894/?spm_id_from=333.1007.0.0

Doesn't work on version 1.38

**Comment by mmkzer0** [comment]
> > https://www.bilibili.com/read/cv25700894/?spm_id_from=333.1007.0.0
> 
> Doesn't work on version 1.38

The Game does work on 2.0.5; however, since App Version 1.38, you need to turn off SIP *and* set nvram args for the game to not close immediately upon launch.

**Comment by Wzxxxsxxxx** [comment]
> > > https://www.bilibili.com/read/cv25700894/?spm_id_from=333.1007.0.0
> > 
> > 
> > Doesn't work on version 1.38
> 
> The Game does work on 2.0.5; however, since App Version 1.38, you need to turn off SIP _and_ set nvram args for the game to not close immediately upon launch.

..I don't know why but I tried it three times and then it finally worked.Thanks.
