### ISSUE TITLE
[App Support]: Apps quit unexpectedly

### ISSUE THREAD

**Issue by kkumamon** [PlayCover/PlayCover#1235]
### Describe the bug

downloaded apps quit unexpectedly.  none of my downloaded ipas are opening even though they did before.  

### Steps to reproduce

open playcover. double click app. fails to launch.

### Expected behaviour

expected ipa to launch

### What version of PlayCover are you using?

2.0.4

### What version of macOS are you using?

Ventura (macOS 13)

### Issue Language

- [X] Yes my issue is written in English

**Comment by mattam301** [comment]
same partern, waiting for fix

**Comment by TheMoonThatRises** [comment]
Version 2.0.4 is considered unsupported, please update to the latest beta (3.0.0 beta 2). Also please provide more information next time.
