### ISSUE TITLE
[Game Support]: Arknights

### ISSUE THREAD

**Issue by Aikoww** [PlayCover/PlayCover#1255]
### App Store link

https://apps.apple.com/us/app/arknights/id1464872022

### Current issues

- [ ] Game fails to install
- [X] Game fails to open
- [ ] Game crashes randomly during gameplay
- [ ] Game does not work with keymapping
- [ ] Game experiences graphical issues or broken UI
- [ ] Game fails to connect to servers or complete download

### More details

said at first that i didnt have access to a specific file, then after that it says it had an unexpected error

### Issue Language

- [X] Yes my issue is written in English

**Comment by TheMoonThatRises** [comment]
Can you give more information (such as screenshots, etc)?

**Comment by Aikoww** [comment]
so today I tried redownloading the ipa and opening it on playcover, which worked. though it couldn't connect to the servers, so i closed it and tried reopening it and now it gave me an error saying it quit unexpectedly. this is the report

-------------------------------------
Translated Report (Full Report Below)
-------------------------------------

Process:               Arknights [898]
Path:                  /Users/USER/Library/Containers/io.playcover.PlayCover/Arknights.app/Arknights
Identifier:            com.YoStarEN.Arknights
Version:               20.0.62 (54)
Code Type:             ARM-64 (Native)
Parent Process:        launchd [1]
User ID:               501

Date/Time:             2023-12-23 13:22:39.1947 +0800
OS Version:            macOS 14.2 (23C64)
Report Version:        12
Anonymous UUID:        DEE78192-5AEA-DE85-96C3-0CD6F9243959


Time Awake Since Boot: 95 seconds

System Integrity Protection: disabled

Crashed Thread:        0  Dispatch queue: com.apple.main-thread

Exception Type:        EXC_BREAKPOINT (SIGTRAP)
Exception Codes:       0x0000000000000001, 0x00000001987ad0f8

Termination Reason:    Namespace SIGNAL, Code 5 Trace/BPT trap: 5
Terminating Process:   exc handler [898]

Application Specific Signatures:
The code signature is not valid: The operation couldn’t be completed. (OSStatus error -67030.)

Thread 0 Crashed::  Dispatch queue: com.apple.main-thread
0   libsystem_secinit.dylib       	       0x1987ad0f8 _libsecinit_appsandbox.cold.9 + 60
1   libsystem_secinit.dylib       	       0x1987ac1b8 _libsecinit_appsandbox + 1608
2   libsystem_trace.dylib         	       0x18bc936d8 _os_activity_initiate_impl + 64
3   libsystem_secinit.dylib       	       0x1987abb1c _libsecinit_initializer + 80
4   libSystem.B.dylib             	       0x1987c2694 libSystem_initializer + 260
5   dyld                          	       0x18bbcda24 invocation function for block in dyld4::Loader::findAndRunAllInitializers(dyld4::RuntimeState&) const::$_0::operator()() const + 168
6   dyld                          	       0x18bc13328 invocation function for block in dyld3::MachOAnalyzer::forEachInitializer(Diagnostics&, dyld3::MachOAnalyzer::VMAddrConverter const&, void (unsigned int) block_pointer, void const*) const + 340
7   dyld                          	       0x18bc06668 invocation function for block in dyld3::MachOFile::forEachSection(void (dyld3::MachOFile::SectionInfo const&, bool, bool&) block_pointer) const + 496
8   dyld                          	       0x18bbad2fc dyld3::MachOFile::forEachLoadCommand(Diagnostics&, void (load_command const*, bool&) block_pointer) const + 300
9   dyld                          	       0x18bc056a0 dyld3::MachOFile::forEachSection(void (dyld3::MachOFile::SectionInfo const&, bool, bool&) block_pointer) const + 192
10  dyld                          	       0x18bc12e3c dyld3::MachOAnalyzer::forEachInitializer(Diagnostics&, dyld3::MachOAnalyzer::VMAddrConverter const&, void (unsigned int) block_pointer, void const*) const + 516
11  dyld                          	       0x18bbc9b38 dyld4::Loader::findAndRunAllInitializers(dyld4::RuntimeState&) const + 524
12  dyld                          	       0x18bbd3928 dyld4::PrebuiltLoader::runInitializers(dyld4::RuntimeState&) const + 44
13  dyld                          	       0x18bbef360 dyld4::APIs::runAllInitializersForMain() + 84
14  dyld                          	       0x18bbb1fa0 dyld4::prepare(dyld4::APIs&, dyld3::MachOAnalyzer const*) + 3192
15  dyld                          	       0x18bbb0edc start + 1844


Thread 0 crashed with ARM Thread State (64-bit):
    x0: 0x0000000000000060   x1: 0x000000012210444c   x2: 0xfffffffffffffff0   x3: 0x000000016d8e2e70
    x4: 0xffffffffb48215bc   x5: 0x0000000000000010   x6: 0x000000016d8e2df0   x7: 0x0000000000000b30
    x8: 0x00000001e1745828   x9: 0x8845c3bee17a003e  x10: 0x0000000000000200  x11: 0x0000000000000060
   x12: 0x0000000000000000  x13: 0x00000000000007fd  x14: 0x0000000081a6000c  x15: 0x000000000000000c
   x16: 0x000000018bd47cc0  x17: 0x00000001eb783c10  x18: 0x0000000000000000  x19: 0x000000012210440c
   x20: 0x000000016d8e2e50  x21: 0x00000000000001f5  x22: 0x0000000000000000  x23: 0x00000000000003e8
   x24: 0x00000001987add5e  x25: 0x00000001987addae  x26: 0x0000000000000000  x27: 0x0000000000000001
   x28: 0x00000001987addf2   fp: 0x000000016d8e2e10   lr: 0x57718001987ad0ec
    sp: 0x000000016d8e2df0   pc: 0x00000001987ad0f8 cpsr: 0x60001000
   far: 0x0000000000000000  esr: 0xf2000001 (Breakpoint) brk 1

Binary Images:
       0x10abc0000 -        0x10abc7fff org.cocoapods.HGEventLog (20.0.62) <404f7267-89e2-336d-b17c-9dad0b7db505> /Users/USER/Library/Containers/io.playcover.PlayCover/Arknights.app/Frameworks/HGEventLog.framework/HGEventLog
       0x10ac78000 -        0x10accbfff org.cocoapods.HGWebView (20.0.62) <fcc26989-096b-31f1-904c-3c51f0c29a15> /Users/USER/Library/Containers/io.playcover.PlayCover/Arknights.app/Frameworks/HGWebView.framework/HGWebView
       0x10ac00000 -        0x10ac17fff com.cloudling.Masonry (20.0.62) <77e13c9e-4bef-3160-b5d1-22b54055c569> /Users/USER/Library/Containers/io.playcover.PlayCover/Arknights.app/Frameworks/Masonry.framework/Masonry
       0x10b428000 -        0x10b5fbfff io.playcover.PlayTools (1.1.7) <54b115ba-c8f2-3670-b738-66e7eeacee5c> /Users/USER/Library/Frameworks/PlayTools.framework/PlayTools
       0x102518000 -        0x1094a3fff com.YoStarEN.Arknights (20.0.62) <8bf6506e-8599-34be-a291-26ff0ca8e159> /Users/USER/Library/Containers/io.playcover.PlayCover/Arknights.app/Arknights
       0x1987ab000 -        0x1987adffb libsystem_secinit.dylib (*) <c2ea7f93-a263-39a2-bcdc-f26dce9dfa32> /usr/lib/system/libsystem_secinit.dylib
       0x18bc8c000 -        0x18bca6fff libsystem_trace.dylib (*) <1f45fd2f-3abc-3ab3-9a6f-cc9c727acbda> /usr/lib/system/libsystem_trace.dylib
       0x1987c1000 -        0x1987c2fff libSystem.B.dylib (*) <c9a4714e-2961-3fbd-8e74-8615b3a5777e> /usr/lib/libSystem.B.dylib
       0x18bbab000 -        0x18bc3f347 dyld (*) <324e4ad9-e01f-3183-b09f-3e20b326643a> /usr/lib/dyld
               0x0 - 0xffffffffffffffff ??? (*) <00000000-0000-0000-0000-000000000000> ???
       0x18bd46000 -        0x18bd7cfff libsystem_malloc.dylib (*) <690a8b04-8e64-3332-b5a5-56a3d5c1c43f> /usr/lib/system/libsystem_malloc.dylib

External Modification Summary:
  Calls made by other processes targeting this process:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0
  Calls made by this process:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0
  Calls made by all processes on this machine:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0

VM Region Summary:
ReadOnly portion of Libraries: Total=1.8G resident=0K(0%) swapped_out_or_unallocated=1.8G(100%)
Writable regions: Total=683.0M written=0K(0%) resident=0K(0%) swapped_out=0K(0%) unallocated=683.0M(100%)

                                VIRTUAL   REGION 
REGION TYPE                        SIZE    COUNT (non-coalesced) 
===========                     =======  ======= 
Activity Tracing                   256K        1 
Kernel Alloc Once                   32K        1 
MALLOC                           668.2M       17 
MALLOC guard page                   96K        6 
STACK GUARD                       56.0M        1 
Stack                             8176K        1 
__AUTH                            3749K      553 
__AUTH_CONST                      38.5M      791 
__CTF                               824        1 
__DATA                            34.0M      786 
__DATA_CONST                      41.9M      803 
__DATA_DIRTY                      2764K      322 
__FONT_DATA                          4K        1 
__LINKEDIT                       899.0M        6 
__OBJC_RO                         71.1M        1 
__OBJC_RW                         2168K        1 
__TEXT                           933.6M      825 
dyld private memory               4384K        4 
shared memory                       32K        2 
===========                     =======  ======= 
TOTAL                              2.7G     4123 



-----------
Full Report
-----------

{"app_name":"Arknights","timestamp":"2023-12-23 13:22:42.00 +0800","app_version":"20.0.62","slice_uuid":"8bf6506e-8599-34be-a291-26ff0ca8e159","build_version":"54","platform":6,"bundleID":"com.YoStarEN.Arknights","share_with_app_devs":0,"is_first_party":0,"bug_type":"309","os_version":"macOS 14.2 (23C64)","roots_installed":0,"name":"Arknights","incident_id":"E989EB63-7501-4B44-A1E4-105AAB06B92F"}
{
  "uptime" : 95,
  "procRole" : "Background",
  "version" : 2,
  "userID" : 501,
  "deployVersion" : 210,
  "modelCode" : "MacBookAir10,1",
  "coalitionID" : 979,
  "osVersion" : {
    "train" : "macOS 14.2",
    "build" : "23C64",
    "releaseType" : "User"
  },
  "captureTime" : "2023-12-23 13:22:39.1947 +0800",
  "codeSigningMonitor" : 1,
  "incident" : "E989EB63-7501-4B44-A1E4-105AAB06B92F",
  "pid" : 898,
  "translated" : false,
  "cpuType" : "ARM-64",
  "roots_installed" : 0,
  "bug_type" : "309",
  "procLaunch" : "2023-12-23 13:22:38.5345 +0800",
  "procStartAbsTime" : 2277926685,
  "procExitAbsTime" : 2293704524,
  "procName" : "Arknights",
  "procPath" : "\/Users\/USER\/Library\/Containers\/io.playcover.PlayCover\/Arknights.app\/Arknights",
  "bundleInfo" : {"CFBundleShortVersionString":"20.0.62","CFBundleVersion":"54","CFBundleIdentifier":"com.YoStarEN.Arknights","DTAppStoreToolsBuild":"15C5065a"},
  "storeInfo" : {"deviceIdentifierForVendor":"A0A43FDD-6102-5847-A26B-27E866DE6DD9","thirdParty":true},
  "parentProc" : "launchd",
  "parentPid" : 1,
  "coalitionName" : "com.YoStarEN.Arknights",
  "crashReporterKey" : "DEE78192-5AEA-DE85-96C3-0CD6F9243959",
  "codeSigningID" : "com.YoStarEN.Arknights",
  "codeSigningTeamID" : "",
  "codeSigningFlags" : 570444289,
  "codeSigningValidationCategory" : 1,
  "codeSigningTrustLevel" : 4294967295,
  "instructionByteStream" : {"beforePC":"8wMCqvQDAKrhAwD5AgAAkEJIPJEBAIFSEgEAlMh8JJAIoSCRFE0AqQ==","atPC":"IAAg1H8jA9X\/wwDR\/XsCqf2DAJFIbiOwCBlG+QgBQPmogx\/4CABA+Q=="},
  "sip" : "disabled",
  "exception" : {"codes":"0x0000000000000001, 0x00000001987ad0f8","rawCodes":[1,6853153016],"type":"EXC_BREAKPOINT","signal":"SIGTRAP"},
  "termination" : {"flags":0,"code":5,"namespace":"SIGNAL","indicator":"Trace\/BPT trap: 5","byProc":"exc handler","byPid":898},
  "os_fault" : {"process":"Arknights"},
  "asiSignatures" : ["The code signature is not valid: The operation couldn’t be completed. (OSStatus error -67030.)"],
  "extMods" : {"caller":{"thread_create":0,"thread_set_state":0,"task_for_pid":0},"system":{"thread_create":0,"thread_set_state":0,"task_for_pid":0},"targeted":{"thread_create":0,"thread_set_state":0,"task_for_pid":0},"warnings":0},
  "faultingThread" : 0,
  "threads" : [{"triggered":true,"id":10268,"threadState":{"x":[{"value":96},{"value":4866458700},{"value":18446744073709551600},{"value":6133001840},{"value":18446744072443008444},{"value":16},{"value":6133001712},{"value":2864},{"value":8077465640,"symbolLocation":8,"symbol":"gCRAnnotations"},{"value":9819469787145306174},{"value":512},{"value":96},{"value":0},{"value":2045},{"value":2175139852},{"value":12},{"value":6640925888,"symbolLocation":0,"symbol":"free"},{"value":8245492752},{"value":0},{"value":4866458636},{"value":6133001808},{"value":501},{"value":0},{"value":1000},{"value":6853156190},{"value":6853156270},{"value":0},{"value":1},{"value":6853156338}],"flavor":"ARM_THREAD_STATE64","lr":{"value":6300958098009542892},"cpsr":{"value":1610616832},"fp":{"value":6133001744},"sp":{"value":6133001712},"esr":{"value":4060086273,"description":"(Breakpoint) brk 1"},"pc":{"value":6853153016,"matchesCrashFrame":1},"far":{"value":0}},"queue":"com.apple.main-thread","frames":[{"imageOffset":8440,"symbol":"_libsecinit_appsandbox.cold.9","symbolLocation":60,"imageIndex":5},{"imageOffset":4536,"symbol":"_libsecinit_appsandbox","symbolLocation":1608,"imageIndex":5},{"imageOffset":30424,"symbol":"_os_activity_initiate_impl","symbolLocation":64,"imageIndex":6},{"imageOffset":2844,"symbol":"_libsecinit_initializer","symbolLocation":80,"imageIndex":5},{"imageOffset":5780,"symbol":"libSystem_initializer","symbolLocation":260,"imageIndex":7},{"imageOffset":141860,"symbol":"invocation function for block in dyld4::Loader::findAndRunAllInitializers(dyld4::RuntimeState&) const::$_0::operator()() const","symbolLocation":168,"imageIndex":8},{"imageOffset":426792,"symbol":"invocation function for block in dyld3::MachOAnalyzer::forEachInitializer(Diagnostics&, dyld3::MachOAnalyzer::VMAddrConverter const&, void (unsigned int) block_pointer, void const*) const","symbolLocation":340,"imageIndex":8},{"imageOffset":374376,"symbol":"invocation function for block in dyld3::MachOFile::forEachSection(void (dyld3::MachOFile::SectionInfo const&, bool, bool&) block_pointer) const","symbolLocation":496,"imageIndex":8},{"imageOffset":8956,"symbol":"dyld3::MachOFile::forEachLoadCommand(Diagnostics&, void (load_command const*, bool&) block_pointer) const","symbolLocation":300,"imageIndex":8},{"imageOffset":370336,"symbol":"dyld3::MachOFile::forEachSection(void (dyld3::MachOFile::SectionInfo const&, bool, bool&) block_pointer) const","symbolLocation":192,"imageIndex":8},{"imageOffset":425532,"symbol":"dyld3::MachOAnalyzer::forEachInitializer(Diagnostics&, dyld3::MachOAnalyzer::VMAddrConverter const&, void (unsigned int) block_pointer, void const*) const","symbolLocation":516,"imageIndex":8},{"imageOffset":125752,"symbol":"dyld4::Loader::findAndRunAllInitializers(dyld4::RuntimeState&) const","symbolLocation":524,"imageIndex":8},{"imageOffset":166184,"symbol":"dyld4::PrebuiltLoader::runInitializers(dyld4::RuntimeState&) const","symbolLocation":44,"imageIndex":8},{"imageOffset":279392,"symbol":"dyld4::APIs::runAllInitializersForMain()","symbolLocation":84,"imageIndex":8},{"imageOffset":28576,"symbol":"dyld4::prepare(dyld4::APIs&, dyld3::MachOAnalyzer const*)","symbolLocation":3192,"imageIndex":8},{"imageOffset":24284,"symbol":"start","symbolLocation":1844,"imageIndex":8}]}],
  "usedImages" : [
  {
    "source" : "P",
    "arch" : "arm64",
    "base" : 4475060224,
    "CFBundleShortVersionString" : "20.0.62",
    "CFBundleIdentifier" : "org.cocoapods.HGEventLog",
    "size" : 32768,
    "uuid" : "404f7267-89e2-336d-b17c-9dad0b7db505",
    "path" : "\/Users\/USER\/Library\/Containers\/io.playcover.PlayCover\/Arknights.app\/Frameworks\/HGEventLog.framework\/HGEventLog",
    "name" : "HGEventLog",
    "CFBundleVersion" : "54"
  },
  {
    "source" : "P",
    "arch" : "arm64",
    "base" : 4475813888,
    "CFBundleShortVersionString" : "20.0.62",
    "CFBundleIdentifier" : "org.cocoapods.HGWebView",
    "size" : 344064,
    "uuid" : "fcc26989-096b-31f1-904c-3c51f0c29a15",
    "path" : "\/Users\/USER\/Library\/Containers\/io.playcover.PlayCover\/Arknights.app\/Frameworks\/HGWebView.framework\/HGWebView",
    "name" : "HGWebView",
    "CFBundleVersion" : "54"
  },
  {
    "source" : "P",
    "arch" : "arm64",
    "base" : 4475322368,
    "CFBundleShortVersionString" : "20.0.62",
    "CFBundleIdentifier" : "com.cloudling.Masonry",
    "size" : 98304,
    "uuid" : "77e13c9e-4bef-3160-b5d1-22b54055c569",
    "path" : "\/Users\/USER\/Library\/Containers\/io.playcover.PlayCover\/Arknights.app\/Frameworks\/Masonry.framework\/Masonry",
    "name" : "Masonry",
    "CFBundleVersion" : "54"
  },
  {
    "source" : "P",
    "arch" : "arm64",
    "base" : 4483874816,
    "CFBundleShortVersionString" : "1.1.7",
    "CFBundleIdentifier" : "io.playcover.PlayTools",
    "size" : 1916928,
    "uuid" : "54b115ba-c8f2-3670-b738-66e7eeacee5c",
    "path" : "\/Users\/USER\/Library\/Frameworks\/PlayTools.framework\/PlayTools",
    "name" : "PlayTools",
    "CFBundleVersion" : "1"
  },
  {
    "source" : "P",
    "arch" : "arm64",
    "base" : 4333862912,
    "CFBundleShortVersionString" : "20.0.62",
    "CFBundleIdentifier" : "com.YoStarEN.Arknights",
    "size" : 116965376,
    "uuid" : "8bf6506e-8599-34be-a291-26ff0ca8e159",
    "path" : "\/Users\/USER\/Library\/Containers\/io.playcover.PlayCover\/Arknights.app\/Arknights",
    "name" : "Arknights",
    "CFBundleVersion" : "54"
  },
  {
    "source" : "P",
    "arch" : "arm64e",
    "base" : 6853144576,
    "size" : 12284,
    "uuid" : "c2ea7f93-a263-39a2-bcdc-f26dce9dfa32",
    "path" : "\/usr\/lib\/system\/libsystem_secinit.dylib",
    "name" : "libsystem_secinit.dylib"
  },
  {
    "source" : "P",
    "arch" : "arm64e",
    "base" : 6640156672,
    "size" : 110592,
    "uuid" : "1f45fd2f-3abc-3ab3-9a6f-cc9c727acbda",
    "path" : "\/usr\/lib\/system\/libsystem_trace.dylib",
    "name" : "libsystem_trace.dylib"
  },
  {
    "source" : "P",
    "arch" : "arm64e",
    "base" : 6853234688,
    "size" : 8192,
    "uuid" : "c9a4714e-2961-3fbd-8e74-8615b3a5777e",
    "path" : "\/usr\/lib\/libSystem.B.dylib",
    "name" : "libSystem.B.dylib"
  },
  {
    "source" : "P",
    "arch" : "arm64e",
    "base" : 6639235072,
    "size" : 607048,
    "uuid" : "324e4ad9-e01f-3183-b09f-3e20b326643a",
    "path" : "\/usr\/lib\/dyld",
    "name" : "dyld"
  },
  {
    "size" : 0,
    "source" : "A",
    "base" : 0,
    "uuid" : "00000000-0000-0000-0000-000000000000"
  },
  {
    "source" : "P",
    "arch" : "arm64e",
    "base" : 6640918528,
    "size" : 225280,
    "uuid" : "690a8b04-8e64-3332-b5a5-56a3d5c1c43f",
    "path" : "\/usr\/lib\/system\/libsystem_malloc.dylib",
    "name" : "libsystem_malloc.dylib"
  }
],
  "sharedCache" : {
  "base" : 6638485504,
  "size" : 4061216768,
  "uuid" : "9787f614-d6d0-32d2-ac62-6596e786e862"
},
  "vmSummary" : "ReadOnly portion of Libraries: Total=1.8G resident=0K(0%) swapped_out_or_unallocated=1.8G(100%)\nWritable regions: Total=683.0M written=0K(0%) resident=0K(0%) swapped_out=0K(0%) unallocated=683.0M(100%)\n\n                                VIRTUAL   REGION \nREGION TYPE                        SIZE    COUNT (non-coalesced) \n===========                     =======  ======= \nActivity Tracing                   256K        1 \nKernel Alloc Once                   32K        1 \nMALLOC                           668.2M       17 \nMALLOC guard page                   96K        6 \nSTACK GUARD                       56.0M        1 \nStack                             8176K        1 \n__AUTH                            3749K      553 \n__AUTH_CONST                      38.5M      791 \n__CTF                               824        1 \n__DATA                            34.0M      786 \n__DATA_CONST                      41.9M      803 \n__DATA_DIRTY                      2764K      322 \n__FONT_DATA                          4K        1 \n__LINKEDIT                       899.0M        6 \n__OBJC_RO                         71.1M        1 \n__OBJC_RW                         2168K        1 \n__TEXT                           933.6M      825 \ndyld private memory               4384K        4 \nshared memory                       32K        2 \n===========                     =======  ======= \nTOTAL                              2.7G     4123 \n",
  "legacyInfo" : {
  "threadTriggered" : {
    "queue" : "com.apple.main-thread"
  }
},
  "logWritingSignature" : "34d83b2ebf24b36fb3b60c6ec338147e276afac5",
  "trialInfo" : {
  "rollouts" : [
    {
      "rolloutId" : "60da5e84ab0ca017dace9abf",
      "factorPackIds" : {

      },
      "deploymentId" : 240000008
    },
    {
      "rolloutId" : "63f9578e238e7b23a1f3030a",
      "factorPackIds" : {

      },
      "deploymentId" : 240000005
    }
  ],
  "experiments" : [

  ]
}
}

Model: MacBookAir10,1, BootROM 10151.61.4, proc 8:4:4 processors, 8 GB, SMC 
Graphics: Apple M1, Apple M1, Built-In
Display: Color LCD, 2560 x 1600 Retina, Main, MirrorOff, Online
Memory Module: LPDDR4, Micron
AirPort: spairport_wireless_card_type_wifi (0x14E4, 0x4378), wl0: Aug 26 2023 17:55:53 version 18.20.439.0.7.8.163 FWID 01-f9b9247b
AirPort: 
Bluetooth: Version (null), 0 services, 0 devices, 0 incoming serial ports
Network Service: Wi-Fi, AirPort, en0
USB Device: USB31Bus
USB Device: USB31Bus
Thunderbolt Bus: MacBook Air, Apple Inc.
Thunderbolt Bus: MacBook Air, Apple Inc.

**Comment by TheMoonThatRises** [comment]
The app needs to be resigned. This can be done by setting the application type to something.
