### ISSUE TITLE
[Bug]: Honkai Star Rail character mouth shut while talking

### ISSUE THREAD

**Issue by XuYicong** [PlayCover/PlayCover#1277]
### Describe the bug

In some quests, there are conversations among characters, and in some of them, characters have voice-over but their mouth shut. afaik, the mouth-shapes are auto-generated from audios, using some machine learning techniques. The failure of mouth shape generation indicates some error in the underlying algorithm.

### Steps to reproduce

It happens sometimes but not all the time. Like 10%-20% of all cases. The most recent place I met it is the adventure mission _Let's Go! Aetherium Wars!_ of _Interastral Tournament Festival_. At the beginning of the mission, March 7 talk without opening mouth, but still have face expressions. 

Playcover nightly 570
M1 Pro 16GB

### Expected behaviour

Characters take appropriate mouth actions while talking.

### What version of PlayCover are you using?

Nightly/beta (please specify build number)

### What version of macOS are you using?

Sonoma (macOS 14)

### Issue Language

- [X] Yes my issue is written in English

**Comment by PseudoKingStephy** [comment]
Sounds like a bug in Honkai Star Rail more than a play cover bug to me, did you update the game to see if they fixed it?

**Comment by XuYicong** [comment]
Looks like this is not playcover's issue
