### ISSUE TITLE
[Feature]: Show key on screen

### ISSUE THREAD

**Issue by kang49** [PlayCover/PlayCover#1279]
### Is your feature request related to a problem?

No, But I think it's good for new users who don't remember what kind of keymapping set is, easier to remember.

### Describe the solution you'd like

Just add this feature in setting like "Transparent Keymapping":

Center Text of key like when i'm set keymapping with CMD+K but make it transparent.

<img width="76" alt="image" src="https://github.com/PlayCover/PlayCover/assets/81503963/cc6ce9e1-7e89-4cf5-83b5-0122a212867e">

### Anything else?

-

### Issue Language

- [X] Yes my issue is written in English

**Comment by TheMoonThatRises** [comment]
Duplicate of https://github.com/PlayCover/PlayTools/issues/74 (also that issue goes into a lot of details and ideas so will be tracking that one).
