### ISSUE TITLE
[Game Support]: ONE PIECE Bounty Rush rotation issue

### ISSUE THREAD

**Issue by Mujiko-013** [PlayCover/PlayCover#1281]
### Describe the bug

This is caused by the game's background image being reversed makes it impossible to look around.. But the keyboard button setting position can still be pressed normally. 

<img width="1470" alt="3" src="https://github.com/PlayCover/PlayCover/assets/151986379/cf8f576e-13fd-434f-9b35-ded1bfb14438">

<img width="1470" alt="5" src="https://github.com/PlayCover/PlayCover/assets/151986379/d06d4f36-d252-4520-863f-67b0db5861ed">

### Steps to reproduce

5 months ago I was still able to play normally but after updating MacOS: Sonoma 14.0 I started playing again. There is a problem like this 

Right now I'm using MacOS : Sonoma14.2 (23C64)
and PlayCover nightly (558)

### Expected behaviour

I want the screen to be fixed so that it can play in full screen again.

### What version of PlayCover are you using?

Nightly/beta (please specify build number)

### What version of macOS are you using?

Sonoma (macOS 14)

### Issue Language

- [X] Yes my issue is written in English

**Comment by TheMoonThatRises** [comment]
Try pressing CMD + R.

**Comment by Mujiko-013** [comment]
> Try pressing CMD + R.

Thank you very much! 🥹💞 I didn't think it was possible to do this..
