### ISSUE TITLE
[Bug]:the Keymap doesn't work

### ISSUE THREAD

**Issue by Dariozuo** [PlayCover/PlayCover#1292]
### Describe the bug

The Keymap doesn't work,I tried importing keymap layout,but it doesn't work.

### Steps to reproduce

Right click application
Import keymap layout
Open application
cmd+k,I don't see anything about keymap layout

### Expected behaviour

I wish Keymap layout work

### What version of PlayCover are you using?

3.0.0 beta 2

### What version of macOS are you using?

Sonoma (macOS 14)

### Issue Language

- [X] Yes my issue is written in English

**Comment by TheMoonThatRises** [comment]
Can you double check to make sure you are on version 3.0.0 instead of 2.0.5? There is a known issue of PlayCover rolling back to an older version, which may cause keymappings to not import correctly.

**Comment by cauphenuny** [comment]
I have the same problem. Seems that PlayCover would always start app with its default settings, which ignores the keymap.

**Comment by Dariozuo** [comment]
> 你能仔细检查一下，确保你使用的是3.0.0版本而不是2.0.5吗？有一个已知的PlayCover回滚到旧版本的问题，这可能会导致键映射无法正确导入。

I've solved the problem you mentioned, but the keyboard mapping still doesn't work.

**Comment by Dariozuo** [comment]
> Can you double check to make sure you are on version 3.0.0 instead of 2.0.5? There is a known issue of PlayCover rolling back to an older version, which may cause keymappings to not import correctly.

I've solved the problem you mentioned, but the keyboard mapping still doesn't work.

**Comment by TheMoonThatRises** [comment]
A new version of PlayCover has released. If this issue still occurs, open a new issue.
