### ISSUE TITLE
[Bug]: Extremely weird behaviour of app

### ISSUE THREAD

**Issue by EugenioDV** [PlayCover/PlayCover#1294]
### Describe the bug

Heyo! After installing beta 2 yesterday I was able to select app type in Misc to fix the common bug of apps crashing as soon as you start them however it seems like to day the app reverted itself because I can't set the app type any more, can't play the app and nothing seems to work.

### Steps to reproduce

I am not sure it's easy to reproduce but here are the steps I took
1) Have playtools beta 3.0.0 installed on MacOS Sonoma 14.2.1
2) Verify you cannot play an app and cannot play an app (in my case: legends of runeterra) because it immediately closes
3) Verify you cannot set the app type (yadda.yadda.com.games is not an option in Misc) 
4) Uninstall and install PlayCover Beta 3.0.0 2 
5) Verify you can actually set the app type to yadda.yadda.com.games and the app works correctly
6) The next day open the app, it will prompt you to install stuff from XCode even tho it just worked
7) After failing the installation the app automagically reverts to step 2) version even tho it was working the day before!!

### Expected behaviour

The app stays the same and does not mess itself up over a night

### What version of PlayCover are you using?

3.0.0 beta 2

### What version of macOS are you using?

Sonoma (macOS 14)

### Issue Language

- [X] Yes my issue is written in English

**Comment by TheMoonThatRises** [comment]
Same issue as #1299. See this comment: https://github.com/PlayCover/PlayCover/issues/1299#issuecomment-1870385673.
