### ISSUE TITLE
[Bug]: Image does not show while using custom Discord activity

### ISSUE THREAD

**Issue by MEMORIEmusic** [PlayCover/PlayCover#1295]
### Describe the bug

While using custom Discord activity, the custom image won't show up.
(I have application ID written in the field, I decided to hide it in the screenshot)

<img width="1217" alt="Screenshot 2023-12-25 at 17 33 19" src="https://github.com/PlayCover/PlayCover/assets/79436281/16d483cf-f948-4d54-b943-755b6ca9e4fc">
<img width="266" alt="Screenshot 2023-12-25 at 17 33 47" src="https://github.com/PlayCover/PlayCover/assets/79436281/1291c624-0d85-4a67-9840-cb2682e02be4">

### Steps to reproduce

1. Set up custom Discord activity
2. Paste an imagur image link in the "Image" section

### Expected behaviour

Custom image to show up

![image](https://github.com/PlayCover/PlayCover/assets/79436281/5ca83ba2-10b2-43dc-a96b-ce414a5c11f9)

### What version of PlayCover are you using?

3.0.0 beta 2

### What version of macOS are you using?

Sonoma (macOS 14)

### Issue Language

- [X] Yes my issue is written in English

**Comment by TheMoonThatRises** [comment]
The link put in the image field isn't actually an image (its the link to the website). Works for me when using a direct link to the png file: https://i.imgur.com/gjUvauj.png.

**Comment by CattorBaconus** [comment]
Necroposting, sure, but can you guys tell me how to get the application ID? Do I have to build and sync it up with my running game using the developer portal and the DiscordGameSDK?

**Comment by MEMORIEmusic** [comment]
> Necroposting, sure, but can you guys tell me how to get the application ID? Do I have to build and sync it up with my running game using the developer portal and the DiscordGameSDK?

You need to create an app in [Discord Developer Portal](https://discord.com/developers/applications) and use its application ID

**Comment by CattorBaconus** [comment]
> > Necroposting, sure, but can you guys tell me how to get the application ID? Do I have to build and sync it up with my running game using the developer portal and the DiscordGameSDK?
> 
> You need to create an app in [Discord Developer Portal](https://discord.com/developers/applications) and use its application ID

I see, however, how do you actually sync up the game? Cuz what seems to be happening is that since PlayCover specifies custom settings for every individual bottle you make, when you go and play that bottle PlayCover just takes whatever random application ID you have and slaps on custom settings. Is there any way to actually sync up the Developer API app to the running game itself?
