### ISSUE TITLE
[Bug]:When I launch the app, it starts in an enlarged state and I can't revert it back.

### ISSUE THREAD

**Issue by sfc0169** [PlayCover/PlayCover#1296]
### Describe the bug

<img width="1512" alt="スクリーンショット 2023-12-25 23 34 42" src="https://github.com/PlayCover/PlayCover/assets/154720983/1a1e504b-ee83-4aff-a62d-0994d17f5fe2">

### Steps to reproduce

Download and open Uma Musume.

### Expected behaviour

When I open the app, it starts in an enlarged state and I can't do anything.

### What version of PlayCover are you using?

3.0.0 beta 2

### What version of macOS are you using?

Sonoma (macOS 14)

### Issue Language

- [X] Yes my issue is written in English

**Comment by TheMoonThatRises** [comment]
Try changing the app's resolution to `App Default` and checking the `Fix window display issue` checkbox.

**Comment by GardieM** [comment]
i have the same issue 
<img width="528" alt="image" src="https://github.com/PlayCover/PlayCover/assets/171927022/15e94bbc-44f0-4c89-a712-42f3447ef68f">
<img width="1501" alt="image" src="https://github.com/PlayCover/PlayCover/assets/171927022/5d1c9401-7438-4f12-b458-07cb962ee030">
and cannot do or touch anything 
help me plz
