### ISSUE TITLE
[Bug]: Version rollback itself to 2.0.5 when relaunch

### ISSUE THREAD

**Issue by TengShao** [PlayCover/PlayCover#1299]
### Describe the bug

I install lastest version 3.0.0 (233) to replace previous version (maybe 2.x), everything works fine. BUT, when I relaunch PlayCover (after quit it for about couple minutes), I can't launch any games. Then I notice the version rollback itself to 2.0.5, and this version has issue with MacOS 14.

### Steps to reproduce

Quit  PlayCover - hold for couple minutes - Launch PlayCover

### Expected behaviour

Version should stay at 3.0.0

### What version of PlayCover are you using?

3.0.0 beta 2

### What version of macOS are you using?

Sonoma (macOS 14)

### Issue Language

- [X] Yes my issue is written in English

**Comment by MEMORIEmusic** [comment]
Since version 3.0 is not signed(yet), the auto-updater recognises 2.0.5 as the latest version and not 3.0. So turn off auto-update.
