### ISSUE TITLE
[Bug]: Framerate dropping when switching to fullscreen

### ISSUE THREAD

**Issue by KyroOW** [PlayCover/PlayCover#1300]
### Describe the bug

I launch Genshin Impact, default resolution, the game is smooth, even at 120 fps in the game, however when i switch to fullscreen mode, i will have random framerate drops where my fps will be cut in half for like 5 seconds before being smooth again, then back to being cut in half, with some stutters as well, making the experience terrible.

What's weird is that Metal HUD reports the framerate as still being 120 fps, 120hz etc, nothing changes there

I absolutely haven't found anything about this online, i'm new with macs and macOS in general and the only thing i could think of was to disable game mode which did not help.

I'm using a MacBook Pro 14" M2 Pro with 16gb of ram running macOS Sonoma.

### Steps to reproduce

Launch Genshin Impact, login to the game, play around for a bit, game is smooth.
Set the game to fullscreen mode, game framerate gets halved (it feels halved but Metal HUD still shows 120fps) for short periods of time constantly, with stutters.

### Expected behaviour

Game should remain smooth like in windowed mode

### What version of PlayCover are you using?

3.0.0 beta 2

### What version of macOS are you using?

Sonoma (macOS 14)

### Issue Language

- [X] Yes my issue is written in English

**Comment by qchenqizhi** [comment]
The problem was solved when I turned off ProMotion, Settings>Displays>Refresh rate>60Hz

**Comment by TheMoonThatRises** [comment]
Try the solution first, if it doesn't work, let me know and I'll reopen this issue.

**Comment by KyroOW** [comment]
Which solution ? If you meant the one above, that's absolutely not a solution, the issue is: if you fullscreen the game window, you drop from 120fps to 60fps from time to time, disabling promotion would effectively halve the framerate constantly, which is even worse.
