### ISSUE TITLE
[Feature]: Automactic volume reduction/mute when audio is played from external source

### ISSUE THREAD

**Issue by MEMORIEmusic** [PlayCover/PlayCover#1305]
### Is your feature request related to a problem?

While playing music(for e.g from apple music, spotify, youtube, etc) the in-game sounds can be annoying

### Describe the solution you'd like

Have a checkbox, which when enabled will automatically mute all in-game sounds when audio is played from an external source

### Anything else?

No

### Issue Language

- [X] Yes my issue is written in English

**Comment by MainasuK** [comment]
The macOS doesn't have an EQ control for volume. But some random apps provide this feature.
> https://github.com/kyleneideck/BackgroundMusic
