### ISSUE TITLE
[App Support]: Procreate

### ISSUE THREAD

**Issue by zomars** [PlayCover/PlayCover#1308]
### App Store link

https://apps.apple.com/es/app/procreate/id425073498

### Current issues

- [ ] App fails to install
- [X] App fails to open
- [ ] App crashes randomly during usage
- [ ] App experiences graphical issues or broken UI
- [ ] App fails to connect to servers
- [ ] Other

### More details

Installed successfully but getting this error when trying to open: "this version of the app cannot be used in this macOS version"

<img width="304" alt="image" src="https://github.com/PlayCover/PlayCover/assets/3504472/8196cd28-d71d-4b85-bd75-ebe79b58d8e0">

### What version of PlayCover are you using?

3.0.0 beta 2

### What version of macOS are you using?

Sonoma (macOS 14)

### Issue Language

- [X] Yes my issue is written in English

**Comment by lwyczawski** [comment]
Hey, do you have any progress on this one? @zomars

**Comment by TheMoonThatRises** [comment]
Procreate is a paid app so we will not provide support for this app.
