### ISSUE TITLE
[App Support]: 光遇

### ISSUE THREAD

**Issue by VKQC** [PlayCover/PlayCover#1309]
### App Store link

(https://apps.apple.com/cn/app/%E5%85%89-%E9%81%87/id1344733855)

### Current issues

- [ ] App fails to install
- [x] App fails to open
- [ ] App crashes randomly during usage
- [ ] App experiences graphical issues or broken UI
- [ ] App fails to connect to servers
- [ ] Other

### More details

[Sky-iOS-Gold-2024-01-05-095301.ips.txt](https://github.com/PlayCover/PlayCover/files/13837084/Sky-iOS-Gold-2024-01-05-095301.ips.txt)

### What version of PlayCover are you using?

3.0.0 beta 2

### What version of macOS are you using?

Sonoma (macOS 14)

### Issue Language

- [X] Yes my issue is written in English

**Comment by greatoe** [comment]
I have the same issue and still can't open the app.  Would you please share how do you solve this? @VKQC
