### ISSUE TITLE
[Bug]:  Joystick not work when press single key on PUBG Mobile

### ISSUE THREAD

**Issue by okiookio** [PlayCover/PlayCover#1312]
### Describe the bug

I have add the joystick.
then press single key A/W/S/D but not thing.

https://github.com/PlayCover/PlayCover/assets/4751517/0d03d33e-9169-4c78-9e1d-4b033f75c19c

### Steps to reproduce

then try with start one key first ex: S+A -> move left, S+W move up, S+D move right, W+S move down

### Expected behaviour

only press A to move left, W to move up, D to move right and S to move down

### What version of PlayCover are you using?

3.0.0 beta 2

### What version of macOS are you using?

Sonoma (macOS 14)

### Issue Language

- [X] Yes my issue is written in English

**Comment by MEMORIEmusic** [comment]
Make the WASD Pad big. Like half of the screen big(it has a hidden feature)

**Comment by TheMoonThatRises** [comment]
Half the screen is a bit of an exaggeration. More like double it's current size, or until it stops giving the issue.

**Comment by kang49** [comment]
> Make the WASD Pad big. Like half of the screen big(it has a hidden feature)

How to make pad bigger?

**Comment by Robert-luo107** [comment]
I Made the WASD PAD very big, about half of the screen, but still need press S+A ->move left, is there any other method to solve this problem?  I want that :::Only press A to move left,W to move up, D to move right and S to move down
