### ISSUE TITLE
[Feature]: Can open the same software simultaneously

### ISSUE THREAD

**Issue by anuiun** [PlayCover/PlayCover#1313]
### Is your feature request related to a problem?

Can I import the same IPA into it to generate two identical applications, so that you can play a game at the same time

### Describe the solution you'd like

none

### Anything else?

none

### Issue Language

- [X] Yes my issue is written in English

**Comment by TheMoonThatRises** [comment]
See https://github.com/PlayCover/PlayCover/issues/349#issuecomment-1250046948. Short answer: no, we won't provide support.
