### ISSUE TITLE
[Bug]: App not working on MacOS Monterey

### ISSUE THREAD

**Issue by akss5768** [PlayCover/PlayCover#1317]
### Describe the bug

When I installed the same IPA file on Mac OS 14.2 and Mac OS 12.6, they encountered different situations. In Mac OS 14.2, I was able to successfully open and run the app, but on Mac OS 12.6, the app could not be opened properly and there were no error reports presented, so I was unable to provide accurate error reports. After checking the system logs, I found that the app was written in Flutter. Is this caused by Flutter. Due to some personal reasons, my Mac OS 12.6 cannot be upgraded. I hope you can provide me with a good solution. Thank you

### Steps to reproduce

Run directly after installation

### Expected behaviour

Run directly after installation

### What version of PlayCover are you using?

Nightly/beta (please specify build number)

### What version of macOS are you using?

Monterey (macOS 12)

### Issue Language

- [X] Yes my issue is written in English

**Comment by Depal1** [comment]
Could you please detail which PlayCover version or build numbers were you before and after this issue?

**Comment by akss5768** [comment]
> Could you please detail which PlayCover version or build numbers were you before and after this issue?

My Playcover Version is 3.0.0 (602). Perhaps you can reproduce this issue. This app can be opened normally on MacOS 14.2, but cannot be opened on MacOS 12.6. Here is its download address https://decrypt.day/app/id1481774307

**Comment by Depal1** [comment]
Sadly I don't have access to a macOS 12 environment at the moment. Could you try launching the app in macOS 12.6 with PlayCover [3.0.0 beta-1](https://github.com/PlayCover/PlayCover/releases/tag/3.0.0-beta.1)?

**Comment by Depal1** [comment]
@akss5768 Did it work?

**Comment by akss5768** [comment]
> Sadly I don't have access to a macOS 12 environment at the moment. Could you try launching the app in macOS 12.6 with PlayCover [3.0.0 beta-1](https://github.com/PlayCover/PlayCover/releases/tag/3.0.0-beta.1)?

It doesn't seem to work. In the end, I suggested that my friend upgrade her macos system and solve the problem, so I closed this issue
