### ISSUE TITLE
[Feature]: sign in with apple id

### ISSUE THREAD

**Issue by akss5768** [PlayCover/PlayCover#1325]
### Is your feature request related to a problem?

how to sign in with apple id or other third-part to sign in 

### Describe the solution you'd like

how to sign in with apple id or other third-part to sign in 

### Anything else?

no

### Issue Language

- [X] Yes my issue is written in English

**Comment by MEMORIEmusic** [comment]
Apple ID login is broken/janky. Use twitter or other means to login instead. Steps to login can be found on the [docs](https://docs.playcover.io/getting_started/troubleshoot_login)

**Comment by toohotz** [comment]
Going to link my comment that I went into detail [here](https://github.com/PlayCover/PlayCover/issues/1428#issuecomment-2240406353) about the _why_ this doesn't work for most and how it would work for someone that has an  dev certificate with the  ID that they would like to use to sign in to the App Store against.

**Comment by emirozmen07** [comment]
You can register to some apps only with apple ID, that would be great addition if it's possible.
