### ISSUE TITLE
[Game Support] : ONE PIECE Bounty Rush " Quit Suddenly "

### ISSUE THREAD

**Issue by Mujiko-013** [PlayCover/PlayCover#1327]
### Describe the bug

I enter the game normally. But it didn't take long to get in. The game suddenly quit and a warning came up.

<img width="503" alt="11" src="https://github.com/PlayCover/PlayCover/assets/151986379/0348d253-5859-4510-a1d1-baaf36d95716">

<img width="502" alt="12" src="https://github.com/PlayCover/PlayCover/assets/151986379/ca28af60-cba5-46dd-af40-bf56a76c3638">

### Steps to reproduce

Before that, I could still play the game normally. But when the next day came, there was a problem. So I think it's a matter of changing the game? If I wait for the game to update new files, will it go back to normal?

Right now I'm using MacOS : Sonoma14.2.1 (23C71)
and PlayCover nightly (558)

### Expected behaviour

I want the game to play normally again.

### What version of PlayCover are you using?

Nightly/beta (please specify build number)

### What version of macOS are you using?

Sonoma (macOS 14)

### Issue Language

- [X] Yes my issue is written in English

**Comment by TheMoonThatRises** [comment]
You need to resign the app. You can do this by setting the application type to something other than the current value.

**Comment by Mujiko-013** [comment]
> You need to resign the app. You can do this by setting the application type to something other than the current value.

sorry I was gone for many days..🥲  I tried reinstalling and changing the settings but it was still the same.. So I want to know if I wait for the new version of the game to update and then install it again, will it go back to normal?
