### ISSUE TITLE
[Bug]: Typing in game

### ISSUE THREAD

**Issue by MhAmerian** [PlayCover/PlayCover#1336]
### Describe the bug
I've installed pubg, and run it from app library, not playcover. in section that players must type a username before they can play, I can't type anything in the game, smartkeymap is on if you want to know
Mac OS 14.0
PlayCover nightly 611

**Comment by TheMoonThatRises** [comment]
Duplicate of #1315.

**Comment by colette-exe** [comment]
Hello! I tried pressing `ctrl` while typing and it worked! I also tried letting go of `ctrl` and it also worked.
