### ISSUE TITLE
[Bug]: Only when I try to install HOKAI:STAR RAIL will I get the error

### ISSUE THREAD

**Issue by A5yncX** [PlayCover/PlayCover#1338]
### Describe the bug

**Only** when I try to install HOKAI:STAR RAIL will I get the error. Everything else is normal.
Error message located in the installation failure popup: 
![](https://img.asyncx.top/images/202401192323116.png)

### Steps to reproduce

Use the Decrypt source to install, click download and report an error. Other applications are normal.

### Expected behaviour

Normal operation.

### Crash log

```shell
[/var/folders/x8/kq0jczz97_5c6cz4xdjbvvnh0000gn/T/TemporaryItems/NSIRD_PlayCover_GZvBof/view.html]
End-of-central-directory signature not found.  Either this file is not
a zipfile, or it constitutes one disk of a multi-part archive.  In the
latter case the central directory and zipfile comment will be found on
the last disk(s) of this archive.
unzip:  cannot find zipfile directory in one of /var/folders/x8/kq0jczz97_5c6cz4xdjbvvnh0000gn/T/TemporaryItems/NSIRD_PlayCover_GZvBof/view.html or
/var/folders/x8/kq0jczz97_5c6cz4xdjbvvnh0000gn/T/TemporaryItems/NSIRD_PlayCover_GZvBof/view.html.zip, and cannot find /var/folders/x8/kq0jczz97_5c6cz4xdjbvvnh0000gn/T/TemporaryItems/NSIRD_PlayCover_GZvBof/view.html.ZIP, period.
```

### What version of PlayCover are you using?

3.0.0 beta 2

### What version of macOS are you using?

Sonoma (macOS 14)

### Issue Language

- [X] Yes my issue is written in English

**Comment by TheMoonThatRises** [comment]
Download directly from source. That error occurs because PlayCover is unable to get the direct link to the IPA.

**Comment by Catta1997** [comment]
#1472
