### ISSUE TITLE
[Bug]: can't import ipa file

### ISSUE THREAD

**Issue by akss5768** [PlayCover/PlayCover#1347]
### Describe the bug

when i try to import ipa file ,it say "An error occurred!"

### Steps to reproduce

when i try to import ipa file ,it say "An error occurred!"
<img width="556" alt="iShot_2024-01-26_03 36 55" src="https://github.com/PlayCover/PlayCover/assets/13168678/e386b1e3-0cd9-4cd4-930f-0b19d8dff8ba">
![iShot_2024-01-26_03 40 18](https://github.com/PlayCover/PlayCover/assets/13168678/e69441f8-0a08-40d9-a3d4-ad5783069e73)

### Expected behaviour

when i try to import ipa file ,it say "An error occurred!"
<img width="556" alt="iShot_2024-01-26_03 36 55" src="https://github.com/PlayCover/PlayCover/assets/13168678/ba156f89-1e8f-4652-a241-bc686606a473">
![iShot_2024-01-26_03 40 18](https://github.com/PlayCover/PlayCover/assets/13168678/ba0ee901-1efb-4dc0-be0a-f6766ca5ea43)

### Crash log

```shell
-------------------------------------
Translated Report (Full Report Below)
-------------------------------------

Incident Identifier: BD5D591A-CFD3-47B1-BC94-5EBE659A8E2E
CrashReporter Key:   51555ED4-56B9-0E4D-C7D9-817890F6CA12
Hardware Model:      Mac14,9
Process:             jkchess [60045]
Path:                /private/var/folders/*/jkchess.app/jkchess
Identifier:          com.tencent.jkchess.AGNYU52N3U
Version:             1.6.17 (1028)
AppStoreTools:       15C5500a
Code Type:           ARM-64 (Native)
Role:                Background
Parent Process:      launchd [1]
Coalition:           com.tencent.jkchess.AGNYU52N3U [32132]

Date/Time:           2024-01-26 03:33:04.6963 +0800
Launch Time:         2024-01-26 03:31:01.2071 +0800
OS Version:          macOS 14.2.1 (23C71)
Release Type:        User
Report Version:      104

Exception Type:  EXC_BAD_ACCESS (SIGSEGV)
Exception Subtype: KERN_INVALID_ADDRESS at 0x000000000000002c
Exception Codes: 0x0000000000000001, 0x000000000000002c
VM Region Info: 0x2c is not in any region.  Bytes before following region: 105553653137364
      REGION TYPE                    START - END         [ VSIZE] PRT/MAX SHRMOD  REGION DETAIL
      UNUSED SPACE AT START
--->  
      MALLOC_NANO              600020000000-600040000000 [512.0M] rw-/rwx SM=PRV  
Triggered by Thread:  0
```

### What version of PlayCover are you using?

Nightly/beta Version 3.0.0 (617)

### What version of macOS are you using?

Sonoma (macOS 14)

### Issue Language

- [X] Yes my issue is written in English

**Comment by akss5768** [comment]
BTW,when I installed using sideloady, it was successful

**Comment by AAAAsir1** [comment]
I also have this bug and I hope it can be resolved.

**Comment by mayifan** [comment]
> BTW,when I installed using sideload, it was successful

I also encountered this problem, could you tell me how to use sideload installation?

**Comment by happy1wawayu** [comment]
I also encountered this problem, could you tell me how to use sideload installation?

**Comment by LinGuoGuoQaQ** [comment]
+1

**Comment by licat233** [comment]
+1

**Comment by akss5768** [comment]
It should be an issue with the IPA file. I tried to obtain the unpacked IPA file through channels. The issue has been resolved

**Comment by shycomet** [comment]
> > BTW,when I installed using sideload, it was successful
> 
> I also encountered this problem, could you tell me how to use sideload installation?

https://www.bilibili.com/video/BV1C64y1w7Di/
