### ISSUE TITLE
[Bug]: Permission denied when installing IPA

### ISSUE THREAD

**Issue by Mr-MaoZi** [PlayCover/PlayCover#1349]
### Describe the bug

![501706261335_ pic](https://github.com/PlayCover/PlayCover/assets/89823850/4503e83e-b986-4662-b917-62e312dab01e)

### Steps to reproduce

I downloaded the IPA in decrypt, but when I poured it in, there was an error in the package

### Expected behaviour

When installing the IPA file, there was an error in the package and it cannot be installed

### What version of PlayCover are you using?

3.0.0 beta 2

### What version of macOS are you using?

Sonoma (macOS 14)

### Issue Language

- [X] Yes my issue is written in English

**Comment by Mr-MaoZi** [comment]
版本14.1（版号23B74）
Installing PlayTools
Copying PlayTools to Frameworks

xattr: [Errno 13] Permission denied: '/var/folders/vc/s82jr1l57g1cv8ns84th85hr0000gn/T/TemporaryItems/NSIRD_PlayCover_JxIQQ6/Payload/jkchess.app/jkchess'
xattr: [Errno 13] Permission denied: '/var/folders/vc/s82jr1l57g1cv8ns84th85hr0000gn/T/TemporaryItems/NSIRD_PlayCover_JxIQQ6/Payload/jkchess.app/PlugIns/Notification.appex/Notification'
xattr: [Errno 13] Permission denied: '/var/folders/vc/s82jr1l57g1cv8ns84th85hr0000gn/T/TemporaryItems/NSIRD_PlayCover_JxIQQ6/Payload/jkchess.app/Frameworks/GCloudCore.framework/GCloudCore'
xattr: [Errno 13] Permission denied: '/var/folders/vc/s82jr1l57g1cv8ns84th85hr0000gn/T/TemporaryItems/NSIRD_PlayCover_JxIQQ6/Payload/jkchess.app/Frameworks/crosCurl.framework/crosCurl'
xattr: [Errno 13] Permission denied: '/var/folders/vc/s82jr1l57g1cv8ns84th85hr0000gn/T/TemporaryItems/NSIRD_PlayCover_JxIQQ6/Payload/jkchess.app/Frameworks/CrashSight.framework/CrashSight'
xattr: [Errno 13] Permission denied: '/var/folders/vc/s82jr1l57g1cv8ns84th85hr0000gn/T/TemporaryItems/NSIRD_PlayCover_JxIQQ6/Payload/jkchess.app/Frameworks/kgvmp_dy.framework/kgvmp_dy'
xattr: [Errno 13] Permission denied: '/var/folders/vc/s82jr1l57g1cv8ns84th85hr0000gn/T/TemporaryItems/NSIRD_PlayCover_JxIQQ6/Payload/jkchess.app/Frameworks/tersafe.framework/tersafe'
xattr: [Errno 13] Permission denied: '/var/folders/vc/s82jr1l57g1cv8ns84th85hr0000gn/T/TemporaryItems/NSIRD_PlayCover_JxIQQ6/Payload/jkchess.app/Frameworks/TDataMaster.framework/TDataMaster'
xattr: [Errno 13] Permission denied: '/var/folders/vc/s82jr1l57g1cv8ns84th85hr0000gn/T/TemporaryItems/NSIRD_PlayCover_JxIQQ6/Payload/jkchess.app/Frameworks/MSDKWebView.framework/MSDKWebView'
xattr: [Errno 13] Permission denied: '/var/folders/vc/s82jr1l57g1cv8ns84th85hr0000gn/T/TemporaryItems/NSIRD_PlayCover_JxIQQ6/Payload/jkchess.app/Frameworks/TDMIDFA.framework/TDMIDFA'
xattr: [Errno 13] Permission denied: '/var/folders/vc/s82jr1l57g1cv8ns84th85hr0000gn/T/TemporaryItems/NSIRD_PlayCover_JxIQQ6/Payload/jkchess.app/Frameworks/Hippy.framework/Hippy'
xattr: [Errno 13] Permission denied: '/var/folders/vc/s82jr1l57g1cv8ns84th85hr0000gn/T/TemporaryItems/NSIRD_PlayCover_JxIQQ6/Payload/jkchess.app/Frameworks/MSDKSensitivity.framework/MSDKSensitivity'
xattr: [Errno 13] Permission denied: '/var/folders/vc/s82jr1l57g1cv8ns84th85hr0000gn/T/TemporaryItems/NSIRD_PlayCover_JxIQQ6/Payload/jkchess.app/Frameworks/tgpa_wrapper.framework/tgpa_wrapper'
xattr: [Errno 13] Permission denied: '/var/folders/vc/s82jr1l57g1cv8ns84th85hr0000gn/T/TemporaryItems/NSIRD_PlayCover_JxIQQ6/Payload/jkchess.app/Frameworks/MSDKDns.framework/MSDKDns'
xattr: [Errno 13] Permission denied: '/var/folders/vc/s82jr1l57g1cv8ns84th85hr0000gn/T/TemporaryItems/NSIRD_PlayCover_JxIQQ6/Payload/jkchess.app/Frameworks/MSDKTDM.framework/MSDKTDM'
xattr: [Errno 13] Permission denied: '/var/folders/vc/s82jr1l57g1cv8ns84th85hr0000gn/T/TemporaryItems/NSIRD_PlayCover_JxIQQ6/Payload/jkchess.app/Frameworks/CrashSightCore.framework/CrashSightCore'
xattr: [Errno 13] Permission denied: '/var/folders/vc/s82jr1l57g1cv8ns84th85hr0000gn/T/TemporaryItems/NSIRD_PlayCover_JxIQQ6/Payload/jkchess.app/Frameworks/MSDKSystem.framework/MSDKSystem'
xattr: [Errno 13] Permission denied: '/var/folders/vc/s82jr1l57g1cv8ns84th85hr0000gn/T/TemporaryItems/NSIRD_PlayCover_JxIQQ6/Payload/jkchess.app/Frameworks/GCloud.framework/GCloud'
xattr: [Errno 13] Permission denied: '/var/folders/vc/s82jr1l57g1cv8ns84th85hr0000gn/T/TemporaryItems/NSIRD_PlayCover_JxIQQ6/Payload/jkchess.app/Frameworks/MSDKLBS.framework/MSDKLBS'
xattr: [Errno 13] Permission denied: '/var/folders/vc/s82jr1l57g1cv8ns84th85hr0000gn/T/TemporaryItems/NSIRD_PlayCover_JxIQQ6/Payload/jkchess.app/Frameworks/CrashSightAdapter.framework/CrashSightAdapter'
xattr: [Errno 13] Permission denied: '/var/folders/vc/s82jr1l57g1cv8ns84th85hr0000gn/T/TemporaryItems/NSIRD_PlayCover_JxIQQ6/Payload/jkchess.app/Frameworks/PluginCrosCurl.framework/PluginCrosCurl'
xattr: [Errno 13] Permission denied: '/var/folders/vc/s82jr1l57g1cv8ns84th85hr0000gn/T/TemporaryItems/NSIRD_PlayCover_JxIQQ6/Payload/jkchess.app/Frameworks/GRobot.framework/GRobot'
xattr: [Errno 13] Permission denied: '/var/folders/vc/s82jr1l57g1cv8ns84th85hr0000gn/T/TemporaryItems/NSIRD_PlayCover_JxIQQ6/Payload/jkchess.app/Frameworks/MSDKCore.framework/MSDKCore'
xattr: [Errno 13] Permission denied: '/var/folders/vc/s82jr1l57g1cv8ns84th85hr0000gn/T/TemporaryItems/NSIRD_PlayCover_JxIQQ6/Payload/jkchess.app/Frameworks/TDMASA.framework/TDMASA'
xattr: [Errno 13] Permission denied: '/var/folders/vc/s82jr1l57g1cv8ns84th85hr0000gn/T/TemporaryItems/NSIRD_PlayCover_JxIQQ6/Payload/jkchess.app/Frameworks/MSDKAdapter.framework/MSDKAdapter'
xattr: [Errno 13] Permission denied: '/var/folders/vc/s82jr1l57g1cv8ns84th85hr0000gn/T/TemporaryItems/NSIRD_PlayCover_JxIQQ6/Payload/jkchess.app/Frameworks/enq_transceiver_dy.framework/enq_transceiver_dy'
xattr: [Errno 13] Permission denied: '/var/folders/vc/s82jr1l57g1cv8ns84th85hr0000gn/T/TemporaryItems/NSIRD_PlayCover_JxIQQ6/Payload/jkchess.app/Frameworks/GPM_dylib.framework/GPM_dylib'
xattr: [Errno 13] Permission denied: '/var/folders/vc/s82jr1l57g1cv8ns84th85hr0000gn/T/TemporaryItems/NSIRD_PlayCover_JxIQQ6/Payload/jkchess.app/Frameworks/CrashSightPlugin.framework/CrashSightPlugin'
xattr: [Errno 13] Permission denied: '/var/folders/vc/s82jr1l57g1cv8ns84th85hr0000gn/T/TemporaryItems/NSIRD_PlayCover_JxIQQ6/Payload/jkchess.app/Frameworks/GVoice_dylib.framework/GVoice_dylib'

**Comment by huhu415** [comment]
i have this bug too ,when i install this https://decrypt.day/app/id1478101301 game .

**Comment by CCCCCCCXH** [comment]
> i have this bug too ,when i install this https://decrypt.day/app/id1478101301 game .
same problem here

**Comment by Zixi0124** [comment]
same problem

**Comment by Anan-X** [comment]
me too

**Comment by Junelce** [comment]
me tooooooooooooo

**Comment by belikers** [comment]
Is this a problem of not having permission to modify a file? I've had this happen to me as well.

**Comment by zhang704** [comment]
yes, me too~

**Comment by licat233** [comment]
I have successfully installed it.
![image](https://github.com/PlayCover/PlayCover/assets/55393143/55ee0084-7a9d-4207-8bf8-8bbed0696fc3)
Share my own solution：
1. Use Keka to decompression the ‘.ipa’ file,  you will get a 'Payload' folder;
2. Use Keka to compress the 'Payload' folder，get a  'Payload.zip' file;
3. Renaming the 'Payload. zip' file to 'Payload. ipa';
4. Okay, now you can use PlayCover to install this 'Payload. ipa' file.

**Comment by Red-Asuka** [comment]
Hi @licat233, can you share the download address of the IPA file? Thank you.

**Comment by zhang704** [comment]
@licat233 no, i can't

**Comment by licat233** [comment]
> @licat233 no, i can't

Try using Keka to extract and compress, that's how I did it.

**Comment by licat233** [comment]
> Hi @licat233, can you share the download address of the IPA file? Thank you.

Of course, [https://decrypt.day/app/id1478101301](url)

**Comment by zhang704** [comment]
@licat233  using keka again, i'm OK ~ thanks

**Comment by licat233** [comment]
> @licat233 using keka again, i'm OK ~ thanks

Happy for you

**Comment by Red-Asuka** [comment]
> I have successfully installed it. ![image](https://private-user-images.githubusercontent.com/55393143/300151827-55ee0084-7a9d-4207-8bf8-8bbed0696fc3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDYzMzExMTUsIm5iZiI6MTcwNjMzMDgxNSwicGF0aCI6Ii81NTM5MzE0My8zMDAxNTE4MjctNTVlZTAwODQtN2E5ZC00MjA3LThiZjgtOGJiZWQwNjk2ZmMzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTI3VDA0NDY1NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWRjMTc1ZjU3Y2RjMzBlOTA2MDJjMGRlMjgwM2ZhODlhZTRhMjAxNmNjYjA0YjY0MDhjYWUxMDQ5YTJhNTBhY2MmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.aeSsI7pPMOwgbmJ9YfPpADq1vqw-Dj986dZXWNyp2Jc) Share my own solution：
> 
> 1. Use Keka to unzip the ‘.ipa’ file,  you will get a 'deploy' folder;
> 2. Use Keka to compress the 'deploy' folder，get a  'deploy.zip' file;
> 3. Renaming the 'deploy. zip' file to 'deploy. ipa';
> 4. Okay, now you can use PlayCover to install this 'deploy. ipa' file.

Thank you for sharing. I have also successfully installed it. By the way, if you still cannot install it using this method, try executing `chmod -R 777 deploy` to modify the folder permissions after step two, and then proceed with the subsequent steps.

**Comment by belikers** [comment]
<img width="1112" alt="截屏2024-01-27 13 12 31" src="https://github.com/PlayCover/PlayCover/assets/109145789/d813c3eb-e491-498b-b2d6-7f164a9c6412">
After installation, it still doesn't work

**Comment by belikers** [comment]
After installation, it still doesn't work
<img width="1112" alt="截屏2024-01-27 13 12 31" src="https://github.com/PlayCover/PlayCover/assets/109145789/99973ed5-a8dc-480a-a5d8-e542d7d73e3e">

**Comment by Anan-X** [comment]
lt`s  ok!

**Comment by licat233** [comment]
> After installation, it still doesn't work <img alt="截屏2024-01-27 13 12 31" width="1112" src="https://private-user-images.githubusercontent.com/109145789/300156433-99973ed5-a8dc-480a-a5d8-e542d7d73e3e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDYzMzQ1NDEsIm5iZiI6MTcwNjMzNDI0MSwicGF0aCI6Ii8xMDkxNDU3ODkvMzAwMTU2NDMzLTk5OTczZWQ1LWE4ZGMtNDgwYS1hNWQ4LWU1NDJkN2Q3M2UzZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTI3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDEyN1QwNTQ0MDFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05NjdhYmU2MTU2NmM4OTE2YzhlMTJhOTdjZjZjNWRiZmUxYjM3Mjc5YTFmZTJhMTNkYTRhM2RiOWRjNjVlMzIyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.SrGrCXttLQ4__aStLrFFyQcZF0fYnbOicrAK5upW72I">

Your file may be damaged. Try again, and it's best to use KeKa to decompress and compress the IPA file.Remember to make the correct settings, otherwise the same problem will occur as well.

**Comment by bysyc** [comment]
> 你好@licat233，可以分享一下IPA文件的下载地址吗？谢谢。

https://dl-premier.decrypt.day/f/alcb53a9cb0569868b6b9aa2719d5138e5e22f68072ee71db973e4ddd8b9584e6681abf389cf341440752787290a81108317d954992b2938b87f013b714d5f735da191fb2967c133f10e62c7968713199fd06faeb6d4976caceb7350aee63e1ea19c511b81fc592aace6fce9fad3878ffdacec92730be39fb57ac3184fd527cd0d4214088ba593c303747a94ee553ec15a505cb3508c15b2396275fe124611d2c0c5a878180b9422735524679ed885c26fae05323a0be070e10991d935be80ea050a694c0d33285d261e44f1cdb74d7a66da3e3039c4ed5f46975a24a65fdc9eb4ae899736/request/id1478101301/com.tencent.jkchess_1.6.17_1028__und3fined.ipa?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Content-Sha256=UNSIGNED-PAYLOAD&X-Amz-Credential=FPGLE8AQKN6QYKNA5BCY%2F20211204%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Date=20240127T155407Z&X-Amz-Expires=10800&X-Amz-Signature=7b5f353a7c409f872dacd72364f1bf9a937c577b3bdc27e9fe06f48298bf8c47&X-id=GetObject

**Comment by bysyc** [comment]
https://dl-premier.decrypt.day/f/alcb53a9cb0569868b6b9aa2719d5138e5e22f68072ee71db973e4ddd8b9584e6681abf389cf341440752787290a81108317d954992b2938b87f013b714d5f735da191fb2967c133f10e62c7968713199fd06faeb6d4976caceb7350aee63e1ea19c511b81fc592aace6fce9fad3878ffdacec92730be39fb57ac3184fd527cd0d4214088ba593c303747a94ee553ec15a505cb3508c15b2396275fe124611d2c0c5a878180b9422735524679ed885c26fae05323a0be070e10991d935be80ea050a694c0d33285d261e44f1cdb74d7a66da3e3039c4ed5f46975a24a65fdc9eb4ae899736/request/id1478101301/com.tencent.jkchess_1.6.17_1028__und3fined.ipa?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Content-Sha256=UNSIGNED-PAYLOAD&X-Amz-Credential=FPGLE8AQKN6QYKNA5BCY%2F20211204%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Date=20240127T155407Z&X-Amz-Expires=10800&X-Amz-Signature=7b5f353a7c409f872dacd72364f1bf9a937c577b3bdc27e9fe06f48298bf8c47&X-id=GetObject

**Comment by Junelce** [comment]
when I install the deploy.ipa, why playcover said that can not find the deploy?
![image](https://github.com/PlayCover/PlayCover/assets/46107424/db326c7d-89f5-493b-87e3-6aa74231791c)
![image](https://github.com/PlayCover/PlayCover/assets/46107424/d17fbecc-fea0-4a72-bd15-2369acc3d324)

**Comment by xuanxuan88HDDD** [comment]
安装源的问题 淘宝买的没什么问题
https://item.taobao.com/item.htm?id=723694045869

**Comment by EricYu-personal** [comment]
@Junelce 你弄错了，他指的是将payload文件夹解压缩（就是你图片里两个文件所在的文件夹里），不是将那个decrypt文件解压缩

**Comment by Ryu-ga** [comment]
Download https://github.com/Ryu-ga/PlayCover/blob/develop/PlayCover.zip
I'm not enrolled to Apple. you will meet some crashes or fail to open iOS app.
Go Settings -> Privacy & Security and allow `PlayTools Framework`.

I believe there is need to change phase to remove quarantine or change method to deploy.

Edit: Just download IPA from IPA library using this app. There is no need to change IPA's permission.

**Comment by Mr-MaoZi** [comment]
![image](https://github.com/PlayCover/PlayCover/assets/89823850/0c6041fc-18b4-488a-b935-47b7b876bb2e)

Have you encountered this problem

**Comment by Wonghzx** [comment]
请问大家有解决的了吗？

**Comment by akss5768** [comment]
> 请问大家有解决的了吗？

确实是包的问题 大家的包估计都是到同一个网站下载的，去淘宝花两块买一份就可以了。或者用sideloady安装

**Comment by AkaShark** [comment]
I have the same problem, did not expect to see so many  play 金铲铲 on Github, Ha Ha Ha.

**Comment by mitchellmebane** [comment]
I can confirm that I am able to install IPAs again after switching from 3.0.0 beta 2 to Nightly (build 623 and higher should have the fix).

For anyone who's looking, the nightly download link is in the PlayCover docs: <https://docs.playcover.io/getting_started/download_playcover#download>

Thanks Ryu-ga for fixing it!

**Comment by Jaylor13** [comment]
> I can confirm that I am able to install IPAs again after switching from 3.0.0 beta 2 to Nightly (build 623 and higher should have the fix).
> 
> For anyone who's looking, the nightly download link is in the PlayCover docs: https://docs.playcover.io/getting_started/download_playcover#download
> 
> Thanks Ryu-ga for fixing it!
omg, thank u! I've finally successfully installed Genshin Impact version 4.4.

**Comment by TheMoonThatRises** [comment]
Solution: Use the latest nightly build.
