### ISSUE TITLE
[Feature]: Hide IPad Controls???

### ISSUE THREAD

**Issue by myatix** [PlayCover/PlayCover#1354]
### Is your feature request related to a problem?

Is it possible to hide the onscreen touch controls anyway so that it looks like the PC version without the touch controls on screen???

### Describe the solution you'd like

A screen without all the touchscreen controls would be really nice!

### Anything else?

No

### Issue Language

- [X] Yes my issue is written in English

**Comment by TheMoonThatRises** [comment]
This isn't possible, as the app is the iPad version.

**Comment by MEMORIEmusic** [comment]
Use a controller. iPad controls can't be hidden since it's the iPad version of the game.(except for when you're using controller)
