### ISSUE TITLE
[功能]：求一个金铲铲 一键卖牌的键盘映射文件

### ISSUE THREAD

**Issue by nxsz379** [PlayCover/PlayCover#1357]
### Is your feature request related to a problem?

求一个金铲铲 一键卖牌的键盘映射文件

### Describe the solution you'd like

求一个金铲铲 一键卖牌的键盘映射文件

### Anything else?

求一个金铲铲 一键卖牌的键盘映射文件

### Issue Language

- [X] Yes my issue is written in English

**Comment by akss5768** [comment]
金铲铲的事情来playcover提issue吗。。。

**Comment by XuYicong** [comment]
你自己设啊，CMD+K可以自己编辑键盘映射，有你提问的时间都设好了

**Comment by liuzhihang** [comment]
主键盘1-5：购买棋子（长按：显示棋子详情但不购买）
F：购买经验
D：刷新商店
S：显示/隐藏商店（针对手机的商店布局。如果是电脑/模拟器/iPad布局无效）
X：锁定/解锁商店

不需要设置映射，已经内置了

**Comment by nxsz379** [comment]
我需要的是一个可以一键出售的键盘映射文件,就是类似pc端那种,鼠标悬停在棋子上,按下键盘e键,可以直接出售,目前网易的mumu模拟器可以实现,但是操作和画面不够playcover丝滑

**Comment by Hogeexxl** [comment]
> 主键盘1-5：购买棋子（长按：显示棋子详情但不购买） F：购买经验 D：刷新商店 S：显示/隐藏商店（针对手机的商店布局。如果是电脑/模拟器/iPad布局无效） X：锁定/解锁商店
> 
> 不需要设置映射，已经内置了

为什么我按了没反应呢
