### ISSUE TITLE
[Bug]: xattr: [Errno 13] Permission denied: 

### ISSUE THREAD

**Issue by DPXDN** [PlayCover/PlayCover#1363]
### Describe the bug

Fail to install the Genshin Impact 4.4, getting a report of.   xattr: [Errno 13] Permission denied: '/var/folders/dw/y9cjv7xj0kj82rv549dnw7tc0000gn/T/TemporaryItems/NSIRD_PlayCover_0GBJlW/Payload/Yuanshen.app/Yuanshen',      tried to reinstall playcover, gave and ungave permission, plus restart none worked.

### Steps to reproduce

xattr: [Errno 13] Permission denied: '/var/folders/dw/y9cjv7xj0kj82rv549dnw7tc0000gn/T/TemporaryItems/NSIRD_PlayCover_0GBJlW/Payload/Yuanshen.app/Yuanshen'

### Expected behaviour

Success installation 

### Crash log

```shell
xattr: [Errno 13] Permission denied: '/var/folders/dw/y9cjv7xj0kj82rv549dnw7tc0000gn/T/TemporaryItems/NSIRD_PlayCover_0GBJlW/Payload/Yuanshen.app/Yuanshen'
```

### What version of PlayCover are you using?

2.0.5

### What version of macOS are you using?

Ventura (macOS 13)

### Issue Language

- [X] Yes my issue is written in English

**Comment by TheMoonThatRises** [comment]
Duplicate of #1349. Use nightly build 623 or higher.
