### ISSUE TITLE
[Bug]: Cannot install Genshin Impact latest version 4.4 on M1 MacOS 14

### ISSUE THREAD

**Issue by ylethingoc** [PlayCover/PlayCover#1366]
### Describe the bug

I'm trying to install the latest Genshin version and getting failure below with all following versions of Playcover, 3.0 Beta1,2, Nightly and 2.5. It was working well with Genshin 4.3.

[/var/folders/h8/drssmn3x3tgb1d87wk8ngnbr0000gn/T/TemporaryItems/NSIRD_PlayCover_a9GNOu/view.html]
End-of-central-directory signature not found.  Either this file is not
a zipfile, or it constitutes one disk of a multi-part archive.  In the
latter case the central directory and zipfile comment will be found on
the last disk(s) of this archive.
unzip:  cannot find zipfile directory in one of /var/folders/h8/drssmn3x3tgb1d87wk8ngnbr0000gn/T/TemporaryItems/NSIRD_PlayCover_a9GNOu/view.html or
/var/folders/h8/drssmn3x3tgb1d87wk8ngnbr0000gn/T/TemporaryItems/NSIRD_PlayCover_a9GNOu/view.html.zip, and cannot find /var/folders/h8/drssmn3x3tgb1d87wk8ngnbr0000gn/T/TemporaryItems/NSIRD_PlayCover_a9GNOu/view.html.ZIP, period.

### Steps to reproduce

Getting failure with either importing the IPA or downloading from the IPA Library, here is the IPA source https://decrypt.day/app/id1517783697.

### Expected behaviour

App should be installed successfully.

### What version of PlayCover are you using?

3.0.0 beta 2

### What version of macOS are you using?

Sonoma (macOS 14)

### Issue Language

- [X] Yes my issue is written in English

**Comment by TheMoonThatRises** [comment]
Download directly from source (and not from within PlayCover) and also use the latest nightly version (623).

**Comment by ylethingoc** [comment]
It worked, thanks a bunch!

> Download directly from source (and not from within PlayCover) and also use the latest nightly version (623).

It worked, thanks a bunch!

**Comment by Catta1997** [comment]
#1472
