### ISSUE TITLE
[游戏支持]：genshin

### ISSUE THREAD

**Issue by KristJeremy** [PlayCover/PlayCover#1379]
### App Store link

https://apps.apple.com/cn/app/原神-海灯节/id1467190251

### Current issues

- [X] Game fails to install
- [ ] Game fails to open
- [ ] Game crashes randomly during gameplay
- [ ] Game does not work with keymapping
- [ ] Game experiences graphical issues or broken UI
- [ ] Game fails to connect to servers or complete download

### More details

the ipa ofgenshin impact cannot be installed in 4.4.0 version
the game crashed in 4.3.0 version when open the "guide" part and the “character”part

### Crash log

```shell
xattr: [Errno 13] Permission denied: '/var/folders/yz/r1ds5nc51hx4qbq2nzct06040000gn/T/TemporaryItems/NSIRD_PlayCover_37RcIv/Payload/Yuanshen.app/Yuanshen'
```

### What version of PlayCover are you using?

3.0.0 beta 2

### What version of macOS are you using?

Sonoma (macOS 14)

### Issue Language

- [X] Yes my issue is written in English

**Comment by XuYicong** [comment]
for the open "character" crash issue, decrease resolution scaler (in playcover,right click Genshin -> Settings -> Graphics Settings) to 1.0

for the permission denied issue, that's already solved in nightly version
