### ISSUE TITLE
Migration Feature

### ISSUE THREAD

**Issue by ZhichGaming** [PlayCover/PlayCover#14]
Add the option to migrate the files from .me to .io when opening for first time.

**Comment by Depal1** [comment]
This feature won’t be implemented. Read https://github.com/PlayCover/PlayCover/pull/40 for more information. Instructions for a migration that consists of deleting apps installed pre 1.0.6 (just to free up space) and reinstalling them might need to be included on the documentation.

**Comment by ZhichGaming** [comment]
I thought that symlink will not be implemented since it would not work if the original PlayCover is completely deleted? As said by lixin9311

> #Since we have changed the installation path of PlayTools https://github.com/PlayCover/PlayCover/blob/develop/PlayCover/Utils/PlayTools.swift#L101-L106

I don't think we can consider the Apps from the original PlayCover to be compatible with the new community version.

Once you completely delete the original PlayCover, the app installed by it will no longer be able to run.

Thus, I don't encourage any in-place migrations.
