### ISSUE TITLE
PlayCover crashes when exporting to Sideloadly and an IPA with the same name already exists in the folder.

### ISSUE THREAD

**Issue by PianothShaveck** [PlayCover/PlayCover#140]
PlayCover crashes when exporting to Sideloadly and an IPA with the same name already exists in the folder.
It gives an alert "Some error happened!", and then it crashes.
I think it should give the option to replace the current existing IPA instead. Or at least, it shouldn't crash.

**Comment by Depal1** [comment]
This has been fixed on nightlies.
