### ISSUE TITLE
[App Support]: Warframe appleid login fails

### ISSUE THREAD

**Issue by AstralNexus25** [PlayCover/PlayCover#1402]
### App Store link

https://apps.apple.com/us/app/warframe/id1520001008

### Current issues

- [ ] App fails to install
- [ ] App fails to open
- [ ] App crashes randomly during usage
- [X] App experiences graphical issues or broken UI
- [X] App fails to connect to servers
- [X] Other

### More details

Warframe downloads and works perfectly, but then at the login screen it asks to log in with apple, clicking on which sends a prompt along the lines of "failed to log in, check your login details".
The login is not broken on Warframe's or the mac's end, since the iOS beta app (which wasn't locked and could be run without playcover) did not have similar issues.

STEPS TO REPRODUCE:

Go to decrypt.day
Get the Warframe iOS ipa file
Launch with Playcover
Set resolution to app default, otherwise it does not register clicks
Let it download, then try to login with appleid.

EXPECTED BEHAVIOUR: It prompts a log in with apple message or opens a browser window, like it does with non-playcover applications.

### What version of PlayCover are you using?

3.0.0 beta 2

### What version of macOS are you using?

Sonoma (macOS 14)

### Issue Language

- [X] Yes my issue is written in English

**Comment by Azyzraissi** [comment]
Some said on the discord that disabling SIP fixes this. And someone else said that they can't login again after re enabling SIP. 
If someone can test this again we can probably have at least the cause of the problem.

**Comment by s4tturn** [comment]
Apparently it just worked for me. I had disabled SIP before the first post, but it didn't work that time. Its probably due to an update in the Warframe app, since I was using 1.0.2. Just checked, the latest update 1.0.3 fixes the login issue. Thanks for the support!

**Comment by j-weiner** [comment]
Disabled SIP, logged in, enabled SIP, logging in fails afterwards. Warframe app version is 1.0.7

**Comment by TheMoonThatRises** [comment]
Apple ID logins are currently not supported (unless SIP is disabled).
