### ISSUE TITLE
Minecraft Bedrock Cursor Problem

### ISSUE THREAD

**Issue by Avyukt-Ballari** [PlayCover/PlayCover#141]
### Discussed in https://github.com/PlayCover/PlayCover/discussions/139

<div type='discussions-op-text'>

<sup>Originally posted by **Avyukt-Ballari** August  2, 2022</sup>
I recently had MCPE decrypted by a friend on mine, and right when I opened the IPA I noticed the cursor kept disappearing when I open my inventory and rearrange it. I messaged a couple friends and I believe its because of Play Tools making the crosshair disappear when you open the app. Please Fix This!</div>

**Comment by IsaacMarovitz** [comment]
Does this issue persist in PlayCover 1.1.1?

**Comment by IsaacMarovitz** [comment]
@Avyukt-Ballari I will be closing this issue for now due to inactivity.
