### ISSUE TITLE
[Game Support]: Please Remove the ban on free fire Max

### ISSUE THREAD

**Issue by notsharuu** [PlayCover/PlayCover#1410]
### App Store link

https://apps.apple.com/us/app/free-fire-max/id1480516829

### Current issues

- [ ] Game fails to install
- [x] Game fails to open
- [ ] Game crashes randomly during gameplay
- [ ] Game does not work with keymapping
- [ ] Game experiences graphical issues or broken UI
- [ ] Game fails to connect to servers or complete download

### More details

The game itself can recognise if a player is on a emulator or not, if someone is, it makes them play against the same player base. which isn't unfair, please unban the game.

### Crash log

Doesn't Open

### What version of PlayCover are you using?

3.0.0 beta 2

### What version of macOS are you using?

Sonoma (macOS 14)

### Issue Language

- [X] Yes my issue is written in English

**Comment by notsharuu** [comment]
Update: Since Garena doesn't recognise Play Cover as emulator, playing free fire could result in a BAN!. My id got banned.

**Comment by MEMORIEmusic** [comment]
> Update: Since Garena doesn't recognise Play Cover as emulator, playing free fire could result in a BAN!. My id got banned.

Yup. PlayCover is not an emulator to begin with. There's no reason for Garena to believe it's an emulator

**Comment by TKVYEMMANUEL** [comment]
account got banned

**Comment by GSCYBER** [comment]
Matchmaking my hacker team

**Comment by GSCYBER** [comment]
Duplicate of #1976

**Comment by dichu9396-code** [comment]
acc banned due to using emulator pls anyone help me unban my id

**Comment by sus91575-sys** [comment]
> ### App Store link
> 
> 
> 
> https://apps.apple.com/us/app/free-fire-max/id1480516829
> 
> 
> 
> ### Current issues
> 
> 
> 
> - [ ] Game fails to install
> 
> - [x] Game fails to open
> 
> - [ ] Game crashes randomly during gameplay
> 
> - [ ] Game does not work with keymapping
> 
> - [ ] Game experiences graphical issues or broken UI
> 
> - [ ] Game fails to connect to servers or complete download
> 
> 
> 
> ### More details
> 
> 
> 
> The game itself can recognise if a player is on a emulator or not, if someone is, it makes them play against the same player base. which isn't unfair, please unban the game.
> 
> 
> 
> ### Crash log
> 
> 
> 
> Doesn't Open
> 
> 
> 
> ### What version of PlayCover are you using?
> 
> 
> 
> 3.0.0 beta 2
> 
> 
> 
> ### What version of macOS are you using?
> 
> 
> 
> Sonoma (macOS 14)
> 
> 
> 
> ### Issue Language
> 
> 
> 
> - [X] Yes my issue is written in English
