### ISSUE TITLE
[App Support]: Mobile Legends black screen

### ISSUE THREAD

**Issue by diamond285** [PlayCover/PlayCover#1414]
### App Store link

https://decrypt.day/app/id1160056295

### Current issues

- [ ] App fails to install
- [X] App fails to open
- [ ] App crashes randomly during usage
- [ ] App experiences graphical issues or broken UI
- [ ] App fails to connect to servers
- [ ] Other

### More details

When I run the app, it become black screen. I tried to rename the app from Mobile Legends: Bang Bang to Mobile Legends but is not work. 
<img width="1470" alt="Снимок экрана 2024-03-14 в 10 42 11" src="https://github.com/PlayCover/PlayCover/assets/59549446/a8299edb-3d37-467e-a0ae-3ae3376f0d32">

### What version of PlayCover are you using?

2.0.5

### What version of macOS are you using?

Ventura (macOS 13)

### Issue Language

- [X] Yes my issue is written in English

**Comment by TheMoonThatRises** [comment]
Use newer version of PlayCover. Do note that in versions 3.0.0 Beta 2 and above (including nightly) there is an issue that requires you to clear PlayChain every time you want to launch (#1429).
