### ISSUE TITLE
[Bug]: Cannot remove apps

### ISSUE THREAD

**Issue by HarryK4673** [PlayCover/PlayCover#1426]
### Describe the bug

When I clicked on uninstall app, it said no permission to it, and the app disappeared, and also the data cannot be cleared. How to fix that?

### Steps to reproduce

Just install any app and then uninstall it.

### Expected behaviour

Uninstall app with clearing its data.

### What version of PlayCover are you using?

3.0.0 beta 1

### What version of macOS are you using?

Sonoma (macOS 14)

### Issue Language

- [X] Yes my issue is written in English

**Comment by TheMoonThatRises** [comment]
Enable Full Disk Access for PlayCover under Privacy & Security in MacOS's settings.
