### ISSUE TITLE
Problems when logging in with Apple ID.

### ISSUE THREAD

**Issue by F-T-F** [PlayCover/PlayCover#1428]
### App Store link

https://apps.apple.com/app/id1571873795

### Current issues

- [ ] App fails to install
- [ ] App fails to open
- [ ] App crashes randomly during usage
- [ ] App experiences graphical issues or broken UI
- [ ] App fails to connect to servers
- [X] Other

### More details

Dear PlayCover developers:
I'm a PlayCover user and I'm having problems logging into my game with my Apple ID.The game always says you can't log in.
<img width="1440" alt="截圖 2024-03-30 01 59 54" src="https://github.com/PlayCover/PlayCover/assets/146746256/875e62d6-4977-40ff-be7a-587c5230bec5">

### What version of PlayCover are you using?

3.0.0 beta 2

### What version of macOS are you using?

Sonoma (macOS 14)

### Issue Language

- [X] Yes my issue is written in English

**Comment by TheMoonThatRises** [comment]
Apple ID logins currently do not work, and will probably not be implemented anytime soon. Try using a different login method.

**Comment by toohotz** [comment]
Prefacing that I'm an iOS dev so this _possibly_ might be niche to me having a dev and distro certificates on my machine already.

Wanted to chime in here as I've been on vacation and wanted a ways to play Warfare on my  silicon Mac and not my iPad as heat dissipation isn't the greatest there.

Was able to get the  login working by disabling SIP on the machine and most importantly, **not** having  PlayChain inject its entitlements and instead looking to grab my own from my Keychain.

On vacation so don't have the luxury of time to dig deeper into **if** my dev certificate here
<img width="1386" alt="Screenshot 2024-07-19 at 23 50 50" src="https://github.com/user-attachments/assets/678f6e6a-a60f-4dfa-80a3-f567d612e783">

is what's being pulled in and traversing the `AppData` of the Warframe install on my machine, I do see that there's sym link to my local Keychain directory where I can see my login keychain db.
<img width="1187" alt="Screenshot 2024-07-20 at 00 11 38" src="https://github.com/user-attachments/assets/07571ae0-b619-4249-a63a-cf2f90c94390">

Once SIP was disabled and I stopped Playchain from injecting its signatures as you can side load apps with your own dev certificate, I was then presented with the option to login with my  ID (I presume this won't work for a dev certificate that _isn't_ tied to your account you're trying to login with).

<img width="1442" alt="Screenshot 2024-07-20 at 00 04 15" src="https://github.com/user-attachments/assets/9e6ac1f9-8a11-4533-8840-327e0d03868b">

I was then able to play and do my weekly missions while on vacation which was nice. :) 

<img width="1442" alt="Screenshot 2024-07-20 at 00 04 38" src="https://github.com/user-attachments/assets/ed21a384-87aa-44c7-9524-849e5ffe606e">


Upon turning SIP on after, I wasn't able to start up the game so decided to test the consistently and turned off SIP again.

Was running into the login issue that you'd normally get when Playcover tries to inject its signatures but I didn't retoggle the box.  Had to end up clearing both `PlayChain Data` and `Clear App Preferences` as when I only cleared the PlayChain data I still had the login issue, clearing app preferences also did the trick and allowed Warframe to pick up my dev certificate and allowing me to sign in with my Apple ID.

<img width="211" alt="Screenshot 2024-07-20 at 00 06 03" src="https://github.com/user-attachments/assets/f92188fd-0859-459b-b96d-8f9b55ceb13d">

Again I'd like to say that this probably **won't** be a solution for many and works out in my case as my day job is writing apps for the  platform and I'm not new to resigning apps as its how I've gotten iPad apps to run on my Vision Pro.

I believe the main takeaway is that for this to work, there needs to be an  development cert within the Keychain for said game to be able to pick up and inject.  Hope the context here helps those curious as to the _why_ this doesn't work as I was curious and went down this rabbit hole.
