### ISSUE TITLE
[Feature]: decrypt.day Login

### ISSUE THREAD

**Issue by Catta1997** [PlayCover/PlayCover#1430]
### Is your feature request related to a problem?

Yes, when I try to download some games with decrypt.day Library I have the error "401" , looking at the page I noticed that happen when all of download require a login 

### Describe the solution you'd like

I don't  know if is possible/will fix but add a way to login in decrypt.day so is possible to download also apps that require login

### Anything else?

no

### Issue Language

- [X] Yes my issue is written in English

**Comment by junghyuneun** [comment]
I was surprised that the issue was not addressed anywhere, neither by the devs nor by the users. I was digging through the doc thinking that I must have missed it, then realized that there's no login feature for any of the ipa libraries.

Seeing that most of the libraries require login / some form of authentication, this feature would greatly improve the usability of the app.

**Comment by CallanBi** [comment]
Same problem here, would be great if Playcover provides library source authorization settings.

**Comment by MEMORIEmusic** [comment]
Likely that it won't happen. Users can add various IPA sources, decrypt.day happens to be the most popular one.

**Comment by XuYicong** [comment]
> I was surprised that the issue was not addressed anywhere, neither by the devs nor by the users. I was digging through the doc thinking that I must have missed it, then realized that there's no login feature for any of the ipa libraries.
> 
> Seeing that most of the libraries require login / some form of authentication, this feature would greatly improve the usability of the app.

Yeah historically libraries just provide free download, acting like a simple file server. Maybe for considerations of sustainable service they add some sort of authorization, where playcover doesn't yet catch up.

The doc may not be always up to time so it may not cover recent changes.

**Comment by Catta1997** [comment]
> Likely that it won't happen. Users can add various IPA sources, decrypt.day happens to be the most popular one.

do you have some other trusted sources without login?

**Comment by TheMoonThatRises** [comment]
> Same problem here, would be great if Playcover provides library source authorization settings.

I've asked the owner of decrypt.day to see if it is possible to implement this.

**Comment by Catta1997** [comment]
I discovered that if you create your own library source , you can download it. But not 100% sure
