### ISSUE TITLE
[App Support]: i cant open genshin 

### ISSUE THREAD

**Issue by bachnoname** [PlayCover/PlayCover#1431]
### App Store link

https://apps.apple.com/us/app/genshin-impact/id1517783697?l=vi

### Current issues

- [ ] App fails to install
- [X] App fails to open
- [ ] App crashes randomly during usage
- [ ] App experiences graphical issues or broken UI
- [ ] App fails to connect to servers
- [ ] Other

### More details

cant open game

### What version of PlayCover are you using?

2.0.4

### What version of macOS are you using?

Sonoma (macOS 14)

### Issue Language

- [X] Yes my issue is written in English

**Comment by arbiyanto** [comment]
Use the latest nightly build [download here](https://nightly.link/PlayCover/PlayCover/workflows/2.nightly_release/develop/PlayCover_nightly_702.dmg)

**Comment by steven202** [comment]
Installed the latest nightly build, and the problem persists.

**Comment by arbiyanto** [comment]
> Installed the latest nightly build, and the problem persists.

try to clean the playchain data, or change the application type settings to random type then change it back to "games". 
not sure why but that usually fixes the problem.

**Comment by steven202** [comment]
@arbiyanto Thank you, it works!

**Comment by MEMORIEmusic** [comment]
> @arbiyanto Thank you, it works!

Please close the post if your issue has been fixed.
