### ISSUE TITLE
[Game Support]: Minecraft 1.20.72 don't display correctly (broken ui)

### ISSUE THREAD

**Issue by ParsaFarin** [PlayCover/PlayCover#1436]
### App Store link

https://apps.apple.com/us/app/minecraft/id479516143

### Current issues

- [ ] Game fails to install
- [ ] Game fails to open
- [ ] Game crashes randomly during gameplay
- [ ] Game does not work with keymapping
- [X] Game experiences graphical issues or broken UI
- [ ] Game fails to connect to servers or complete download

### More details

when you open Minecraft display and ui is broken
I tried to use Resolution : Auto (Based on Display) but when I set that game crash.
please help
Thanks
<img width="1440" alt="Screenshot 1403-01-16 at 9 08 13 PM" src="https://github.com/PlayCover/PlayCover/assets/113428160/6bebef1c-6efe-4565-922c-3d68aa2e618b">

<img width="672" alt="Screenshot 1403-01-16 at 9 08 04 PM" src="https://github.com/PlayCover/PlayCover/assets/113428160/ff3b2697-bb8c-4b8c-8948-0df07341b52c">

### What version of PlayCover are you using?

2.0.4

### What version of macOS are you using?

Sonoma (macOS 14)

### Issue Language

- [X] Yes my issue is written in English

**Comment by TheMoonThatRises** [comment]
Use a newer version of PlayCover (3.0.0).
