### ISSUE TITLE
All APP crash

### ISSUE THREAD

**Issue by isshe** [PlayCover/PlayCover#144]
```
-------------------------------------
Translated Report (Full Report Below)
-------------------------------------

Incident Identifier: 143A46CD-FA79-4C81-B35B-AEB9C867E489
CrashReporter Key:   4A337D41-E102-2F58-7AAF-96AFE63CFA95
Hardware Model:      Macmini9,1
Process:             YouTube [4787]
Path:                /Users/USER/Library/Containers/io.playcover.PlayCover/YouTube.app/YouTube
Identifier:          com.google.ios.youtube
Version:             17.24.4 (17.24.4)
AppStoreTools:       13F100
Code Type:           ARM-64 (Native)
Role:                Default
Parent Process:      launchd [1]
Coalition:           com.google.ios.youtube [1648]

Date/Time:           2022-08-06 17:01:13.4770 +0800
Launch Time:         2022-08-06 17:01:13.4645 +0800
OS Version:          macOS 12.5 (21G72)
Release Type:        User
Report Version:      104

Exception Type:  EXC_CRASH (SIGKILL (Code Signature Invalid))
Exception Codes: 0x0000000000000000, 0x0000000000000000
Exception Note:  EXC_CORPSE_NOTIFY
Termination Reason: CODESIGNING 1 

Highlighted by Thread:  0

Backtrace not available

No thread state (register information) available

Binary Images:
Binary images description not available

Error Formulating Crash Report:
_dyld_process_info_create failed with 6
dyld_process_snapshot_get_shared_cache failed
Failed to create CSSymbolicatorRef - corpse still valid ¯\_(ツ)_/¯
thread_get_state(PAGEIN) returned 0x10000003: (ipc/send) invalid destination port
thread_get_state(EXCEPTION) returned 0x10000003: (ipc/send) invalid destination port
thread_get_state(FLAVOR) returned 0x10000003: (ipc/send) invalid destination port

EOF

-----------
Full Report
-----------

{"app_name":"YouTube","timestamp":"2022-08-06 17:01:15.00 +0800","app_version":"17.24.4","slice_uuid":"5e1c38f1-6a70-3456-b9b7-43ee73f36f56","build_version":"17.24.4","platform":0,"bundleID":"com.google.ios.youtube","share_with_app_devs":0,"is_first_party":0,"bug_type":"309","os_version":"macOS 12.5 (21G72)","incident_id":"143A46CD-FA79-4C81-B35B-AEB9C867E489","name":"YouTube"}
{
  "uptime" : 2500,
  "procLaunch" : "2022-08-06 17:01:13.4645 +0800",
  "procRole" : "Default",
  "version" : 2,
  "userID" : 502,
  "deployVersion" : 210,
  "modelCode" : "Macmini9,1",
  "procStartAbsTime" : 62164375772,
  "coalitionID" : 1648,
  "osVersion" : {
    "train" : "macOS 12.5",
    "build" : "21G72",
    "releaseType" : "User"
  },
  "captureTime" : "2022-08-06 17:01:13.4770 +0800",
  "incident" : "143A46CD-FA79-4C81-B35B-AEB9C867E489",
  "bug_type" : "309",
  "pid" : 4787,
  "procExitAbsTime" : 62164666977,
  "translated" : false,
  "cpuType" : "ARM-64",
  "procName" : "YouTube",
  "procPath" : "\/Users\/USER\/Library\/Containers\/io.playcover.PlayCover\/YouTube.app\/YouTube",
  "bundleInfo" : {"CFBundleShortVersionString":"17.24.4","CFBundleVersion":"17.24.4","CFBundleIdentifier":"com.google.ios.youtube","DTAppStoreToolsBuild":"13F100"},
  "storeInfo" : {"deviceIdentifierForVendor":"1906269A-D13D-5308-BC48-32367C91E4ED","thirdParty":true},
  "parentProc" : "launchd",
  "parentPid" : 1,
  "coalitionName" : "com.google.ios.youtube",
  "crashReporterKey" : "4A337D41-E102-2F58-7AAF-96AFE63CFA95",
  "sip" : "disabled",
  "isCorpse" : 1,
  "exception" : {"codes":"0x0000000000000000, 0x0000000000000000","rawCodes":[0,0],"type":"EXC_CRASH","signal":"SIGKILL (Code Signature Invalid)"},
  "termination" : {"namespace":"CODESIGNING","flags":66,"code":1},
  "extMods" : {"caller":{"thread_create":0,"thread_set_state":0,"task_for_pid":0},"system":{"thread_create":0,"thread_set_state":0,"task_for_pid":0},"targeted":{"thread_create":0,"thread_set_state":0,"task_for_pid":0},"warnings":0},
  "legacyInfo" : {
  "threadHighlighted" : 0
},
  "trialInfo" : {
  "rollouts" : [
    {
      "rolloutId" : "61af99aeda72d16a4beb7756",
      "factorPackIds" : {

      },
      "deploymentId" : 240000298
    },
    {
      "rolloutId" : "5fb4245a1bbfe8005e33a1e1",
      "factorPackIds" : {

      },
      "deploymentId" : 240000015
    }
  ],
  "experiments" : [

  ]
},
  "reportNotes" : [
  "_dyld_process_info_create failed with 6",
  "dyld_process_snapshot_get_shared_cache failed",
  "Failed to create CSSymbolicatorRef - corpse still valid ¯\\_(ツ)_\/¯",
  "thread_get_state(PAGEIN) returned 0x10000003: (ipc\/send) invalid destination port",
  "thread_get_state(EXCEPTION) returned 0x10000003: (ipc\/send) invalid destination port",
  "thread_get_state(FLAVOR) returned 0x10000003: (ipc\/send) invalid destination port"
]
}

Model: Macmini9,1, BootROM 7459.141.1, proc 8:4:4 processors, 16 GB, SMC 
Graphics: Apple M1, Apple M1, Built-In
Display: U27P2G6B, 3840 x 2160 (2160p/4K UHD 1 - Ultra High Definition), Main, MirrorOff, Online
Memory Module: LPDDR4
AirPort: Wi-Fi, wl0: Mar 23 2022 19:57:59 version 18.60.27.0.7.8.129 FWID 01-570be953
Bluetooth: Version (null), 0 services, 0 devices, 0 incoming serial ports
Network Service: Wi-Fi, AirPort, en1
USB Device: USB31Bus
USB Device: USB31Bus
USB Device: USB30Bus
USB Device: USB Receiver
USB Device: 69M-RGB
Thunderbolt Bus: Mac mini, Apple Inc.
Thunderbolt Bus: Mac mini, Apple Inc.
```

<img width="606" alt="image" src="https://user-images.githubusercontent.com/13636347/183242433-ddd9f89a-3528-4d3b-a62a-3d933030701d.png">

**Comment by ZhichGaming** [comment]
So from what I'm understanding, all apps are crashing as soon as you open them? Does Genshin Impact crash too? And right click on an app, click app settings and tell me if the option enable jailbreak bypass is enabled.

**Comment by Depal1** [comment]
Or just YouTube?

**Comment by isshe** [comment]
I have tried Netflix, Youtube, Genshin Impact, 原神, and they all crash.


https://user-images.githubusercontent.com/13636347/183346586-fd29fe87-8347-45ae-9abf-9db06b2feb4c.mov


<img width="536" alt="image" src="https://user-images.githubusercontent.com/13636347/183346705-0c4ea389-5ad9-41ea-97d8-cbc741eb2145.png">

**Comment by ZhichGaming** [comment]
> I have tried Netflix, Youtube, Genshin Impact, 原神, and they all crash.
> 
> 
> 
> 
> 
> https://user-images.githubusercontent.com/13636347/183346586-fd29fe87-8347-45ae-9abf-9db06b2feb4c.mov
> 
> 
> 
> 
> 
> <img width="536" alt="image" src="https://user-images.githubusercontent.com/13636347/183346705-0c4ea389-5ad9-41ea-97d8-cbc741eb2145.png">
> 
> 
> 
> 
> 
> 

You should update to the lastest version as the old versions do not pass the store check anymore, if that's that problem.

**Comment by isshe** [comment]
I am using this version: https://github.com/PlayCover/PlayCover/releases/tag/1.0.7
Just downloaded it a few days ago.

**Comment by Depal1** [comment]
The store issue is still present on 1.0.7. Therefore, using the App without an internet connection might explain this behaviour. Did this happen with an active internet connection?

**Comment by springeye** [comment]
Has your IPA been decrypted?

**Comment by ZhichGaming** [comment]
> Has your IPA been decrypted?

If I recall correctly, PlayCover will not install the app if it's not decrypted.

**Comment by isshe** [comment]
> The store issue is still present on 1.0.7. Therefore, using the App without an internet connection might explain this behaviour. Did this happen with an active internet connection?

Yes, the network is working. The complete process is rough as follows.
- When I first downloaded it, I installed the `Genshin Impact` and was able to open it properly, but I couldn't enter the captcha.
- So I disabled the SIP according to the documentation: `csrutil disable`
- After restarting, I opened PlayCover
- Click on a button right below PlayCover (now gone)
    - <img width="777" alt="image" src="https://user-images.githubusercontent.com/13636347/184181045-9ed14525-c800-40c3-adda-951fa1c4e430.png">

- PlayCover is stuck
- I restarted PlayCover
- I can't open any application on PlayCover anymore
- I tried uninstalling PlayCover and reinstalling it, but it still doesn't work
- I tried uninstalling PlayCover via AppCleaner and reinstalling it, but it still doesn't work
- I tried to find files related to PlayCover with the find command, deleted them all, and reinstalled them,  but it still doesn't work
- Then I showed up here 😄

**Comment by isshe** [comment]
> Has your IPA been decrypted?

Sorry, I'm not sure. I just downloaded it from the website and imported it.

**Comment by bayramog** [comment]
I have the same issue. There is no resolution till now.

**Comment by ZhichGaming** [comment]
> I have the same issue. There is no resolution till now.

From what I see in the op's crash log, the code signature of the app is invalid. Where did you download your apps from?

**Comment by bayramog** [comment]
From this site: https://ipa.decrypt.day/

**Comment by IsaacMarovitz** [comment]
Please update to PlayCover 1.1.1 and try again

**Comment by clintandrewhall** [comment]
I'm on 1.1.1 and am having the same issue.

**Comment by parth1241** [comment]
me too

**Comment by ZhichGaming** [comment]
> > The store issue is still present on 1.0.7. Therefore, using the App without an internet connection might explain this behaviour. Did this happen with an active internet connection?
> 
> 
> 
> Yes, the network is working. The complete process is rough as follows.
> 
> - The first app I installed was `Genshin Impact` and was able to open it properly, but I couldn't enter the captcha.
> 
> - So I disabled the SIP according to the documentation: `csrutil disable`
> 
> - After restarting, I opened PlayCover
> 
> - Click on a button right below PlayCover (now gone, the button is located in the red box in the figure below)
> 
>     - <img width="777" alt="image" src="https://user-images.githubusercontent.com/13636347/184181045-9ed14525-c800-40c3-adda-951fa1c4e430.png">
> 
> 
> 
> - PlayCover is stuck
> 
> - I restarted PlayCover
> 
> - I can't open any application on PlayCover anymore
> 
> - I tried uninstalling PlayCover and reinstalling it, but it still doesn't work
> 
> - I tried uninstalling PlayCover via AppCleaner and reinstalling it, but it still doesn't work
> 
> - I tried to find files related to PlayCover with the `find` command, deleted them all, and reinstalled PlayCover,  but it still doesn't work
> 
> - Then I showed up here 😄
> 
> 

Now that I read this carefully, you did not put any nvram boot args and did not enable sip either. You need to the former to log in to Genshin.

**Comment by ZhichGaming** [comment]
Try reenabling SIP and then doing this: 
> Try again after deleting all the following:
> 
> (**Warning** this will erase all PlayCover installed apps and their settings. This is a very crude way of potentially solving the issue.)
> 
> ```
> 
>     "~/Library/Application Support/io.playcover.PlayCover",
> 
>     "~/Library/Caches/io.playcover.PlayCover",
> 
>     "~/Library/Containers/io.playcover.PlayCover",
> 
>     "~/Library/Frameworks/PlayTools.framework",
> 
>     "~/Library/Preferences/io.playcover.PlayCover.plist",
> 
>     "~/Library/Saved Application State/io.playcover.PlayCover.savedState",
> 
>     "~/Library/Application Support/me.playcover.PlayCover",
> 
>     "~/Library/Caches/me.playcover.PlayCover",
> 
>     "~/Library/Containers/me.playcover.PlayCover",
> 
>     "~/Library/Preferences/me.playcover.PlayCover.plist",
> 
>     "~/Library/Saved Application State/me.playcover.PlayCover.savedState",
> 
> ```
> 
> 
- Quoted from Depal

**Comment by Depal1** [comment]
This issue will be closed now, unless we hear back.
