### ISSUE TITLE
[Bug]: playcover games closing when opening

### ISSUE THREAD

**Issue by Destery34** [PlayCover/PlayCover#1440]
### Describe the bug

I try to open a game and it instantly closes 

### Steps to reproduce

open app
app instantly closes 

### Expected behavior

i open the game and it works

### What version of PlayCover are you using?

Nightly/beta (please specify build number)

### What version of macOS are you using?

Other (please specify)

### Issue Language

- [X] Yes my issue is written in English

**Comment by TheMoonThatRises** [comment]
Duplicate of #1429. Either clear PlayChain or downgrade to an older nightly version of PlayCover.
