### ISSUE TITLE
[Game Support]: Genshin not installing

### ISSUE THREAD

**Issue by b4nztruck** [PlayCover/PlayCover#1443]
### Current issues

- [X] Game fails to install
- [X] Game fails to open
- [ ] Game crashes randomly during gameplay
- [ ] Game does not work with keymapping
- [ ] Game experiences graphical issues or broken UI
- [ ] Game fails to connect to servers or complete download

### More details

Genshin is not installing on my Mac m1 

### What version of PlayCover are you using?

3.0.0 beta 2

### What version of macOS are you using?

Sonoma (macOS 14)

### Issue Language

- [X] Yes my issue is written in English

**Comment by TheMoonThatRises** [comment]
Can you provide more information?

**Comment by TheMoonThatRises** [comment]
Close due to being stale and lack of information.
