### ISSUE TITLE
[Bug]: "An Error Occured not Aurthorized" 

### ISSUE THREAD

**Issue by jaminW55** [PlayCover/PlayCover#1447]
### Describe the bug

Attempt to download Honkai Star Rail, receive the below error:
<img width="283" alt="Screenshot 2024-04-17 at 12 19 44 AM" src="https://github.com/PlayCover/PlayCover/assets/133602605/85ae19d8-8e90-46a3-9e21-55cd5edc1cf5">

I am not certain exactly what this error means as there exists nothing else that I am able to see.

### Steps to reproduce

1. Enter IPA Library
2. Click to install Honkai Star Rail

### Expected behaviour

Honkai Star Rail to be installed.

### What version of PlayCover are you using?

3.0.0 beta 2

### What version of macOS are you using?

Sonoma (macOS 14)

### Issue Language

- [X] Yes my issue is written in English

**Comment by MEMORIEmusic** [comment]
Download from decrypt.day website instead of IPA Library.

**Comment by jaminW55** [comment]
> Download from decrypt.day website instead of IPA Library.

Hello. I followed your advice, and it seems to have added to the library, but there are launch issues. My only available bypass options are the "jailbreak bypass".

Do I need to do anything with SIP to address this issue? Similar to as outlined in the following link:
https://docs.playcover.io/getting_started/troubleshoot_login

Sorry for my confusion. The associated error can be seen below.

<img width="270" alt="Screenshot 2024-04-21 at 12 03 47 AM" src="https://github.com/PlayCover/PlayCover/assets/133602605/26808940-6cae-4218-ac92-749d396c3189">

**Comment by TheMoonThatRises** [comment]
> > Download from decrypt.day website instead of IPA Library.
> 
> Hello. I followed your advice, and it seems to have added to the library, but there are launch issues. My only available bypass options are the "jailbreak bypass".
> 
> Do I need to do anything with SIP to address this issue? Similar to as outlined in the following link: https://docs.playcover.io/getting_started/troubleshoot_login
> 
> Sorry for my confusion. The associated error can be seen below.
> 
> <img alt="Screenshot 2024-04-21 at 12 03 47 AM" width="270" src="https://private-user-images.githubusercontent.com/133602605/324222425-26808940-6cae-4218-ac92-749d396c3189.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQ3Njg4NjUsIm5iZiI6MTcxNDc2ODU2NSwicGF0aCI6Ii8xMzM2MDI2MDUvMzI0MjIyNDI1LTI2ODA4OTQwLTZjYWUtNDIxOC1hYzkyLTc0OWQzOTZjMzE4OS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTAzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUwM1QyMDM2MDVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zZDIzNGU1OGZhM2M0MzQ1NmMzZTk2MGZhNzQ0YWJlZjI1YTE1YTFmYzU4NzkwNTg0OWNhNzRlOWRlMDAyOGE3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.UmEXN8m9y6H8yHf-tnWln2xpN4hbkLWG1yuMoXKESe8">

Clear PlayChain or downgrade to an older nightly version of PlayCover.

**Comment by jaminW55** [comment]
Nightly did the trick.
