### ISSUE TITLE
support to bind Escape key

### ISSUE THREAD

**Issue by zyxkad** [PlayCover/PlayCover#145]
Support bind ESC key, it is really useful for me
But now ESC can only exit full screen mode

**Comment by JoseMoreville** [comment]
Please, provide a more in depth explanation of your issue

**Comment by zyxkad** [comment]
> Please, provide a more in depth explanation of your issue

I want to use `CMD-K` to bind ESC key _(The key on the keyboard at the left-top most)_ many computer game use it to open settings, so I don't want to have two key board habits.

But now, the ESCape key can only exit from the full screen mode, I can't bind it

**Comment by ZhichGaming** [comment]
> > Please, provide a more in depth explanation of your issue
> 
> 
> 
> I want to use `CMD-K` to bind ESC key _(The key on the keyboard at the left-top most)_ many computer game use it to open settings, so I don't want to have two key board habits.
> 
> 
> 
> But now, the ESCape key can only exit from the full screen mode, I can't bind it

Binding escape key should work just as well as other keys from my experience. What version of PlayCover are you using and can you record a video of what you described?

**Comment by zyxkad** [comment]
I'm using PlayCover Version 1.0.7 (1)  
I installed it use homebrew

<img width="396" alt="Screen Shot 2022-08-08 at 2 41 45 PM" src="https://user-images.githubusercontent.com/91082411/183510593-d9ca3c41-492b-4bc1-8753-0b9c08345f1a.png">

**Comment by ZhichGaming** [comment]
You can use handbrake to compress the video.

**Comment by zyxkad** [comment]
https://user-images.githubusercontent.com/91082411/183512071-ad1212b6-70c2-44e8-96a8-91d604550659.mov

As you see, when I pressed ESC, I exited from full screen mode

**Comment by Candygoblen123** [comment]
As a temporary workaround, you can export your current keymapping in play cover, open in in a text editor, and change the binding you want to change (in your video it looks you currently have the pain menu set to `Z`, so you would search for `29`) to `41`.

basically, from this:
```
<array>
  <real>29</real>
  <real>0.034245469835069396</real>
  <real>0.053669942579505282</real>
  <real>3.645</real>
</array>
```

to this:
```
<array>
  <real>41</real>
  <real>0.034245469835069396</real>
  <real>0.053669942579505282</real>
  <real>3.645</real>
</array>
```
