### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by moranguelena** [PlayCover/PlayCover#1453]
### Describe the bug

I am trying to install the new version 4.6
<img width="983" alt="Screenshot 2024-04-24 at 18 18 58" src="https://github.com/PlayCover/PlayCover/assets/151404936/2c1d83f5-fae4-481d-bbd9-a102e707fe0c">

### Steps to reproduce

<img width="1008" alt="Screenshot 2024-04-24 at 18 20 06" src="https://github.com/PlayCover/PlayCover/assets/151404936/7ddc9317-d7b2-4e96-a57a-972cc4a3a737">

### Expected behaviour

I have installed every version since 4.0 with no problem

### What version of PlayCover are you using?

3.0.0 beta 1

### What version of macOS are you using?

Sonoma (macOS 14)

### Issue Language

- [X] Yes my issue is written in English

**Comment by TheMoonThatRises** [comment]
Download directly from source. The library provider you are using seems to have broken links.
