### ISSUE TITLE
Identify V crashes when opening.

### ISSUE THREAD

**Issue by Joshwangder** [PlayCover/PlayCover#1458]
### App Store link

I can't open Identify V when opening, keep crashing down. Tried restarting my computer and redownload Identify V. Not working. 

### Current issues

- [ ] Game fails to install
- [X] Game fails to open
- [ ] Game crashes randomly during gameplay
- [ ] Game does not work with keymapping
- [ ] Game experiences graphical issues or broken UI
- [ ] Game fails to connect to servers or complete download

### More details

It keep crashing down when opening, I have tried for 2 hours. Not working. 

### What version of PlayCover are you using?

3.0.0 beta 2

### What version of macOS are you using?

Sonoma (macOS 14)

### Issue Language

- [X] Yes my issue is written in English

**Comment by TheMoonThatRises** [comment]
Duplicate of #657.
