### ISSUE TITLE
[Bug]: Genshin Crashes Whenever I go into the wishing window, the character window and the battle pass window.

### ISSUE THREAD

**Issue by Bo-not-yum** [PlayCover/PlayCover#1464]
### Describe the bug

Whenever I click or use the keybind for going into either the wishing window, the character window and the battle pass window, genshin crashes. The game does make the sound of going into the window so I think it's crashing on entry.

### Steps to reproduce

1. Launch up genshin
2. Launch either the wishing window, the character window or the battle pass window
3. Crash

### Expected behaviour

I expected it to launch into the window.

### What version of PlayCover are you using?

3.0.0 beta 2

### What version of macOS are you using?

Sonoma (macOS 14)

### Issue Language

- [X] Yes my issue is written in English

**Comment by FlyMeToTheMoonAndLetMePlayAmongTheStars** [comment]
Might be because your game resolution is set too high, can you post a screenshot of what your playcover app settings are for genshin?

**Comment by Bo-not-yum** [comment]
It's solved, I think I just turned on some experimental setting that made it crash.

**Comment by Funkysan** [comment]
What settings did you change to fix this, I’m having the same issue
