### ISSUE TITLE
[Bug]: FlutterOS Code Signing Fails

### ISSUE THREAD

**Issue by Kief5555** [PlayCover/PlayCover#1469]
### Describe the bug

Duolingo fails to install while on play tools step.
**Even without having play tools installation selected, the same issue is there.**

Different error on 2.05.

MacOS 14.5 Beta RC 1

### Steps to reproduce

1. Get duolingo IPA
2. Put it in
3. Watch it say: Installing play tools then fail

### Expected behaviour

For it to work

### Crash log

```shell
3.0.0 B2:
/private/var/folders/09/qtkbw3lj75dg8rp2cfk2wx840000gn/T/TemporaryItems/NSIRD_PlayCover_2ntOAt/Payload/DuolingoMobile.app/Frameworks/FlutterOS.framework/FlutterOS: replacing existing signature
/private/var/folders/09/qtkbw3lj75dg8rp2cfk2wx840000gn/T/TemporaryItems/NSIRD_PlayCover_2ntOAt/Payload/DuolingoMobile.app/Frameworks/FlutterOS.framework/FlutterOS: internal error in Code Signing subsystem

2.0.5:
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/install_name_tool: fatal error: file not in an order that can be processed (link edit information does not fill the __LINKEDIT segment): /private/var/folders/09/qtkbw3lj75dg8rp2cfk2wx840000gn/T/TemporaryItems/NSIRD_PlayCover_1FRmBW/Payload/DuolingoMobile.app/Frameworks/FlutterOS.framework/FlutterOS
```

### What version of PlayCover are you using?

3.0.0 beta 2

### What version of macOS are you using?

macOS beta (please state the specific version)

### Issue Language

- [X] Yes my issue is written in English

**Comment by TheMoonThatRises** [comment]
Cannot reproduce this issue with the IPA from decrypt.day and PlayCover 3.0.0.
