### ISSUE TITLE
[Game Support]: Wuthering Waves keymapping

### ISSUE THREAD

**Issue by BrentRosen** [PlayCover/PlayCover#1479]
### App Store link

https://apps.apple.com/us/app/wuthering-waves/id6475033368

### Current issues

- [ ] Game fails to install
- [ ] Game fails to open
- [ ] Game crashes randomly during gameplay
- [X] Game does not work with keymapping
- [ ] Game experiences graphical issues or broken UI
- [ ] Game fails to connect to servers or complete download

### More details

I am attempting to use this keymap that I made for Wuthering Waves but it is not working completely and I am unsure of how to fix it. Any help would be greatly appreciated to both me and the community.

### What version of PlayCover are you using?

3.0.0 beta 2

### What version of macOS are you using?

Sonoma (macOS 14)

### Issue Language

- [X] Yes my issue is written in English

**Comment by BrentRosen** [comment]
[wuthering.playmap.txt](https://github.com/PlayCover/PlayCover/files/15410711/wuthering.playmap.txt)
this is my current keymapping setup(delete the .txt when downloading, this is just to allow uploading on github as it wouldn't have uploaded otherwise)

**Comment by Dariozuo** [comment]
I have same problem, it doesn't work on all game!!

**Comment by agusmuss** [comment]
![Uploading Screenshot 2024-05-23 at 13.26.17.png…]()
interesting... my game cant even open because it gives an error editing the files. **(Failed to get patch list: File Rename** **Error)**                which version did you download, perhaps I have the wrong one or something? My app's name seems to be in chinese

**Comment by BrentRosen** [comment]
@agusmuss to fix that, run the game until the error appears and then run this in the terminal. `rm -r /Users/$USER/Library/Containers/com.kurogame.wutheringwaves.global/Data/Library/Users/$USER/Library/Containers/com.kurogame.wutheringwaves.global/Data && ln -sf /Users/$USER/Library/Containers/com.kurogame.wutheringwaves.global/Data /Users/$USER/Library/Containers/com.kurogame.wutheringwaves.global/Data/Library/Users/$USER/Library/Containers/com.kurogame.wutheringwaves.global/Data`

**Comment by XuYicong** [comment]
Could you please describe in more details, like does keyboard work? Does mouse work? Can you see your keymap if pressed CMD+K?

**Comment by dimasn130397** [comment]
> [wuthering.playmap.txt](https://github.com/PlayCover/PlayCover/files/15410711/wuthering.playmap.txt) this is my current keymapping setup(delete the .txt when downloading, this is just to allow uploading on github as it wouldn't have uploaded otherwise)

I've tried using the setup you recommended, but no change occurred.

**Comment by Boomspring** [comment]
I took the example that @BrentRosen made and adapted it so it is somewhat playable using a controller
It isn't perfect but feel free to use it / modify further -> [Wuwa.playmap.txt (Remember to remove the .txt at the end to import)](https://github.com/PlayCover/PlayCover/files/15447457/Wuwa.playmap.txt)

**Comment by Cerlus** [comment]
> I took the example that @BrentRosen made and adapted it so it is somewhat playable using a controller It isn't perfect but feel free to use it / modify further -> [Wuwa.playmap.txt (Remember to remove the .txt at the end to import)](https://github.com/PlayCover/PlayCover/files/15447457/Wuwa.playmap.txt)

Thanks so much for this!

I'm not skilled at all in this but wanted to try to modify, do we know what the key codes are for the other icons? Like skill, special, the extra function (for the grapple, detector, etc) and echo summon?

**Comment by paulopontovaz** [comment]
Is there any GUI for creating keymappings? Like a website or something like that? 
The numbers are too specific for me, I don't think I can just try stuff around in the screen XD

**Comment by EXMACHINA-002** [comment]
im using playcover on a mac, keymap works fine but i cant interact with anyone and is there a way for the camera to follow to mouse? thanks

**Comment by xx1stxx** [comment]
TT i have port the keymap to playcover but nothing change ingame

**Comment by yogithesymbian** [comment]
how to use sensor change utilities in game. ?
