### ISSUE TITLE
Support for changing the amount of RAM used

### ISSUE THREAD

**Issue by Stanzilla** [PlayCover/PlayCover#148]
Hey there, I'm testing with an application that restricts a few things based on the amount of ram of the device and it looks like PlayCover reports a super low number. This could either be a bug with it not properly detecting the specs of my M2 MacBook Air properly or something in the application.

BUT, I was wondering if you guys could expose a setting for this, regardless of what the cause is.

**Comment by Candygoblen123** [comment]
What app are you using?

**Comment by Stanzilla** [comment]
A non public one, sadly can't tell you guys much about it.

**Comment by Candygoblen123** [comment]
Then there’s not much we can really do. 

And honestly, if you have access to a non-public app, then I assume that you have direct contact with the development team. A much better solution is for you to convince them to make the app available for download on the Mac App Store for Apple Silicon macs.  

If you don’t have this direct contact, then I’m sure that it’s possible for you to tell us at least the name of the application.

**Comment by Stanzilla** [comment]
Well that's why I made this ticket about adding the option to be able to specify the amount of RAM that the emulated device provides

**Comment by Depal1** [comment]
The most that can be done is to implement an iPad model identifier selector (you can tinker with the source code here https://github.com/PlayCover/PlayTools/blob/master/PlayTools/PlayLoader.m). In that case, the threshold for RAM would be increased by at least 2Gb (assuming an M1 iPad is chosen).

**Comment by Depal1** [comment]
> The most that can be done is to implement an iPad model identifier selector (you can tinker with the source code here https://github.com/PlayCover/PlayTools/blob/master/PlayTools/PlayLoader.m). In that case, the threshold for RAM would be increased by at least 2Gb (assuming an M1 iPad is chosen).

The model identifier for an M1 iPad is commented in that file.

**Comment by Stanzilla** [comment]
> > The most that can be done is to implement an iPad model identifier selector (you can tinker with the source code here [https://github.com/PlayCover/PlayTools/blob/master/PlayTools/PlayLoader.m](https://github.com/PlayCover/PlayTools/blob/master/PlayTools/PlayLoader.m?rgh-link-date=2022-08-10T22%3A36%3A18Z)). In that case, the threshold for RAM would be increased by at least 2Gb (assuming an M1 iPad is chosen).
> 
> The model identifier for an M1 iPad is commented in that file.

Awesome, thank you
