### ISSUE TITLE
[Game Support]: Wuthering Waves mouse pointer

### ISSUE THREAD

**Issue by ZeroTwo0912** [PlayCover/PlayCover#1481]
### App Store link

Wuthering Waves https://apps.apple.com/us/app/wuthering-waves/id6475033368

### Current issues

- [ ] Game fails to install
- [ ] Game fails to open
- [ ] Game crashes randomly during gameplay
- [X] Game does not work with keymapping
- [X] Game experiences graphical issues or broken UI
- [ ] Game fails to connect to servers or complete download

### More details

I could not call out my mouse pointer when I pressed option and I could not make my keymapping, it doesn't allow me to change the key bind, it will automatic became a key call right thumb stick

### What version of PlayCover are you using?

3.0.0 beta 1

### What version of macOS are you using?

Sonoma (macOS 14)

### Issue Language

- [X] Yes my issue is written in English

**Comment by zwan669** [comment]
I've encountered the same issue; the left click is always bound to the attack key.

**Comment by ZeroTwo0912** [comment]
I have the same situation too

**Comment by vhcrack** [comment]
Same issue here, someone please update when a fix is found.

**Comment by ZeroTwo0912** [comment]
I found a solution that you can try to turn the mapping mode to touchpad mode, and set your key binding and everything should work well

**Comment by kang49** [comment]
1. You can't change default key bind of game because they have preparing that feature for Mac version that is coming soon.
2. If you can't use "Option" to hide mouse cursor, Pls try create "mouse keymapping" type before.
3. If "WASD keymapping" type can't "run", Try adjust size of it to bigger.

This's all issue if found and solution.

**Comment by OverLord86** [comment]
> I've encountered the same issue; the left click is always bound to the attack key.

And right is alway bound to sprint key... IDK what to do the keymaps aren't working

**Comment by XuYicong** [comment]
Disable touch alternatives
![图片](https://github.com/PlayCover/PlayCover/assets/16048758/9dd4b519-85b7-45a7-8b89-194861ca6407)

Including controller mocking, disable it.

**Comment by kang49** [comment]
> Disable touch alternatives
> 
> ![图片](https://github.com/PlayCover/PlayCover/assets/16048758/9dd4b519-85b7-45a7-8b89-194861ca6407)
> 
> 
> 
> Including controller mocking, disable it.

It's already turn off.

**Comment by XuYicong** [comment]
> It's already turn off.

Are you talking about the issue of right thumbstick? Cause I see you discussing something else before, and I'm helping specifically on the "right thumbstick" issue.

**Comment by kang49** [comment]
Ah i got it what you're talking about. Sorry i misunderstood.

**Comment by Moonshee5288** [comment]
how do u turn off touch alternatives, im using nightly build if that changes anything

**Comment by KingGlacier** [comment]
> how do u turn off touch alternatives, im using nightly build if that changes anything

1. Open play cover
2.  On the top left corner of your screen press playcover
3.  press setting and you will see touch alternatives option
