### ISSUE TITLE
[Game Support]: Wutheringwaves failed google oauth login

### ISSUE THREAD

**Issue by ghdic** [PlayCover/PlayCover#1482]
### App Store link

[https://apps.apple.com/us/app/wuthering-waves/id6475033368](https://apps.apple.com/us/app/wuthering-waves/id6475033368)

### Current issues

- [ ] Game fails to install
- [ ] Game fails to open
- [ ] Game crashes randomly during gameplay
- [ ] Game does not work with keymapping
- [ ] Game experiences graphical issues or broken UI
- [ ] Game fails to connect to servers or complete download

### More details

[google oauth.webm](https://github.com/PlayCover/PlayCover/assets/28496724/e4d6ec12-c2d8-4c10-8f6a-dd8d09643130)
Google oauth authentication not working.
I confirmed that it works properly in Genshin Impact and Star Rail.
There were no differences in settings.

### What version of PlayCover are you using?

3.0.0 beta 2

### What version of macOS are you using?

Sonoma (macOS 14)

### Issue Language

- [X] Yes my issue is written in English

**Comment by vhcrack** [comment]
I used Google OAuth to login with WuWa and it worked for me. This might be an isolated issue. Same version of macOS, same version of PlayCover.

**Comment by kang49** [comment]
I think this's not PlayCover's issue.

**Comment by jiu-lin107141137** [comment]
Google OAuth works fine for me.
I once experienced the same issue, and I figured out it was caused by the inappropriate way of solving the issue of "Failed to get patch list: File Rename Error", after reinstalling the game and following the instructions given [here](https://github.com/PlayCover/PlayCover/issues/1478) I was able to login with Google OAuth.

**Comment by nika-skybytska** [comment]
Could you try signing into your account by manually inputting your email? If it says account not found, chances are you have a similar issue to mine. I solved it by signing into my account on mobile and explicitly linking my email address to my Kuro account. Please don't ask me why it wasn't there to begin with. And yes, this appears to be completely unrelated to playcover.

**Comment by dogukankse** [comment]
This issue still exists. I can't sign in manually because Kuro Games does not support accounts created with Google Auth.
