### ISSUE TITLE
[Game Support]: Wuthering Waves Unable to sign in via apple 

### ISSUE THREAD

**Issue by flowersyrup** [PlayCover/PlayCover#1484]
### App Store link

https://apps.apple.com/th/app/wuthering-waves/id6475033368?platform=ipad

### Current issues

- [ ] Game fails to install
- [X] Game fails to open
- [ ] Game crashes randomly during gameplay
- [ ] Game does not work with keymapping
- [ ] Game experiences graphical issues or broken UI
- [ ] Game fails to connect to servers or complete download

### More details

Game installed just fine, but at the moment of attempting to sign in with Apple Sign it just does a little spin and says failed to sign in. Other platforms with other methods of signing in work just fine. It seems :/

### Crash log

```shell
Using PlayCover nightly 752
```

### What version of PlayCover are you using?

Nightly/beta (please specify build number)

### What version of macOS are you using?

Sonoma (macOS 14)

### Issue Language

- [X] Yes my issue is written in English

**Comment by TheMoonThatRises** [comment]
Apple sign-in is currently not supported on PlayCover, try using another method.

**Comment by mrtonguelicker** [comment]
i did the apple sign in with sip disabled but i wouldnt recommend keeping it disabled for everyone
