### ISSUE TITLE
[Bug]: Nightly(3.00(751)) After using Command+K to set the mapping, the mouse icon disappears and the mouse cannot move

### ISSUE THREAD

**Issue by Sagiri777** [PlayCover/PlayCover#1485]
### Describe the bug

When I set key mapping in the game and exit the set key mapping mode, the mouse disappears and cannot move

### Steps to reproduce

Open the game, Command+K twice

### Expected behaviour

The mouse icon is displayed normally and can be moved

### What version of PlayCover are you using?

Nightly/beta (please specify build number)

### What version of macOS are you using?

Sonoma (macOS 14)

### Issue Language

- [X] Yes my issue is written in English

**Comment by XuYicong** [comment]
You can press **Option** key to show cursor.

**Comment by Sagiri777** [comment]
Sorry, I just found out about this. Thank you very much

> You can press **Option** key to show cursor.
