### ISSUE TITLE
[Game Support]:  I can't start Wuthering Waves after I selected there server

### ISSUE THREAD

**Issue by MisterPur** [PlayCover/PlayCover#1490]
### App Store link

https://apps.apple.com/ro/app/wuthering-waves/id6475033368

### Current issues

- [ ] Game fails to install
- [X] Game fails to open
- [ ] Game crashes randomly during gameplay
- [ ] Game does not work with keymapping
- [x] Game experiences graphical issues or broken UI
- [ ] Game fails to connect to servers or complete download

### More details

After i did the last update i had to choose on what server i want to play. after that i couldn't start the game. it let me logout and change the server but it didn't let me to start it. i did try it to reopen many times but nothing change. every time the game ask me to chose a server  and than never opens. I even reinstall the game and nothing.

### What version of PlayCover are you using?

3.0.0 beta 2

### What version of macOS are you using?

Sonoma (macOS 14)

### Issue Language

- [X] Yes my issue is written in English

**Comment by kryptofaz** [comment]
right click on the game icon in playcover, go into the 'misc' tab and change the application type to 'games', see if that works

**Comment by MisterPur** [comment]
> right click on the game icon in playcover, go into the 'misc' tab and change the application type to 'games', see if that works


I did that. still the same result.
