### ISSUE TITLE
[Bug]: wuthering waves visual glitch

### ISSUE THREAD

**Issue by PZTHH** [PlayCover/PlayCover#1491]
### Describe the bug

<img width="1800" alt="Screenshot 2024-05-26 at 3 03 39 PM" src="https://github.com/PlayCover/PlayCover/assets/131446954/34948926-36e9-470e-8bc8-c156237df7a4">
<img width="1800" alt="Screenshot 2024-05-26 at 3 03 44 PM" src="https://github.com/PlayCover/PlayCover/assets/131446954/3545fe11-e5a5-48a9-be0a-3917a342e743">

### Steps to reproduce

just download the game from decrypt.day and run it in the story quest and character screen you can see this happening for some characters

### Expected behaviour

Weird lines appear inside characters heads or other parts like their hands

### What version of PlayCover are you using?

3.0.0 beta 2

### What version of macOS are you using?

Sonoma (macOS 14)

### Issue Language

- [X] Yes my issue is written in English

**Comment by XuYicong** [comment]
This is WuWa's shader bug, they're in charge to fix this. And they are gradually releasing hot patches to fix these. They're releasing all kinds of hot patches these days, and I believe they would fix this in no more than a week. Playcover can not do anything with this.
