### ISSUE TITLE
[Bug]: (WutheringWaves): Camera Movement Freezes During Fast or Extended Panning

### ISSUE THREAD

**Issue by kang49** [PlayCover/PlayCover#1492]
### Summary:
When panning the camera quickly or for a prolonged duration, the movement becomes stuck. To resume panning, the mouse must be stationary for a moment.

### Side effect: 
**Sometime** when this issue occurs, the left mouse button (LMB) cannot be used to attack in the game by default unless it is specifically set to do so.

### demo video
https://github.com/PlayCover/PlayCover/assets/81503963/eb39e7f9-5dee-4195-a4f9-5725005cd4fc

### Keymapping
<img width="1440" alt="Screenshot 2024-05-26 at 18 50 17" src="https://github.com/PlayCover/PlayCover/assets/81503963/75c934bc-a331-4a0c-b539-068f758a6840">

### More detail:
PlayCover Nightly 749
MacOS Sonoma 14.5
Game version 1.0.0
Bluetooth Mouse

### Steps to reproduce

1. Open the game with PlayCover.
2. Start moving the camera by panning rapidly or for an extended period.
3. Observe the camera movement freeze.
4. Stop moving the mouse for a second to resume panning.

### Expected behaviour

The camera should pan smoothly without interruptions, regardless of the speed or duration of the mouse movement.

### What version of PlayCover are you using?

Nightly/beta (please specify build number)

### What version of macOS are you using?

Sonoma (macOS 14)

### Issue Language

- [X] Yes my issue is written in English

**Comment by XuYicong** [comment]
You mention "Bluetooth Mouse", does this only happen to a mouse but not a trackpad?

**Comment by kang49** [comment]
> You mention "Bluetooth Mouse", does this only happen to a mouse but not a trackpad?

Yes, or maybe it's because the TrackPad is too small to drag long enough to encounter the bug.

But mentioning 'Bluetooth Mouse' doesn't mean that other devices won't experience the issue. It's just a detail to indicate what device I am using.

**Comment by Christoph-XJ** [comment]
the same situation

**Comment by JZVince** [comment]
Same issue, moreover, I find changing the polling rate of the mouse (250) help with the camera rotation problem. However, mouse cursor will appear outside the app when I move and I have already pressed option key to hide it.

**Comment by kang49** [comment]
> You mention "Bluetooth Mouse", does this only happen to a mouse but not a trackpad?

I confirm that the trackpad have this issue because i tried change trackpad speed in setting and i found this issue also. And in the latest game version, the trackpad can be used for attacking and dodging normally, whereas the mouse currently cannot perform these actions.

**Comment by Christoph-XJ** [comment]
The similar problem occurs when the mouse sampling rate is too high, after I replaced the usb gaming mouse with a cheaper bluetooth mouse, the situation is much alleviated, in my understanding this should be a problem that can be fixed in the code.

**Comment by XuYicong** [comment]
Fixed by PlayCover/PlayTools#144
