### ISSUE TITLE
[Game Support]: Camera views during game play gets locked randomly. 

### ISSUE THREAD

**Issue by annatseng0725** [PlayCover/PlayCover#1495]
### App Store link

https://apps.apple.com/us/app/wuthering-waves/id6475033368

### Current issues

- [ ] Game fails to install
- [ ] Game fails to open
- [ ] Game crashes randomly during gameplay
- [ ] Game does not work with keymapping
- [ ] Game experiences graphical issues or broken UI
- [ ] Game fails to connect to servers or complete download

### More details

Camera views during game play gets locked randomly (unable to move screen). When attempting to move the mouse, the view gets zooms in and out. 

(Sorry for my bad english) 

### What version of PlayCover are you using?

Nightly

### What version of macOS are you using?

Sonoma (macOS 14)

### Issue Language

- [X] Yes my issue is written in English

**Comment by kang49** [comment]
It appears this issue is similar to #1483 . The camera locking and zooming problems might be related. Please check the details and solutions discussed in that thread to see if they address your problem.

**Comment by XuYicong** [comment]
Duplication of #1483
