### ISSUE TITLE
[Bug]: RT and LT Buttons on Game Controller Unresponsive in the latest Genshin Impact (4.7 CN)

### ISSUE THREAD

**Issue by Aintor** [PlayCover/PlayCover#1503]
### Describe the bug

In the latest Genshin Impact, the RT and LT buttons on the game controller are unresponsive. This issue prevents some essential in-game actions and significantly impacts the gaming experience. While these buttons work well in Honkai: Star Rail.

**Details:**
Xbox elite controller 2
MacBook Pro (M1 Pro)
Sonoma 14.5
Genshin Impact (4.7 CN version)
Playcover nightly build (764)

### Steps to reproduce

Connect the game controller to the Mac.
Attempt to press the RT or LT buttons in Genshin Impact.

### Expected behaviour

When pressing the RT or LT buttons, the game should respond with the corresponding actions, such as character using Elemental Skill.

### What version of PlayCover are you using?

Nightly/beta (please specify build number)

### What version of macOS are you using?

Sonoma (macOS 14)

### Issue Language

- [X] Yes my issue is written in English

**Comment by acbasco** [comment]
I'm experiencing the same issue, my controller is 8BitDo Ultimate 2.4G controller

**Comment by lemon-sundae** [comment]
Same here using a Nintendo®️ Switch Pro controller. RT and LT buttons do not work. They work well on iPhone/iPad so it is probably not a issue with the game itself.

**Comment by acbasco** [comment]
I got it working again.

What I did was, I go to Settings->Controller Setup->Restore Defaults
Then I remapped the keys again to my liking.
Works again

**Comment by Aintor** [comment]
> I got it working again.
> 
> 
> 
> What I did was, I go to Settings->Controller Setup->Restore Defaults
> 
> Then I remapped the keys again to my liking.
> 
> Works again
> 
> 

Thanks, I'll take a try.

**Comment by Skyearn** [comment]
same problem

**Comment by Skyearn** [comment]
> I got it working again.
> 
> What I did was, I go to Settings->Controller Setup->Restore Defaults Then I remapped the keys again to my liking. Works again

Hi, The Setting is Genshin Impact setting or Playcover setting or System setting?

**Comment by lemon-sundae** [comment]
> > I got it working again.
> 
> > 
> 
> > What I did was, I go to Settings->Controller Setup->Restore Defaults Then I remapped the keys again to my liking. Works again
> 
> 
> 
> Hi, The Setting is Genshin Impact setting or Playcover setting or System setting?

Setting inside the game

**Comment by Skyearn** [comment]
> > > I got it working again.
> > 
> > 
> > > 
> > 
> > 
> > > What I did was, I go to Settings->Controller Setup->Restore Defaults Then I remapped the keys again to my liking. Works again
> > 
> > 
> > Hi, The Setting is Genshin Impact setting or Playcover setting or System setting?
> 
> Setting inside the game

Thanks, it's work for me.

**Comment by hi94740** [comment]
> I got it working again.
> 
> What I did was, I go to Settings->Controller Setup->Restore Defaults Then I remapped the keys again to my liking. Works again

I believe this is actually a genshin bug. I encountered the same bug on my iPad and this fix worked for me too.
