### ISSUE TITLE
[Bug]: App settings UI does not update properly when changing settings

### ISSUE THREAD

**Issue by mitchellmebane** [PlayCover/PlayCover#1505]
### Describe the bug

In the settings UI for apps within PlayCover, controls do not visually update when clicked.  E.g., if I click on a checkbox, it does not appear to change.  However, when I click the OK button then re-open settings, I can see that the checkbox has updated.

This appears to happen with all controls.  E.g., if I go to the Graphics tab in Settings and change the Resolution dropdown to Custom, the Width/Height boxes do not appear until I click OK and then re-open settings.

This is occurring in Nightly 765.  I checked some older nightly builds that I had, and Nightly 663 has the issue, but Nightly 636 does not.  Unfortunately, those old Nightly builds are expired so I can't download any in between to narrow it down any further than that.

Demo:
![PlayCover Settings UI Bug.mp4](https://github.com/PlayCover/PlayCover/assets/6096942/0b4340de-52af-4d9e-9d73-c60dee696f28)

### Steps to reproduce

1. Right-click an app in PlayCover and choose Settings
2. In the Settings UI, click on any control (e.g., the Keymapping checkbox on the Keymapping page)
3. Note that the state of the control does not update
4. Click the OK button
5. Re-open the app settings
6. Note that the state of the control has now updated

### Expected behaviour

1. Right-click an app in PlayCover and choose Settings
2. In the Settings UI, click on any control (e.g., the Keymapping checkbox on the Keymapping page)
3. The state of the control has updated

### What version of PlayCover are you using?

Nightly/beta (please specify build number) Nightly 765

### What version of macOS are you using?

Sonoma (macOS 14) 14.5

### Issue Language

- [X] Yes my issue is written in English

**Comment by Depal1** [comment]
Very many thanks for reporting this!

**Comment by mitchellmebane** [comment]
I tried building from source.  I have Xcode 15.4 installed.  I was unable to build commit d40cce9, which corresponds to Nightly 636, but I _was_ able to build d7ac538, one commit later.  It doesn't look like there were any app code changes in that commit, but my build still had the GUI issue, so it may be a dependency bug or SwiftUI issue.  Or it could be something I'm doing wrong, since this is the first time I've ever tried building PlayCover.

**Comment by Catta1997** [comment]
Maybe https://github.com/feedback-assistant/reports/issues/444

**Comment by Catta1997** [comment]
Working on a fix #1511
