### ISSUE TITLE
[Bug]: Hsr always crashing on log in page

### ISSUE THREAD

**Issue by Moonshee5288** [PlayCover/PlayCover#1508]
### Describe the bug

Everytime i try to log into hsr after updating to sonoma 14.5 it crashes after i put in my log in details and press submit. 

### Steps to reproduce

playcover nightly build 235 (i think)
hsr 
sonoma 14.5
try to log in

### Expected behaviour

for the page to load but it just crashes

### What version of PlayCover are you using?

Nightly/beta (please specify build number)

### What version of macOS are you using?

Sonoma (macOS 14)

### Issue Language

- [X] Yes my issue is written in English

**Comment by TheMoonThatRises** [comment]
Try using a newer nightly version.

**Comment by Moonshee5288** [comment]
Worked thanq
