### ISSUE TITLE
[Bug]: Genshin Impact PlayTools not installed

### ISSUE THREAD

**Issue by bellamellaff** [PlayCover/PlayCover#1509]
### Describe the bug

I can play Genshine if I remove the playtools. But I need it right? Do you know how I can install the playtools?

### Steps to reproduce

Playcover nightly 767
Genshin Impact download successfully
Upload the Genshin into the Playcover
Uploading stopped when it was doing installing playtools.
Remove Playtools
Game Worked
But the screen is cropped and I can't use keyboard

### Expected behaviour

I have no idea why I couldn't install the playtools.

### Crash log

```shell
/var/folders/_z/ngppvt8x3752bs0ghjf4xfwh0000gn/T/TemporaryItems/NSIRD_PlayCover_hzUnlh/Payload/GenshinImpact.app/PlugIns/AKInterface.bundle: replacing existing signature
/var/folders/_z/ngppvt8x3752bs0ghjf4xfwh0000gn/T/TemporaryItems/NSIRD_PlayCover_hzUnlh/Payload/GenshinImpact.app/PlugIns/AKInterface.bundle: resource fork, Finder information, or similar detritus not allowed
```

### What version of PlayCover are you using?

Nightly/beta (please specify build number)

### What version of macOS are you using?

Sonoma (macOS 14)

### Issue Language

- [X] Yes my issue is written in English

**Comment by mitchellmebane** [comment]
Have you set the Application Type to `public.app-category.games` in the Misc tab of the Genshin settings in PlayCover?

**Comment by TheMoonThatRises** [comment]
Try using the latest stable release of PlayCover.

**Comment by TheMoonThatRises** [comment]
A new version of PlayCover has released. If this issue still occurs, open a new issue.
