### ISSUE TITLE
[Game Support]: Mobile Legends black screen

### ISSUE THREAD

**Issue by liazcoder** [PlayCover/PlayCover#1510]
### App Store link

https://decrypt.day/app/id1160056295

### Current issues

- [ ] Game fails to install
- [X] Game fails to open
- [ ] Game crashes randomly during gameplay
- [ ] Game does not work with keymapping
- [ ] Game experiences graphical issues or broken UI
- [ ] Game fails to connect to servers or complete download

### More details

showing black screen even I tried all the steps that u had provided on troubleshoot

### What version of PlayCover are you using?

3.0.0 beta 2

### What version of macOS are you using?

Ventura (macOS 13)

### Issue Language

- [X] Yes my issue is written in English

**Comment by TheMoonThatRises** [comment]
Try using the nightly version of PlayCover.

**Comment by TheMoonThatRises** [comment]
This issue should be fixed with PlayCover 3.0.0.
