### ISSUE TITLE
[Bug]: Cannot compile on Xcode 15.1 (15C65) - PhaseScriptExecution failed with a nonzero exit code

### ISSUE THREAD

**Issue by FreedomLabsIO** [PlayCover/PlayCover#1513]
### Describe the bug

When I try to build the latest develop branch I get this error

```
Converting to maccatalyst
Codesigning PlayTools
A shell task (/usr/bin/xcrun codesign --force --sign XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX --preserve-metadata=identifier,entitlements /Users/MACUSER/Library/Developer/Xcode/DerivedData/PlayCover-cwnwrdjpuvhnepaurdyndfdxxvbg/Build/Products/Nightly/PlayCover.app/Contents/Frameworks/PlayTools.framework) failed with exit code 1:

/Users/MACUSER/Library/Developer/Xcode/DerivedData/PlayCover-cwnwrdjpuvhnepaurdyndfdxxvbg/Build/Products/Nightly/PlayCover.app/Contents/Frameworks/PlayTools.framework: resource fork, Finder information, or similar detritus not allowed

Command PhaseScriptExecution failed with a nonzero exit code
```

### Steps to reproduce

git clone https://github.com/PlayCover/PlayCover.git
Open on Xcode, set the signing properties and try to build

### Expected behaviour

Code to be compiled

### Crash log

```shell
Converting to maccatalyst
Codesigning PlayTools
A shell task (/usr/bin/xcrun codesign --force --sign XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX --preserve-metadata=identifier,entitlements /Users/MACUSER/Library/Developer/Xcode/DerivedData/PlayCover-cwnwrdjpuvhnepaurdyndfdxxvbg/Build/Products/Nightly/PlayCover.app/Contents/Frameworks/PlayTools.framework) failed with exit code 1:

/Users/MACUSER/Library/Developer/Xcode/DerivedData/PlayCover-cwnwrdjpuvhnepaurdyndfdxxvbg/Build/Products/Nightly/PlayCover.app/Contents/Frameworks/PlayTools.framework: resource fork, Finder information, or similar detritus not allowed

Command PhaseScriptExecution failed with a nonzero exit code
```
```


### What version of PlayCover are you using?

Latest develop branch

### What version of macOS are you using?

MacOS Sonoma 14.5

### Issue Language

- [X] Yes my issue is written in English

**Comment by Catta1997** [comment]
Try to clean build folder and then close and reopen Xcode, it worked for me

**Comment by FreedomLabsIO** [comment]
> Try to clean build folder and then close and reopen Xcode, it worked for me

Tried that already. Doesn't work. Closed Xcode, deleted project, cloned it again and issue persists.

**Comment by Catta1997** [comment]
> > Try to clean build folder and then close and reopen Xcode, it worked for me
> 
> Tried that already. Doesn't work. Closed Xcode, deleted project, cloned it again and issue persists.

try:
```
xattr -cr <path_to_.app>
```
Clean Xcode and Re-build.

**Comment by FreedomLabsIO** [comment]
> > > Try to clean build folder and then close and reopen Xcode, it worked for me
> > 
> > 
> > Tried that already. Doesn't work. Closed Xcode, deleted project, cloned it again and issue persists.
> 
> try:
> 
> ```
> xattr -cr <path_to_.app>
> ```
> 
> Clean Xcode and Re-build.

I erased the project folder, erased the `DerivedData` folder
```
rm -rf /Users/MACUSER/Library/Developer/Xcode/DerivedData
```
and re-cloned PlayCover thru git

Now it worked. Thanks!
