### ISSUE TITLE
[Bug]: HSR not opening

### ISSUE THREAD

**Issue by Moonshee5288** [PlayCover/PlayCover#1515]
### Describe the bug

when i try to open hsr it keeps giving me the error message of you force quit and gives me the reopen or dont reopen nomatter what i click it just doesnt open

### Steps to reproduce

force quit hsr from decrypt.day
playcover nightly 768

### Expected behaviour

it opens

### What version of PlayCover are you using?

Nightly/beta (please specify build number)

### What version of macOS are you using?

Sonoma (macOS 14)

### Issue Language

- [X] Yes my issue is written in English

**Comment by Catta1997** [comment]
I have no issue, HSR start normally (build 773). Have you tried to Clear play chain data? Also check if you have Game category in application type (app settings > misc)

**Comment by Moonshee5288** [comment]
completely uninstalled it and reinstalled it, still not working, also it was already in the game category

**Comment by Moonshee5288** [comment]
nvm it works now

**Comment by Dabiolu** [comment]
Can you explain how you did it?

**Comment by Dabiolu** [comment]
So the solution is to find Honkai Star rail in finder and hold shift when opening it

**Comment by Moonshee5288** [comment]
i did quite litterally nothing
i just opened it one time and it worked

**Comment by Dariozuo** [comment]
<img width="553" alt="截屏2024-06-17 00 21 45" src="https://github.com/PlayCover/PlayCover/assets/109204390/fc396904-16b0-40b2-b6d4-fd25c4be98c8">
try this,open Force Insert iOS Frameworks

**Comment by Kief5555** [comment]
Seems to be a code signing problem. When assets are downloaded, the next launch gives error 5 and code signing errors.

**Comment by iLokendra45** [comment]
you can use play cover nightly build of latest version. or maybe u can  add application type into public app category none. or public app category games.

**Comment by MEMORIEmusic** [comment]
@Moonshee5288 If you've fixed the bug, can you close the post please?
