### ISSUE TITLE
[Feature]: Download game to External Drive

### ISSUE THREAD

**Issue by HayesWang** [PlayCover/PlayCover#1524]
### Is your feature request related to a problem?

Many users have limited internal storage space on their devices. Currently, the game can only be installed on the internal hard drive, which can lead to storage issues and prevent some users from installing or updating the game.

### Describe the solution you'd like

I suggest adding functionality to allow the game to be installed on an external hard drive. This would provide users with more flexibility and help manage their storage more efficiently.

### Anything else?

thx

### Issue Language

- [X] Yes my issue is written in English

**Comment by MEMORIEmusic** [comment]
Games installed on internal SSD can be symlinked onto an external SSD.

**Comment by YBHPG** [comment]
> Games installed on internal SSD can be symlinked onto an external SSD.

How does this work? As I understand from googling, for the game to be on an external drive and be available for apps as if it was on an internal drive, I have to symlink the _external_ version to an _internal_ location. Do I miss something in this process?

Also I tried to do the describes process, copying the game files to an external SSD and creating a symlink for it in the Library/Containers folder. After rebooting the game just didn't want to launch. And it was able to start again after copying the game folder to the original location without symlink.

**Comment by TheMoonThatRises** [comment]
The only part of the game that can be moved to an external drive is the app itself. But most of the app's data is in it's container, and that location cannot be changed. Check this discussion https://github.com/PlayCover/PlayCover/discussions/473.
