### ISSUE TITLE
[Game Support]: (尘白禁区/Snowbreak) How can I remove the controller cursor

### ISSUE THREAD

**Issue by lzEvanZheng** [PlayCover/PlayCover#1526]
### App Store link

How to remove the built-in fixed controller cursor when using the keyboard and mouse

### Current issues

- [ ] Game fails to install
- [ ] Game fails to open
- [ ] Game crashes randomly during gameplay
- [ ] Game does not work with keymapping
- [ ] Game experiences graphical issues or broken UI
- [ ] Game fails to connect to servers or complete download

### More details

Sometimes it works well, but in most cases, due to the presence of the built-in cursor, the mouse click will not respond

### What version of PlayCover are you using?

3.0.0 beta 1

### What version of macOS are you using?

Sonoma (macOS 14)

### Issue Language

- [X] Yes my issue is written in English

**Comment by lzEvanZheng** [comment]
Well, it seems that I have found a way to solve this problem by connecting two mice at the same time

**Comment by TheMoonThatRises** [comment]
This is the same fundamental issue as in #1493. We currently do not have a solution to this.

**Comment by ReoSaKo** [comment]
> Well, it seems that I have found a way to solve this problem by connecting two mice at the same time

I have same problem, could you tell me how to solve it?

**Comment by lzEvanZheng** [comment]
> > Well, it seems that I have found a way to solve this problem by connecting two mice at the same time
> 
> I have same problem, could you tell me how to solve it?

You just need to connect two mice to the computer at the same time, and the latter one will work. Or if you have a controller, both the mouse and controller will work.

**Comment by ReoSaKo** [comment]
> > > Well, it seems that I have found a way to solve this problem by connecting two mice at the same time
> > 
> > 
> > I have same problem, could you tell me how to solve it?
> 
> You just need to connect two mice to the computer at the same time, and the latter one will work. Or if you have a controller, both the mouse and controller will work.

Thank you for your help.
It seems working but there is another issue that there are conflict between Snowbreak built-in key and keymapping.
For example the game has some feature with button "Q" and my keymap another and I want only my keymapping.
Before I update to Macos 15, it sometimes works to disable the built-in key while I tried to restart the game few times.
But it doesn't work anymore after I updated to Macos 15. Do you know how to solve it?

**Comment by lzEvanZheng** [comment]
> > > > Well, it seems that I have found a way to solve this problem by connecting two mice at the same time
> > > 
> > > 
> > > I have same problem, could you tell me how to solve it?
> > 
> > 
> > You just need to connect two mice to the computer at the same time, and the latter one will work. Or if you have a controller, both the mouse and controller will work.
> 
> Thank you for your help. It seems working but there is another issue that there are conflict between Snowbreak built-in key and keymapping. For example the game has some feature with button "Q" and my keymap another and I want only my keymapping. Before I update to Macos 15, it sometimes works to disable the built-in key while I tried to restart the game few times. But it doesn't work anymore after I updated to Macos 15. Do you know how to solve it?

Sorry, I don't seem to have encountered this type of issue. Perhaps you could ask the developers of this tool, or see if others have the same problem.

**Comment by ReoSaKo** [comment]
> > > > > Well, it seems that I have found a way to solve this problem by connecting two mice at the same time
> > > > 
> > > > 
> > > > I have same problem, could you tell me how to solve it?
> > > 
> > > 
> > > You just need to connect two mice to the computer at the same time, and the latter one will work. Or if you have a controller, both the mouse and controller will work.
> > 
> > 
> > Thank you for your help. It seems working but there is another issue that there are conflict between Snowbreak built-in key and keymapping. For example the game has some feature with button "Q" and my keymap another and I want only my keymapping. Before I update to Macos 15, it sometimes works to disable the built-in key while I tried to restart the game few times. But it doesn't work anymore after I updated to Macos 15. Do you know how to solve it?
> 
> Sorry, I don't seem to have encountered this type of issue. Perhaps you could ask the developers of this tool, or see if others have the same problem.

nvm
Thank you very much.
