### ISSUE TITLE
[Bug]: Genshin breaking audio

### ISSUE THREAD

**Issue by Moonshee5288** [PlayCover/PlayCover#1528]
### Describe the bug

Whenever i open genshin, all of my audio except from the genshin audio breaks and is in a constant stutter, i have no idea why this happens because it only happened recently

### Steps to reproduce

Genshin from decrypt.day
Playcover nightly 768
and play audio

### Expected behaviour

My audio doesn't break

### What version of PlayCover are you using?

Nightly/beta (please specify build number)

### What version of macOS are you using?

Sonoma (macOS 14)

### Issue Language

- [X] Yes my issue is written in English

**Comment by TheMoonThatRises** [comment]
Can you provide what graphics settings you have for Genshin in PlayCover? Like resolution, aspect ratio, and resolution scalar?
