### ISSUE TITLE
Verification Failed (Genshin)

### ISSUE THREAD

**Issue by velevetzrose** [PlayCover/PlayCover#1529]
### Describe the bug

So firstly I downloaded the version with blue icon, and disabled SIP and put code into terminal, still this message was appearing, tried few times, then downloaded nightly version, so the same issue. How to fix this?
<img width="1680" alt="Screenshot 2024-06-27 at 1 56 49 AM" src="https://github.com/PlayCover/PlayCover/assets/173957263/9031f015-39d0-4ae6-a8f2-e7a614844089">

### Steps to reproduce

PlayCover Nightly 786

### Expected behaviour

To login into the game

### What version of PlayCover are you using?

Nightly/beta (please specify build number)

### What version of macOS are you using?

Sonoma (macOS 14)

### Issue Language

- [X] Yes my issue is written in English

**Comment by TheMoonThatRises** [comment]
Can you try again with SIP enabled? That process isn't necessary with newer versions of PlayCover.
