### ISSUE TITLE
[Game Support]: (Wuthering Waves) Mouse input not working properly

### ISSUE THREAD

**Issue by jaeiyden** [PlayCover/PlayCover#1531]
### App Store link

https://apps.apple.com/us/app/wuthering-waves/id6475033368

### Current issues

- [ ] Game fails to install
- [ ] Game fails to open
- [ ] Game crashes randomly during gameplay
- [ ] Game does not work with keymapping
- [ ] Game experiences graphical issues or broken UI
- [ ] Game fails to connect to servers or complete download

### More details

9 out of every 10 times i launch WuWa the mouse controls seem to be whack. The game seems to be registering my left clicks even when i'm out of tab. I tried unbinding my left click but for some reason it still performs as if i didn't. I'm pretty sure left click keymaps are not supposed to register when i'm in the mode where my pointer can freely move, since all of the other games i've played are like that. 

video linked here to see what i'm talking abt:
https://youtu.be/Juu-CHBWh18?si=oiqP9ZxTOz0-VoRc

I'm using the latest ver of the nightly build btw

### What version of PlayCover are you using?

Nightly/beta (please specify build number)

### What version of macOS are you using?

Sonoma (macOS 14)

### Issue Language

- [X] Yes my issue is written in English

**Comment by MEMORIEmusic** [comment]
PlayCover is not bugged. Wuwa is. It has in-built partial KBM support. It's not the keymap triggering it, it's the game itself. Nothing can be done about it. 

The buttons Q, R, M are also pre-mapped. Again, nothing to do with PlayCover.

**Comment by jaeiyden** [comment]
oh damn thats a bummer
tysm

**Comment by TheMoonThatRises** [comment]
Tracking here #1493.
