### ISSUE TITLE
Playcover run in the background

### ISSUE THREAD

**Issue by CrazyEig** [PlayCover/PlayCover#1533]
### App Store link

no

### Current issues

- [ ] App fails to install
- [ ] App fails to open
- [ ] App crashes randomly during usage
- [ ] App experiences graphical issues or broken UI
- [ ] App fails to connect to servers
- [X] Other

### More details

Hello, can Playcover run in the background? I wrote a Python script to automatically play a game, but the script only works when the game window is in the foreground. Additionally, simulating mouse clicks causes my mouse to move to the game window, which prevents me from doing other work. Is it possible to add a feature ，such as I send coordinates (x, y) to Playcover, and Playcover automatically clicks in the background? Thank you.

### What version of PlayCover are you using?

3.0.0 beta 2

### What version of macOS are you using?

Ventura (macOS 13)

### Issue Language

- [X] Yes my issue is written in English

**Comment by TheMoonThatRises** [comment]
Take a look at https://github.com/PlayCover/PlayTools if you really need to. We can't provide much more support otherwise.
