### ISSUE TITLE
[Game Support]: Genshin Impact fails to open

### ISSUE THREAD

**Issue by thinh48999** [PlayCover/PlayCover#1535]
### App Store link

<img width="1007" alt="Screenshot 2024-06-28 at 23 28 55" src="https://github.com/PlayCover/PlayCover/assets/174134940/5f33d528-59bf-4b40-9f0d-c3e30a446ce0">

### Current issues

- [ ] Game fails to install
- [X] Game fails to open
- [ ] Game crashes randomly during gameplay
- [ ] Game does not work with keymapping
- [ ] Game experiences graphical issues or broken UI
- [ ] Game fails to connect to servers or complete download

### More details

i can't open game

### What version of PlayCover are you using?

3.0.0 beta 2

### What version of macOS are you using?

Sonoma (macOS 14)

### Issue Language

- [X] Yes my issue is written in English

**Comment by TheMoonThatRises** [comment]
Can you provide the full crash report?
