### ISSUE TITLE
Launching PlayCover changes the audio output device

### ISSUE THREAD

**Issue by dixtdf** [PlayCover/PlayCover#154]
There seems to be a problem with the latest version, starting PlayCover will change the audio output device, I did not try other versions, this phenomenon is 100% triggered

MacStudio Apple M1 Max 32G macOS Ventura 13.0

**Comment by Candygoblen123** [comment]
This has been fixed in dev I believe. Can you confirm if the issue persists on the latest nightly build? You can download it from the Actions tab.

**Comment by dixtdf** [comment]
https://github.com/PlayCover/PlayCover/actions/runs/2848980343
The issue has been fixed on the latest daily build
