### ISSUE TITLE
[Game Support]: HSR 2.3.1 can not login

### ISSUE THREAD

**Issue by fhnstephen** [PlayCover/PlayCover#1546]
### App Store link

https://apps.apple.com/us/app/honkai-star-rail/id1599719154

### Current issues

- [ ] Game fails to install
- [ ] Game fails to open
- [ ] Game crashes randomly during gameplay
- [ ] Game does not work with keymapping
- [ ] Game experiences graphical issues or broken UI
- [ ] Game fails to connect to servers or complete download

### More details

If I login using username password, it says "invalid parameter".
If I use facebook to login, it says "faild to login"

I tried setting boot-args, no luck.

Playchain is enabled, preferences are cleared.

### What version of PlayCover are you using?

3.0.0

### What version of macOS are you using?

Sonoma (macOS 14)

### Issue Language

- [X] Yes my issue is written in English

**Comment by dain98** [comment]
I have the exact same issue. Was on 14, tried 14.5.

**Comment by valodes** [comment]
Same issue here

**Comment by bshaydullin** [comment]
Can confirm, same issue on 2.3.1 (Russian version)
![image](https://github.com/PlayCover/PlayCover/assets/84585143/c3336d81-bfa8-496f-a656-49a52476894c)

**Comment by mrjasonzee** [comment]
open terminal
type cd ~/Library/Containers/io.playcover.PlayCover/
type mkdir PlayChain
it seems like something can goof and the playchain folder just doesnt exist

**Comment by Wendor** [comment]
> open terminal type cd ~/Library/Containers/io.playcover.PlayCover/ type mkdir PlayChain it seems like something can goof and the playchain folder just doesnt exist

In my case cleaning PlayChain data helps
```bash
rm -rf ~/Library/Containers/io.playcover.PlayCover/PlayChain/*
```
