### ISSUE TITLE
[Bug]: Zenless Zone Zeroo laggy and unresponsive controller

### ISSUE THREAD

**Issue by YoloEY** [PlayCover/PlayCover#1550]
### Describe the bug

As the title says, the controller does not respond in the game
The controller is xbox，I have tried many methods but nothing works.

### Steps to reproduce

the controller does not work

### Expected behaviour

the controller does not work

### What version of PlayCover are you using?

3.0.0

### What version of macOS are you using?

Sonoma (macOS 14)

### Issue Language

- [X] Yes my issue is written in English

**Comment by Zhang0577** [comment]
I encountered the same problem
When playing with an Xbox controller, disconnection often occurs. At this time, pressing the Xbox logo button can call out the Mac game scheduling menu, but the instructions of other buttons cannot be passed into the game

**Comment by YoloEY** [comment]
> I encountered the same problem When playing with an Xbox controller, disconnection often occurs. At this time, pressing the Xbox logo button can call out the Mac game scheduling menu, but the instructions of other buttons cannot be passed into the game

Yes, I tried Genshin Impact again and there is no problem.  The controller works fine on the iphone.

**Comment by Zhang0577** [comment]
您好，您的来信已收到。

**Comment by mtaras0** [comment]
Can confirm, was able to login on 3.0.0 beta 2 (initial login on 3.0.0 release doesn't work), gamepad worked initially but then stopped on the cutscene. After that it never worked.

**Comment by mtaras0** [comment]
Disabling keymapping for the game seems to fix the issue

**Comment by Aintor** [comment]
I have the same problem

**Comment by YoloEY** [comment]
> 解决

I turned it off at the beginning, but the controller still has a lag, and if you turn on the keyboard mapping controller it doesn't respond at all

**Comment by YoloEY** [comment]
The lag problem is much better when playing in window mode

**Comment by shatyuka** [comment]
it turns out to be a focus issue. sometimes the game lost focus and controller won't work 
just click another window and switch back to game

**Comment by Usakapi** [comment]
> it turns out to be a focus issue. sometimes the game lost focus and controller won't work just click another window and switch back to game

I tried it but it didn't improve.

**Comment by waterlens** [comment]
I found that if I don't use AC power adapter on my macbook, the controller would work well. I'm also using a Xbox controller. Is its bluetooth too weak?

**Comment by Aintor** [comment]
> I found that if I don't use AC power adapter on my macbook, the controller would work well. I'm also using a Xbox controller. Is its bluetooth too weak?

I don't think it's a problem with Bluetooth, the situation also occurred when I used a wired one.

**Comment by dale502** [comment]
> it turns out to be a focus issue. sometimes the game lost focus and controller won't work just click another window and switch back to game

same here, if I don't use second screen on Mac, only use one screen with zzz fullscreen, disconnection get less
——
update my solution: one main desktop, creat a empty desktop put in the middle, zzz full screen in the right, disconnection will less, if disconect, swipe to empty desktop, then swipe back to zzz

**Comment by Misaka-Tang** [comment]
> it turns out to be a focus issue. sometimes the game lost focus and controller won't work just click another window and switch back to game

Same issue here, what's meaning of focusing issue? since I play game every time the game always online. Do you mean when reading text from game and don't use it, the controller will disconnect?

**Comment by Ding-Kyoma** [comment]
Same issue. The controller input signal is good (I can see input in joystick mapper), but ZZZ sometimes no response

**Comment by Juan-VC** [comment]
> Disabling keymapping for the game seems to fix the issue

Tested this, disabled key mapping, smart keycap and mouse scroll wheel and the controller works. At least its a good enough solution for me that I do not want to play with the keyboard.

**Comment by ChaseGQH** [comment]
same to you, but mine is ps5 controller

**Comment by Ding-Kyoma** [comment]
None of the above methods worked for me. I have a weird method, but at least the controller works.

In windowed mode, use the mouse clicker to click on the menu bar (e.g. help) every 300ms. Controller works so well!

**Comment by harukawu** [comment]
> None of the above methods worked for me. I have a weird method, but at least the controller works.
> 
> In windowed mode, use the mouse clicker to click on the menu bar (e.g. help) every 300ms. Controller works so well!

Thanks! This is the only method which is useful for me. The only flaw of this method is that because of the clicking behavior, the blinking menu bar makes my eyes a little uncomfortable. lol

**Comment by Azyzraissi** [comment]
> None of the above methods worked for me. I have a weird method, but at least the controller works.
> 
> In windowed mode, use the mouse clicker to click on the menu bar (e.g. help) every 300ms. Controller works so well!

This sounds like the best hack we can use for now. If someone find the nightly build that fixes this, please consider linking it here. It also may be a problem in the game itself. I've seen people reporting problems with DS4/5 controllers on PC, hopefully they fix it on their end if that's the case. 

Thank you so much for the tip.

**Comment by CRYst-Alies** [comment]
> > None of the above methods worked for me. I have a weird method, but at least the controller works.
> > In windowed mode, use the mouse clicker to click on the menu bar (e.g. help) every 300ms. Controller works so well!
> 
> This sounds like the best hack we can use for now. If someone find the nightly build that fixes this, please consider linking it here. It also may be a problem in the game itself. I've seen people reporting problems with DS4/5 controllers on PC, hopefully they fix it on their end if that's the case.
> 
> Thank you so much for the tip.

Running a shortcut every few seconds and then going back to the Zenless Zone Zeroo will also make the controller work properly, and choosing a shortcut that doesn't actually do anything will make the experience better. But it will be more troublesome.

**Comment by Dreamacro** [comment]
write an apple script workaround for the controller, it needs `cliclick` because `click at` not working.

if it doesn't work, try to adjust `200,20`

```shell
$ brew install cliclick
```

```applescript
tell application "com.miHoYo.Nap" to activate

repeat
	delay 0.5
	
	tell application "System Events"
		set activeApp to name of first application process whose frontmost is true
	end tell
	
	if activeApp is not "ZenlessZoneZero" then exit repeat
	
	do shell script "/opt/homebrew/bin/cliclick c:200,20"
end repeat
```

**Comment by mrjasonzee** [comment]
What worked for me was completely turning off any and all keymapping settings and also in system settings>game controllers disabling the option for the home button to activate launch pad (idk why that affects it). unless i rapidly swipe between my desktop and game it usually works fine. hope this works for somebody else

**Comment by Dreamacro** [comment]
@killersquid1440 disable launch pad on setting solve my problem, thx

**Comment by ChaseGQH** [comment]
> 以上方法都不适用于我。我有一个奇怪的方法，但至少控制器有效。
> 
> 在窗口模式下，每 300 毫秒使用鼠标点击器点击菜单栏（例如帮助）。控制器工作得很好！

i tried it. but, why does it cause my game to quit unexpectly…

**Comment by wasd96040501** [comment]
Full screen mode and click title bar should also help and will not quit unexpectedly.
Or set frame rate to 30 should also help.

**Comment by mrjasonzee** [comment]
this appears to be either a macOS issue with the gamepad or playcover because if I launch ZZZ and the controller didn't work whatsoever, that persisted into Honkai Star Rail. Hopefully a nightly fixes the issue. 
edit - killing finder helps significantly, so i think it is a macOS issue

**Comment by Ding-Kyoma** [comment]
> None of the above methods worked for me. I have a weird method, but at least the controller works.
> 
> In windowed mode, use the mouse clicker to click on the menu bar (e.g. help) every 300ms. Controller works so well!

The previous method may make the game laggy. The flashing menu bar also made uncomfortable. The following method handle is slightly laggy, but does not affect the game and no flashing bar.

In windowed mode, use the mouse clicker to click the zzz game window every 50ms.

**Comment by ZhengW-99** [comment]
please solve it quickly, lalalalllalllalalallalalallalalalal

**Comment by Adaliciously** [comment]
> please solve it quickly, lalalalllalllalalallalalallalalalal

This project is OpenSource, done by volunteers, for free. You are welcome to "solve it" yourself instead of spamming the issue with your whining.

**Comment by Zexin-Li** [comment]
set display's refresh rate as 60, set game fps as 60

**Comment by hongzuL** [comment]
> set display's refresh rate as 60, set game fps as 60

omg, this works for me! thx a lot!

**Comment by jamesbee** [comment]
> set display's refresh rate as 60, set game fps as 60

works for m2 max, Sonoma 14.5, build 3.0.0 (797), windowed.
but the controller is still unresponsive when playing full screen.
anyway it is finally a playable workaround, thanks a lot 👍

**Comment by ChaseGQH** [comment]
> > 显示器刷新率为60，游戏帧率为60
> 
> 适用于 m2 max、Sonoma 14.5、build 3.0.0 (797)、窗口。 但全屏播放时控制器仍然无响应。 无论如何，这终于是一个可玩的解决方法，非常感谢👍

In fact, just adjust the frame rates of the two to be the same, both 120 will also work.

**Comment by DeveloperCraig** [comment]
> set display's refresh rate as 60, set game fps as 60

This does seem to fix the issue and also works in fullscreen mode on my M2Pro MacBook, I wonder if the reason for this issue is related to the how the Game records inputs with controller and since the game can only be 30 or 60FPS by setting your Mac to use Promotion Display maybe the game can't register the inputs correctly?

**Comment by hongzuL** [comment]
> > set display's refresh rate as 60, set game fps as 60
> 
> omg, this works for me! thx a lot!
Mine is mac mini, m1 2020, Ventura 13.6.7.  Controller works well in both windowed and full screen mode.

**Comment by XuYicong** [comment]
The cause may be that the main dispatch queue, in which controller events are processed, is not served in time. A fix on the PlayCover side may be to manually drain the main dispatch queue periodically.

**Comment by YoloEY** [comment]
> set display's refresh rate as 60, set game fps as 60将显示器的刷新率设置为 60，将游戏 FPS 设置为 60

Thanks！ This works for me.

**Comment by ritoma424** [comment]
> set display's refresh rate as 60, set game fps as 60

Thanks！works for me！My device is MacBookPro M1 pro ，Sonoma 14.5

**Comment by Moremist** [comment]
> The cause may be that the main dispatch queue, in which controller events are processed, is not served in time. A fix on the PlayCover side may be to manually drain the main dispatch queue periodically.

Thanks to this fabulous man, fix branch recently merged into master of PlayTools waiting for new PlayCover build to try. Be patient, traverels 🥇

**Comment by mrjasonzee** [comment]
I just built PlayCover myself to get the latest PlayTools since the most recent Nightly compiled an hour before the fix was merged and all the things that would otherwise cause freezing stopped! @XuYicong Thank you so much!

**Comment by Zhang0577** [comment]
> I just built PlayCover myself to get the latest PlayTools since the most recent Nightly compiled an hour before the fix was merged and all the things that would otherwise cause freezing stopped! @XuYicong Thank you so much!

hello，could you pls tell me how to build Playcover myself? I urgently hope to use this bug fix。If it involves complex and professional tools/operations, then ignore me, I'll wait for the official public version

**Comment by mrjasonzee** [comment]
> > I just built PlayCover myself to get the latest PlayTools since the most recent Nightly compiled an hour before the fix was merged and all the things that would otherwise cause freezing stopped! @XuYicong Thank you so much!
> 
> hello，could you pls tell me how to build Playcover myself? I urgently hope to use this bug fix。If it involves complex and professional tools/operations, then ignore me, I'll wait for the official public version

i would recommend waiting for the next nightly release of PlayCover, but on the readme for the github page of playcover you can get to the documentation to build it if you really want to. It does require some basic knowledge of the terminal.

**Comment by Zhang0577** [comment]
> > > I just built PlayCover myself to get the latest PlayTools since the most recent Nightly compiled an hour before the fix was merged and all the things that would otherwise cause freezing stopped! @XuYicong Thank you so much!
> > 
> > 
> > hello，could you pls tell me how to build Playcover myself? I urgently hope to use this bug fix。If it involves complex and professional tools/operations, then ignore me, I'll wait for the official public version
> 
> i would recommend waiting for the next nightly release of PlayCover, but on the readme for the github page of playcover you can get to the documentation to build it if you really want to. It does require some basic knowledge of the terminal.

thx! I'll try

**Comment by Azyzraissi** [comment]
> > I just built PlayCover myself to get the latest PlayTools since the most recent Nightly compiled an hour before the fix was merged and all the things that would otherwise cause freezing stopped! @XuYicong Thank you so much!
> 
> hello，could you pls tell me how to build Playcover myself? I urgently hope to use this bug fix。If it involves complex and professional tools/operations, then ignore me, I'll wait for the official public version

For future references, everything you need to know is here : https://docs.playcover.io/building_from_source/index 
The latest build(802) has the fix.

Enjoy and good luck with your pulls

**Comment by Zhang0577** [comment]
Thanks a lot, already started playing!

**Comment by Zhang0577** [comment]
> > > I just built PlayCover myself to get the latest PlayTools since the most recent Nightly compiled an hour before the fix was merged and all the things that would otherwise cause freezing stopped! @XuYicong Thank you so much!
> > 
> > 
> > hello，could you pls tell me how to build Playcover myself? I urgently hope to use this bug fix。If it involves complex and professional tools/operations, then ignore me, I'll wait for the official public version
> 
> For future references, everything you need to know is here : https://docs.playcover.io/building_from_source/index The latest build(802) has the fix.
> 
> Enjoy and good luck with your pulls

Thanks a lot, already started playing!

**Comment by PaleNeutron** [comment]
@Zhang0577 , can you share your self-built playcover binary?

**Comment by Aintor** [comment]
> @Zhang0577 , can you share your self-built playcover binary?

Just try the latest nightly release
https://nightly.link/playcover/playcover/workflows/2.nightly_release/develop
