### ISSUE TITLE
Controller disconnection and crash when playing Zenless Zone Zero

### ISSUE THREAD

**Issue by Zhang0577** [PlayCover/PlayCover#1551]
### Describe the bug

1. When playing with an Xbox controller, disconnection often occurs. At this time, pressing the Xbox logo button can call out the Mac game scheduling menu, but the instructions of other buttons cannot be passed into the game

2. Occasionally, there will be crash during the game, and the error message is:

Exception Type:: EXC_BREAKPOINT(SIGTRAP)
Exception Codes: 0x0000000000000001, 0x00000001a20beef4
Termination Reason: Namespace SIGNAL, Code 5 Trace/BPT trap: 5
Terminating Process: exc handler [35251]

MBP x  M1 pro  x  Mac OS 15 beta  x sip on
Playcover version：3.0.0（793） x  2560*1440 

### Steps to reproduce

Open the game and play normally,  controller disconnection occurs frequently
The crash occurs in the battle scene

### Expected behaviour

The controller operates normally and the game does not crash

### Crash log

```shell
Exception Type:: EXC_BREAKPOINT(SIGTRAP)
Exception Codes: 0x0000000000000001, 0x00000001a20beef4
Termination Reason: Namespace SIGNAL, Code 5 Trace/BPT trap: 5
Terminating Process: exc handler [35251]
```

### What version of PlayCover are you using?

3.0.0

### What version of macOS are you using?

macOS beta (please state the specific version)

### Issue Language

- [X] Yes my issue is written in English

**Comment by zhugunick** [comment]
I also have this question. I asked my friends around me, and they also have this question!

**Comment by kang49** [comment]
Duplicate issue #1550
