### ISSUE TITLE
can't open game Zenless zone zero 

### ISSUE THREAD

**Issue by Tertory** [PlayCover/PlayCover#1557]
### App Store link

Zenless zone zero

### Current issues

- [ ] Game fails to install
- [X] Game fails to open
- [ ] Game crashes randomly during gameplay
- [ ] Game does not work with keymapping
- [ ] Game experiences graphical issues or broken UI
- [ ] Game fails to connect to servers or complete download

### More details

If enable SIP I can't login game  
if I disable SIP I can't open game

### Crash log

```shell
-
```

### What version of PlayCover are you using?

3.0.0

### What version of macOS are you using?

Sonoma (macOS 14)

### Issue Language

- [X] Yes my issue is written in English

**Comment by anz507** [comment]
same here, even after reinstalling recent 3.0

**Comment by TheMoonThatRises** [comment]
Do you have PlayChain enabled?

**Comment by Tertory** [comment]
How can I know that PlayChain enabled?

**Comment by IrsyadFikriansyah** [comment]
Same here, I have tried with PlayChain enable and disabled still won't open when the SIP is disabled

**Comment by mrjasonzee** [comment]
Enable SIP

**Comment by butterknight** [comment]
I have the same issue:
1. enable SIP - can't login
2. disable SIP - can't open

PlayChain enabled/disabled seemed to have no effect on the outcome. Anyone has any new info?

Version: 3.0.0 (793)

**Comment by mrjasonzee** [comment]
open terminal
type cd ~/Library/Containers/io.playcover.PlayCover/
type mkdir PlayChain
this works with SIP enabled, this is an issue with pretty much all of hoyo games

**Comment by anz507** [comment]
> mkdir PlayChain

It's already exists

**Comment by Catta1997** [comment]
On Playocover right click on ZZZ, show in finder then shift+double click

**Comment by butterknight** [comment]
> open terminal type cd ~/Library/Containers/io.playcover.PlayCover/ type mkdir PlayChain this works with SIP enabled, this is an issue with pretty much all of hoyo games

This resolved it for me! Amazing! Thank you!
