### ISSUE TITLE
[Game Support]: Genshin won't let me log in my account.

### ISSUE THREAD

**Issue by Yunasski** [PlayCover/PlayCover#1560]
### App Store link

https://genshin.hoyoverse.com/en/

### Current issues

- [ ] Game fails to install
- [X] Game fails to open
- [ ] Game crashes randomly during gameplay
- [ ] Game does not work with keymapping
- [ ] Game experiences graphical issues or broken UI
- [X] Game fails to connect to servers or complete download

### More details

So, technically, I've been trying to play Genshin impact on my Mac, by using Playcover.
But, unfortunately, when I open the app, (Genshin Impact) It is all good, until I want to connect my account, it say Parameter Error. I've tried everything, seen so much tutorials, and asked for help in the Discord server, but nobody succeeded to help me.
Also, when I go into the genshin app, settings, and try to save my account in, it won't work. So I'm stuck, and I would love to have some help.

### Crash log

```shell
Parameter Error.
```

### What version of PlayCover are you using?

3.0.0

### What version of macOS are you using?

Sonoma (macOS 14)

### Issue Language

- [X] Yes my issue is written in English

**Comment by Yunasski** [comment]
![Uploading Capture d’écran 2024-07-04 à 23.49.24.png…]()

**Comment by TheMoonThatRises** [comment]
Make sure you are on the latest release of PlayCover and have PlayChain enabled.

**Comment by TheMoonThatRises** [comment]
Clear PlayChain data, launch Genshin through PlayCover and try again.

**Comment by Jaivalk1234jk** [comment]
why it is saying i have to log in the game center in settings but I have already logged it
