### ISSUE TITLE
[Game Support]: Can't Log in game Zenless zone zero  with PlayCover_nightly_796.dmg

### ISSUE THREAD

**Issue by Tertory** [PlayCover/PlayCover#1565]
### App Store link

-

### Current issues

- [ ] Game fails to install
- [ ] Game fails to open
- [ ] Game crashes randomly during gameplay
- [ ] Game does not work with keymapping
- [ ] Game experiences graphical issues or broken UI
- [X] Game fails to connect to servers or complete download

### More details

Can't Log in game Zenless zone zero

PlayCover_nightly_796.dmg

### Crash log

```shell
-
```

### What version of PlayCover are you using?

Nightly/beta (please specify build number)

### What version of macOS are you using?

Sonoma (macOS 14)

### Issue Language

- [X] Yes my issue is written in English

**Comment by TheMoonThatRises** [comment]
Use a newer nightly build of PlayCover, clear PlayChain data, and login again. If this doesn't work, reopen another issue.
