### ISSUE TITLE
it doesn't work

### ISSUE THREAD

**Issue by hecker1230** [PlayCover/PlayCover#157]
<img width="1440" alt="Screen Shot 2022-08-14 at 00 55 17" src="https://user-images.githubusercontent.com/110428399/184517101-153b4b88-135c-41d4-99a4-dbaaa0ab6160.png">

**Comment by ZhichGaming** [comment]
Run this in your terminal: 
`xcode-select --install`

**Comment by hecker1230** [comment]
why?

**Comment by ZhichGaming** [comment]
What do you mean by why?

**Comment by hecker1230** [comment]
why should I write it it redirects me to Xcode download

**Comment by hecker1230** [comment]
here is my discord:
theone10011#8799

**Comment by ZhichGaming** [comment]
You need xCode command line tools to run PlayCover.

**Comment by hecker1230** [comment]
no play cover works its when I add app that doesn't work

**Comment by ZhichGaming** [comment]
Yes, you need xCode command line tools to install and run apps.

**Comment by hecker1230** [comment]
ok

**Comment by hecker1230** [comment]
thx u very very much bro
