### ISSUE TITLE
[Bug]: Gamepad freezes/stops working in Zenless Zone Zero

### ISSUE THREAD

**Issue by tdrkDev** [PlayCover/PlayCover#1570]
### Describe the bug

I'm using Xbox Wireless Controller to play some games with PlayCover on my MacBook Air M1. Gamepad is working as expected in all games but Zenless Zone Zero.

In ZZZ, either after selecting gamepad as input source, either swiping the full-screen game window with 3-finger touchpad gesture, gamepad just dies.

Sometimes it starts to work again if I press random buttons on it very fast.
If not, the only way to make it work again is to disconnect it, open game window, enable gamepad (Xbox controller automatically powers off after disconnection) and do not even open the menu bar, otherwise it'll have terrible input lag or it'll just die again.

Maybe this issue should have a `game support` tag, but I think that `bug` one is more relevant here, cause game is still playable.

### Steps to reproduce

Variant 1
1. Open Zenless Zone Zero
2. On login screen, go to Settings -> Input and change input device to gamepad. With 50% chance, game won't react to gamepad buttons.

Variant 2
1. Open Zenless Zone Zero
2. Login
3. Start any conversation, where you need to manually press A to continue
4. Swipe game window with 3-finger touchpad gesture
5. After minute or two, swipe game window back again

### Expected behaviour

Normal gamepad work without any input lag or unhandled input events

### What version of PlayCover are you using?

3.0.0

### What version of macOS are you using?

Sonoma (macOS 14)

### Issue Language

- [X] Yes my issue is written in English

**Comment by Azyzraissi** [comment]
Duplicate of #1550

**Comment by tdrkDev** [comment]
> Duplicate of #1550

Whoops, missed that issue. Closing.
