### ISSUE TITLE
[Game Support]: Brown Dust 2 Api Server Error

### ISSUE THREAD

**Issue by JecerSE** [PlayCover/PlayCover#1574]
### App Store link

https://apps.apple.com/us/app/browndust2-adventure-rpg/id6450099588

### Current issues

- [ ] Game fails to install
- [ ] Game fails to open
- [ ] Game crashes randomly during gameplay
- [ ] Game does not work with keymapping
- [ ] Game experiences graphical issues or broken UI
- [X] Game fails to connect to servers or complete download

### More details

An error occured while processing API server. / -2
And wont connect to internet despite having abnormal speeds

### What version of PlayCover are you using?

Nightly/beta (please specify build number)

### What version of macOS are you using?

Sonoma (macOS 14)

### Issue Language

- [X] Yes my issue is written in English

**Comment by JecerSE** [comment]
i found a weird alternative to this problem, by removing play chain in its self the server come back to life a bit chonky image though. checking in later if i can revert it while still logging in

**Comment by JecerSE** [comment]
the issue of api network in browndust 2 was fixed by disabling play chain and all setting on the bypasses tab after i injected back play chain.

**Comment by KyonP** [comment]
Is there any additional solution for this issue? 😢

**Comment by RobbySa** [comment]
I managed to fix the issue by clearing playchain data every time I start the app.
This just forces you to re-login but everything else works fine

**Comment by Freewayy** [comment]
> I managed to fix the issue by clearing playchain data every time I start the app. This just forces you to re-login but everything else works fine

it doesn't work

**Comment by frank61003** [comment]
any update ?
I can't use apple login and it shows the error code.

**Comment by Freewayy** [comment]
defaults delete com.neowizgames.game.browndust2ios neo_google_user_id
