### ISSUE TITLE
[App Support]: HSR failed to open 

### ISSUE THREAD

**Issue by annatseng0725** [PlayCover/PlayCover#1576]
### App Store link

https://decrypt.day/app/id1599719154 

### Current issues

- [ ] App fails to install
- [X] App fails to open
- [ ] App crashes randomly during usage
- [ ] App experiences graphical issues or broken UI
- [ ] App fails to connect to servers
- [ ] Other

### More details

Everytime I want to open HSR, This appears:
<img width="256" alt="Screenshot 2024-07-10 at 14 09 47" src="https://github.com/PlayCover/PlayCover/assets/123565186/96db26d0-b097-4779-88ba-8b264c061e91">

No matter which option I click, it always closes. 

### What version of PlayCover are you using?

3.0.0

### What version of macOS are you using?

Sonoma (macOS 14)

### Issue Language

- [X] Yes my issue is written in English

**Comment by Catta1997** [comment]
try: 
- Open PlayCover
- Right click on hsr -> open in finder / show in finder
- Shift + Double click

**Comment by chair-man-f** [comment]
> try:
> 
> * Open PlayCover
> * Right click on hsr -> open in finder / show in finder
> * Shift + Double click

Thanks, this worked for me


what does it do exactly?

**Comment by Catta1997** [comment]
> > try:
> > 
> > * Open PlayCover
> > * Right click on hsr -> open in finder / show in finder
> > * Shift + Double click
> 
> Thanks, this worked for me
> 
> what does it do exactly?

Shift + double click will stop the app from trying to restore the last session
