### ISSUE TITLE
[Game Support]: Zenless zone zero failed to open。

### ISSUE THREAD

**Issue by hydra-bu** [PlayCover/PlayCover#1578]
### App Store link

none

### Current issues

- [ ] Game fails to install
- [X] Game fails to open
- [ ] Game crashes randomly during gameplay
- [ ] Game does not work with keymapping
- [ ] Game experiences graphical issues or broken UI
- [ ] Game fails to connect to servers or complete download

### More details

<img width="958" alt="image" src="https://github.com/PlayCover/PlayCover/assets/37682426/68d9d338-43b0-4050-a17a-559434d8cb4d">

I have tried the 3.0.0 release version as well as various nightly or beta versions, but none of them can run this game properly.

### What version of PlayCover are you using?

3.0.0

### What version of macOS are you using?

Sonoma (macOS 14)

### Issue Language

- [X] Yes my issue is written in English

**Comment by mrjasonzee** [comment]
are you starting it from within playcover?

**Comment by chirou-git** [comment]
> are you starting it from within playcover?

I am also having this issue when starting it within playcover.
How would I launch the game?

**Comment by mrjasonzee** [comment]
> > are you starting it from within playcover?
> 
> I am also having this issue when starting it within playcover. Should I try to launch it via shortcut instead?

try the shortcut

**Comment by hydra-bu** [comment]
> > > are you starting it from within playcover?
> > 
> > 
> > I am also having this issue when starting it within playcover. Should I try to launch it via shortcut instead?
> 
> try the shortcut

<img width="443" alt="image" src="https://github.com/PlayCover/PlayCover/assets/37682426/c5b446a3-6561-4f98-a2fa-7cbb88c26ffc">

Do you mean to start from here?  I have already tried that, and it still gives the same error.

**Comment by mrjasonzee** [comment]
have you tried any of the bypasses? under playcover, go to the app settings, bypasses, and try to see if any of those work

**Comment by mrjasonzee** [comment]
The game starts for me (i installed the CN version too), and i think you need SIP enabled. Try enabling it and starting the game again.

**Comment by hydra-bu** [comment]
> The game starts for me (i installed the CN version too), and i think you need SIP enabled. Try enabling it and starting the game again.

Thank you very much. After disabling SIP, it worked.
