### ISSUE TITLE
[App Support]: Despite following the login troubleshooting doc for Genshin Impact, I can't get it.

### ISSUE THREAD

**Issue by cwyh-7** [PlayCover/PlayCover#1580]
### App Store link

I'm..not sure what this is. 

### Current issues

- [ ] App fails to install
- [ ] App fails to open
- [ ] App crashes randomly during usage
- [ ] App experiences graphical issues or broken UI
- [ ] App fails to connect to servers
- [X] Other

### More details

Hello! So I'm trying to get into genshin impact on mac and keep getting the 'parameter error' despite following everything here: https://docs.playcover.io/getting_started/troubleshoot_login 

I've tried both boot-args and looked at keychain access but still nothing. Would love some help please! Thank you.

### What version of PlayCover are you using?

3.0.0

### What version of macOS are you using?

Sonoma (macOS 14)

### Issue Language

- [X] Yes my issue is written in English

**Comment by iTaysonLab** [comment]
try creating "PlayChain" folder (without quotes) in `~/Library/Containers/io.playcover.PlayCover/`, helped for me

(https://github.com/PlayCover/PlayTools/issues/161)
