### ISSUE TITLE
[Bug]: Random intermittent unresponsive controller input in Zenless Zone Zero

### ISSUE THREAD

**Issue by FlyMeToTheMoonAndLetMePlayAmongTheStars** [PlayCover/PlayCover#1584]
### Describe the bug

PS5 Dualsense controller input randomly goes unresponsive when playing the game, often when browsing through menus or simply walking around. It sometimes quickly goes away or sometimes stay stuck until the game is restarted. When controller input bugs out, it may either not accept any input altogether or get stuck on the previous registered input, like walking forward with joystick or panning camera angle.

- I've tested this with macOS game mode on/off, the problem happens regardless. 
- Also tested other games like Genshin Impact and other native Mac games to rule out any issue with the controller or macOS, there are no issues whatsoever with controller responsiveness in those games. 
- This seems to be a problem only with controller input as keymapping worked fine without lag.
- Happens in both release version (793) and nightly (802)

### Steps to reproduce

1. Enable controller support 
2. Select controller input in-game
3. Play the game

### Expected behaviour

Smooth, consistent controller input without any random periods of unresponsiveness. 

### What version of PlayCover are you using?

3.0.0

### What version of macOS are you using?

Sonoma (macOS 14)

### Issue Language

- [X] Yes my issue is written in English

**Comment by mrjasonzee** [comment]
Use nightly 802 or above. a fix was patched into playtools

**Comment by FlyMeToTheMoonAndLetMePlayAmongTheStars** [comment]
I thought I was using 802 already but it was actually 801, my mistake. Will close this once I confirm the fix.

**Comment by FlyMeToTheMoonAndLetMePlayAmongTheStars** [comment]
Can confirm issue is fixed as of nightly 802
