### ISSUE TITLE
[Bug]: Tried to access Honkai: Star Rail and could not log in

### ISSUE THREAD

**Issue by hamsterhugs** [PlayCover/PlayCover#1589]
### Describe the bug

When I first downloaded the api, the issue described here https://docs.playcover.io/getting_started/troubleshoot_login#1 popped up, which is that it said "Invalid Parameter". I tried troubleshooting including using a different boot-arg but it did not work. I could not login with my Hoyoverse account, but I could login with my icloud account but that means restarting all my progress in the game. One issue might be that I forgot to carry out step 2 before carrying out step 3 the first time, and then I went back and did it again.
<img width="743" alt="Screenshot 2024-07-13 at 11 24 22 PM" src="https://github.com/user-attachments/assets/701a80d8-dc80-4063-aff1-9f68f204c111">

(https://nightly.link/PlayCover/PlayCover/workflows/2.nightly_release/develop/PlayCover_nightly_803.dmg.zip link used to download version of PlayCover)

### Steps to reproduce

Download Honkai api
Shut down MacBook
Open startup options and then type csrutil disable in the terminal
Restart MacBook
Open PlayCover and attempt to login to Honkai
Realise I missed step 2 and then open the terminal and type sudo nvram etc
Restart MacBook
Login and then fail and get stuck here
Shut down MacBook and open startup options and type cstrutil disable again
Restart
Type in sudo nvram boot-args="amfi_get_out_of_my_way=1"

### Expected behaviour

Login was supposed to work afterwards

### What version of PlayCover are you using?

Nightly/beta (please specify build number)

### What version of macOS are you using?

Sonoma (macOS 14)

### Issue Language

- [X] Yes my issue is written in English

**Comment by MEMORIEmusic** [comment]
step 1: open terminal
step 2: type `cd ~/Library/Containers/io.playcover.PlayCover/`
step 3: type `mkdir PlayChain`

if youre wondering what it does, it creates a folder named PlayChain. yeah, thats all it does

**Comment by hamsterhugs** [comment]
> step 1: open terminal step 2: type `cd ~/Library/Containers/io.playcover.PlayCover/` step 3: type `mkdir PlayChain`
> 
> if youre wondering what it does, it creates a folder named PlayChain. yeah, thats all it does

Thank you! During what step do I open the terminal

**Comment by MEMORIEmusic** [comment]
> > step 1: open terminal step 2: type `cd ~/Library/Containers/io.playcover.PlayCover/` step 3: type `mkdir PlayChain`
> > if youre wondering what it does, it creates a folder named PlayChain. yeah, thats all it does
> 
> Thank you! During what step do I open the terminal

None. SIP method has been deprecated. Reset your boot-args, turn SIP back on. then when it boots up, type the above commands in.

**Comment by hamsterhugs** [comment]
> > > step 1: open terminal step 2: type `cd ~/Library/Containers/io.playcover.PlayCover/` step 3: type `mkdir PlayChain`
> > > if youre wondering what it does, it creates a folder named PlayChain. yeah, thats all it does
> > 
> > 
> > Thank you! During what step do I open the terminal
> 
> None. SIP method has been deprecated. Reset your boot-args, turn SIP back on. then when it boots up, type the above commands in.

How do I reset my boot-args

**Comment by hamsterhugs** [comment]
It worked! Thank you so much
