### ISSUE TITLE
Permission Error [Ventura]

### ISSUE THREAD

**Issue by allwh1tesay** [PlayCover/PlayCover#159]
Recently, I updated my Macbook 2020 13inch M1 to Ventura Public Beta, and came along with the error that says: "You don’t have permission to save the file “Frameworks” in the folder “Library”.
Some things I used to solve this problem:
1. Reinstall Playcover X
2. Restart Computer X
3. Go into recovery mode and used `repairHomePermissions` (Discord Idea) X

Possible ways to solve it but just not ideal:
1. Reinstall and rollback to Monterey (My files and stuff is running on Ventura so rollback is a problem)
2. Change my computer (Certainly not possible)

Since playcover runs fine on 99% of Ventura Beta Computers, I suspect to be a bug.

note: the log here

```
Version 13.0 (Build 22A5321d)
Installing PlayTools
System Integrity Protection status: enabled.

/Library/Developer/CommandLineTools
```

**Comment by allwh1tesay** [comment]
Oh and also I do tried everything under SIP disabled, same issue :(

**Comment by elisezhu123** [comment]
you should download the command line tools of your Xcode which can make play cover work but as the Xcode in App Store only support 13.4 version you should go to apple developer .com and download command line tools beta 5 for play cover to work

**Comment by allwh1tesay** [comment]
> you should download the command line tools of your Xcode which can make play cover work but as the Xcode in App Store only support 13.4 version you should go to apple developer .com and download command line tools beta 5 for play cover to work

nope, that did not help either with both the beta Xcode and the beta Command line tools

**Comment by ohaiibuzzle** [comment]
Test if you can write normally to `~/Library/Frameworks` (Open Finder, press ⌘ + ⇧ + G, put that in, then try creating a folder there)

**Comment by allwh1tesay** [comment]
> 

Yes I can do that.

**Comment by allwh1tesay** [comment]
> Test if you can write normally to `~/Library/Frameworks` (Open Finder, press ⌘ + ⇧ + G, put that in, then try creating a folder there)

Yes I can do that.

**Comment by lixin9311** [comment]
It seems like we need to move the PlayTools to another place.

**Comment by XuYicong** [comment]
If your username is different from your home directory name, or you did not accept the license, this will happen. Try changing your username to the same as home directory name, or run `sudo xcrun cc` in Terminal to be asked to accept the license.

**Comment by IsaacMarovitz** [comment]
This is resolved in nightlies
