### ISSUE TITLE
[Bug]: I can't download the IPA file for Genshin Impact

### ISSUE THREAD

**Issue by moranguelena** [PlayCover/PlayCover#1597]
### Describe the bug

It's written in the error window but I don't really understand it so I don't know what to do (and also I can't download it from decrypt.day because it says I have an ad block but I really do not I even turned off the one from safari) also other applications other than genshin are downloaded normally

### Steps to reproduce

went into the IPA library and tried to download the new version of the game

### Expected behaviour

the download is completed and I am able to open the game

### Crash log

```shell
[/var/folders/94/1k0chn393vsgphf4st88_jq00000gn/T/TemporaryItems/NSIRD_PlayCover_qZxbOS/download.html]
End-of-central-directory signature not found.  Either this file is not
a zipfile, or it constitutes one disk of a multi-part archive.  In the
latter case the central directory and zipfile comment will be found on
the last disk(s) of this archive.
unzip:  cannot find zipfile directory in one of /var/folders/94/1k0chn393vsgphf4st88_jq00000gn/T/TemporaryItems/NSIRD_PlayCover_qZxbOS/download.html or
/var/folders/94/1k0chn393vsgphf4st88_jq00000gn/T/TemporaryItems/NSIRD_PlayCover_qZxbOS/download.html.zip, and cannot find /var/folders/94/1k0chn393vsgphf4st88_jq00000gn/T/TemporaryItems/NSIRD_PlayCover_qZxbOS/download.html.ZIP, period.
```

### What version of PlayCover are you using?

3.0.0

### What version of macOS are you using?

Sonoma (macOS 14)

### Issue Language

- [X] Yes my issue is written in English

**Comment by Catta1997** [comment]
Google Drive quota limit, download it manually. If decrypt not work use another website
If you are logged in a Google account, you can download a quota limited file, without a logged account you can have this error if the file is download too much times in the last 24h

**Comment by moranguelena** [comment]
> Google Drive quota limit, download it manually. If decrypt not work use another website If you are logged in a Google account, you can download a quota limited file, without a logged account you can have this error if the file is download too much times in the last 24h

thank you! what other website is safe to download?
