### ISSUE TITLE
[App Support]: Genshin impact not able to log in

### ISSUE THREAD

**Issue by georgezheng1234** [PlayCover/PlayCover#1602]
### App Store link

in ipa form so can't drop here

### Current issues

- [ ] App fails to install
- [ ] App fails to open
- [ ] App crashes randomly during usage
- [ ] App experiences graphical issues or broken UI
- [ ] App fails to connect to servers
- [X] Other

### More details

I cannot log in to the account. says invalid parameter. I'v tried the troubleshoot and it didn't work. There's nothing related to genshin impact in keychain

### What version of PlayCover are you using?

3.0.0

### What version of macOS are you using?

Sonoma (macOS 14)

### Issue Language

- [X] Yes my issue is written in English

**Comment by heimeo** [comment]
I hope that by making this comment I can bump this post or something along the lines of that because I am having this same exact issue with both genshin and honkai star rail.

**Comment by heimeo** [comment]
I had the same exact issue. If you're using nightly, try switching to the regular build. I did and the invalid parameter error stopped appearing.

**Comment by hotsno** [comment]
Had the same with ZZZ. Found solution in the Discord that worked for me:

Run the following command in terminal: `mkdir ~/Library/Containers/io.playcover.PlayCover/PlayChain`

**Comment by TheMoonThatRises** [comment]
If the above solution doesn't work, clear PlayChain data for Genshin.
