### ISSUE TITLE
[Feature]: APP can change storage location

### ISSUE THREAD

**Issue by yulimfish** [PlayCover/PlayCover#1613]
### Is your feature request related to a problem?

The storage space on Mac is running low. The storage space on Mac is running low. I hope to find a different location, such as an external hard drive, to store app data or the app itself.

### Describe the solution you'd like

I hope to be allowed to choose my own data storage location in the app settings.

### Anything else?

![image](https://github.com/user-attachments/assets/ebcaed08-1e3a-43e6-ae4f-f075ecc6b768)

### Issue Language

- [X] Yes my issue is written in English

**Comment by TheMoonThatRises** [comment]
The majority of the app's data is stored in `~/Library/Containers/app-id`, and that cannot be moved (see https://github.com/PlayCover/PlayCover/discussions/473#discussioncomment-4024138). However, the app itself can be moved, but that is only 5gb out of ~30gb, depending on the app.
