### ISSUE TITLE
[Game Support]: 

### ISSUE THREAD

**Issue by kkb0235** [PlayCover/PlayCover#1617]
### App Store link

Zenless zone zero

### Current issues

- [ ] Game fails to install
- [ ] Game fails to open
- [ ] Game crashes randomly during gameplay
- [X] Game does not work with keymapping
- [ ] Game experiences graphical issues or broken UI
- [ ] Game fails to connect to servers or complete download

### More details

Zenless zone zero recognizes the controller, but there is a delay
No problem with Genshin impact

### What version of PlayCover are you using?

3.0.0

### What version of macOS are you using?

Sonoma (macOS 14)

### Issue Language

- [X] Yes my issue is written in English

**Comment by JecerSE** [comment]
Have you tried lowering the resolution? Or enabling playchain?

**Comment by kkb0235** [comment]
> Have you tried lowering the resolution? Or enabling playchain?

plyachain is enabled
It's better if I lower the resolution
But there are still delays
Insufficient PC specs...

**Comment by MEMORIEmusic** [comment]
Issue fixed in the latest nightly.

**Comment by kkb0235** [comment]
> Issue fixed in the latest nightly.

thank you
solved
