### ISSUE TITLE
[特点]：Icon customization

### ISSUE THREAD

**Issue by Dariozuo** [PlayCover/PlayCover#1618]
### Is your feature request related to a problem?

no

### Describe the solution you'd like

Hope to add a custom icon function, such as dark and light color changes.

### Anything else?

no

### Issue Language

- [X] Yes my issue is written in English

**Comment by Catta1997** [comment]
idk if this has be added recently but on macOS you can't, like on iOS, add multiple icon on your app. But since is macOS you can change the app in any moment with app "preferences"

**Comment by TheMoonThatRises** [comment]
This can be done natively on MacOS pretty easily (you can check out this guide https://9to5mac.com/2021/11/08/change-mac-icons/) and I doubt it warrants another method.
