### ISSUE TITLE
Screen Title too Big

### ISSUE THREAD

**Issue by Dhi47** [PlayCover/PlayCover#1625]
### Describe the bug

Hello, Im trying to play grandsummoners, but my screen game is too big to enter the game . Currently using play cover version 3.0.0
<img width="1440" alt="Screenshot 2024-08-07 at 8 33 31 PM" src="https://github.com/user-attachments/assets/e81f4592-5970-4606-bf90-7d7a349e6801">

### Steps to reproduce

Install and re-install back still the same

### Expected behaviour

So far the screen didn't crash. 

### What version of PlayCover are you using?

3.0.0

### What version of macOS are you using?

Sonoma (macOS 14)

### Issue Language

- [X] Yes my issue is written in English

**Comment by TheMoonThatRises** [comment]
You can go to the app's graphical settings in PlayCover, set the resolution to `App Default` and tick the box that says `Fix window display issues`. This will put the app into portrait mode and fixes the window being cut off.
