### ISSUE TITLE
[Bug]: Wuthering Waves new update

### ISSUE THREAD

**Issue by ihavelotsofissues** [PlayCover/PlayCover#1632]
### Describe the bug

what do i do now?
<img width="1440" alt="Screenshot 2024-08-13 at 8 51 35 PM" src="https://github.com/user-attachments/assets/be31f52f-171d-4c09-b070-ec78b96be89f">

### Steps to reproduce

i reinstalled WuWa after it crashing and now it does this, waht do i do

### Expected behaviour

i was going to play WuWa but it just said to download the new version but in using a macbook air and it doesnt let me download it

### What version of PlayCover are you using?

3.0.0

### What version of macOS are you using?

Sonoma (macOS 14)

### Issue Language

- [X] Yes my issue is written in English

**Comment by MEMORIEmusic** [comment]
Update your game.

**Comment by kang49** [comment]
Close this issue pls, it's not Playcover's bug.

**Comment by ihavelotsofissues** [comment]
how @kang49

**Comment by kang49** [comment]
> how @kang49

## UPDATE YOUR GAME!!!
First, you open the game with 1.0.0 version 

<img width="77" alt="Screenshot 2024-08-14 at 16 23 26" src="https://github.com/user-attachments/assets/af3c42b4-28b0-43ee-971a-a0238b2335e4">


(Latest version is 1.1.0), So you can update a latest version at (https://decrypt.day/app/id6475033368) before open a game with PlayCover again. And recheck that you have a latest game version on the right top of the screen.

<img width="500" alt="Screenshot 2024-08-14 at 16 30 54" src="https://github.com/user-attachments/assets/1bc005dd-0aab-4af9-8c7e-d429e823a9bb">

I hope you can fix this problem with your self.

**Comment by ihavelotsofissues** [comment]
> > how @kang49
> 
> ## UPDATE YOUR GAME!!!
> First, you open the game with 1.0.0 version
> 
> <img alt="Screenshot 2024-08-14 at 16 23 26" width="77" src="https://private-user-images.githubusercontent.com/81503963/357757462-af3c42b4-28b0-43ee-971a-a0238b2335e4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM2NjYwMDIsIm5iZiI6MTcyMzY2NTcwMiwicGF0aCI6Ii84MTUwMzk2My8zNTc3NTc0NjItYWYzYzQyYjQtMjhiMC00M2VlLTk3MWEtYTAyMzhiMjMzNWU0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODE0VDIwMDE0MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRiNzU0ZTc1NDUwNDA0ZjcwNTU5NTU1MTVmNmIzYmQwNzA3YTBjZmRiNDljMTUwYTUwZDRhZTAzMzhjZTJkYzMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.RbLIM4zssN7P6nUFD77Tx2NnbunOKhxJ4u2ghaeKa0w">
> (Latest version is 1.1.0), So you can update a latest version at (https://decrypt.day/app/id6475033368) before open a game with PlayCover again. And recheck that you have a latest game version on the right top of the screen.
> 
> <img alt="Screenshot 2024-08-14 at 16 30 54" width="500" src="https://private-user-images.githubusercontent.com/81503963/357758406-1bc005dd-0aab-4af9-8c7e-d429e823a9bb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM2NjYwMDIsIm5iZiI6MTcyMzY2NTcwMiwicGF0aCI6Ii84MTUwMzk2My8zNTc3NTg0MDYtMWJjMDA1ZGQtMGFhYi00YWY5LThjN2UtZDQyOWU4MjNhOWJiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODE0VDIwMDE0MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWE3ZmM2ZDZhZjViNDVlMzk2MWE4ZGIwMjEzODE2ZDFkNTc4MzlmMWNlNGU3YTQwMWU3MjFjZDE4MTkzYmVjNGMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.PZuEPIj1cFs4mTCqpEKAMzpxNQ1c1UcSzay8of0N4FQ">
> I hope you can fix this problem with your self.

ty
