### ISSUE TITLE
[Bug]: use brew to install playcover having an error

### ISSUE THREAD

**Issue by yhwyxy** [PlayCover/PlayCover#1648]
### Describe the bug

use brew to install
Error: Cask playcover-community depends on hardware architecture being one of [{:type=>:arm, :bits=>64}], but you are running {:type=>:intel, :bits=>64}.
![QQ_1724471003178](https://github.com/user-attachments/assets/b3f549bd-d19e-4717-aad2-e29ef258783c)

### Steps to reproduce

1. open terminal, input "brew install --cask PlayCover/playcover/playcover-community" 
2.  run this command

### Expected behaviour

Install successfully.

### What version of PlayCover are you using?

3.0.0

### What version of macOS are you using?

Sonoma (macOS 14)

### Issue Language

- [X] Yes my issue is written in English

**Comment by b1bradders** [comment]
Try reinstalling brew, the installer may have installed the wrong type of brew or configured something incorrectly.
The official command to run after uninstalling brew is:
> ```
> /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
>```
> from [brew.sh](https://brew.sh)

Or you can use their [`.pkg` installer](https://github.com/Homebrew/brew/releases/latest)

**Comment by TheMoonThatRises** [comment]
If the suggestion above doesn't work, check out this Homebrew discussion about migrating from intel to arm brew https://github.com/orgs/Homebrew/discussions/417.
