### ISSUE TITLE
[Game Support]: Onmyoji

### ISSUE THREAD

**Issue by SaltnonSugar** [PlayCover/PlayCover#1649]
### App Store link

https://apps.apple.com/us/app/onmyoji/id1257031979

### Current issues

- [ ] Game fails to install
- [X] Game fails to open
- [ ] Game crashes randomly during gameplay
- [ ] Game does not work with keymapping
- [ ] Game experiences graphical issues or broken UI
- [ ] Game fails to connect to servers or complete download

### More details

can't open app when click app icon

### What version of PlayCover are you using?

3.0.0

### What version of macOS are you using?

Sonoma (macOS 14)

### Issue Language

- [X] Yes my issue is written in English

**Comment by TheMoonThatRises** [comment]
Duplicate of #419.
