### ISSUE TITLE
[Bug]: Error upon downloading Genshin 5.0 from IPA source Decrypt.Day

### ISSUE THREAD

**Issue by Sollever** [PlayCover/PlayCover#1652]
### Describe the bug

<img width="502" alt="Screenshot 2024-08-28 at 3 01 10 PM" src="https://github.com/user-attachments/assets/59dd0779-e2c0-4230-81ec-133fe76fff9c">

Tried to update to version 5.0 by downloading it from the ipa library. Upon Clicking the genshin icon in the IPA library within the play cover app to download, the mentioned error shows up.
I tried deleting genshin and then reinstalling but the same error shows up.
 I did pre-download the update resources beforehand. 

### Steps to reproduce

Double clicking Genshin app icon to download the app from decrypt.day library within play cover app.

### Expected behaviour

Download the 5.0 Genshin app and update the existing one

### What version of PlayCover are you using?

3.0.0

### What version of macOS are you using?

Sonoma (macOS 14)

### Issue Language

- [x] Yes my issue is written in English

**Comment by Catta1997** [comment]
Download it again (for me I tried like 4 times), it can happen if the link is a google drive link with quota limit

**Comment by Sollever** [comment]
> Download it again (for me I tried like 4 times), it can happen if the link is a google drive link with quota limit

Are you telling me to click again to try to download? If that's the case I've been at it for 12 hours now.
And if I may ask did you face the same error?
