### ISSUE TITLE
Strange "Success!" message, app not starting other apps [Ventura]

### ISSUE THREAD

**Issue by taupter** [PlayCover/PlayCover#166]
Recently upgraded to Ventura. When I open the app everything seems normal, but when I try to run Genshin Impact I get a popup "Success!" with the message "PlayTools are not installed! Please move PlayCover.app into Applications!" and an Ok button.

PlayCover is in /Applications.

If I right-click on Genshin Impact's icon and "Open in Finder" I'm able to run GI directly by double-clicking on its icon.

Tested with 1.0.7 nightly 13, nightly 16 and 1.1.0 Preview.

**Comment by Depal1** [comment]
This could be related to #159

**Comment by taupter** [comment]
1.1.1 Hotfix seems to have corrected this issue.
