### ISSUE TITLE
[Feature]: Add an option to run iOS app with `sudo`

### ISSUE THREAD

**Issue by cswords** [PlayCover/PlayCover#1665]
### Is your feature request related to a problem?

Wuthering Waves can run with `sudo` after installation with PlayCover. I guess this may help other app/games therefore creating this as a feature request.

### Describe the solution you'd like

Just add an option to run iOS app/game with `sudo`. PlayCover itself does not need to run with admin access, to minimize the impact of security.

### Anything else?

N/A

### Issue Language

- [X] Yes my issue is written in English

**Comment by TheMoonThatRises** [comment]
Apps on MacOS should generally not be run as sudo, as it can cause undesirable behaviors and is not the best course for fixing broken applications. See #1478 for the Wuthering Waves fix.
