### ISSUE TITLE
[Bug]: App & IPA Library contents disappear after viewing IPA Library folder

### ISSUE THREAD

**Issue by FlyMeToTheMoonAndLetMePlayAmongTheStars** [PlayCover/PlayCover#1666]
### Describe the bug

PlayCover version 3.1.0 (856)
macOS Sequoia Public Beta (24A5331b)

The content aka "apps" shown within App Library and IPA Library load normally as expected if you click between them back and fourth, but once you click on a new folder listed under IPA Library and then go back to either App Library or IPA Library, they will fail to load the content completely. 

Temporary workarounds: 
- Click on the library again 
- Restart PlayCover
- Don't click on any folders

### Steps to reproduce

1. Open PlayCover 
<img width="952" alt="image" src="https://github.com/user-attachments/assets/d35231aa-235a-4feb-85d0-4a2289700167">
2. Click on a folder listed under IPA Library
<img width="952" alt="image" src="https://github.com/user-attachments/assets/ce6c6be8-5e53-4d70-8fd6-b3898908931f">
3. Click on IPA Library or App Library, the apps inside all disappeared 
<img width="952" alt="image" src="https://github.com/user-attachments/assets/742ee278-f3d6-4815-9271-d58747348033">

### Expected behaviour

App Library and IPA Library contents not disappearing when you go back to them after you click on a source folder under IPA Library. 

### Crash log

```shell
N/A
```

### What version of PlayCover are you using?

3.1.0

### What version of macOS are you using?

macOS beta (please state the specific version)

### Issue Language

- [X] Yes my issue is written in English

**Comment by Depal1** [comment]
This bug is exclusive to the macOS Sequoia beta.

**Comment by TheMoonThatRises** [comment]
This issue was fixed in #1687.
