### ISSUE TITLE
[Bug]: Switch Pro Controller does not connected

### ISSUE THREAD

**Issue by TheSalts** [PlayCover/PlayCover#1668]
### Describe the bug

Switch Pro Controller does not connected.
The controller is detected on the controller check site, but it is not detected in-game (ZZZ, Genshin Impact).
Both wired and Bluetooth are not working, but it worked when connected via Bluetooth to the iPhone 15.
<img width="1680" alt="스크린샷 2024-09-04 오후 10 28 24" src="https://github.com/user-attachments/assets/fdb9a730-275d-42e7-aa23-386dd39ac0f0">

### Steps to reproduce

connect the pro controller

### Expected behaviour

connect the pro controller

### What version of PlayCover are you using?

3.1.0

### What version of macOS are you using?

Sonoma (macOS 14)

### Issue Language

- [X] Yes my issue is written in English

**Comment by einstein95** [comment]
Change the Bluetooth name of the controller to either `DUALSHOCK 4 Wireless Controller` or `Xbox Wireless Controller`

**Comment by TheSalts** [comment]
> Change the Bluetooth name of the controller to either `DUALSHOCK 4 Wireless Controller` or `Xbox Wireless Controller`

It doesn't work.

**Comment by MasterJ93** [comment]
Try doing the following:
1. Go to System Settings > Game Controllers.
2. Select the Switch Pro Controller in the options.
3. Click on the "+" button on the bottom left corner of the window.
4. Go to the location where Zenless Zone Zero is installed. Then select it and click "Open."
<img width="827" alt="Screenshot 2024-09-08 at 10 42 01 PM" src="https://github.com/user-attachments/assets/b7e9e97e-c0bd-4916-945b-2eac510c146b">

5. You might need to select the "Increase Compatibility" switch; this controller's buttons seem to be swapped on any platform that's not a Nintendo Switch (meaning the A and B buttons are swapped, and the X and Y buttons are swapped; it's why Steam has an option to deal with this issue).

**Comment by TheSalts** [comment]
> Try doing the following:
> 
> 1. Go to System Settings > Game Controllers.
> 2. Select the Switch Pro Controller in the options.
> 3. Click on the "+" button on the bottom left corner of the window.
> 4. Go to the location where Zenless Zone Zero is installed. Then select it and click "Open."
> 
> <img alt="Screenshot 2024-09-08 at 10 42 01 PM" width="827" src="https://private-user-images.githubusercontent.com/894736/365495908-b7e9e97e-c0bd-4916-945b-2eac510c146b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU4ODcyODIsIm5iZiI6MTcyNTg4Njk4MiwicGF0aCI6Ii84OTQ3MzYvMzY1NDk1OTA4LWI3ZTllOTdlLWMwYmQtNDkxNi05NDViLTJlYWM1MTBjMTQ2Yi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTA5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkwOVQxMzAzMDJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02Zjk2Zjk0N2RkNjZhMDUzZTViMmE0YjFmMmVkMjlmYjUxNGIxZWIwNWI2NDM2OTU2NzUzZmE3ZjViMjcyMzFkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.WzwhRsjgpHyFYfCTkD7wb2hE-0UptRMwLNSW1VKEJi4">
> 5. You might need to select the "Increase Compatibility" switch; this controller's buttons seem to be swapped on any platform that's not a Nintendo Switch (meaning the A and B buttons are swapped, and the X and Y buttons are swapped; it's why Steam has an option to deal with this issue).

![image](https://github.com/user-attachments/assets/1b006830-5457-44d4-b8c0-4b80c39619c8)

Game Controllers option has gone
I think mac recognize it as a earphone

**Comment by TheSalts** [comment]
OMG I solved it.
Steam was the problem.
I removed Steam from the login options and restarted, and it works now. 
It seems to be due to Steam's controller support.
