### ISSUE TITLE
[Game Support]: CHN Genshin Impact(原神）game crashes

### ISSUE THREAD

**Issue by FURINA-FD** [PlayCover/PlayCover#1683]
### App Store link

www.genshin.com

### Current issues

- [ ] Game fails to install
- [ ] Game fails to open
- [X] Game crashes randomly during gameplay
- [ ] Game does not work with keymapping
- [ ] Game experiences graphical issues or broken UI
- [ ] Game fails to connect to servers or complete download

### More details

macOS15 cant load the game

### What version of PlayCover are you using?

3.1.0

### What version of macOS are you using?

Other (please specify)

### Issue Language

- [X] Yes my issue is written in English

**Comment by Yew0329** [comment]
我在更新15.0后也遇到过这样的问题，游戏一直在加载，无法点击进入，不过之后我关闭了防火墙，游戏就可以正常进行了。很有可能是因为刚更新15.0后第一次上游戏跳出“是否允许传入连接”的时候我选择了“否”，在15.0之前我一直选择的“否”也可以正常游戏。这一次更新后可能就不行了。在防火墙的选项中也无法正常单独打开原神的“允许传入连接”，这个选项即便我打开点击确认，再次查看的时候还是显示“阻止传入连接”，只有将防火墙全部关闭才能正常加载原神

**Comment by Yew0329** [comment]
所以我认为可能是连接的问题，我实验了很多次，关闭防火墙后游戏可以正常运行，打开防火墙会阻止原神传入链接，在单独打开选项中无法单独打开原神的允许选项，所以只能选择全部关闭防火墙。我不知道是否和更新后第一次上游戏时跳出的“是否允许”有关，但是后续我也无法在防火墙选项中单独打开原神的“允许”选项了，不知道是故障还是别的，也希望有大佬可以答疑解惑并给出解决方案

**Comment by Catta1997** [comment]
Duplicate of #1672

**Comment by funtrip** [comment]
> Duplicate of #1672

I added domains to the Host following the method described here. It worked initially, but soon it can't work again.

**Comment by CAiNSEMBRACE** [comment]
> 所以我认为可能是连接的问题，我实验了很多次，关闭防火墙后游戏可以正常运行，打开防火墙会阻止原神传入链接，在单独打开选项中无法单独打开原神的允许选项，所以只能选择全部关闭防火墙。我不知道是否和更新后第一次上游戏时跳出的“是否允许”有关，但是后续我也无法在防火墙选项中单独打开原神的“允许”选项了，不知道是故障还是别的，也希望有大佬可以答疑解惑并给出解决方案所以我认为可能是连接的问题，我实验了很多次，关闭防火墙后游戏可以正常运行，打开防火墙会阻止原神传入链接，在单独打开选项中无法单独打开原神的允许选项，所以只能选择全部关闭防火墙。我不知道是否和更新后第一次上游戏时跳出的“是否允许”有关，但是后续我也无法在防火墙选项中单独打开原神的“允许”选项了，不知道是故障还是别的，也希望有大佬可以答疑解惑并给出解决方案所以我认为可能是连接的问题，我实验了很多次，关闭防火墙后游戏可以正常运行，打开防火墙会阻止原神传入链接，在单独打开选项中无法单独打开原神的允许选项，所以只能选择全部关闭防火墙。 我不知道是否和更新后第一次上游戏时跳出的“是否允许”有关，但是后续我也无法在防火墙选项中单独打开原神的“允许”选项了，不知道是故障还是别的，也希望有大佬可以答疑解惑并给出解决方案

不,选择是之后也不会正常登录, 网络连接感觉并无问题, 因为能正常登录账号但是无法链接游戏服务器

**Comment by geminiarv** [comment]
我的mac版本 14.4.1 使用play cover启动原神，在点击开门界面后就直接闪退，提示我意外中断，很突然就出现这样的问题，无论我重新安装playcover还是重新安装原神都会出现一样的问题，请大佬们帮帮忙，指导指导怎么办，谢谢。

**Comment by Yew0329** [comment]
>我的mac版本14.4.1使用playcover启动原神，在点击开门界面后直接闪退，提示我意外中断，突然出现这样的问题，无论我重新安装playcover还是重新安装原神都会出现一样的问题，请大佬们帮忙，指导指导怎么办，谢谢。

1.启动台搜索终端打开《终端》应用程序；
2.复制粘贴此行代码并回车：sudo -- sh -c 'echo "0.0.0.0 dispatchcnglobal.yuanshen.com\n0.0.0.0 ys-log-upload.mihoyo.com\n0.0.0.0 apm-log-upload-v6.mihoyo.com" >> /etc/hosts'
3.输入Mac开机密码（输入内容不可见），输完后回车关闭终端，现在应该可以玩了。还不行，就重启一下电脑

**Comment by geminiarv** [comment]
非常感谢，问题成功解决了发自我的手机-------- 原始邮件 --------发件人： Yew0329 ***@***.***>日期： 2024年9月20日周五 13:09收件人： PlayCover/PlayCover ***@***.***>抄送： geminiarv ***@***.***>, Comment ***@***.***>主    题： Re: [PlayCover/PlayCover] [Game Support]: CHN Genshin Impact(原神）game crashes (Issue #1683)

我的mac版本14.4.1使用playcover启动原神，在点击开门界面后直接闪退，提示我意外中断，突然出现这样的问题，无论我重新安装playcover还是重新安装原神都会出现一样的问题，请大佬们帮忙，指导指导怎么办，谢谢。

1.启动台搜索终端打开《终端》应用程序；
2.复制粘贴此行代码并回车：sudo -- sh -c 'echo "0.0.0.0 dispatchcnglobal.yuanshen.com\n0.0.0.0 ys-log-upload.mihoyo.com\n0.0.0.0 apm-log-upload-v6.mihoyo.com" >> /etc/hosts'
3.输入Mac开机密码（输入内容不可见），输完后回车关闭终端，现在应该可以玩了。还不行，就重启一下电脑
