### ISSUE TITLE
[Bug]: Log-in attempt crash

### ISSUE THREAD

**Issue by lxynmnsr** [PlayCover/PlayCover#1684]
### Describe the bug

When I try to launch a HoYoverse game (Genshin Impact, Honkai: Star Rail, etc..), when I attempt a log in, it crashes no matter how many times I try, it may be because of a location change, but even after 1 month after a location change without VPN usage, it crashes.

### Steps to reproduce

1- Open Genshin Impact, Honkai: Star Rail, etc..
2- Make sure you're completely logged out of any account
3- Attempt a log in without Facebook, Apple or Google
4- Click the "Log In."

### Expected behaviour

It'll crash and after a few seconds, a popup should appear saying that the app crashed unexpectedly.

### What version of PlayCover are you using?

3.1.0

### What version of macOS are you using?

Sonoma (macOS 14)

### Issue Language

- [X] Yes my issue is written in English

**Comment by Catta1997** [comment]
Global Genshin?

**Comment by shuttle666** [comment]
Same bug with China mainland version.

**Comment by TheMoonThatRises** [comment]
Clear PlayChain data and try again (in PlayCover, left click the app and it should show you a menu with the option).

**Comment by Catta1997** [comment]
try #1672

**Comment by aiaoxd** [comment]
it works for me. FYI.


基于 @orchidflower 的解决方法简化了操作步骤：

在启动台搜索 终端 打开《终端》应用；
复制粘贴这行代码并回车：
sudo -- sh -c 'echo "0.0.0.0 dispatchcnglobal.yuanshen.com\n0.0.0.0 ys-log-upload.mihoyo.com\n0.0.0.0 apm-log-upload-v6.mihoyo.com" >> /etc/hosts'
输入Mac开机密码（输入内容不可见），输完后回车
关闭终端，现在应该能玩了。还不行就重启一下电脑
其实就是本地屏蔽了三个网址，阻断游戏某些日志上传和某种配置下发。老米的服务器只会以为你网不好
