### ISSUE TITLE
[Feature]: Add keyboard mapping to simulate swipe gestures

### ISSUE THREAD

**Issue by zanezhangzz** [PlayCover/PlayCover#1689]
### Is your feature request related to a problem?

No

### Describe the solution you'd like

Add keyboard mapping to simulate swipe gestures.
Sliding from one position to another can be customized.

### Anything else?

None

### Issue Language

- [X] Yes my issue is written in English

**Comment by TheMoonThatRises** [comment]
Duplicate of #378. See this comment https://github.com/PlayCover/PlayCover/issues/378#issuecomment-1257208374.
