### ISSUE TITLE
When using Ver1.1.0, vertical screen applications overhang the screen by a large amount.

### ISSUE THREAD

**Issue by tellus1019** [PlayCover/PlayCover#169]
The ability to change the resolution was implemented in Ver. 1.1.0 PlayCover.
This is a desirable improvement for landscape applications such as Genshin.

On the other hand, it was a very annoying feature for Vertical Screen applications.
Even if the smallest 1080p is selected, the vertical screen size can be as large as 1920px.
This is a size that cannot be displayed on a Full HD or WQHD monitor.
It would be desirable to implement a "720p" option, which is one step smaller.

It would be a small and significant improvement.
Please consider it.

**Comment by JoseMoreville** [comment]
Mhh, I'll look into it tomorrow and also ask the other devs, it shouldn't take me a lot to implement it, meanwhile can you show me examples of what your problem is, how do apps look?

**Comment by tellus1019** [comment]
Sure.

I am using a 4K monitor with 2560x1440 resolution in a HiDPI environment.
When I launch a vertical screen game, the screen is largely obscured as shown in the screenshot.
The attached screenshots are samples of 1440p and 1080p.
![1080p](https://user-images.githubusercontent.com/25951129/185431278-0f827e08-58c8-41f8-9c51-051cf8a39462.jpg)
![1440p](https://user-images.githubusercontent.com/25951129/185431354-1de31a27-bd77-46a6-accb-62e0fa4beec4.jpg)

**Comment by JoseMoreville** [comment]
Have you used auto?

**Comment by tellus1019** [comment]
Of course.
Using the auto setting in my environment (2540x1440 on a 4K monitor) forces a 1440p display.
This is true for both vertical and landscape screen apps.

**Comment by JoseMoreville** [comment]
https://github.com/PlayCover/PlayCover/pull/180 here is the PR that fixes the issue
