### ISSUE TITLE
[Bug]: I want to ask why I can’t go to the website of playcover nightly? Is that my problem or is the website’s problem

### ISSUE THREAD

**Issue by JerryYin123** [PlayCover/PlayCover#1690]
### Describe the bug

I want to ask why I can’t go to the website of playcover nightly? Is that my problem or is the website’s problem

### Steps to reproduce

I want to ask why I can’t go to the website of playcover nightly? Is that my problem or is the website’s problem

### Expected behaviour

I want to ask why I can’t go to the website of playcover nightly? Is that my problem or is the website’s problem

### What version of PlayCover are you using?

3.1.0

### What version of macOS are you using?

Sonoma (macOS 14)

### Issue Language

- [X] Yes my issue is written in English

**Comment by Catta1997** [comment]
Nightly are atm broken so website not work, you can download the Nightly number 866 (2 weeks ago) on Github Action

**Comment by JerryYin123** [comment]
> Nightly are atm broken so website not work, you can download the Nightly number 866 (2 weeks ago) on Github Action

Ok, Thank you then when you guys will fix the problem?

**Comment by XuYicong** [comment]
@JerryYin123 Should have been fixed now. If everything goes right the next nightly should build normally.

**Comment by JerryYin123** [comment]
<img width="1778" alt="截屏2024-09-24 19 56 37" src="https://github.com/user-attachments/assets/d5097498-344a-45ff-9b7c-53b7b4a87b70">

**Comment by XuYicong** [comment]
@JerryYin123 I mean it's fixed in the code. If you want the website normal, you should wait for the next nightly build to succeed, which is schduled at 03:39am.

**Comment by JerryYin123** [comment]
> @JerryYin123 I mean it's fixed in the code. If you want the website normal, you should wait for the next nightly build to succeed, which is schduled at 03:39am.

Still not working

**Comment by JerryYin123** [comment]
> > @JerryYin123 I mean it's fixed in the code. If you want the website normal, you should wait for the next nightly build to succeed, which is schduled at 03:39am.
> 
> Still not working

@XuYicong

**Comment by Catta1997** [comment]
> > > @JerryYin123 I mean it's fixed in the code. If you want the website normal, you should wait for the next nightly build to succeed, which is schduled at 03:39am.
> > 
> > 
> > Still not working
> 
> @XuYicong

spam mention will not magically solve the problem, there is another PR that is not pushed atm. So as I said use [GitHub action](https://github.com/PlayCover/PlayCover/actions/runs/10837545363) and download the 2 weeks old nightly if you want a nightly. (there are no new important commit so will be the same)

**Comment by XuYicong** [comment]
@JerryYin123 Yeah I forgot there is still a PR not merged when I commented yesterday... Sorry I was dealing with other things while commenting yesterday and forgot that. We'll have to wait for another maintainer to merge it... And I'm not available all the time on GitHub so if you don't get replied in several hours that's normal. I have my work to do. And I have my own live. If you're in a real hurry you could ask @Depal1 or @JoseMoreville to merge it. Or we can delete that PR and let @Catta1997 open the same PR so that I and @TheMoonThatRises could merge it.

**Comment by JerryYin123** [comment]
> @JerryYin123 Yeah I forgot there is still a PR not merged when I commented yesterday... Sorry I was dealing with other things while commenting yesterday and forgot that. We'll have to wait for another maintainer to merge it... And I'm not available all the time on GitHub so if you don't get replied in several hours that's normal. I have my work to do. And I have my own live. If you're in a real hurry you could ask @Depal1 or @JoseMoreville to merge it. Or we can delete that PR and let @Catta1997 open the same PR so that I and @TheMoonThatRises could merge it.

Doesn't matter, I just want to know what the problem is, and when you guys can solve it.

**Comment by TheMoonThatRises** [comment]
Nightlies have been fixed.
