### ISSUE TITLE
[Feature]: Account Switching GUI for Zenless Zone Zero

### ISSUE THREAD

**Issue by Azyzraissi** [PlayCover/PlayCover#1692]
### Is your feature request related to a problem?

No. 

### Describe the solution you'd like

Implement a GUI in PlayCover to switch accounts in Zenless Zone Zero. 

### Anything else?

Since it's already implemented for Genshin Impact, I suppose it's straightforward to add it for Zenless Zone Zero. 
I'll be happy to test it out if someone's willing to implement it. 
Zenless Zone Zero supports login via Hoyoverse Account / Twitter and Facebook. Users can use multiple login methods to register multiple accounts. 

### Issue Language

- [X] Yes my issue is written in English

**Comment by TheMoonThatRises** [comment]
The account switcher is already deprecated and removed from PlayCover starting version 3.1.0. The feature is not necessary as you can already log in and out the same way you could on mobile devices.
