### ISSUE TITLE
在1.1.0版本上打开游戏光遇出现失败的情况

### ISSUE THREAD

**Issue by TeaWu** [PlayCover/PlayCover#170]
在使用1.0.7版本的PlayCover时，从安装-打开-使用一款叫光遇的游戏都没有问题
升级到1.1.0版本后，如果直接覆盖安装光遇，仍然能够正常打开并使用
一旦删除应用数据之后再次重新安装光遇，就会出现无法打开应用的情况
两种情况的差异在于是否删除应用程序数据，如果解决这个问题需要任何协助，我很乐意提供开发者需要的帮助。

**Comment by XuYicong** [comment]
能提供详细报错信息吗？

**Comment by XuYicong** [comment]
目前判断是1.1.0版本引入的Bug，会在后续版本修复，应该明天之内就会发布新版本（1.1.1），到时候试一下看看解决了没有

**Comment by Candygoblen123** [comment]
duplicate of #175

**Comment by krislint** [comment]
> 

求分享光遇 ipa 文件

please share with me the sky

**Comment by TeaWu** [comment]
I use Baidu net disk to share the IPA files of Sky with you
Link：https://pan.baidu.com/s/1niB9qPPVw5EOO6RM22fAzw?pwd=w7Es 
Extraction code：w7Es

**Comment by TeaWu** [comment]
> > 
> 
> 求分享光遇ipa文件
> 
> 请与我分享天空
I use Baidu net disk to share the IPA files of Sky with you
Link：https://pan.baidu.com/s/1niB9qPPVw5EOO6RM22fAzw?pwd=w7Es
Extraction code：w7Es

**Comment by TeaWu** [comment]
> 



> > 
> 
> 求分享光遇 ipa 文件
> 
> please share with me the sky

I use Baidu net disk to share the IPA files of Sky with you
Link：https://pan.baidu.com/s/1niB9qPPVw5EOO6RM22fAzw?pwd=w7Es
Extraction code：w7Es

**Comment by roeegh** [comment]
@TeaWu the issues tab is not a place to share IPA files. Please find another method of sharing.
