### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by bennite** [PlayCover/PlayCover#1700]
### Describe the bug

After updating to macOS 15, when logging into Genshin Impact via PlayCover, a 'parameter error' appears after entering the username and password.

### Steps to reproduce

After updating to macOS 15, when logging into Genshin Impact via PlayCover, a 'parameter error' appears after entering the username and password.

### Expected behaviour

succesful log in

### What version of PlayCover are you using?

3.1.0

### What version of macOS are you using?

macOS beta (please state the specific version)

### Issue Language

- [X] Yes my issue is written in English

**Comment by bennite** [comment]
please help

**Comment by TheMoonThatRises** [comment]
Clear PlayChain data then try again (you can do this by left clicking Genshin in PlayCover).

**Comment by bennite** [comment]
> 清除 PlayChain 数据，然后重试（您可以通过在 PlayCover 中左键单击 Genshin 来执行此操作）。

thank u so much ， and every time I switch screens, it freezes, and when I return after a while, it has to reload. This didn't happen before I updated to macOS 15. Could you please help me resolve this?

**Comment by Catta1997** [comment]
> > 清除 PlayChain 数据，然后重试（您可以通过在 PlayCover 中左键单击 Genshin 来执行此操作）。
> 
> thank u so much ， and every time I switch screens, it freezes, and when I return after a while, it has to reload. This didn't happen before I updated to macOS 15. Could you please help me resolve this?

its a "feature" of macOS 15. you can't do anything

**Comment by bennite** [comment]
> > > 清除 PlayChain 数据，然后重试（您可以通过在 PlayCover 中左键单击 Genshin 来执行此操作）。
> > 
> > 
> > thank u so much ， and every time I switch screens, it freezes, and when I return after a while, it has to reload. This didn't happen before I updated to macOS 15. Could you please help me resolve this?
> 
> its a "feature" of macOS 15. you can't do anything

can't I even do some change in the setting?  or can I download the old version of macOS
