### ISSUE TITLE
[Bug]:  the game in the background no more continue running.

### ISSUE THREAD

**Issue by viivuwu** [PlayCover/PlayCover#1707]
### Describe the bug

"Before the Mac version update, when I switched between windows (for example, by swiping on the trickpad), the game in the background would continue running. However, after the Mac update, this no longer happens. Is this a bug, or is there any way to fix it?"

### Steps to reproduce

updating my mac to version 15

### Expected behaviour

continue running in the background

### What version of PlayCover are you using?

3.1.0

### What version of macOS are you using?

Sonoma (macOS 14)

### Issue Language

- [X] Yes my issue is written in English

**Comment by TheMoonThatRises** [comment]
Duplicate of #1568. Currently no fixes.
