### ISSUE TITLE
[Bug]: Mac OS 14.7 can't run app, such as Yuanshen

### ISSUE THREAD

**Issue by magicvoid** [PlayCover/PlayCover#1708]
### Describe the bug

Process:               Yuanshen [62155]
Path:                  /Users/USER/*/原神.app/Yuanshen
Identifier:            com.miHoYo.Yuanshen
Version:               5.0.0 (879)
Code Type:             ARM-64 (Native)
Parent Process:        launchd [1]
User ID:               502

Date/Time:             2024-10-05 19:47:14.3807 +0800
OS Version:            macOS 14.7 (23H124)
Report Version:        12
Anonymous UUID:        649E412B-C61E-2FEA-0A7D-7F6027C6A212

Sleep/Wake UUID:       5749302F-02D3-4230-8AA5-753B8DF5BA0F

Time Awake Since Boot: 240000 seconds
Time Since Wake:       790 seconds

System Integrity Protection: enabled

Crashed Thread:        0

Exception Type:        EXC_CRASH (SIGABRT)
Exception Codes:       0x0000000000000000, 0x0000000000000000

**Termination Reason:    Namespace DYLD, Code 1 Library missing
Library not loaded: @rpath/Telemetry.framework/Telemetry**
Referenced from: <4BC3A9EE-0738-3C45-B7F9-00EE8C87D60F> /Users/USER/Library/Containers/io.playcover.PlayCover/*/com.miHoYo.Yuanshen.app/Yuanshen
Reason: tried: '/usr/lib/swift/Telemetry.framework/Telemetry' (no such file, not in dyld cache), '/System/Volumes/Preboot/Cryptexes/OS/usr/lib/swift/Telemetry.framework/Telemetry' (no such file), '/Users/magicvoid/Library/Containers/io.playcover.PlayCover/Applications/com.miHoYo.Yuanshen.app/Frameworks/Telemetry.framework/Telemetry' (mach-o file (/Users/magicvoid/Library/Containers/io.playcover.PlayCover/Applications/com.miHoYo.Yuanshen.app/Frameworks/Telemetry.framework/Telemetry), but incompatible platform (have 'iOS', need 'MacCatalyst')), '/usr/lib/swift/Telemetry.framework/Telemetry' (no such file, not in dyld cache), '/System/Volumes/Preboot/Cryptexes/OS/usr/lib/swift/Telemetry.framework/Telemetry' (no such file), '/Users/magicvoid/Library/Containers/io.playcover.PlayCover/Application
(terminated at launch; ignore backtrace)

### Steps to reproduce

1 Double click to run app.

### Expected behaviour

Open app.

### What version of PlayCover are you using?

3.1.0

### What version of macOS are you using?

Sonoma (macOS 14)

### Issue Language

- [X] Yes my issue is written in English

**Comment by zhengyoutan** [comment]
我也遇到了相同问题，请问你的解决了吗

**Comment by panda361** [comment]
It seems can be solved by adding some domain in hosts. See #1699

**Comment by Catta1997** [comment]
Check if #1672 solve

**Comment by magicvoid** [comment]
> It seems can be solved by adding some domain in hosts. See #1699

Thank you，but I have already tried modifying the hosts file, but the issue still persists.

**Comment by magicvoid** [comment]
> Check if #1672 solve


Thank you, I have gone through that post multiple times and followed the steps, but the issue still persists.

**Comment by TheMoonThatRises** [comment]
This issue is unrelated to #1672, as it seems that when installing Yuanshen, the Telemetry framework was not properly converted to MacCatalyst. There is a temporary solution available in #691 with `vtool` and `codesign` to fix the wrong package type. You can also try reinstalling Yuanshen and see if that helps.

**Comment by TheMoonThatRises** [comment]
I'll close this in favour of #1615 for now.
