### ISSUE TITLE
EXC_BAD_ACCESS (SIGKILL (Code Signature Invalid))

### ISSUE THREAD

**Issue by vtu-dog** [PlayCover/PlayCover#171]
Hello,
I've just tried running Yeelight 3.3.37 and I encountered a peculiar error:
1. The app opened fine at first, but it crashed as soon as I tried to log in (file: `first-crash.txt`)
2. The app could no longer be opened, throwing the same error each time (`first-crash` again)
3. Reinstalling the app resulted in an invalid code signature (`subsequent-crashes.txt`), self-signing doesn't seem to work

[first-crash.txt](https://github.com/PlayCover/PlayCover/files/9372443/first-crash.txt)
[subsequent-crashes.txt](https://github.com/PlayCover/PlayCover/files/9372445/subsequent-crashes.txt)

**Comment by vtu-dog** [comment]
I renamed files from `.ips` to `.txt`, assuming that the output would not change, but using quicklook revealed that macOS cares about the extension after all. Sorry for the inconvenience!

**Comment by IsaacMarovitz** [comment]
This is a known issue in PlayCover 1.1.0 (#176). For now, please downgrade to PlayCover 1.0.7 until a fix is released.

**Comment by vtu-dog** [comment]
Downgrading to 1.0.7 and disabling jailbreak bypass fixed the issue, thank you.

**Comment by IsaacMarovitz** [comment]
The issue will be resolved in hotfix 1.1.1 coming out in the next few hours.
