### ISSUE TITLE
[Bug]: Genshin Impact doesn't open anymore after update

### ISSUE THREAD

**Issue by Eevee-obsesser** [PlayCover/PlayCover#1711]
### Describe the bug

After updating the Genshin impact IPA to the newest patch (5.1), it suddenly stopped opening, even though it was working just fine before the update. Whenever I try to open it, I get this message. 
<img width="266" alt="Screenshot 2024-10-09 at 9 51 10 AM" src="https://github.com/user-attachments/assets/29f87574-8b75-47f0-bc00-e97fe6df66d2">
No matter if I press "re-open" or "don't reopen", the icon for Genshin Impact disappears from the Dock and I end up having to try opening Genshin from the Playcover Library.
Then the same pop-up shows up and the cycle repeats.
Occasionally I get a crash report saying that Genshin impact quit suddenly when I click re-open.
My Mac is macOS Sequoia 15.0.1

### Steps to reproduce

I click Genshin Impact on Playcover. The icon shows up on the dock and then the popup about reopening Genshin shows up. I click re-open and the icon diappears. Either nothing happens and the cycle restarts or I get a crash report about Genshin quitting unexpectedly. I have tried changing the application type to games but nothing changed.

### Expected behaviour

I expected for Genshin Impact to open after clicking it on Playcover. I have no login or loading issues.

### Crash log

```shell
Crashed Thread:        24  Dispatch queue: playcover.toucher

Exception Type:        EXC_BREAKPOINT (SIGTRAP)
Exception Codes:       0x0000000000000001, 0x000000010ea5213c

Termination Reason:    Namespace SIGNAL, Code 5 Trace/BPT trap: 5
Terminating Process:   exc handler [6439]
```

### What version of PlayCover are you using?

3.1.0

### What version of macOS are you using?

Sonoma (macOS 14)

### Issue Language

- [X] Yes my issue is written in English

**Comment by Catta1997** [comment]
try to: 
1) right click on Genshin (Inside Playcover) -> show in finder
2) shift + double click on Genshin Impact app

**Comment by Eevee-obsesser** [comment]
> try to:
> 
> 1. right click on Genshin (Inside Playcover) -> show in finder
> 2. shift + double click on Genshin Impact app

IT WORKED!! How?????

**Comment by Catta1997** [comment]
> > try to:
> > 
> > 1. right click on Genshin (Inside Playcover) -> show in finder
> > 2. shift + double click on Genshin Impact app
> 
> IT WORKED!! How?????

open the app without trying to restore the (broken) state
