### ISSUE TITLE
[Bug]: Nightly download problem happen again

### ISSUE THREAD

**Issue by JerryYin123** [PlayCover/PlayCover#1721]
### Describe the bug

Can't download Nightly playcover
<img width="882" alt="截屏2024-10-18 09 44 45" src="https://github.com/user-attachments/assets/0991f4cb-1a15-4aea-8b46-8ded898cdf6b">

### Steps to reproduce

Can't download Nightly playcover

### Expected behaviour

Can't download Nightly playcover

### What version of PlayCover are you using?

3.1.0

### What version of macOS are you using?

Sonoma (macOS 14)

### Issue Language

- [X] Yes my issue is written in English

**Comment by TheMoonThatRises** [comment]
This should be fixed in #1720.

**Comment by JerryYin123** [comment]
So what can I do

**Comment by MEMORIEmusic** [comment]
> So what can I do

Wait.

**Comment by JerryYin123** [comment]
Ok, Thank you
