### ISSUE TITLE
[Bug]: Genshin login failure (Invalid Parameter)

### ISSUE THREAD

**Issue by stoll-plantinum** [PlayCover/PlayCover#1722]
### Describe the bug

My Genshin has been working fine, then suddenly after I took a break for like a month, it isn't working anymore. Whenever I log in, it says "invalid parameter". 
Device: Macbook Air M1
Macbook version: Sequoia 15.0.1
Playcover: nightly 3.1
Login type: email

*i used to do `sudo nvram boot-args="amfi_get_out_of_my_way=0x1 ipc_control_port_options=0` for the old login method

I tried clearing playchain data, deleting and reinstalling both playcover and genshin.
When i try using the old login method, the text 'invalid parameter' doesnt show up, but genshin is signed out as soon as i enable sip. 

When I type cd ~/Library/Containers/io.playcover.PlayCover/
mkdir PlayChain , it says the file exists. 

can anyone help me? pls- im desperate T-T 

### Steps to reproduce

Entered Genshin impact
logged in

### Expected behaviour

genshin to login

### Crash log

```shell
parameter error
```

### What version of PlayCover are you using?

Nightly/beta (please specify build number)

### What version of macOS are you using?

Other (please specify)

### Issue Language

- [X] Yes my issue is written in English

**Comment by TheMoonThatRises** [comment]
Try using the stable release of PlayCover (3.1.0).
