### ISSUE TITLE
[Bug]: Uninstalling an app does not clear its data from Users/$USER/Library/Containers/

### ISSUE THREAD

**Issue by devgocri** [PlayCover/PlayCover#1736]
### Describe the bug

Uninstalling an app does not clear the Container for the app, keeping its data stored even after you want it deleted.

### Steps to reproduce

1. Download an app & install it
2. Uninstall it using PlayCover app
3. Navigate to /Users/$USER/Library/Containers/ in Finder and you will be able to find the old container for your app.

eg. with "Zenless Zone Zero", which I have uninstalled,
<img width="659" alt="image" src="https://github.com/user-attachments/assets/2bd804db-30ef-4795-923a-669f537ee827">

### Expected behaviour

The folder for the app in "Containers" being deleted or cleared after an uninstall. 

### What version of PlayCover are you using?

3.1.0

### What version of macOS are you using?

Sonoma (macOS 14)

### Issue Language

- [X] Yes my issue is written in English

**Comment by TheMoonThatRises** [comment]
PlayCover is only able to remove app containers when it has the permission Full Disk Access.
