### ISSUE TITLE
文件Otool不存在（File "otool" not found)

### ISSUE THREAD

**Issue by qjasn** [PlayCover/PlayCover#174]
![image](https://user-images.githubusercontent.com/73731689/185375851-b065d88c-5c3c-4557-80c4-e45d640c0047.jpeg)
我已经安装了Xcode command tools，并且在终端中，该命令可用
但是Playcover提示文件Otool不存在

以下是我使用系统的信息： 
macOS13 Public Beta(22A5321d)
Xcode Command Tools for Xcode14 Beta 5

**Comment by IsaacMarovitz** [comment]
This is a known issue in PlayCover 1.1.0 (#176). For now, please downgrade to PlayCover 1.0.7 until a fix is released.

**Comment by qjasn** [comment]
Ok，thank you for your answer.

**Comment by Depal1** [comment]
You can use today's nightly if you are in a hurry to make it work. https://nightly.link/PlayCover/PlayCover/actions/runs/2884904627/PlayCover_nightly_35.dmg.zip

**Comment by fengshenx** [comment]
Still have the same problem after upgrade to 1.1.1

**Comment by livc** [comment]
> Still have the same problem after upgrade to 1.1.1

https://apple.stackexchange.com/questions/415563/repeatedly-being-asked-to-install-command-line-tools 
works for me.
