### ISSUE TITLE
[Feature]: store account switch

### ISSUE THREAD

**Issue by cs445194891** [PlayCover/PlayCover#1741]
### Is your feature request related to a problem?

no

### Describe the solution you'd like

The account switcher is already deprecated and removed from PlayCover starting version 3.1.0. I know that.
But, When I make a purchase in the game, my appstore user automatically pops up to pay, even if I have changed my account on the Appstore.
I've tried Clear App Data and Clear App Preferences. 
Now, How to switch my appstore account.

### Anything else?

no

### Issue Language

- [X] Yes my issue is written in English

**Comment by cs445194891** [comment]
I mean I'm going to use a different appstore account to pay in-game. My current account can't be paid in the current region

**Comment by Catta1997** [comment]
Afaik you can't buy in-App things using PlayCover

**Comment by TheMoonThatRises** [comment]
Using in-app purchases is not available through PlayCover.
