### ISSUE TITLE
Crash！！！

### ISSUE THREAD

**Issue by imAnonyme** [PlayCover/PlayCover#175]
-------------------------------------
Translated Report (Full Report Below)
-------------------------------------

Process:               Game [2345]
Path:                  /Users/USER/Library/Containers/io.playcover.PlayCover/Game.app/Game
Identifier:            com.netease.immortal
Version:               1.5.3 (976576)
Code Type:             ARM-64 (Native)
Parent Process:        launchd [1]
User ID:               501

Date/Time:             2022-08-18 18:58:08.8375 +0800
OS Version:            macOS 12.5.1 (21G83)
Report Version:        12
Anonymous UUID:        3CDA69AB-9FC4-40F7-8320-47E86F3216CB

Time Awake Since Boot: 1500 seconds

System Integrity Protection: disabled

Crashed Thread:        0

Exception Type:        EXC_CRASH (SIGABRT)
Exception Codes:       0x0000000000000000, 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFY

Termination Reason:    Namespace DYLD, Code 1 Library missing
Library not loaded: '@rpath/GLAIDetectSDK_Unisdk.framework/GLAIDetectSDK_Unisdk'
Referenced from: '/Users/USER/Library/Containers/io.playcover.PlayCover/Game.app/Game'
Reason: tried: '' (no such file), '' (no such file), '' (no such file), '' (code signature invalid (errno=1) sliceOffset=0x00000000, codeBlobOffset=0x000E7A80, codeBlobSize=0x0000A820 for ''), '
(terminated at launch; ignore backtrace)

Thread 0 Crashed:
0   dyld                          	       0x10ecd3e98 __abort_with_payload + 8
1   dyld                          	       0x10ecdb024 abort_with_payload_wrapper_internal + 104
2   dyld                          	       0x10ecdb058 abort_with_payload + 16
3   dyld                          	       0x10ec92a28 dyld4::halt(char const*) + 580
4   dyld                          	       0x10ec8dfb8 dyld4::prepare(dyld4::APIs&, dyld3::MachOAnalyzer const*) + 3644
5   dyld                          	       0x10ec8d06c start + 488

Thread 0 crashed with ARM Thread State (64-bit):
    x0: 0x0000000000000006   x1: 0x0000000000000001   x2: 0x000000016d64ea08   x3: 0x0000000000000092
    x4: 0x000000016d64e608   x5: 0x0000000000000000   x6: 0x0000000000000000   x7: 0x0000000000000ec0
    x8: 0x0000000000000020   x9: 0x0000000000000009  x10: 0x000000016d64e66d  x11: 0x00000000000000a7
   x12: 0x0000000000000000  x13: 0x0000000000000032  x14: 0x000000025ec9375c  x15: 0x0000000000000000
   x16: 0x0000000000000209  x17: 0x000000010ec8b14c  x18: 0x0000000000000000  x19: 0x0000000000000000
   x20: 0x000000016d64e608  x21: 0x0000000000000092  x22: 0x000000016d64ea08  x23: 0x0000000000000001
   x24: 0x0000000000000006  x25: 0x000000016d64e608  x26: 0x0000000000000400  x27: 0x000000000000016d
   x28: 0x00000000000003c0   fp: 0x000000016d64e5d0   lr: 0x000000010ecdb024
    sp: 0x000000016d64e590   pc: 0x000000010ecd3e98 cpsr: 0x00001000
   far: 0x000000010eb0c000  esr: 0x56000080  Address size fault

Binary Images:
       0x10ec88000 -        0x10ece7fff dyld (*) <75627683-a780-32ad-ae34-cf86dd23a26b> /usr/lib/dyld

External Modification Summary:
  Calls made by other processes targeting this process:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0
  Calls made by this process:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0
  Calls made by all processes on this machine:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0

VM Region Summary:
ReadOnly portion of Libraries: Total=176.1M resident=0K(0%) swapped_out_or_unallocated=176.1M(100%)
Writable regions: Total=17.0M written=0K(0%) resident=0K(0%) swapped_out=0K(0%) unallocated=17.0M(100%)

                                VIRTUAL   REGION 
REGION TYPE                        SIZE    COUNT (non-coalesced) 
===========                     =======  ======= 
STACK GUARD                       56.0M        1 
Stack                             8176K        1 
VM_ALLOCATE                         16K        1 
__DATA                            18.8M        3 
__DATA_CONST                        96K        1 
__LINKEDIT                       112.5M        2 
__TEXT                            63.6M        2 
dyld private memory               1024K        1 
===========                     =======  ======= 
TOTAL                            260.1M       12 

-----------
Full Report
-----------

{"app_name":"Game","timestamp":"2022-08-18 18:58:10.00 +0800","app_version":"1.5.3","slice_uuid":"6c02b44d-b9af-37d7-b1c6-3ef745f5aff6","build_version":"976576","platform":6,"bundleID":"com.netease.immortal","share_with_app_devs":0,"is_first_party":0,"bug_type":"309","os_version":"macOS 12.5.1 (21G83)","incident_id":"E1A9765A-63A2-40F0-B658-F94D0CCEE9E7","name":"Game"}
{
  "uptime" : 1500,
  "procLaunch" : "2022-08-18 18:58:08.7411 +0800",
  "procRole" : "Default",
  "version" : 2,
  "userID" : 501,
  "deployVersion" : 210,
  "modelCode" : "Macmini9,1",
  "procStartAbsTime" : 36257814299,
  "coalitionID" : 2573,
  "osVersion" : {
    "train" : "macOS 12.5.1",
    "build" : "21G83",
    "releaseType" : "User"
  },
  "captureTime" : "2022-08-18 18:58:08.8375 +0800",
  "incident" : "E1A9765A-63A2-40F0-B658-F94D0CCEE9E7",
  "bug_type" : "309",
  "pid" : 2345,
  "procExitAbsTime" : 36260065000,
  "translated" : false,
  "cpuType" : "ARM-64",
  "procName" : "Game",
  "procPath" : "\/Users\/USER\/Library\/Containers\/io.playcover.PlayCover\/Game.app\/Game",
  "bundleInfo" : {"CFBundleShortVersionString":"1.5.3","CFBundleVersion":"976576","CFBundleIdentifier":"com.netease.immortal","DTAppStoreToolsBuild":"13F100"},
  "storeInfo" : {"deviceIdentifierForVendor":"1B547181-0A56-5950-9E66-52806E729368","thirdParty":true},
  "parentProc" : "launchd",
  "parentPid" : 1,
  "coalitionName" : "com.netease.immortal",
  "crashReporterKey" : "3CDA69AB-9FC4-40F7-8320-47E86F3216CB",
  "sip" : "disabled",
  "isCorpse" : 1,
  "exception" : {"codes":"0x0000000000000000, 0x0000000000000000","rawCodes":[0,0],"type":"EXC_CRASH","signal":"SIGABRT"},
  "termination" : {"code":1,"flags":518,"namespace":"DYLD","indicator":"Library missing","details":["(terminated at launch; ignore backtrace)"],"reasons":["Library not loaded: '@rpath\/GLAIDetectSDK_Unisdk.framework\/GLAIDetectSDK_Unisdk'","Referenced from: '\/Users\/USER\/Library\/Containers\/io.playcover.PlayCover\/Game.app\/Game'","Reason: tried: '' (no such file), '' (no such file), '' (no such file), '' (code signature invalid (errno=1) sliceOffset=0x00000000, codeBlobOffset=0x000E7A80, codeBlobSize=0x0000A820 for ''), '"]},
  "extMods" : {"caller":{"thread_create":0,"thread_set_state":0,"task_for_pid":0},"system":{"thread_create":0,"thread_set_state":0,"task_for_pid":0},"targeted":{"thread_create":0,"thread_set_state":0,"task_for_pid":0},"warnings":0},
  "faultingThread" : 0,
  "threads" : [{"triggered":true,"id":41457,"threadState":{"x":[{"value":6},{"value":1},{"value":6130297352},{"value":146},{"value":6130296328},{"value":0},{"value":0},{"value":3776},{"value":32},{"value":9},{"value":6130296429},{"value":167},{"value":0},{"value":50},{"value":10180179804},{"value":0},{"value":521},{"value":4543000908,"symbolLocation":392,"symbol":"__simple_bprintf"},{"value":0},{"value":0},{"value":6130296328},{"value":146},{"value":6130297352},{"value":1},{"value":6},{"value":6130296328},{"value":1024},{"value":365},{"value":960}],"flavor":"ARM_THREAD_STATE64","lr":{"value":4543328292},"cpsr":{"value":4096},"fp":{"value":6130296272},"sp":{"value":6130296208},"esr":{"value":1442840704,"description":" Address size fault"},"pc":{"value":4543299224,"matchesCrashFrame":1},"far":{"value":4541431808}},"frames":[{"imageOffset":310936,"symbol":"__abort_with_payload","symbolLocation":8,"imageIndex":0},{"imageOffset":340004,"symbol":"abort_with_payload_wrapper_internal","symbolLocation":104,"imageIndex":0},{"imageOffset":340056,"symbol":"abort_with_payload","symbolLocation":16,"imageIndex":0},{"imageOffset":43560,"symbol":"dyld4::halt(char const*)","symbolLocation":580,"imageIndex":0},{"imageOffset":24504,"symbol":"dyld4::prepare(dyld4::APIs&, dyld3::MachOAnalyzer const*)","symbolLocation":3644,"imageIndex":0},{"imageOffset":20588,"symbol":"start","symbolLocation":488,"imageIndex":0}]}],
  "usedImages" : [
  {
    "source" : "P",
    "arch" : "arm64e",
    "base" : 4542988288,
    "size" : 393216,
    "uuid" : "75627683-a780-32ad-ae34-cf86dd23a26b",
    "path" : "\/usr\/lib\/dyld",
    "name" : "dyld"
  }
],
  "sharedCache" : {
  "base" : 7094190080,
  "size" : 3144712192,
  "uuid" : "f8ab76fb-504c-32dd-a5db-15a1f2f028f8"
},
  "vmSummary" : "ReadOnly portion of Libraries: Total=176.1M resident=0K(0%) swapped_out_or_unallocated=176.1M(100%)\nWritable regions: Total=17.0M written=0K(0%) resident=0K(0%) swapped_out=0K(0%) unallocated=17.0M(100%)\n\n                                VIRTUAL   REGION \nREGION TYPE                        SIZE    COUNT (non-coalesced) \n===========                     =======  ======= \nSTACK GUARD                       56.0M        1 \nStack                             8176K        1 \nVM_ALLOCATE                         16K        1 \n__DATA                            18.8M        3 \n__DATA_CONST                        96K        1 \n__LINKEDIT                       112.5M        2 \n__TEXT                            63.6M        2 \ndyld private memory               1024K        1 \n===========                     =======  ======= \nTOTAL                            260.1M       12 \n",
  "legacyInfo" : {
  "threadTriggered" : {

  }
},
  "trialInfo" : {
  "rollouts" : [
    {
      "rolloutId" : "60186475825c62000ccf5450",
      "factorPackIds" : {

      },
      "deploymentId" : 240000025
    },
    {
      "rolloutId" : "6112e14f37f5d11121dcd519",
      "factorPackIds" : {
        "SIRI_TEXT_TO_SPEECH" : "62f3b97053c7e4550fbc6100"
      },
      "deploymentId" : 240000198
    }
  ],
  "experiments" : [

  ]
}
}

Model: Macmini9,1, BootROM 7459.141.1, proc 8:4:4 processors, 8 GB, SMC 
Graphics: Apple M1, Apple M1, Built-In
Display: LG HDR 4K, 3840 x 2160 (2160p/4K UHD 1 - Ultra High Definition), Main, MirrorOff, Online
Memory Module: LPDDR4
AirPort: Wi-Fi, wl0: Mar 23 2022 19:57:59 version 18.60.27.0.7.8.129 FWID 01-570be953
Bluetooth: Version (null), 0 services, 0 devices, 0 incoming serial ports
Network Service: Wi-Fi, AirPort, en1
USB Device: USB31Bus
USB Device: ROG STRIX Arion
USB Device: USB31Bus
USB Device: 4-Port USB 2.0 Hub
USB Device: Keychron K1
USB Device: G700s Rechargeable Gaming Mouse
USB Device: USB Controls
USB Device: USB30Bus
Thunderbolt Bus: Mac mini, Apple Inc.
Thunderbolt Bus: Mac mini, Apple Inc.

**Comment by imAnonyme** [comment]
WHY？Someone could help？

**Comment by IsaacMarovitz** [comment]
This is a known issue in PlayCover 1.1.0 (#176). For now, please downgrade to PlayCover 1.0.7 until a fix is released.

**Comment by IsaacMarovitz** [comment]
The issue will be resolved in hotfix 1.1.1 coming out in the next few hours.

**Comment by JoseMoreville** [comment]
Please, have a self explainatory title and more information, not only the crash report.
