### ISSUE TITLE
[Bug]: 我更新了playconver版本，但是游戏列表无法加载出游戏，只能重新下载

### ISSUE THREAD

**Issue by buzuosheng** [PlayCover/PlayCover#1750]
### Describe the bug

我从3.0.0 beta版本更新到了3.1.0，打开playcover后发现游戏列表是空的，但是在Library/containers/io.playcover.PlayCover还能看到两个.app文件，我应该怎么做才能继续之前的游戏

I updated from the 3.0.0 beta version to 3.1.0, and when I opened Playcover, I found that the game list was empty, but in Library/containers/io. Playcover PlayCover can still see two. app files, what should I do to continue the previous game

### Steps to reproduce

我从3.0.0 beta版本更新到了3.1.0，打开playcover后发现游戏列表是空的

I updated from the 3.0.0 beta version to 3.1.0, and when I opened Playcover, I found that the game list was empty

### Expected behaviour

游戏列表正确显示已经下载的游戏

The game list correctly displays downloaded games

### What version of PlayCover are you using?

3.1.0

### What version of macOS are you using?

Ventura (macOS 13)

### Issue Language

- [X] Yes my issue is written in English

**Comment by buzuosheng** [comment]
I move `.app` files in `Library/containers/io.playcover.PlayCover` to`Applications/PlayCover` and it work, but other files Still in original place.

**Comment by buzuosheng** [comment]
When I use the `option` key to make the cursor disappear, but moving the mouse causes it to move outside of the game or even onto my other monitor, perhaps I should downgrade the version of Playcover? It didn't apper in Beta version, maybe i should try 3.0.0 version?

当我使用`option`键使光标消失，但是移动鼠标会导致鼠标移动到游戏以外，甚至移动到我的另一个显示器上，我在[beta版本](https://github.com/PlayCover/PlayCover/releases/tag/3.0.0-beta.1)的时候，并没有出现这个问题，只是有上述的问题。难道我要降级安装吗，或者我应该考虑3.0.0版本？

**Comment by buzuosheng** [comment]
btw, i have unable to typo chinese in game, is this not support yet?

**Comment by buzuosheng** [comment]
Finally returned to the original starting point

**Comment by TheMoonThatRises** [comment]
Manually move the applications to `Application` directory *inside* the PlayCover container (`~/Library/Containers/io.playcover.PlayCover/Applications`, create this directory if it doesn't exist), and then the app should be detected by PlayCover. For being able to type in Chinese, open a new issue for that.
