### ISSUE TITLE
[Feature]: Sandbox to prevent access home folder of users?

### ISSUE THREAD

**Issue by spherical-stone** [PlayCover/PlayCover#1753]
### Is your feature request related to a problem?

Since I could not find this in documentation, is it the case that with default settings, the ipa app loaded in play cover cannot access files in users' home folder? This is important for privacy.

### Describe the solution you'd like

Could anyone confirm if this feature exists?

### Anything else?

.

### Issue Language

- [X] Yes my issue is written in English

**Comment by TheMoonThatRises** [comment]
All IPAs installed through PlayCover are sandboxed.
