### ISSUE TITLE
[Feature]: Install Application in external hard drive

### ISSUE THREAD

**Issue by MamboJiang** [PlayCover/PlayCover#1754]
### Is your feature request related to a problem?

Many games take up a lot of storage space. Maybe a game costs 20G or even larger. The local hard disk is too easy to ran out of space.

### Describe the solution you'd like

Add feature to select the location of the application to be installed during installation or in the settings, or select the location where the data of the application is stored. For example, the huge space occupied by Genshin Impact is in the data folder of the application.

### Anything else?

no

### Issue Language

- [X] Yes my issue is written in English

**Comment by Catta1997** [comment]
The "problem" is not the Genshin app but the Genshin app data (located in Library/Containers) that cannot be moved

**Comment by TheMoonThatRises** [comment]
This is a feature we are not looking to implement, but if you really want to move the app container, check out this discussion: https://github.com/PlayCover/PlayCover/discussions/1712.
