### ISSUE TITLE
[Game Support]: Infinity Nikki

### ISSUE THREAD

**Issue by holidayyy777** [PlayCover/PlayCover#1760]
### App Store link

infinity nikki

### Current issues

- [ ] Game fails to install
- [X] Game fails to open
- [ ] Game crashes randomly during gameplay
- [ ] Game does not work with keymapping
- [ ] Game experiences graphical issues or broken UI
- [ ] Game fails to connect to servers or complete download

### More details

Cant open

### What version of PlayCover are you using?

3.1.0

### What version of macOS are you using?

Sonoma (macOS 14)

### Issue Language

- [X] Yes my issue is written in English

**Comment by Joan1226yyy** [comment]
1

**Comment by qqice** [comment]
Duplicate of #1755.
