### ISSUE TITLE
[Bug]: zenless zone zero on playcover

### ISSUE THREAD

**Issue by bennite** [PlayCover/PlayCover#1772]
### Describe the bug

I use zenless zone zero on macOS15 , playcover 3.1.0, but when I open zenless it said error -10670 and I cannot open it

### Steps to reproduce

just open it

### Expected behaviour

open it succesfully

### Crash log

```shell
none
```

### What version of PlayCover are you using?

3.1.0

### What version of macOS are you using?

Other (please specify)

### Issue Language

- [X] Yes my issue is written in English

**Comment by bennite** [comment]
please help

**Comment by TheMoonThatRises** [comment]
Open Activity Manager, search of Zenless Zone Zero, and force quit it.
