### ISSUE TITLE
Macro feature not working

### ISSUE THREAD

**Issue by AppleDestroyer** [PlayCover/PlayCover#18]
<img width="1051" alt="Screen Shot 2022-07-13 at 5 42 36 PM" src="https://user-images.githubusercontent.com/54783280/178659328-63ebb47b-bafd-4239-a7a9-342e4992775a.png">
The macro feature doesn't seem working. Even though it pops up the messages like 'Started Recording', nothing seems to record.

**Comment by ZhichGaming** [comment]
This feature developed by iVoider but he did not commit it to GitHub. Macros will be added/fixed in the future.

**Comment by Depal1** [comment]
Macros won't be implemented on PlayCover.
