### ISSUE TITLE
Encryption error message gets triggered by other issues?

### ISSUE THREAD

**Issue by brsotis** [PlayCover/PlayCover#183]
A known good IPA was not opening. Updated PlayCover, and received a "move play cover to Applications" error. 
Disabled SIP, removed the installed IPA, and went to reinstall after updating PlayCover. 

Getting "This app is encrypted! Please use a decrypted IPA from AppDb or download one from the internal store. iMazing IPA are not currently supported!" on multiple, decrypted IPA's.

**Comment by Candygoblen123** [comment]
What app are you trying to run? Specific examples would be best.

**Comment by Depal1** [comment]
> Updated PlayCover, and received a "move play cover to Applications" error.

This first issue is literally for running PlayCover out of the Applications folder, perhaps you ran it from the installation disk. Move it to the Applications folder.

**Comment by ZhichGaming** [comment]
> A known good IPA was not opening. Updated PlayCover, and received a "move play cover to Applications" error. Disabled SIP, removed the installed IPA, and went to reinstall after updating PlayCover.
> 
> Getting "This app is encrypted! Please use a decrypted IPA from AppDb or download one from the internal store. iMazing IPA are not currently supported!" on multiple, decrypted IPA's.

It seems that you are trying to run an encrypted IPA file. You need to use ipas that have been decrypted yourself or by someone else. You can find those here: https://ipa.playcover.workers.dev/0:/, here https://armconverter.com/decryptedappstore or here https://ipa.decrypt.day/.

**Comment by brsotis** [comment]
App was decrypted myself on a jailbroken iPhone. It runs directly out of the ~containers folder from a backup, but will not launch, or let me reinstall from Playcover.

Playcover is and was in the applications folder. Before this error, it said something about playtools and wouldn't launch.

**Comment by brsotis** [comment]
Tried with the Netflix download as well, and get This app is encrypted! Please use a decrypted IPA from AppDb or download one from the internal store. iMazing IPA are not currently supported!"

**Comment by Depal1** [comment]
I reckon this can be a legitimate issue as the original poster has just written. Perhaps the error message is too broad, and it isn't triggered because of encryption, or he is using 1.1.0 instead of 1.1.1.

@brsotis What PlayCover version are you using?

**Comment by brsotis** [comment]
Version 1.1.0 (17)

**Comment by Depal1** [comment]
Please use 1.1.1. There were issues related to yours that were fixed.

**Comment by Depal1** [comment]
Keep me posted.

**Comment by brsotis** [comment]
Same error with the known good decrypted app (Azur Lane) that can still launch from containers from a backup. 

<img width="895" alt="Screen Shot 2022-08-18 at 8 20 21 PM" src="https://user-images.githubusercontent.com/111543579/185516643-8bc02e0d-4ebd-46f0-8849-be81457c100a.png">
 
 Will try netflix now

**Comment by brsotis** [comment]
The above error is from Version 1.1.1 (36)

**Comment by brsotis** [comment]
<img width="895" alt="Screen Shot 2022-08-18 at 8 23 41 PM" src="https://user-images.githubusercontent.com/111543579/185516878-1855e537-2c72-41d8-9dd1-de28287f6374.png">

**Comment by brsotis** [comment]
Weirdly enough Netflix works after the above error is thrown. I can try re-cracking the app, but it took a long time originally

**Comment by Depal1** [comment]
Are you on Ventura by any chance?

**Comment by Depal1** [comment]
Nevermind, it was macOS 12.5.1.

**Comment by ZhichGaming** [comment]
You can try deleting the playcover apps folder and reinstalling your apps.

**Comment by ohaiibuzzle** [comment]
This error is thrown not only when an app main binary is encrypted but also when **any** Mach-O binaries after extraction is found encrypted. You may want to check if your dumper has properly decrypted everything including dylibs and such, as even if one of them stays encrypted (`otool -l` output has `LC_ENCRYPTION_INFO` and `cryptid 1`), installation will immediately be aborted.

**Comment by yuchenxi2000** [comment]
> Same error with the known good decrypted app (Azur Lane) that can still launch from containers from a backup.
> 
> <img alt="Screen Shot 2022-08-18 at 8 20 21 PM" width="895" src="https://user-images.githubusercontent.com/111543579/185516643-8bc02e0d-4ebd-46f0-8849-be81457c100a.png">
> 
> Will try netflix now

Was your Azur Line app downloaded from Playcover's decrypted IPA server? (https://ipa.playcover.workers.dev/) I downloaded the app in CN region, but I think it's the same case with the app in US region.

The main binary has two architectures, armv7 and arm64. The arm64 code is decrypted, while the armv7 code is not decrypted. M1 Macs will run the arm64 code, therefore this app should run in Playcover. However, Playcover think the binary is encrypted, because it runs otool command and only checks if the output contains "cryptid 1".

The fix is to ignore the cryptid under LC_ENCRYPTION_INFO load command, and only check the cryptid under LC_ENCRYPTION_INFO_64 load command. If you want to run the app before the fix, you can extract the arm64 code using lipo command, and make another IPA that doesn't contain any encrypted armv7 code.

**Comment by Candygoblen123** [comment]
We could also add an install anyway button to the error popup, just as a manual bypass.
