### ISSUE TITLE
[V1.1.1 Hotfix] BUG Cannot select vertical 720 screen resolution, or other sizes

### ISSUE THREAD

**Issue by sheaahhoi1** [PlayCover/PlayCover#184]
Cannot select vertical 720 screen resolution, or other sizes

Some should not require high resolution, such as chat app & online shopping app, which can provide iPhone size 4.7 "(375x667) & 6.1" (390x844)

![螢幕截圖 2022-08-19 上午8 12 05](https://user-images.githubusercontent.com/10239384/185516341-f16ca794-3931-482c-a9de-a50e282b2980.png)

**Comment by Depal1** [comment]
Try double clicking on the top bar of your app to make it smaller.

**Comment by sheaahhoi1** [comment]
@Depal1 double-clicking the top bar of the app to make it bigger.

**Comment by sheaahhoi1** [comment]
Vertical functionality is fine, but other lower resolutions are not available

**Comment by JoseMoreville** [comment]
> Vertical functionality is fine, but other lower resolutions are not available

it is just 720p vertical
