### ISSUE TITLE
The bottom option of Program Preferences is incomplete on the MacBook Pro (14", 2021)

### ISSUE THREAD

**Issue by hoobnn** [PlayCover/PlayCover#185]
When I open the application preferences, the "OK" and "Restore default settings" buttons at the bottom are blocked by the dock bar, when I resize the dock bar or close the dock bar at the bottom of the Mac, the problem is solved. I hope that I can increase the adaptability of the program display. Here is a screenshot of my screen, the screen resolution settings are in the default state
<img width="740" alt="iShot_2022-08-19_09 39 58" src="https://user-images.githubusercontent.com/111053672/185524101-98285e5f-66f7-4643-a275-f23352b91c41.png">

**Comment by JoseMoreville** [comment]
Move playcover app with the modal closed

**Comment by IsaacMarovitz** [comment]
Issues with model extending past the window bounds will be fixed in #126

**Comment by Dvvarf** [comment]
Please, reopen.
PR #126 was closed without any changes merged, and parent window cannot be moved in such a way that the buttons are accessible on some systems.

**Comment by Depal1** [comment]
The changes were merged in #290, and are currently available in nightly builds.
