### ISSUE TITLE
Error occurs when saving a Genshin account if a file of that name is at that location. 

### ISSUE THREAD

**Issue by ZhichGaming** [PlayCover/PlayCover#191]
The error messages should should prompt the user to choose whether to override or cancel saving this account. 
<img width="372" alt="Screen Shot 2022-08-19 at 00 32 08" src="https://user-images.githubusercontent.com/93055907/185543501-985f9040-e923-4600-9e9d-6e97bf594bc9.png">
<img width="372" alt="Screen Shot 2022-08-19 at 00 33 48" src="https://user-images.githubusercontent.com/93055907/185543509-70ec7673-045f-4559-a613-c6f5e2b93b81.png">

**Comment by JoseMoreville** [comment]
That's supposed to happen, please remove the item first, overriding is not implemented.
