### ISSUE TITLE
On 1.1.1, Update check says 1.1.0 is the latest build

### ISSUE THREAD

**Issue by amirsaam** [PlayCover/PlayCover#192]

**Comment by JoseMoreville** [comment]
Please, provide images and more information about the issue

**Comment by amirsaam** [comment]
I think it's an obvious issue ^_^ <img width="372" alt="Screenshot 1401-05-28 at 10 08 32" src="https://user-images.githubusercontent.com/1331289/185550616-44f64506-d23d-43de-90c9-2825c9e09418.png">

**Comment by JoseMoreville** [comment]
All issues needs to have more context, just a title makes little hard to understand. this problem will be fixed soon
