### ISSUE TITLE
All of Infinity Blades (I, II, III) on install stop with "Some error happened!"

### ISSUE THREAD

**Issue by amirsaam** [PlayCover/PlayCover#194]
<img width="372" alt="Screenshot 1401-05-28 at 10 28 52" src="https://user-images.githubusercontent.com/1331289/185552996-7d91f1ec-fa1d-4055-8382-a9ac650235b6.png">

Tried on 1.0.7. 1.1.0 and 1.1.1

My Device: M1 MacBook Pro 2020 13" on macOS 12.5.1

Using IPA files from Infinity Blades official discord server: https://discord.gg/Rn6FXf2

**Comment by IsaacMarovitz** [comment]
What version of PlayCover are you using,

**Comment by amirsaam** [comment]
Like I said, I tried them all on 1.0.7, 1.1.0 and 1.1.1 none of them worked.
For now I am on 1.1.1

**Comment by ZhichGaming** [comment]
Is your IPA decrypted?

**Comment by amirsaam** [comment]
Yes, they are.

As I mentioned they are from the Official IB Discord Server and they say that those IPAs are decrypted.

**Comment by ZhichGaming** [comment]
So what I am getting is that your game does not install? Does this only occur with infinity blade or does it occur with other apps too? Try installing a different infinity blade ipa.

**Comment by amirsaam** [comment]
There is no other IPAs for IBs because Epic Games got banned from App Store and no one can download and decrypt them anymore but those links for their decrypted IPAs are being used for installing them with Sideloadly on new iOS devices, so if new iOS devices can run IBs, PlayCover could do I assume but I dunno what is them problem. 

This kind of error only happens with IBs that I tried. after extraction of the IPA PlayCover just says some error happened and no install.

**Comment by ohaiibuzzle** [comment]
Do you have the logs of the apps being installed? You can grab the log in the PlayCover menu in the top bar after the failure

**Comment by amirsaam** [comment]
No Logs, only this few lines:
```
Version 12.5.1 (Build 21G83)
/Applications/Xcode.app/Contents/Developer

Installing PlayTools
Copying PlayTools to Frameworks
```
