### ISSUE TITLE
Abnormal display of Genshin feedback page

### ISSUE THREAD

**Issue by lushuyu** [PlayCover/PlayCover#195]
<img width="792" alt="image" src="https://user-images.githubusercontent.com/27007632/185591409-ecb501a5-d3bb-4075-a468-648d624f90b5.png">
The window is rotated, but the content is not.
Exists in Playcover1.1.1 and com.mihoyo.yuanshen(com.mihoyo.Genshin is not tested)

**Comment by Candygoblen123** [comment]
Related to #97
