### ISSUE TITLE
The problem of high power consumption brought about by the resolution

### ISSUE THREAD

**Issue by hoobnn** [PlayCover/PlayCover#196]
In versions 1.1.0 and 1.1.1, the ability to select a resolution was added, which is certainly a great improvement, but the game I'm using, called Light Encounter, seems to be rendered in resolutions below 1080p, so if you select 1080p resolution, it will bring the problem of high power consumption of the computer, so I hope that a lower resolution option can be added additionally to maintain the previous version's The game works.

**Comment by zanderp25** [comment]
@TeaWu Is it better if you enable auto resize?

**Comment by hoobnn** [comment]
> @TeaWu Is it better if you enable auto resize?

yes,it worked,thanks

**Comment by zanderp25** [comment]
Alright, i will close this now
