### ISSUE TITLE
Graphic quality in Genshin Impact just declined when changing the device model to newer ones

### ISSUE THREAD

**Issue by Carlos-Mero** [PlayCover/PlayCover#198]
I just updated my playcover to version 1.1.1, and expected the new feature that switches between iPad models would help to enhance the graphic quality of the games. But actually, it did the opposite. By switching from iPad with A12Z chip to that with M1 chip, the resolution of Genshin Impact just decreased a lot. I am using the highest settings but the quality is still far lower than before, and of course lower than that of a real iPad. By the way, I also experienced high power consumption while using higher resolution, It's up to 10W higher than before according to Asitop, but the graphic quality still remains the same.

It may be too hard to be solved in a short period, and it's alright for me to play anyway. But I'm just wondering why this problem would happen.

**Comment by IsaacMarovitz** [comment]
If read the announcements channel in Discord you will see that the iPad with the A12Z option is the best option for Genshin. Newer iPad model identifier != better quality always.

Higher resolution will require more resources so it will use more power yes. Regarding graphical differences refer to issue #179 for an explanation.
