### ISSUE TITLE
[Bug]: Namespace SIGNAL, Code 5 Trace/BPT trap: 5

### ISSUE THREAD

**Issue by abdullahsaeed98** [PlayCover/PlayCover#208]
### Describe the bug

Bug "Namespace SIGNAL, Code 5 Trace/BPT trap: 5" reported in multiple Gaming Apps.

Some of them are 

- CSR Racing 2
- Jetpack Joyride 2

installed through there decrypted ipas.

### Steps to reproduce

- Installing Ipa and then executing through playcover

### Expected behaviour

Game Starting Sucessfully

### Crash log

```shell
System Integrity Protection: enabled

Crashed Thread:        0  Dispatch queue: com.apple.main-thread

Exception Type:        EXC_BREAKPOINT (SIGTRAP)
Exception Codes:       0x0000000000000001, 0x000000018ef6bd84
Exception Note:        EXC_CORPSE_NOTIFY

Termination Reason:    Namespace SIGNAL, Code 5 Trace/BPT trap: 5
Terminating Process:   exc handler [4612]
```

### What version of PlayCover are you using?

1.1.1

### What version of macOS are you using?

Monterey (macOS 12)

### Issue Language

- [X] Yes my issue is written in English

**Comment by IsaacMarovitz** [comment]
Try running with SIP disabled

**Comment by XuYicong** [comment]
Please try with the latest nightly build.

**Comment by abdullahsaeed98** [comment]
@XuYicong Just tried. CSR Racing 2 now get closed after just few seconds with no error prompt.

**Comment by IsaacMarovitz** [comment]
@abdullahsaeed98 Please run through LLDB:
1. Install in PlayCover
2. Right click `Open in Finder`
3. Open terminal run `lldb` then a space, then the path to the app in finder (you can drag it in to terminal`
4. Run that command, wait for it to finish processing
5. Run `r`
6. Send whatever logs are returned
