### ISSUE TITLE
[Feature]: please support call of duty

### ISSUE THREAD

**Issue by yzh9865** [PlayCover/PlayCover#209]
### Is your feature request related to a problem?

can’t play call of duty

### Describe the solution you'd like

please support

### Anything else?

thanks 

### Issue Language

- [X] Yes my issue is written in English

**Comment by amirsaam** [comment]
I think CoD is supported but your risk for getting banned is very high because they only accept GameLoop for gaming with Keyboard and Mouse (for not letting people cheat)
