### ISSUE TITLE
[Game Support]: VainGlory (Becomes "Not Responding" after Launch)

### ISSUE THREAD

**Issue by amirsaam** [PlayCover/PlayCover#213]
**UPDATE September 5: It will run on Nightly 53 so far**

### App Store link

https://apps.apple.com/us/app/vainglory/id671464704

### Current issues

- [ ] Game fails to install
- [X] Game fails to open
- [ ] Game crashes randomly during gameplay
- [ ] Game does not work with keymapping
- [ ] Game experiences graphical issues or broken UI
- [ ] Game fails to connect to servers or complete download

### More details

You can install the game with no error but when you try to open it, it fails to open.
No window will show up, you can't even click on the menubar items, it freezes and you will need to force quit it.

Tried IPAs from [Decrypt Day](https://ipa.decrypt.day) and [Decrypted AppStore](https://armconverter.com/decryptedappstore), and also the one in PlayCover's IPA directory.

Tested on PlayCover 1.0.7, 1.1.0 and 1.1.1 - All have the same result.
My Device: M1 MacBook Pro 2020 13" on macOS 12.5.1

### Crash log

```shell
Version 12.5.1 (Build 21G83)
/Applications/Xcode.app/Contents/Developer

Installing PlayTools
Copying PlayTools to Frameworks

<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "https://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
  <dict>
    <key>com.apple.security.app-sandbox</key>
    <true/>
    <key>com.apple.security.assets.movies.read-write</key>
    <true/>
    <key>com.apple.security.assets.music.read-write</key>
    <true/>
    <key>com.apple.security.assets.pictures.read-write</key>
    <true/>
    <key>com.apple.security.device.audio-input</key>
    <true/>
    <key>com.apple.security.device.bluetooth</key>
    <true/>
    <key>com.apple.security.device.camera</key>
    <true/>
    <key>com.apple.security.device.usb</key>
    <true/>
    <key>com.apple.security.files.downloads.read-write</key>
    <true/>
    <key>com.apple.security.files.user-selected.read-write</key>
    <true/>
    <key>com.apple.security.network.client</key>
    <true/>
    <key>com.apple.security.network.server</key>
    <true/>
    <key>com.apple.security.personal-information.addressbook</key>
    <true/>
    <key>com.apple.security.personal-information.calendars</key>
    <true/>
    <key>com.apple.security.personal-information.location</key>
    <true/>
    <key>com.apple.security.print</key>
    <true/>
    <key>com.apple.security.temporary-exception.sbpl</key>
    <array>
      <string>(allow user-preference-write (preference-domain ".GlobalPreferences"))</string>
      <string>(allow user-preference-read (preference-domain ".GlobalPreferences"))</string>
      <string>(allow file* file-read* file-write* file-write-data file-read-metadata file-ioctl (literal "/Users/amirsaam/Library/Preferences/playcover.plist"))</string>
      <string>(allow file* file-read* file-read-metadata file-ioctl (subpath "/Users/amirsaam/Library/Frameworks/PlayTools.framework"))</string>
    </array>
  </dict>
</plist>

/usr/bin/vtool

/Users/amirsaam/Library/Frameworks/PlayTools.framework/PlayTools:
Load command 50
      cmd LC_BUILD_VERSION
  cmdsize 24
 platform MACCATALYST
    minos 11.0
      sdk 14.0
   ntools 0

/usr/bin/vtool

/Users/amirsaam/Library/Containers/io.playcover.PlayCover/GameKindred.app/GameKindred:
Load command 40
      cmd LC_BUILD_VERSION
  cmdsize 24
 platform MACCATALYST
    minos 11.0
      sdk 14.0
   ntools 0

Executable=/Users/amirsaam/Library/Containers/io.playcover.PlayCover/GameKindred.app/GameKindred
Identifier=com.superevilmegacorp.kindred
Format=app bundle with Mach-O thin (arm64)
CodeDirectory v=20400 size=205462 flags=0x2(adhoc) hashes=6410+7 location=embedded
Signature=adhoc
Info.plist entries=42
TeamIdentifier=not set
Sealed Resources version=2 rules=10 files=48362
Internal requirements count=0 size=12
```

### Issue Language

- [X] Yes my issue is written in English

**Comment by amirsaam** [comment]
I closed my previously opened issue about this problem in order to open an issue with newly added templates.

**Comment by ohaiibuzzle** [comment]
I suspect this might be down to jailbreak detection again. Most competitive games would just refuse to work if they detect anything but a sane-looking iOS environment

**Comment by amirsaam** [comment]
> I suspect this might be down to jailbreak detection again. Most competitive games would just refuse to work if they detect anything but a sane-looking iOS environment

@ohaiibuzzle I tried jailbreak bypass too, same result.

**Comment by amirsaam** [comment]
I have confirmed that Vainglory works fine on Jailbroken devices.
So it's not the problem that creates this issue.

**Comment by Depal1** [comment]
In what year was that game released?

**Comment by amirsaam** [comment]
Latest update is from a year ago (currently paused developing) but I don't think that's the problem.
Vainglory and Catalyst Black (updated less than a month ago) are from same developer and both share the same problem in PlayCover

**Comment by Depal1** [comment]
If the game is too old, it might not use Metal, and that is a problem.

**Comment by amirsaam** [comment]
Sideloadly can successfully install and run Vainglory with Apple ID signing. There is something wrong with it in PlayCover that causes the issue.
<img width="1163" alt="Screenshot 1401-06-04 at 21 15 08" src="https://user-images.githubusercontent.com/1331289/186953544-d595f905-dde2-42e1-8fb5-2318aaf6d665.png">

**Comment by amirsaam** [comment]
It will run on 2.0 (nightly 53 so far), so I close this issue.
