### ISSUE TITLE
[Bug]: Selecting the display size "Vertical" causes vertical screen apps to become horizontal.

### ISSUE THREAD

**Issue by tellus1019** [PlayCover/PlayCover#229]
### Describe the bug

First of all, thank you for your response.
The Vertical option has been added but it does not seem to be behaving as desired.

The application does indeed appear to be sized like 720p, but the height and width are reversed.
The first issue I registered was for a solution to the problem of vertical screen apps not fitting within the screen.
Is the currently implemented "Vertical" option a different feature?
Or is it the result of my request being implemented incorrectly?

Either way, a game played on a vertical screen is an undesirable result.
Attached are screenshots of the video when started with the 1080p option and when started with the Vetical option.
You will see that they are not the same aspect ratio.

<img width="943" alt="1080p" src="https://user-images.githubusercontent.com/25951129/185884885-3459d41c-234d-4214-8e2f-2ba3c51212a3.png">
<img width="1097" alt="Vertical" src="https://user-images.githubusercontent.com/25951129/185884929-2672fe24-6330-4ae9-abe2-71168d5ce5b8.png">

### Steps to reproduce

Launch vertical screen game applications using the 1080p and Vertical options.

For reference I use the following apps
https://apps.apple.com/jp/app/id1205841875

### Expected behaviour

Vertical screen game applications should be adjusted to a size that fits within the screen.

The use of the 1080p option on FullHD and 2540x1440 monitors should not cause problems with large out-of-focus areas on the screen.

### What version of PlayCover are you using?

1.1.1

### What version of macOS are you using?

Monterey (macOS 12)

### Issue Language

- [X] Yes my issue is written in English

**Comment by tellus1019** [comment]
The current ability to use vertical screen apps in landscape mode is convenient.
Please do not kill this feature, but add an option to allow vertical screen games to be displayed in a size that fits on the monitor.

My first issue is here.
https://github.com/PlayCover/PlayCover/issues/169

**Comment by tellus1019** [comment]
PS
The vertical screen game app I am using does not support iPad rotation.

It is not supported, but the UI and other important display items will be severely disrupted if it is converted to a horizontal screen.
The issue of vertical games not fitting on the display and applications that support rotation should be treated as separate issues.

*I feel that this may be confused with the following issue.
https://github.com/PlayCover/PlayCover/issues/182

**Comment by ZhichGaming** [comment]
There is a 720p horizontal option in the lastest nightly build.

**Comment by JoseMoreville** [comment]
If that doesn't fit, please use the custom resolution on todays nightly build
