### ISSUE TITLE
[Game Support]: Genshin Impact logged out when SIP is re-enabled

### ISSUE THREAD

**Issue by jeremyphilson27** [PlayCover/PlayCover#234]
### App Store link

https://apps.apple.com/us/app/genshin-impact/id1517783697

### Current issues

- [ ] Game fails to install
- [X] Game fails to open
- [ ] Game crashes randomly during gameplay
- [ ] Game does not work with keymapping
- [ ] Game experiences graphical issues or broken UI
- [ ] Game fails to connect to servers or complete download

### More details

I have disabled SIP, ran the nvram boot args command line then restarted my mac. I logged in on Genshin until the door appeared, then I quit (command+Q) Genshin app and shut down my macbook to enable the SIP. When SIP is re-enabled, my account is logged out again, and no matter what login option I use, it won't work.

You can see the process here : 
https://drive.google.com/file/d/1NJsOuKWnDE-uW6ZXsiaYjBNsuU3hIF6K/view?usp=sharing

My device is Macbook Air M1
macOS Monterey Version 12.5

### Issue Language

- [X] Yes my issue is written in English

**Comment by JoseMoreville** [comment]
Try login in again, with sip and close the game, or click the hoyoicon, and open twice to close and open the login prompt.

**Comment by jeremyphilson27** [comment]
I have tried that actually, and it still won't log me in. Btw I am currently playing Genshin without SIP.

**Comment by jeremyphilson27** [comment]
> Try login in again, with sip and close the game, or click the hoyoicon, and open twice to close and open the login prompt.

I have tried that actually, and it still won't log me in. Btw I am currently playing Genshin without SIP.

**Comment by IsaacMarovitz** [comment]
Try logging in with Twitter instead. You can link a Twitter account to your Genshin account in HoYo Lab.

**Comment by jeremyphilson27** [comment]
> Try logging in with Twitter instead. You can link a Twitter account to your Genshin account in HoYo Lab.

I have tried that too, one of the contributor on discord told me to do that, and still can't log in when SIP is enabled again.

**Comment by ZhichGaming** [comment]
Try another build. There is an issue about this in #29 so you can try using 1.0.4 in the PlayVault archives. Here are the instructions to use it: ﻿
[] - **Command + Space** on your keyboard  
﻿[] - Type `Terminal`  
﻿[] - Type or copy+paste the following commands:  
﻿```chmod -R +x /Applications/PlayCover.app  
﻿xattr -cr /Applications/PlayCover.app 
codesign --force --deep --sign - /Applications/PlayCover.app  ```

**Comment by ghost** [comment]
im having this issue too

**Comment by amirsaam** [comment]
it's a bad solution to be honest but if you want you can use this this command in macOS recovery to get rid of most disabled protections and have what is required:
`csrutil enable  --without fs --without kext --without nvram`
I do not recommend it btw, it requires you to be caution about what you install and where download apps and files since it is partly enabled sip and has no full protection.

**USE AT YOUR OWN RISK**

**Comment by amirsaam** [comment]
did you try installing xclt with this command?
`xcode-select --install`

**Comment by ZhichGaming** [comment]
It would be better to have SIP completely disabled as to not forget that your SIP is partially off.

**Comment by ghost** [comment]
Hey, Zhich(contributor in PlayCover) helped me find a fix! The fix was removing all Mihoyo related files in "Keychain Access". Hope this works!

**Comment by jeremyphilson27** [comment]
> Hey, Zhich(contributor in PlayCover) helped me find a fix! The fix was removing all Mihoyo related files in "Keychain Access". Hope this works!

can you show me how?

**Comment by amirsaam** [comment]
There is an app called Keychain Access, open it, search for Genshin Impact, delete all of those then disable sip put nvram boot args, login to genshin but DO NOT PASS THE DOOR, close the game store account then re-enable sip and try if it's working

**Comment by taupter** [comment]
There's a workaround you can test. On another device, open Genshin Impact, log into it and link your Twitter account to your Genshin Impact one. Then go back to your Mac, SIP enabled and all, and log in Genshin Impact using the Twitter option. After you authorize it will log in just fine, without captcha's or slider test. Simple as this.

**Comment by 623637646** [comment]
> There's a workaround you can test. On another device, open Genshin Impact, log into it and link your Twitter account to your Genshin Impact one. Then go back to your Mac, SIP enabled and all, and log in Genshin Impact using the Twitter option. After you authorize it will log in just fine, without captcha's or slider test. Simple as this.

Thanks! This works for me.
