### ISSUE TITLE
[游戏支持]Ask for support for Peace Elite

### ISSUE THREAD

**Issue by crane3200** [PlayCover/PlayCover#236]
### App Store link

https://apps.apple.com/cn/app/%E5%92%8C%E5%B9%B3%E7%B2%BE%E8%8B%B1/id1321803705

### Current issues

- [ ] Game fails to install
- [X] Game fails to open
- [ ] Game crashes randomly during gameplay
- [ ] Game does not work with keymapping
- [ ] Game experiences graphical issues or broken UI
- [ ] Game fails to connect to servers or complete download

### More details

After I successfully installed Peace Elite through playcover, I couldn't open the app, and the prompt: ''You may receive a ban! There have been reports of bans when playing this game using PlayCover.''
Can playcover disguise an iPad like an iOS jailbreak plugin? Make the app not recognize that playcover is an emulator.

### Issue Language

- [X] Yes my issue is written in English

**Comment by amirsaam** [comment]
Have you tried to use "Jailbreak Bypass" option?
Open your game's "App preferences" in PlayCover and you will see an option for it.
<img width="777" alt="Screenshot 1401-06-02 at 13 52 00" src="https://user-images.githubusercontent.com/1331289/186382085-e025428e-9d01-425f-b49b-b9dbd46d1450.png">

P.S: If you have tried and it gave you the warning, maybe it's because the game does not support 3rd party launchers just like CoD: Mobile.

**Comment by crane3200** [comment]
I turned it on, but playcover gave me a warning that I couldn't launch the game normally.

**Comment by amirsaam** [comment]
maybe share a screenshot of the warning?

**Comment by crane3200** [comment]
![image](https://user-images.githubusercontent.com/88588548/186397324-c1e09cda-00fe-4c7c-b238-040b88d61cfc.png)

**Comment by amirsaam** [comment]
This is the warning you talked about in the original issue post.
What happens after you turn on the bypass?
If it is what still show you, then I explained the reason in previous comments.

**Comment by crane3200** [comment]
The warning in the original post, I have been unable to successfully open this app

**Comment by amirsaam** [comment]
If you still getting the original warning for ban risk after enabling jailbreak bypass, then this is about the game restricted their launch from 3rd party launchers. This means you could get banned, it's not about PlayCover ability to run the game.
Like I mentioned CoD: Mobile has such restrictions and you can get banned by playing this game on PlayCover as CoD: Mobile.

**Comment by yzh9865** [comment]
I don't care even if I get banned man, just let me open the game at least for god sake

**Comment by amirsaam** [comment]
> We currently have no plans to allow users to install apps that will cause their accounts to be banned because of PlayCover

This is an official statement.

**Comment by Depal1** [comment]
There won't be an official amendment to this. You could remove your game from this [list](https://github.com/PlayCover/PlayCover/blob/aff873878bd6503fd5c6787a96f8218202c255f4/PlayCover/Model/PlayApp.swift#L138) and build it from source. You do so at your own risk.
