### ISSUE TITLE
[Bug]: I can't download genshin with the link

### ISSUE THREAD

**Issue by tofucurd** [PlayCover/PlayCover#237]
### Describe the bug

I use safari to open ``https://ipa.playcover.workers.dev/0:/Genshin%20Impact/US/Genshin%20Impact_2.8.0.ipa``.

But it shows that there's no such file.

<img width="763" alt="截屏2022-08-24 19 12 02" src="https://user-images.githubusercontent.com/108205653/186404536-f85be6fa-a5ca-4df8-9e4f-2c036e50ef55.png">

### Steps to reproduce

Just open the link with safari.

### Expected behaviour

Download the file.

### Crash log

```shell
There's no crash
```

### What version of PlayCover are you using?

1.1.1

### What version of macOS are you using?

Monterey (macOS 12)

### Issue Language

- [X] Yes my issue is written in English

**Comment by tofucurd** [comment]
Sorry, I solved it myself: there's a new 3.0.0 version under ``https://ipa.playcover.workers.dev/0:/Genshin%20Impact/US/ ``

**Comment by amirsaam** [comment]
Close the issue please.

**Comment by tofucurd** [comment]
I want to use aria2 to download ``https://ipa.playcover.workers.dev/0:/Genshin%20Impact/US/Genshin%20Impact_3.0.0.ipa``,but safari has already started downloading, so I stop safari and it comes this:
<img width="1089" alt="截屏2022-08-24 19 51 29" src="https://user-images.githubusercontent.com/108205653/186411526-034431de-aab7-421b-96c5-a60406885442.png">

But actually I didn't download it. So when can I download it again?

**Comment by amirsaam** [comment]
Try some other links to download the file from the discord server announced in PlayCover server for decrypted IPAs.

**Comment by JoseMoreville** [comment]
For the record, avoid posting this type of posts in the future here, everything related to that feature and page is on the server, not here
