### ISSUE TITLE
[Game Support]: CODM is blocked from opening 

### ISSUE THREAD

**Issue by yzh9865** [PlayCover/PlayCover#238]
### App Store link

the latestest version playcover won't allow you to open weather it's call of duty mobile or the chinese version 使命召唤手游，please unlock the disabled, even if that really bans me, thank you !

### Current issues

- [ ] Game fails to install
- [ ] Game fails to open
- [ ] Game crashes randomly during gameplay
- [ ] Game does not work with keymapping
- [ ] Game experiences graphical issues or broken UI
- [ ] Game fails to connect to servers or complete download

### More details

all the other old possible versions of playcover that I tried maybe crush, mabye not be able to login, the latest version of playcover has the best optimization but it's unable to let us try out the game that was previously crushing all the time. please enable to be able to open CODM at the latest playcover version at least, thank you !

### Issue Language

- [X] Yes my issue is written in English

**Comment by Candygoblen123** [comment]
Playing the game you listed, CODM, with PlayCover will result in a ban from CODM. It's basically a 100% guarantee.

It is not a matter of **if** you will get banned, it is a better of **when** you will get banned.

We currently have no plans to allow users to install apps that will cause their accounts to be banned because of PlayCover

**Comment by amirsaam** [comment]
Originally posted by @Depal1 on **#236**:
> There won't be an official amendment to this. You could remove your game from this [list](https://github.com/PlayCover/PlayCover/blob/aff873878bd6503fd5c6787a96f8218202c255f4/PlayCover/Model/PlayApp.swift#L138) and build it from source. You do so at your own risk.

Posting it here just to complete the information for people with such asks.

**Comment by amirsaam** [comment]
I suggest changing the name of this issue to: "**Read if your game is blocked from launch with a Ban Risk warn**" (because this a pinned issue)

**Comment by adinetech** [comment]
> Playing the game you listed, CODM, with PlayCover will result in a ban from CODM. It's basically a 100% guarantee.
> 
> It is not a matter of **if** you will get banned, it is a better of **when** you will get banned.
> 
> We currently have no plans to allow users to install apps that will cause their accounts to be banned because of PlayCover

It doesn't make sense, consider adding an option to accept or decline the warning.

**Comment by ohaiibuzzle** [comment]
> It doesn't make sense, consider adding an option to accept or decline the warning.

For what? If you can run the game, but it is practically unusable, why would you even do it

Plus, you have always been able to do that by right clicking the app > Open in Finder, then just run the .app

**Comment by adinetech** [comment]
I didn't know that I can do that, I would like to give the "New State" game a try. Thanks.

**Comment by JoseMoreville** [comment]
Any changes will be added to make the game playable via PlayCover, we rather keep user account's save... If they get to play outside of the launcher, it's on their own risk. 

Neither we will give any support for those games.

**Comment by yzh9865** [comment]
﻿Hi there is a Chinese version of CODM called 使命召唤手游，it is safe to play on playcover, but the only playcover version that allows it to run is 0.95, and I have been playing it more than half a year not getting banned, so would you consider adding the game suppport into the latest version of play cover? As new version supports more features than 0.95 do.

**Comment by ohaiibuzzle** [comment]
> Hi there is a Chinese version of CODM called 使命召唤手游，it is safe to play on playcover, but the only playcover version that allows it to run is 0.95, and I have been playing it more than half a year not getting banned, so would you consider adding the game suppport into the latest version of play cover? As new version supports more features than 0.95 do.

Would love to do that, unfortunately PlayCover versions before 1.x were completely closed source. so we don't know what changes introduced that causes it to trip detection

**Comment by TonDevv** [comment]
> Hi there is a Chinese version of CODM called 使命召唤手游，it is safe to play on playcover, but the only playcover version that allows it to run is 0.95, and I have been playing it more than half a year not getting banned, so would you consider adding the game suppport into the latest version of play cover? As new version supports more features than 0.95 do.
> […](#)
> Sent from my iPhone
> On Apr 4, 2023, at 1:46 AM, José Moreno ***@***.***> wrote: ﻿ Any changes will be added to make the game playable via PlayCover, we rather keep user account's save... If they get to play outside of the launcher, it's on their own risk. Neither we will give any support for those games. — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.

how can i access to 0.95 ?
