### ISSUE TITLE
[Feature]: Prompt availability on Mac App Store of the game/app that user tries to install

### ISSUE THREAD

**Issue by amirsaam** [PlayCover/PlayCover#239]
### Is your feature request related to a problem?

No

### Describe the solution you'd like

Here is the step by step scenario of what I have in mind:

1. User tries to install a decrypted app/game
2. PlayCover gets the identifier/name of the app/game
3. PlayCover does a match query with Mac App Store
4. If the app/game is available to install through Mac App Store, PlayCover shows two option to user with a message like:
> PlayCover suggests installing **$AppName** from official sources. Any problem related to installing or running **$AppName** through PlayCover is on the user and our community are not responsible for solving it.
- A button _(as secondary action)_ to proceed as "Install Anyway"
- A button _(as main action)_ to open the link of the app/game in the Mac App Store

### Anything else?

This feature helps PlayCover to avoid unwanted and unnecessary extra support for apps and games that already are available to download and install as "Designed for iPad/iPhone" through Mac App Store and push the problems related to those such apps and games to the original developers of them.

For example, "Among Us" is available to download from Mac App Store as Designed for iPad and you cannot login to your account with or without PlayCover and login issues are related to the original developer not PlayCover.
So PlayCover can easily avoid problems and issues related to these kind of apps and games with just prompt for user to notice.

### Issue Language

- [X] Yes my issue is written in English

**Comment by ZhichGaming** [comment]
I support this feature, but I think that most people will still try to use PlayCover because of reasons like broken key mapping on App Store version. I think that we should still help people with those games if we know a solution, since most games installed on PlayCover are marked as made for iPad/iPhone.

**Comment by amirsaam** [comment]
> I support this feature, but I think that most people will still try to use PlayCover because of reasons like broken key mapping on App Store version.

I think it will avoid any future extra work for real issues.
Broken keymap is not a big concern for PlayCover because you already have the solution but in fact that is a responsibility for the originals devs not you (and the users can install the game/app anyway at their own risk for issues)

> I think that we should still help people with those games if we know a solution, since most games installed on PlayCover are marked as made for iPad/iPhone.

I don't think PlayCover has the most apps installed from already released as Designed for iPad/iPhone.
Genshin Impact, LoL: Wild Rift, Pokemon Unite, Instagram, Youtube, Diablo Immortal or etc. have bigger user-bases.

Anyway, at some level you should gain users from apps and games that are not already on Mac App Store because original devs eventually begin fixing their issues. You should focus on support legacy games or not intended for Mac release I think.

**Comment by ZhichGaming** [comment]
Genshin impact is not designed for iPhone and iPad? But yes, I agree that this feature would stop some people from asking for support.

**Comment by amirsaam** [comment]
> What? Genshin impact and Pokémon go are not designed for iPhone and iPad?

No, they are **not** released in the Mac App Store as Designed for iPad/iPhone.
Pokemon Unite not Go btw. Go is outdoor based and it's very hard to be played on a Mac :D

> But yes, I agree that this feature would stop some people from asking for support.

That is not the only benefit, it will prevent backlashes from developers too from saying you are stealing users from their Mac App Store, you will show your goodwill to them with just a little prompt.

**Comment by ZhichGaming** [comment]
Oh oops, I read the wrong Pokémon. Yeah, I didn't think of that since I never saw anyone in the server complaining about that but if that ever happens, we can just reply with this feature.

**Comment by amirsaam** [comment]
Believe me if some big Mac gaming content creators like MrMacRight starts to promote PlayCover, unfortunately backlashes will come.

**Comment by amirsaam** [comment]
If we have a game like Last Day on Earth available on Mac App Store (with all issues it has) why we cannot just download it from App Store and use it under PlayCover with on condition: If it has **Designed for iPad/iPhone** tag on the store?
Don't you think it would create a long and better future for PlayCover?

**Comment by IsaacMarovitz** [comment]
PlayCover needs decrypted apps to work correctly. Apps downloaded from the App Store are encrypted, so this feature would not be possible.

**Comment by amirsaam** [comment]
My bad
I thought the same structures of .app package contents are the important things.
Anyway the main feature that I opened issue for is not relative to [my latest comment](https://github.com/PlayCover/PlayCover/issues/239#issuecomment-1236192113).

**Comment by amirsaam** [comment]
@IsaacMarovitz  I think there had been misunderstanding about this issue that you closed. My latest comments was not related to the actual requested feature.

**Comment by IsaacMarovitz** [comment]
@amirsaam Can you please clarify what the feature you are requesting is?

**Comment by amirsaam** [comment]
@IsaacMarovitz let's say you want to install Among Us in PlayCover, while it is available in Mac App Store and is marked with "Designed for iPad" tag, PlayCover should alert user as I described in the original message that it is available in Mac App Store (due to copyright and etc.) but give them option to install it anyway.

**Comment by IsaacMarovitz** [comment]
I'm not sure about the utility of this feature. This sort of check would be quite expensive.
