### ISSUE TITLE
Blurry/Lowered Resolution in the community reboot version.

### ISSUE THREAD

**Issue by AarnavSin** [PlayCover/PlayCover#24]
Tested in Genshin Impact 2.8, PlayCover 1.0.6. The render resolution, at highest settings, is still blurry. This problem is not seen in 1.0.4. As discussed on the server, it could be because of the iPad Model identifier.

**Comment by AarnavSin** [comment]
Graphics Comparison

<img width="1680" alt="Screenshot_2022-07-13_at_7 33 28_PM" src="https://user-images.githubusercontent.com/62804454/178757564-50d12897-6793-4cc7-ac81-b4a7233b26f1.png">
Version 1.0.6.

<img width="1680" alt="Screenshot 2022-07-13 at 7 54 41 PM" src="https://user-images.githubusercontent.com/62804454/178757652-870e8de5-724f-4259-b87a-3ca6a5d71b0d.png">
Version 1.0.4. 

As you can observe, it is much sharper in the latter image (Sorry for the different in-game locations)

**Comment by lixin9311** [comment]
I see the differences. I will look into it later. Meanwhile, if you located the issue, please make a PR.

**Comment by JoseMoreville** [comment]
I'm already working on this issue. Thanks for the information
