### ISSUE TITLE
[Bug]: High Controller Input Lag When Starting Genshin Impact

### ISSUE THREAD

**Issue by JaceThings** [PlayCover/PlayCover#245]
### Describe the bug

Currently using an 8BitDo Pro 2 Controller over bluetooth on my MacBook Pro M1 Max with 64GB of ram.

Been playing Genshin for over 3 weeks now and no issues were present. Today I connect my bluetooth controller, open Genshin and notice heavy input lag when trying to press any button.

Thinking it was an issue with my controller, so I turn on a Controller tester and notice it was also showing input lag. I turn off Genshin, thinking it might be taking too many recourses. Check the Gamepad tester, all working well.

So it seem like Genshin Impact creates heavy Controller input lag for some reason. Worked fine yesterday

### Steps to reproduce

- Connect Bluetooth Controller to Macbook via Bluetooth
- Test Controller input lag on [GamepadTester](https://gamepad-tester.com/)
- View no input lag
- Open Genshin Impact
- Notice heavy input lag
- Check [GamepadTester](https://gamepad-tester.com/), it also agrees.
- Turn off Genshin Impact
- Wait 1-2 Minutes
- Check [GamepadTester](https://gamepad-tester.com/) again
- See that all is well.

### Expected behaviour

No input lag is created when running Genshin Impact

### What version of PlayCover are you using?

1.1.1

### What version of macOS are you using?

Monterey (macOS 12)

### Issue Language

- [X] Yes my issue is written in English

**Comment by Depal1** [comment]
Did you fix it?

**Comment by JaceThings** [comment]
> Did you fix it?

Yea, reported too fast, tried restarting the MacBook, worked faster

**Comment by JaceThings** [comment]
Nevermind,

Keeps Happening

**Comment by Depal1** [comment]
We can look into it. It may require a ground up rework of PlayTools which we started plotting today in a very promising path to fix screen and input lagging issues.

**Comment by JoseMoreville** [comment]
Support is currently for PS4 or PS5 as it is supported by Mac. Once it is implemented in Ventura public release we can take a look into lt
