### ISSUE TITLE
[Bug]: Audio issues with games on PlayCover.

### ISSUE THREAD

**Issue by Araide** [PlayCover/PlayCover#249]
### Describe the bug

Sound effects and music are sometimes not played. In my case, in the game Genshin Impact. The chest opening sound, character dialogues, and interactions with on-screen buttons don't sound. In PvZ2, 50% of the sound effects don't sound, and the background music doesn't sound at all. After several restarts of the game, the problem still persists. Above are the only games I've tested, they all have audio issues.

### Steps to reproduce

No specific procedure.

### Expected behaviour

It is expected to hear both music and sound FX.

### What version of PlayCover are you using?

1.1.1

### What version of macOS are you using?

Monterey (macOS 12)

### Issue Language

- [x] Yes my issue is written in English

**Comment by Araide** [comment]
Also tried on nightly builds, still didn't quite work.

**Comment by CarolineYe07** [comment]
I've been having a similar issue but I haven't had any instances of character dialogues or background music not playing. For me, sometimes sounds when clicking buttons or opening menus don't play, and also the music played by the new harp doesn't have any sound effects half the time, which is what made the issue really obvious to me. The sounds effects are often normal but randomly go silent. I remember a couple instances where the harp notes played normally but there was no sound on the little song that's supposed to play afterward.

**Comment by Depal1** [comment]
Has anyone tested the behaviour of sound on an iOS device?

**Comment by zanderp25** [comment]
I have noticed that in high load areas, my iPhone 11 occasionally omits a good portion of the sounds, especially during combat when a lot of stuff is happening at once.

**Comment by IsaacMarovitz** [comment]
I believe this is a limitation with iOS rather than with PlayCover

**Comment by OhDeepDarkFantasy** [comment]
Right click --> Open in finder --> Rename the game to "jkchess.app" could work
