### ISSUE TITLE
[Bug]: Netflix profile does not open

### ISSUE THREAD

**Issue by Dev-ManishTomar** [PlayCover/PlayCover#251]
### Describe the bug

I successfully login into Netflix but when I clicked on one of the profiles, It threw error "There was a problem selecting this
profile. Please try again later."
![Screenshot 2022-08-27 at 12 29 23 AM](https://user-images.githubusercontent.com/43315327/186973981-31818d94-df09-4583-a8f9-f6a65eda8a53.jpg)

### Steps to reproduce

Launch Netflix then sign in and try to open profile

### Expected behaviour

The Profile should open 

### What version of PlayCover are you using?

1.1.1

### What version of macOS are you using?

Monterey (macOS 12)

### Issue Language

- [X] Yes my issue is written in English

**Comment by ZhichGaming** [comment]
Currently, you can only use the first profile created on the account with Netflix.

**Comment by Dev-ManishTomar** [comment]
I have 3 profiles in my account and none of them open

**Comment by ZhichGaming** [comment]
Did you delete the first profile created on that account?

**Comment by Dev-ManishTomar** [comment]
May be but it's very unlikely

**Comment by JoseMoreville** [comment]
I don't think this is a problem related to how PlayCover makes the .app to work, maybe it's a limitation of the catalyst framework

**Comment by ZhichGaming** [comment]
Can any of you try using Sideloady to run Netflix to see if that works?

**Comment by singhalrishi27** [comment]
I've Also Noticed it..

**Comment by singhalrishi27** [comment]
> I don't think this is a problem related to how PlayCover makes the .app to work, maybe it's a limitation of the catalyst framework

nahhh app works fine with SIP Disabled

**Comment by Dev-ManishTomar** [comment]
> 

I did, but Netflix app didn't even start using sideloadly.

**Comment by Dev-ManishTomar** [comment]
> nahhh app works fine with SIP Disabled

what happens when you Re-Enable SIP.

**Comment by singhalrishi27** [comment]
> I did, but Netflix app didn't even start using sideloadly.

use play cover to sideload

> what happens when you Re-Enable SIP.

you can't choose profile it will return login error

**Comment by stek29** [comment]
it was fixed in #406

you can also override default.yaml without building PlayCover from source
so you can copy `PlayCover.app/Contents/Resources/default.yaml` to `~/.config/PlayCover/default.yaml`, and add changes from #406 to get Netflix to work.

**Comment by singhalrishi27** [comment]
> it was fixed in #406
> 
> you can also override default.yaml without building PlayCover from source so you can copy `PlayCover.app/Contents/Resources/default.yaml` to `~/.config/PlayCover/default.yaml`, and add changes from #406 to get Netflix to work.

is there any guide?
