### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by parth1241** [PlayCover/PlayCover#255]
### Describe the bug

The file “ldid” doesn’t exist.

### Steps to reproduce

I just intstalled Instagram with the .ipa file 

### Expected behaviour

it should launch

### Crash log

```shell
didn't pop up
```

### What version of PlayCover are you using?

1.1.1

### What version of macOS are you using?

Ventura (macOS 13)

### Issue Language

- [X] Yes my issue is written in English

**Comment by ZhichGaming** [comment]
Are you sure you are using 1.1.1? ldid is only needed for 1.0.6 I think. Can you send a screenshot of the error?

**Comment by JoseMoreville** [comment]
Please, provide a title when you submit an issue, that way we can figure out something before entering the issue

**Comment by parth1241** [comment]
m sorry for the inconvenience 
I tried on 1.1.1 too but it just won't launch
with sip enabled and disabled both

**Comment by ZhichGaming** [comment]
Please give more details about how it does not work in 1.1.1. Does it crash? If so then does it give a crash log? Where did you get your IPA?

**Comment by Depal1** [comment]
Try again after deleting all the following:
(**Warning** this will erase all PlayCover installed apps and their settings. This is a very crude way of potentially solving the issue.)
```
    "~/Library/Application Support/io.playcover.PlayCover",
    "~/Library/Caches/io.playcover.PlayCover",
    "~/Library/Containers/io.playcover.PlayCover",
    "~/Library/Frameworks/PlayTools.framework",
    "~/Library/Preferences/io.playcover.PlayCover.plist",
    "~/Library/Saved Application State/io.playcover.PlayCover.savedState",
    "~/Library/Application Support/me.playcover.PlayCover",
    "~/Library/Caches/me.playcover.PlayCover",
    "~/Library/Containers/me.playcover.PlayCover",
    "~/Library/Preferences/me.playcover.PlayCover.plist",
    "~/Library/Saved Application State/me.playcover.PlayCover.savedState",
```
