### ISSUE TITLE
[Bug]: After keyboard mapping, the mouse doesn't work.

### ISSUE THREAD

**Issue by py14551** [PlayCover/PlayCover#259]
### Describe the bug

After keyboard mapping, the mouse doesn't work.

### Steps to reproduce

After keyboard mapping, the mouse doesn't work.

### Expected behaviour

After the keyboard mapping, the mouse is OK under version 1.0.4.

### What version of PlayCover are you using?

1.1.1

### What version of macOS are you using?

Monterey (macOS 12)

### Issue Language

- [X] Yes my issue is written in English

**Comment by JoseMoreville** [comment]
You need to add a mouse mapping, there's a mouse icon when you want to add a keymap, select that option

**Comment by py14551** [comment]
I didn't find an icon for mouse mapping.
Is it in game or in playcover？

**Comment by JoseMoreville** [comment]
Game, please check docs

**Comment by py14551** [comment]
Maybe there is a problem with my expression. It should be said that after the keyboard mapping is completed, the mouse pointer disappears. If the keyboard mapping function and the mouse pointer click work at the same time.

**Comment by JoseMoreville** [comment]
Could be but it's also 3AM, so i might be reading wrong hahaha. just in case press the opt key or please go to discord on help channel

**Comment by jiemi** [comment]
same problem

**Comment by ohaiibuzzle** [comment]
The keyboard and mouse binding must both be active at the same time, so even if you bind nothing to your mouse, it will most likely disable the normal pointer in keymap mode, and you have to press Option to switch between mouse pointer and joystick mode
