### ISSUE TITLE
[Feature]: Add App Delete Confirmation 

### ISSUE THREAD

**Issue by amirsaam** [PlayCover/PlayCover#261]
### Is your feature request related to a problem?

Yes (not literally), I miss-clicked that option multiple times 🥴

### Describe the solution you'd like

A pop-up with two button for confirming:
- Cancel
- Yes, Delete

### Anything else?

I dunno if this option implemented in 2.0-UI already or not while its beta has not been released, so I opened an issue for it.

### Issue Language

- [X] Yes my issue is written in English

**Comment by IsaacMarovitz** [comment]
This will be added in 2.0 UI

**Comment by amirsaam** [comment]
PR #322 added this feature, so I close this request.
