### ISSUE TITLE
[Bug]: can't login

### ISSUE THREAD

**Issue by idk2233** [PlayCover/PlayCover#264]
### Describe the bug

I do the steps to get Genshin impact on my laptop and it works fine until Genshin just refuses to let me login, Ive made sure the login info is correct and made sure I followed the directions right and it still didn't let me login (there was no error message it just said analysing and then failed) but if I did login with twitter it works but its a new account. I disabled SIP and inputed boot-args twice (restarted after both) before coming to this issue.

https://user-images.githubusercontent.com/112288815/187051467-a383c987-3e2f-43c5-8a6c-9e48d01422f1.mov

### Steps to reproduce

Idk I followed the steps and it worked up until the point of logging into Genshin

### Expected behaviour

to be able to login 

### What version of PlayCover are you using?

1.1.1

### What version of macOS are you using?

Ventura (macOS 13)

### Issue Language

- [X] Yes my issue is written in English

**Comment by ZhichGaming** [comment]
Please add a valid title, valid steps to reproduce and more details, like if you inputed nvram boot-args and disabled SIP.

**Comment by ohaiibuzzle** [comment]
Have you enabled PlaySign within the GUI (the "Experiencing issues?" button)?

**Comment by ZhichGaming** [comment]
Try another build while waiting. There is an issue about this in #29 so you can try using 1.0.4 in the PlayVault archives. There will be a lot of missing features and you may need to reinstall your app, but here are the instructions to use it: ﻿
[] - **Command + Space** on your keyboard  
﻿[] - Type `Terminal`  
﻿[] - Type or copy+paste the following commands:  
﻿```chmod -R +x /Applications/PlayCover.app  
﻿xattr -cr /Applications/PlayCover.app 
codesign --force --deep --sign - /Applications/PlayCover.app  ```

**Comment by Druidss** [comment]
same, Genshin ver 3.0, palycover ver 1.1.1.

**Comment by ZhichGaming** [comment]
> same, Genshin ver 3.0, palycover ver 1.1.1.

Did you read the documentation?

**Comment by zaerald** [comment]
Here's the [documentation](https://docs.playcover.io/getting_started/troubleshoot_login.html#troubleshoot-app-login-issues).

**Comment by ex18228** [comment]
Hi I got the same issue... anyone come up with solutions?

**Comment by sonye232** [comment]
I have the same problem

**Comment by Amachik** [comment]
Update to latest version of playcover

**Comment by MEMORIEmusic** [comment]
Please read the documentations carefully. The fix has already been written in there

**Comment by Kusano13** [comment]
i fixed it with the help of playcover discord

**Comment by Kusano13** [comment]
1. Disable SIP
➤ This can be done by shutting down your mac, holding down power button
➤ After this, click on your username/ssd, then keep going until you can see Utilities at the top
➤ When you see this, click on it and click on Terminal
➤ After this, you should be in a terminal window
➤ Type csrutil disable in that terminal window
➤ It will ask for your mac username, type it and press return
➤ Then if will ask for that user's password, type it and press return
➤ Your password will not be shown on screen, so don't panic!
➤ Click on Apple logo on the top and Restart your mac
2. Allow the nvram boot-args
➤ When you have SIP Disabled (this command only works with SIP disabled), do the following steps:
➤ Command + Space; type "Terminal" in the search box
➤ It should open a normal terminal window
➤ Type the following in this window (or copy paste it)
sudo nvram boot-args="amfi_get_out_of_my_way=0x1 ipc_control_port_options=0"

➤ If it appears that nothing has happened, this is correct.
➤ Now restart your Mac once again
3. Login to Genshin
➤ Open Genshin Impact with PlayCover, and you should be greeted with a Login button
➤ Login to your account, then wait until the door appears and quit the game with Command + Q
➤ Thats all which is required in Genshin for now
4. Enable SIP Again
➤ Shut down your Mac again
➤ Hold down the power button until you get to recovery options
➤ Click on your username and your storage disk respectively like you did for step 1.
➤ You should see Utilities at the top
➤ Click on it, and Click on Terminal
➤ In terminal, type the following: csrutil enable
➤ csrutil clear should also work
➤ Reboot your Mac by going to Apple Logo>Restart
5. Open Genshin
➤ You're done! Enjoy playing genshin!

**Comment by Kusano13** [comment]
this is the whole instruction, it worked for me so hope it does the same for u

**Comment by Kusano13** [comment]
Credit to the playcover discord, plz join it is very useful

**Comment by 623637646** [comment]
This works for me https://github.com/PlayCover/PlayCover/issues/234#issuecomment-1262251786
