### ISSUE TITLE
[Bug]: Can't open Signal With SIP Enabled 

### ISSUE THREAD

**Issue by singhalrishi27** [PlayCover/PlayCover#265]
### Describe the bug

A Popular chatting app Signal which is open-source By The Way! can't be used after enabling SIP. The app works fine when SIP is Disabled which prevents other apps from running properly downloaded from the app store.

### Steps to reproduce

1.) Download Signal From ARM Converter.
2.)Disable SIP and Install it using Using PlayCover.
3.)Create Account and Setup the app.
4.)Enable SIP.
5.)The App wont Launch

### Expected behaviour

The App Sholudn't Crash.

### Crash log

```shell
https://debuglogs.org/ios/5.49.0/f8fd10f9cca9047a8b033fd783053cd5458f688c219b2864f606e385df1a3c7d.zip
```

### What version of PlayCover are you using?

1.1.1

### What version of macOS are you using?

Ventura (macOS 13)

### Issue Language

- [x] Yes my issue is written in English

**Comment by ZhichGaming** [comment]
I think you mean "Enable SIP" at step 4, but there was an issue about this if I recall correctly.

**Comment by ZhichGaming** [comment]
Did you try enabling jailbreak detection bypass in PlayCover? And did you try entering boot-args? Try reinstalling signal with AppCleaner.

**Comment by singhalrishi27** [comment]
> Did you try enabling jailbreak detection bypass in PlayCover? And did you try entering boot-args? Try reinstalling signal with AppCleaner.

yup did it when i enable jailbreak bypass it gives storage error
<img width="1470" alt="Screenshot 2022-08-28 at 10 41 11 AM" src="https://user-images.githubusercontent.com/67616808/187058585-8cf49a3b-3de9-43b0-a7ac-3dfc1db44657.png">


This error happens even with Disabled System Integrity Protection i think its bug in Jailbreak detection Bypass.

**Comment by singhalrishi27** [comment]
> Did you try enabling jailbreak detection bypass in PlayCover? And did you try entering boot-args? Try reinstalling signal with AppCleaner.

Which boot args?

**Comment by ZhichGaming** [comment]
> > Did you try enabling jailbreak detection bypass in PlayCover? And did you try entering boot-args? Try reinstalling signal with AppCleaner.
> 
> 
> 
> Which boot args?
> 
> 

Nvram boot args. You can get instructions on that in our documentation.

**Comment by IsaacMarovitz** [comment]
@singhalrishi27 Has the issue been resolved?

**Comment by singhalrishi27** [comment]
> @singhalrishi27 Has the issue been resolved?

nope

**Comment by ZhichGaming** [comment]
Have you tried boot-args yet? `sudo nvram boot-args="amfi_get_out_of_my_way=0x1 ipc_control_port_options=0"`
<img width="522" alt="Screen Shot 2022-09-24 at 11 17 45" src="https://user-images.githubusercontent.com/93055907/192105759-c0e29190-6ed4-45de-b7b0-289720285586.png">

**Comment by singhalrishi27** [comment]
> Have you tried boot-args yet? `sudo nvram boot-args="amfi_get_out_of_my_way=0x1 ipc_control_port_options=0"` <img alt="Screen Shot 2022-09-24 at 11 17 45" width="522" src="https://user-images.githubusercontent.com/93055907/192105759-c0e29190-6ed4-45de-b7b0-289720285586.png">

I'm no longer on signal

**Comment by ZhichGaming** [comment]
Ah I see.
