### ISSUE TITLE
[Feature]: Add continue to game option to "you may be banned" warning

### ISSUE THREAD

**Issue by CompactLethargy13** [PlayCover/PlayCover#267]
### Is your feature request related to a problem?

When trying to play games like codm or pubg, there is a warning with no continue option that you may be banned. 

### Describe the solution you'd like

Id like a button so that i can play codm if i can accept the fact that my account may be banned. 

### Anything else?

NIL

### Issue Language

- [X] Yes my issue is written in English

**Comment by JoseMoreville** [comment]
Please check pinned issue
