### ISSUE TITLE
[Bug]: Can't open the app

### ISSUE THREAD

**Issue by CoolJosh0221** [PlayCover/PlayCover#269]
### Describe the bug

<img width="257" alt="Screen Shot 2022-08-29 at 12 12 36 PM" src="https://user-images.githubusercontent.com/88709160/187122542-dbf319cf-f8fb-49a4-bc80-dd8232bd77f2.png">
This picture describes all

### Steps to reproduce
(My SIP is off)
1. I uninstalled the old version of playcover
2. I installed the newest version of playcover
3. I download the .ipa file and install the app
4. When i open it, here comes the error message

Can't open the app as above

### Expected behaviour

It should work normally

### Crash log

```shell
Where is the log?
```

### What version of PlayCover are you using?

1.1.1

### What version of macOS are you using?

Monterey (macOS 12)

### Issue Language

- [x] Yes my issue is written in English

**Comment by ZhichGaming** [comment]
More detail is needed. You did not indicate when this pops up.

**Comment by CoolJosh0221** [comment]
> More detail is needed. You did not indicate when this pops up.

Ok I updated it

**Comment by ZhichGaming** [comment]
Did you try reinstalling your app?

**Comment by CoolJosh0221** [comment]
> Did you try reinstalling your app?

yep

**Comment by CoolJosh0221** [comment]
i tried two ipas and none of them work

**Comment by ZhichGaming** [comment]
Both Genshin impact and PlayCover? Where did you get your IPAs from?

**Comment by CoolJosh0221** [comment]
> Both Genshin impact and PlayCover? Where did you get your IPAs from?

IPA:
https://ipa.decrypt.day/
and
discord.gg/8SXCXbzzBe

both don't work

Playcover:
https://github.com/PlayCover/PlayCover/releases/download/1.1.1/Playcover_1.1.1.dmg

**Comment by ZhichGaming** [comment]
Can you record a video of your issue? This is really not enough for me to go on.

**Comment by CoolJosh0221** [comment]
https://user-images.githubusercontent.com/88709160/187131413-231d06c1-53ee-49f2-a87e-252ddd9955e6.mp4

**Comment by ZhichGaming** [comment]
This is wierd, did you ever succeed opening Genshin impact? The IPA may be corrupted. Use a download manager to download the ipa again.
