### ISSUE TITLE
[Bug]: malformed object (load command 95 cmdsize not a multiple of 8)

### ISSUE THREAD

**Issue by lunjielee** [PlayCover/PlayCover#271]
### Describe the bug

can't install certain ipa files with PlayTools, logs attached

`/Applications/Xcode-beta.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/install_name_tool: object: /Users/myusername/Documents/PlayCoverInstall/tmp/0F246BC7-4A31-4517-9F56-8501181D42BE/Payload/firenow.app/Frameworks/UnityFramework.framework/UnityFramework malformed object (load command 95 cmdsize not a multiple of 8)`

### Steps to reproduce

drag pre-modified ipa files by iOSGods to Playcover, installation process will abort when installing Playtools to the extracted app file

### Expected behaviour

install without error

### Crash log

```shell
https://gist.github.com/lunjielee/b64b47c792cc80002b98527f956354e7
```

### What version of PlayCover are you using?

Nightly/beta

### What version of macOS are you using?

Ventura (macOS 13)

### Issue Language

- [X] Yes my issue is written in English

**Comment by ZhichGaming** [comment]
Tweaked IPAs currently do not work.

**Comment by lunjielee** [comment]
> Tweaked IPAs currently do not work.

<img width="442" alt="Screenshot 2022-08-29 at 4 58 01 PM" src="https://user-images.githubusercontent.com/32808108/187297650-016c2ce6-3d91-4285-9c98-1664edaec9af.png">
PlayCover Version 1.0.4 (1) installed without a problem

**Comment by ZhichGaming** [comment]
How does it run?

**Comment by lunjielee** [comment]
> How does it run?
<img width="754" alt="Screenshot 2022-08-29 at 5 08 36 PM" src="https://user-images.githubusercontent.com/32808108/187299507-fde1f232-62af-4af4-af1f-756ed291ae64.png">

Working fine, only issue is that you can't log in to the GameCenter

**Comment by ZhichGaming** [comment]
I see, we will have to see what changed from iVoider's 1.0.4.

**Comment by lunjielee** [comment]
Just tried the first community build [Release 1.0.6](https://github.com/PlayCover/PlayCover/releases/tag/1.0.6), that's where the problem begins

> I see, we will have to see what changed from iVoider's 1.0.4.

Sure, thank you for your time and effort

**Comment by JoseMoreville** [comment]
It might be a ventura problem, please keep using on monterey

**Comment by lunjielee** [comment]
Problem solved with the latest Xcode 14 RC1(14A309), should be a problem related to the beta version of Xcode.
