### ISSUE TITLE
[Feature]: Use 'appdecrypt' for encrypted apps

### ISSUE THREAD

**Issue by Oct4Pie** [PlayCover/PlayCover#272]
### Is your feature request related to a problem?

The installation is aborted when `cryptid 1`.

### Describe the solution you'd like

Using appdecrypt to decrypt encrypted ipa

### Anything else?

I believe that the first versions of PlayCover used ipatool and then decrypted the ipa on device.
Finding decrypted ipa for some apps can be very difficult, especially now with the jailbreak situation.
I am not sure if the kernel will reject if platform is not iOS.
If any info is known how the earlier versions did this, I can volunteer to implement it.

### Issue Language

- [X] Yes my issue is written in English

**Comment by Candygoblen123** [comment]
Appdecrypt does not work on macOS versions 11.3 and up.
