### ISSUE TITLE
[Game Support]: Cookie Run Kingdom is crashed after 10s

### ISSUE THREAD

**Issue by b10102016** [PlayCover/PlayCover#274]
### App Store link

https://apps.apple.com/us/app/cookie-run-kingdom/id1509450845

### Current issues

- [ ] Game fails to install
- [X] Game fails to open
- [X] Game crashes randomly during gameplay
- [ ] Game does not work with keymapping
- [ ] Game experiences graphical issues or broken UI
- [ ] Game fails to connect to servers or complete download

### More details

When open the game, it works well in first 10 seconds.
After about 10 seconds, the game is exit without any message

### Issue Language

- [X] Yes my issue is written in English

**Comment by JoseMoreville** [comment]
This game is not currently supported

**Comment by b10102016** [comment]
Hi @JoseMoreville,

May I ask for the reason? I can help to collect log, but I don't know where to find the log.

Thanks
