### ISSUE TITLE
[Feature]: Keymapping + mouse control

### ISSUE THREAD

**Issue by crayton** [PlayCover/PlayCover#277]
### Is your feature request related to a problem?

currently when the key-mapping is enabled. Mouse control will turn off.
possible making both working in the same time?

### Describe the solution you'd like

-

### Anything else?

-

### Issue Language

- [X] Yes my issue is written in English

**Comment by ZhichGaming** [comment]
This is already a feature, just enable Gaming Mode in app settings and you will be able to use both at the same time.

**Comment by jiemi** [comment]
In the latest version, when turn on game mode, Mouse control still will turn off when the key-mapping is enabled

**Comment by jiemi** [comment]
I made a mistake.I just found only canceling the game mode  make both working in the same time
