### ISSUE TITLE
[Feature]: keymapping + mouse [multi-touch support]

### ISSUE THREAD

**Issue by crayton** [PlayCover/PlayCover#278]
### Is your feature request related to a problem?

currently, keymapping touch from the keyboard will interupt mouse control each other.
Hope the keyboard keymapping and mouse control have own uninterrupted touch. (multi touch)

### Describe the solution you'd like

-

### Anything else?

-

### Issue Language

- [X] Yes my issue is written in English

**Comment by JoseMoreville** [comment]
Can you give me more context for this issue?

**Comment by crayton** [comment]
let say 
left finger touch = keyboard
right finger touch = mouse

when we touching the screen moving the character, on the same time we firing the skill/ button with right finger. It do interrupt/end the left finger touch.
I think it is because 2 interactions is sharing one touch pointer. When second touch (either mouse or keyboard) take place, it will stop the previous control and overlapped it. I think the problem can be solved by each touch come with standalone object.

**Comment by ZhichGaming** [comment]
What game are you playing for you to need those 2 at the same time?

**Comment by crayton** [comment]
Game : Ragnarok Mobile
I believe pubg games also have the same problem. Current it just take 1 input in a time.
You can imaging the concept like control with xbox joystick.
Left analog for moving the character, right analog moving the angle of camera. Both input is not interrupt each other in the same time.

I just tested, keyboard input is multitouch (can touch multiple buttons in the same times uninterupted ). but the mouse input will end the keyboard input.

**Comment by ZhichGaming** [comment]
For PUBG games, you can just activate Gaming Mode. It is possible to control the camera angle with Gaming Mode on and if you need access to menus and similar things, just press option to toggle the cursor. You can try that out for your game and see if it works for you, since I do not know what Ragnarok Mobile is.

**Comment by crayton** [comment]
possible to make the mouse touch = keyboard like touch?(I just tested, keyboard touch can be multiple input in the same time) it will be perfect for competitive games like able to moving the character in the same time adjusting cursor input without the toggle option.

Concept : mouse curser = live moving keymapping

**Comment by ZhichGaming** [comment]
You don't understand, it is currently possible to adjust the screen with gaming mode and keymapping mode on. You can add a mouse area, which is like dragging the screen around.

**Comment by crayton** [comment]
I understand it. But that will make mouse click not usable. At least, without pressing the option key which will interupt the keymapping. 
Hope have an option, keymapping on + free to use mouse click and drag on the same time able to click on any elements on the screen.

**Comment by ZhichGaming** [comment]
Yes, I agree with you. There will be a new version of playtools that will maybe be on the nightly build tomorrow that implements a whole new system for keymapping. It will maybe work in that build but no guarantees.

**Comment by crayton** [comment]
We appreciate that very much, good work guys!

**Comment by XuYicong** [comment]
https://cdn.discordapp.com/attachments/996713647827066981/1013902534584320000/draggableButton.mp4

Is this what you want?

**Comment by crayton** [comment]
> https://cdn.discordapp.com/attachments/996713647827066981/1013902534584320000/draggableButton.mp4
> 
> Is this what you want?

nope, what I want is mouse can freely input( with cursor and click/touch ) like the video in your screen(right part in the video) while your left character control by the keyboard. 

if you use LDplayer android emulator before, that is exact how they handling the keymapping and mouse input, they both working simultaneously, and the mouse cursor is free going anywhere. This method will cover wide range of supported games, the current gaming mode is awesome as well, but it is just to specifically design for certain game.

**Comment by XuYicong** [comment]
You just said the reason you need free mouse is to freely use in-game skills while moving. How cannot the mapping type in the video satisfy your requirement? Using keyboard to fire skills is even faster than moving the cursor to find the skill button, especially in your competitive games where reaction time matters.

**Comment by crayton** [comment]
The problem(keyboard and mouse interrupt each other) comes when i want to use the mouse moving and control the character(either mouse drag and click to move switching seemlessly ), while my keyboard input (keymapping) use to do the skill buttons. 
The core issues is when the game need your mouseclick-to-move to the certain map location or screen location at the same time use mouse drag to changing their position.

Gaming mode off with uninterupted touch and click will be perfectly solved my problem.

**Comment by XuYicong** [comment]
So your game is different from PUBG in the operation methods, right? In PUBG we move by a joystick and rotate camera by dragging the screen, and these operations do not need a free mouse. But in your game there is no joystick or camera rotation, but instead your whole screen is a 2D map, you click somewhere on the map to let the character move to that point, is it? In addition to that, you have some operation that needs to drag on the screen while moving the character, or in other words if it were to be played on a touch screen device it would need two fingers with one touching arbitrary point on the screen and the other dragging at the same time?

**Comment by crayton** [comment]
correct, PUBG or Csgo is default by mouse dragging for camera angle and click for fire.
Some game will like PC gaming RPG keyboard and mouse dragging (manually by user click to drag) and that is good for clicking the game UI like mission or in game elements (door items and so on)

**Comment by XuYicong** [comment]
I see, your game needs to click on arbitrary point on the screen while holding or dragging other buttons. But to achieve this needs some architectural modifications of some low level code, which may not happen very soon. You may have to wait some time before this get added.

**Comment by guendev** [comment]
PUBG huh? I thought, we cant play PUBG with Playcover. I got banned before.

**Comment by ZhichGaming** [comment]
Yeah, you will most probably be banned on most FPS games with an anticheat if you play them on PlayCover.

**Comment by crayton** [comment]
2.0 is freaking awesome good work guys! love it

**Comment by 35MMM** [comment]
> 2.0 is freaking awesome good work guys! love it

can help me how to solve this problem too? I'm using Playcover 2.0 but seems the update same as your problem here
