### ISSUE TITLE
[Feature]: How to resize the game window

### ISSUE THREAD

**Issue by hcg1023** [PlayCover/PlayCover#279]
### Is your feature request related to a problem?

I opened <<金铲铲之战>> and found that the game window is fixed and cannot be zoomed out

### Describe the solution you'd like

window can be resized

### Anything else?

---

### Issue Language

- [X] Yes my issue is written in English

**Comment by ZhichGaming** [comment]
Custom resolution is already implemented, window resize has been removed because of various issues with it.
