### ISSUE TITLE
[Bug]: Keymappinng is more and more unstable 

### ISSUE THREAD

**Issue by 47thforce** [PlayCover/PlayCover#284]
### Describe the bug

Keymapping is very laggy, sometimes unusable even in low load

### Steps to reproduce

Genshin Impact with no modifications in PlayCover settings, with no 3rd party apps running in background, all is freshed
(M1 Macbook Air, 8GPU 16GB RAM, Razer magsafe thermal fan and thermal pad is equipped)

### Expected behaviour

after logging in about 10 minutes, the keymapping is becoming so laggy. cmd+tab can use again, but for a short moment. sometimes even freeze and unusable.

also happended with grayraven and beta of Star Rail. All with medium settings

### What version of PlayCover are you using?

1.1.1

### What version of macOS are you using?

Monterey (macOS 12)

### Issue Language

- [X] Yes my issue is written in English

**Comment by Depal1** [comment]
Please use a the latest nightly build with the M1 iPad model identifier and try again.
