### ISSUE TITLE
[Bug]: Duolingo | Learn dashboard freezes app

### ISSUE THREAD

**Issue by EmilianoTalamo** [PlayCover/PlayCover#289]
### Describe the bug

Duolingo seems to be working mostly fine, I'm using the version 6.177.0.4 of the app.

I've been able to login and even practice excercises, but when the 'learn' dashboard renders, the app freezes and you can't interact at all, even after restarting the app.
It's pretty annoying because this seems to be the only thing that keeps the app from working perfectly. 

My best guess is that there's some kind of modal or popup that is not loading properly or preventing any user interaction. When you do a fresh start of the app, you can scroll through the dashboard for a split second until a tiny black flash appears that locks you out completely:

https://user-images.githubusercontent.com/12476222/188289888-ec26a628-4451-405f-a375-591b52042fb4.mp4

### Steps to reproduce

* Install Duolingo.
* Open Duolingo.
* Login.
* Do the daily practice or any excercise that the app offers you when you open it.
* Restart the app.
* You should be taken straight to the dashboard.
* You won't be able to interact with the app anymore.

### Expected behaviour

Being able to pick excercises from the learn dashboard or navigate through the app.

### What version of PlayCover are you using?

1.1.1

### What version of macOS are you using?

Monterey (macOS 12)

### Issue Language

- [X] Yes my issue is written in English

**Comment by ZhichGaming** [comment]
Did you try disabling SIP and inputting NVRAM tags?

**Comment by EmilianoTalamo** [comment]
> Did you try disabling SIP and inputting NVRAM tags?

Same behaviour with SIP disabled and nvram boot-args. Even with a clean reinstall of the *.ipa

**Comment by ZhichGaming** [comment]
What about with jailbreak bypass enabled?

**Comment by EmilianoTalamo** [comment]
> What about with jailbreak bypass enabled?

With jailbreak bypass it crashes instantly.

<img width="372" alt="image" src="https://user-images.githubusercontent.com/12476222/188297005-2e5eaf97-22f1-40ad-b139-51ea0572dcef.png">

**Comment by ohaiibuzzle** [comment]
Open a terminal then type `open /Applications/PlayCover.app/Contents/Resources`, then dump the content of [this](https://github.com/PlayCover/PlayCover/blob/develop/PlayCover/Rules/default.yaml) file into `default.yaml`

This will temporarily fix jailbreak detection

**Comment by ZhichGaming** [comment]
> Open a terminal then type `open /Applications/PlayCover.app/Contents/Resources`, then dump the content of [this](https://github.com/PlayCover/PlayCover/blob/develop/PlayCover/Rules/default.yaml) file into `default.yaml`

What does that file do? Does it vary for different apps? And if yes, how do I know what to modify if I want to do that?

**Comment by ohaiibuzzle** [comment]
Refer to #260 for the details. This is a very general profile used for all apps. Doing those steps simply replace it with the one from develop which is less broken than the release one.

**Comment by ZhichGaming** [comment]
I see, thank you very much.

**Comment by EmilianoTalamo** [comment]
> Open a terminal then type `open /Applications/PlayCover.app/Contents/Resources`, then dump the content of [this](https://github.com/PlayCover/PlayCover/blob/develop/PlayCover/Rules/default.yaml) file into `default.yaml`
> 
> This will temporarily fix jailbreak detection

Thank you! Now Duolingo opens with jailbreak bypass, but it keeps freezing in the dashboard.

**Comment by ohaiibuzzle** [comment]
That appears to be the intro video for the New Duolingo Experience opening as a layer on top of the app.
Works fine on my machine however, try toggling notifications for Duolingo, and make sure you have an internet connection that can handle a bit of video streaming

**Comment by EmilianoTalamo** [comment]
> That appears to be the intro video for the New Duolingo Experience opening as a layer on top of the app. Works fine on my machine however, try toggling notifications for Duolingo, and make sure you have an internet connection that can handle a bit of video streaming

Yeah, I figured it was some kind of video not working properly. The weird part is that the in-between video ads between challenges work fine.

Anyway, I updated my Duolingo to a different version and it seems to be working properly, at least for now... so maybe it was a specific bug of that version (or a broken ipa, I don't know).

I'll close this issue, thank you for your support!
