### ISSUE TITLE
V1.1.1 playcover cannot use image verification in Genshin Impact, but downgrade to V1.0.4 playcover can

### ISSUE THREAD

**Issue by sheaahhoi1** [PlayCover/PlayCover#29]
V1.0.6 playcover cannot use image verification in Genshin Impact, but downgrade to V1.0.4 playcover can.
request to test this issue

**Comment by JoseMoreville** [comment]
@sheaahhoi1 Can you explain me more about this problem so i can look up for a fix or a solution?

**Comment by sheaahhoi1** [comment]
@JoseMoreville 
Genshin Impact login method The original author of playcover has an instructional video. When you log in to the account number on a new device, a picture verification will appear.
The tests of playcover 1.0.6&1.0.4 are all in the video
[https://youtu.be/ptnfNaQy9PU](url)
Videos are deleted after a few days

**Comment by sheaahhoi1** [comment]
https://youtu.be/ptnfNaQy9PU

**Comment by ohaiibuzzle** [comment]
Is it with PlaySign off or on? GeeTest has never really worked correctly with PlaySign off, so you might want to check that

**Comment by sheaahhoi1** [comment]
@ohaiibuzzle How does PlaySign start?

**Comment by JoseMoreville** [comment]
There's a button on launcher that says enable playsign

**Comment by 47thforce** [comment]
Disable System Integrity Protocol (go to recovery to do that) and restart.

Then copy and paste this command: _sudo nvram boot-args="-v cs_enforcement_disable=1 amfi_get_out_of_my_way=1 keepsyms=1 intcoproc_unrestricted=1 amfi_unrestrict_task_for_pid=1 **amfi_allow_any_signature=1 cs_debug=1**"_
and reboot again. This is the old .nvram command from 0.8.x

The new .nvram command may not work in some devices. My M2 Macbook Air still get that issue even after typing the new .nvram command, but when I type the old one, it works.

**Comment by 47thforce** [comment]
> V1.0.6 playcover cannot use image verification in Genshin Impact, but downgrade to V1.0.4 playcover can.
> request to test this issue

Disable System Integrity Protocol (go to recovery, open terminal and type **csrutil disable**) and restart.

Then copy and paste this command: _sudo nvram boot-args="-v cs_enforcement_disable=1 amfi_get_out_of_my_way=1 keepsyms=1 intcoproc_unrestricted=1 amfi_unrestrict_task_for_pid=1 amfi_allow_any_signature=1 cs_debug=1 ipc_control_port_options=0"_
and reboot again. This is the old .nvram command from 0.8.x

The new .nvram command (only _amfi_get_out_of_my_way=1_ and _ipc_control_port_options=0_) only get may not work in some devices. My M2 Macbook Air still get that issue even after typing the new .nvram command, but when I type the old one, it works.

**Comment by sheaahhoi1** [comment]
V1.0.7 playcover cannot use image verification in Genshin Impact,SIP is closed, the command is set, but the image verification cannot be started
https://youtu.be/ptnfNaQy9PU

**Comment by BaeBae33** [comment]
same issue

**Comment by ZhichGaming** [comment]
@BaeBae33 @sheaahhoi1 Can you please try inputting nvram boot-args `sudo nvram boot-args="amfi_get_out_of_my_way=1"` instead of `sudo nvram boot-args="amfi_get_out_of_my_way=0x1 ipc_control_port_options=0"`? It has also been reported that it would work for some if you spam login or if you use a VPN to login.

**Comment by sheaahhoi1** [comment]
@ZhichGaming test results
![ 2022-09-16 上午12 26 41](https://user-images.githubusercontent.com/10239384/190457919-8fe0f023-1583-418f-9fcf-be54a731a9d6.png)

**Comment by ZhichGaming** [comment]
You did not disable SIP. And copy paste the command instead of entering it manually.

**Comment by sheaahhoi1** [comment]
@ZhichGaming NEW test results
![IMG_1669](https://user-images.githubusercontent.com/10239384/190885618-380cf647-a86b-4e5f-a8d9-7186916a00ac.jpg)

**Comment by ZhichGaming** [comment]
Nvram has to be set in normal terminal.

**Comment by sheaahhoi1** [comment]
@ZhichGaming 
M1 Mac 
https://user-images.githubusercontent.com/10239384/190886197-0ce69caa-aa9f-4827-b81e-cbdabc96d973.mov

iPad pro
![IMG_1F4405C93CA4-1](https://user-images.githubusercontent.com/10239384/190886219-4917393a-197c-4a5d-8540-5dc30ea95d73.jpeg)

**Comment by ZhichGaming** [comment]
It looks to me that you did not restart your Mac after inputting the tags.

**Comment by sheaahhoi1** [comment]
@ZhichGaming 
The problem is solved
1. disable SIP
2. Restart Mac
3. Mac normal mode using terminal
input command
`sudo nvram boot-args="amfi_get_out_of_my_way=1"`
4. Restart Mac
5. can use image verification in Genshin Impact

**Comment by ZhichGaming** [comment]
Yep, exactly what I said. Nice.
