### ISSUE TITLE
[Game Support]: Blue Archive [EN/Global] - Stuck on File verification

### ISSUE THREAD

**Issue by mmkzer0** [PlayCover/PlayCover#296]
### App Store link

https://apps.apple.com/us/app/blue-archive/id1571873795

### Current issues

- [ ] Game fails to install
- [ ] Game fails to open
- [ ] Game crashes randomly during gameplay
- [ ] Game does not work with keymapping
- [ ] Game experiences graphical issues or broken UI
- [X] Game fails to connect to servers or complete download

### More details

The Global / EN Version of the game installs and starts without issue. It gets stuck however. After an initial short download, the Game gets stuck on "Verifying downloaded file" and stays on this step indefinitely. It however neither crashes nor locks up.

### Crash log

```shell
/Users/******/Library/Containers/io.playcover.PlayCover/bluearchive.app/bluearchive:
Load command 28
      cmd LC_BUILD_VERSION
  cmdsize 24
 platform MACCATALYST
    minos 11.0
      sdk 14.0
   ntools 0

Executable=/Users/******/Library/Containers/io.playcover.PlayCover/bluearchive.app/bluearchive
Identifier=com.nexon.bluearchive
Format=app bundle with Mach-O thin (arm64)
CodeDirectory v=20400 size=750 flags=0x2(adhoc) hashes=13+7 location=embedded
Signature=adhoc
Info.plist entries=69
TeamIdentifier=not set
Sealed Resources version=2 rules=10 files=1731
Internal requirements count=0 size=12
```

### Issue Language

- [X] Yes my issue is written in English

**Comment by Depal1** [comment]
What PlayCover version are you using?

**Comment by mmkzer0** [comment]
I tried the game both on the latest Release (1.1.1) as well as the latest Nightly (53). I also uninstalled the Game and re-installed it for each Version.

Edit: This is the screen in question the game gets stuck on

<img width="1590" alt="Screenshot 2022-09-05 at 15 38 31" src="https://user-images.githubusercontent.com/74553440/188462685-354d6c77-e883-4450-86c6-9996618ff529.png">

**Comment by KhoraLee** [comment]
I know how to fix stucking at `Verifying downloaded file`. But it will not work either because of NGSM(Nexon's anti cheat solution). Game will show alert same as MDNF(https://github.com/PlayCover/PlayCover/issues/57)

**Comment by ohaiibuzzle** [comment]
> I know how to fix stucking at `Verifying downloaded file`. But it will not work either because of NGSM(Nexon's anti cheat solution). Game will show alert same as MDNF(#57)

Any idea on what it might potentially check? I am working on an option to not inject PlayTools (so that games detecting dylibs won't get tripped), but if it is something related to the game executables, it would be a nightmare to do.

**Comment by mmkzer0** [comment]
I should also mention that the game seemingly has no Jailbreak Detection, as it works as it should on my Jailbroken [checkra1n] iPhone 6s and 7 (both which are primarily used to dump and decrypt IPAs).

That said, if there is anything I can/should test or can do, I'd be more than willing to.

**Comment by ohaiibuzzle** [comment]
> I should also mention that the game seemingly has no Jailbreak Detection, as it works as it should on my Jailbroken [checkra1n] iPhone 6s and 7 (both which are primarily used to dump and decrypt IPAs).
> 
> That said, if there is anything I can/should test or can do, I'd be more than willing to.

The issue being that it might not just be anti-cheat, but also anti-tampering

Can you try reinstalling the dumped IPA into the device and see if it still work?

**Comment by KhoraLee** [comment]
@ohaiibuzzle Oh installing decrypted ipa on real device with sideloadly also shows Illegal program detected.

**Comment by ohaiibuzzle** [comment]
> @ohaiibuzzle Oh installing decrypted ipa on real device with sideloadly also shows Illegal program detected.

Well, not Sideloadly (which signs the file again), rather, maybe try installing a patch like AppSync Unified from Cydia and install the unencrypted IPA that way. If it still trips, we know for sure that is integrity check since apps are permitted to read their executable contents

**Comment by mmkzer0** [comment]
I will try once I am back home. I will also try decrypting the IPA with different Programs.

**Comment by mmkzer0** [comment]
The dumped IPA cannot open on my iPhone 7 after I re-installed it, but that may be an issue with my iPhone. I will try with my 6s as well.

Another thing. I downloaded the Japanese Version on my iPhone 7 to decrypt and play around with. The JP Version however detects my iPhone being jailbroken and closes the game after a short time with "Illegal Program detected" and closes. That did not stop me from dumping it however. A-Bypass and KernBypass were also unable to fool the Game.

Now here is the weird thing: the JP Version installs without issue with PlayCover, opens, downloads assets, and can be played. It needs the Jailbreak Bypass Option set, otherwise the Game will throw an "Illegal Program detected" exception, and then just works.

So, the JP and Global Version must differ in some tangible way when it comes to their JB detection.

**Comment by ZhichGaming** [comment]
Blue Archive JP has been fixed in version 1.0.6 by Lucus but I don't think Blue Archive EN ever worked.

**Comment by KhoraLee** [comment]
Yes JP version is whole different game. It uses XignCode for anti-cheat solution not NGSM.

**Comment by Helloyunho** [comment]
same with the korean version

**Comment by Helloyunho** [comment]
okay so I somehow managed to get over the verification but now it gets killed with the error 'NexonNgsmValidateFail' and `Illegal program has been detected`

<img width="1590" alt="CleanShot 2022-12-28 at 12 22 27@2x" src="https://user-images.githubusercontent.com/10192625/209767424-f3e0e4d8-1a69-41c0-96b9-04d29ba45b7c.png">
<img width="1590" alt="CleanShot 2022-12-28 at 12 22 29@2x" src="https://user-images.githubusercontent.com/10192625/209767433-92752136-65d3-41f3-a3ed-369b017ece48.png">

**Comment by ohaiibuzzle** [comment]
I wrote an absolutely terrifying hax to get around it. Unfortunately it seems like it might be too dirty at this point in time to get merged

**Comment by Helloyunho** [comment]
it's good to hear that you at least got a way to pass the NGSM

**Comment by IsaacMarovitz** [comment]
Not planned unless a suitable patch is proposed

**Comment by Helloyunho** [comment]
even though this issue is closed I'm still trying to bypass NGSM so if anyone can help me please do

**Comment by Riinka2803** [comment]
<img width="1680" alt="Ảnh màn hình 2023-06-28 lúc 12 40 49" src="https://github.com/PlayCover/PlayCover/assets/138097976/4d7a940c-5e34-4b68-bac5-103518fa2231">
i use playcover 3.0 beta and have this ....,pls help me

**Comment by ewof** [comment]
can we get spoonfeed guide or something on how to use the dirty hack i just wanna play ba
