### ISSUE TITLE
[Bug]: Key Reg issue

### ISSUE THREAD

**Issue by soohyeok** [PlayCover/PlayCover#298]
### Describe the bug

However for keyboard keys, other than option +K and LShift, no key registers
I cannot create a new key by pressing button on my keyboard (both bluetooth and built-in keyboard)
I attempted to import a keymap but other than "Lshift" and "option + K"

- SIP instruction was followed for login
- Genshin loads well, (with login), and cursor is usable (click)
- Keymap shortcut option + K works, I am able to create new button and map them but no key registers for keys on keyboard other than L shift

### Steps to reproduce

- Installed newest public version [Release 1.1.1 Hotfix](https://github.com/PlayCover/PlayCover/releases/tag/1.1.1)
- Followed instructions on documentation for login and re-enabled SIP
- restarted and loggin in to genshin
- attempted to press keyboard keys & also tried to use imported keymap

### Expected behaviour

WASD, E, Q, etc keys should work but does not

### What version of PlayCover are you using?

1.1.1

### What version of macOS are you using?

Monterey (macOS 12)

### Issue Language

- [X] Yes my issue is written in English

**Comment by XuYicong** [comment]
Try the latest nightly builds, might have fixed the issue.

**Comment by soohyeok** [comment]
Just tried the latest nightly build :/
does not seem to work..
It's so weird because all UTF character keys do not reg on key mapping or trigger a key
yet I can still type for logging in and when I navigate to chat

**Comment by ZhichGaming** [comment]
Are you using an external keyboard/another keyboard type than english QWERTY?

**Comment by soohyeok** [comment]
> Are you using an external keyboard/another keyboard type than english QWERTY?

I am using english keyboard. I have even removed my extra language keyboards to double check.
Also I have attempted to use both built in keyboard on my macbook and a bluetooth keyboard
but in both cases QWERTY does not reg in keymap
I can still type in chat though ;( after navigating with clicks with mouse / touchpad

Only keys that registers for me on the keyboard for key mapping are caps lock and Lshift Rshift
and I can also trigger the keymap menu via option + K

**Comment by soohyeok** [comment]
Only keys that registers for me on the keyboard for key mapping are caps lock and Lshift Rshift
and I can also trigger the keymap menu via option + K

**Comment by soohyeok** [comment]
Sorry -_- ... i happened to recall that I was using a keylogger disruptor...
my bad
