### ISSUE TITLE
[Bug]: Unable to log in to genshin 

### ISSUE THREAD

**Issue by plsdontyell** [PlayCover/PlayCover#301]
### Describe the bug

Even though I followed all the instructions (disabling sip & nvram + restarting) im still not able to log in,  

### Steps to reproduce

im not sure what the problem is but it seems to be something to do with my computer

### Expected behaviour

being able to log in after completing all the steps 

### What version of PlayCover are you using?

1.1.1

### What version of macOS are you using?

Monterey (macOS 12)

### Issue Language

- [X] Yes my issue is written in English

**Comment by ugzhu** [comment]
Same problem, disabled SIP, changed boot-args, restarted. Pop-up window showing "parameter error".
Genshin version: 3.0 CN
MacOS: Monterey 12.3.1
Chip: M1 Pro

**Comment by ugzhu** [comment]
I solved this issue by clicking on the small "Experiencing issue?" button at the bottom right corner of Playcover UI. Followed instructions (confirmed SIP is disabled and restarted my mac again), then it works like a charm!

**Comment by ZhichGaming** [comment]
> I solved this issue by clicking on the small "Experiencing issue?" button at the bottom right corner of Playcover UI. Followed instructions (confirmed SIP is disabled and restarted my mac again), then it works like a charm!

So did you not have SIP disabled before?
