### ISSUE TITLE
[Bug]: Shared Executable Names between sagas causes Replacement

### ISSUE THREAD

**Issue by amirsaam** [PlayCover/PlayCover#304]
### Describe the bug

Games that have a shared Executable Name with different Bundle Names (saga's mostly) will replace each other.

### Steps to reproduce

All of Infinity Blades are using "SwordGame" as Executable Name. So:

1. Install IB1 or 2 or 3
2. Try Installing different one from step 1
3. The one from step 2 will replace installed one in step 1

### Expected behaviour

PlayCover should be able to differentiate between such games and install them separately not replace them on each other.

Solution 1: Use Bundle Identifiers as .app names
Solution 2: While installing an app, check the executable name if it already exist, then check if bundle identifiers are different or not, if not send a replacement warning to user if they were different add something at the end of executable app name. (basically you will add a replace warning while fixing this bug)

### Crash log

```shell
None
```

### What version of PlayCover are you using?

Nightly/beta

### What version of macOS are you using?

Monterey (macOS 12)

### Issue Language

- [X] Yes my issue is written in English

**Comment by ZhichGaming** [comment]
This is a feature request and not a bug.

**Comment by amirsaam** [comment]
@ZhichGaming that's a bug if causes different apps replace each other, is it not?

**Comment by ZhichGaming** [comment]
A feature request can be related to a bug and you can give details on it in the first box.

**Comment by amirsaam** [comment]
@ZhichGaming I have sent feature requests before, but I think it's better to be described as a bug because it's not a problem on an actual iOS device.
iOS uses Bundle Name as Home Screen app name.

**Comment by ZhichGaming** [comment]
Hmm ok, well it's not a big deal anyway.

**Comment by amirsaam** [comment]
This issue has been fixed by side effects of PR #368 with commit `Change .app name to display name on install`
