### ISSUE TITLE
[Bug]: All apps crashing after opening

### ISSUE THREAD

**Issue by Zerp500** [PlayCover/PlayCover#311]
### Describe the bug

I try to open a app, but then it immediately crashes

### Steps to reproduce

Download a decrypted ipa (any)
Install it onto playcover
Run it and then it crashes
[Crash.rtf.zip](https://github.com/PlayCover/PlayCover/files/9505443/Crash.rtf.zip)

### Expected behaviour

The app should run, instead of crashing

### Crash log

```shell
Log had to be provided as an rtf file, because of github character limit.
```

### What version of PlayCover are you using?

1.1.1

### What version of macOS are you using?

Monterey (macOS 12)

### Issue Language

- [X] Yes my issue is written in English

**Comment by ZhichGaming** [comment]
More details are needed as to what ipas specifically you have tried.

**Comment by Zerp500** [comment]
> More details are needed as to what ipas specifically you have tried.

So far I've tried and crashed out in Pokemon Unite, Nier Reincarnation, Genshin and Dissidia Final Fantasy Opera Omnia

**Comment by ZhichGaming** [comment]
Where did you download the IPAs from?

**Comment by Zerp500** [comment]
Pokemon Unite and Genshin were from Appocalypse discord and the other two were from armconverter

**Comment by ZhichGaming** [comment]
Try reinstalling your PlayCover and app.

**Comment by Zerp500** [comment]
I have done it, although I have said this bug was on 1.1.1, I have also tried the nightly builds and I have even tried to run these apps by disabling SIP, all to no avail. Unless if PlayCover is hiding some extra folders somewhere, which are not being deleted when I uninstall it.

**Comment by Depal1** [comment]
Here are the instructions for a full reinstall. https://github.com/PlayCover/PlayCover/issues/257

**Comment by Zerp500** [comment]
Thank you very much for sending, working on it right now.

**Comment by Zerp500** [comment]
> Here are the instructions for a full reinstall. #257

Have prowled through all the listed directories and deleted all files within, crashes still persist

**Comment by ZhichGaming** [comment]
Are you using a VM?

**Comment by Depal1** [comment]
If you are using a VM, you have to enable graphics acceleration with Apple's virtualization framework, and only games that use Metal would run.

**Comment by Zerp500** [comment]
I am not using a virtual machine.

**Comment by Zerp500** [comment]
Sidenote, I have pokemon unite and dissidia installed currently. Pokemon Unite provides me with a crash log, but dissidia simply crashes.

**Comment by Zerp500** [comment]
Update on the situation, I've used nightly builds, reinstalled playcover fully and even reinstalled xcode, however playcover still refuses to launch games for me, will boot args help???

Also, sideloadly works for me, but not playcover

**Comment by IsaacMarovitz** [comment]
@Zerp500 Pokemon Unite is confirmed to have issues right now. Does Genshin work?

**Comment by IsaacMarovitz** [comment]
Stale, old PlayCover version, duplicate, non-specific

**Comment by spinxzq** [comment]
So i found the solution, go to settings->more (the 4th option) and change the settings.applicationCategoryType to public.app-category.games
