### ISSUE TITLE
[Bug]: Diablo Immortal , xbox controller is not supported even connected successfully and game capture it 

### ISSUE THREAD

**Issue by Tonny1986** [PlayCover/PlayCover#315]
### Describe the bug

Diablo Immortal , xbox controller is not supported even connected successfully and game capture it 
<img width="1097" alt="image" src="https://user-images.githubusercontent.com/39816819/188992541-87456081-58a0-4b0f-a2a4-732fd182ca27.png">

### Steps to reproduce

1、The xbox controller connected with mac m1 using bluetooth
2、the version of playcover is 1.1.1
3、install the Diablo Immortal 
4、login the game
5、cut the xbox controller connect with mac，reconnect then the game recognized the controller
6、but can not recognized any movement of controller when click the button of controller

### Expected behaviour

xbox controller effective in Diablo Immortal

### What version of PlayCover are you using?

1.1.1

### What version of macOS are you using?

Monterey (macOS 12)

### Issue Language

- [X] Yes my issue is written in English

**Comment by Tonny1986** [comment]
I reinstall the playcover1.1.1 and the ipa of the game , not set any keyboard mapping , then connect the contrller, it works~now~ so amazing~why?

**Comment by ZhichGaming** [comment]
I'm guessing you had a bad installation. So it is the issue resolved?

**Comment by Tonny1986** [comment]
> I'm guessing you had a bad installation. So it is the issue resolved?

no，when I connected the controller before game starting ， the playcover cannot recognize the controller，you can check the issue
