### ISSUE TITLE
[Bug]: Cannot quit Sims City properly without force quitting

### ISSUE THREAD

**Issue by lockieluke** [PlayCover/PlayCover#335]
### Describe the bug

Sims City becomes unresponsive after being closed(including Command+Q and clicking the red dot), you'll have to quit it by click force quit again

### Steps to reproduce

Open Sims City, then quit it

### Expected behaviour

Quit gracefully without having to force quit it

### What version of PlayCover are you using?

1.1.1

### What version of macOS are you using?

Monterey (macOS 12)

### Issue Language

- [X] Yes my issue is written in English

**Comment by IsaacMarovitz** [comment]
Can you try in the latest nightly and see if this issue persists?

**Comment by IsaacMarovitz** [comment]
Closing as stale.
