### ISSUE TITLE
[Bug]: You don't have the permission to save the file "Frameworks" in the folder "Library".

### ISSUE THREAD

**Issue by tunaww** [PlayCover/PlayCover#337]
### Describe the bug

Recently I've been trying to install Playcover. When I install the program and launch it, I would receive the error you just read from the title. 
<img width="243" alt="Screen Shot 2022-09-13 at 5 41 48 PM" src="https://user-images.githubusercontent.com/113411739/189818545-a574e440-ac7b-4ea5-901d-c5772b5cb5e3.png">

I tried researching for info but I was too dumb to find any solutions. 
Though I think I might know the problem, I think it's because when I got my mac I was dumb and I created an account on accident and then created another account just to migrate on, aka I have 2 accounts. Playcover is probably trying to put the frameworks folder into the other account, I tried giving it permission to just let it put the folder there but it didn't work. I also realized that the 2nd account's (main account) account name and the home directory aren't the same. So that might be the problem, I haven't touched it yet though.

I'm think what's causing the problem is the account name and home directory aren't the same. Or that Playcover is trying to put the frameworks folder somewhere else but can't. However Playcover does work on my main account though.

### Steps to reproduce

I don't know the exact way to reproduce but when I got my new mac I created an account and then created another account to migrate on. The first account is my alt and my second account is my main. Also notice that the names on the second account aren't the same. So if you want to reproduce this then well do that as well. 
1st account
<img width="588" alt="image" src="https://user-images.githubusercontent.com/113411739/189818935-e7269a06-8250-4877-bb67-07096cc56621.png">

2nd account
<img width="609" alt="image" src="https://user-images.githubusercontent.com/113411739/189818969-430878b4-f07a-48c9-bac9-9a5c69f9a9d0.png">

### Expected behaviour

Playcover would do the frameworks thing and run normally afterwards.

### What version of PlayCover are you using?

1.1.1

### What version of macOS are you using?

Monterey (macOS 12)

### Issue Language

- [x] Yes my issue is written in English

**Comment by ohaiibuzzle** [comment]
Try manually copying PlayTools to that folder. Run `open /Applications/PlayCover.app/Contents/Frameworks` in a terminal window, then copy PlayTools.framework to the Frameworks folder

**Comment by tunaww** [comment]
> Try manually copying PlayTools to that folder. Run `open /Applications/PlayCover.app/Contents/Frameworks` in a terminal window, then copy PlayTools.framework to the Frameworks folder

Thought that was gonna work but It didn't work, still shows the warning thingy D:

**Comment by ohaiibuzzle** [comment]
In a terminal, run `sudo xcodebuild -license accept`
Enter your Mac's password
Then PlayCover will work normally

**Comment by tunaww** [comment]
> In a terminal, run `sudo xcodebuild -license accept` Enter your Mac's password Then PlayCover will work normally

do i have to install xcode?

davids-poopoo-macbook-pro:~ davidliu1$ sudo xcodebuild -license accept
Password:
xcode-select: error: tool 'xcodebuild' requires Xcode, but active developer directory '/Library/Developer/CommandLineTools' is a command line tools instance

**Comment by ohaiibuzzle** [comment]
Try `sudo xcrun cc`. It should also allow you to accept the Apple License

It will throw a "No input file". This is OK

**Comment by XuYicong** [comment]
This may also happen if your username is different from your home folder name. Try changing them to the same if this is the case.

**Comment by ohaiibuzzle** [comment]
> This may also happen if your username is different from your home folder name. Try changing them to the same if this is the case.

I think we should see if this is a common enough issue. If it is, we can switch to ` FileManager.default.homeDirectoryForCurrentUser` which should be more stable

**Comment by IsaacMarovitz** [comment]
This should be fixed by #345
