### ISSUE TITLE
[Bug]: Version 1.1.1 (36) on macOS 12.6 shows "PlayTools are not installed! Please move PlayCover.app into Applications!"

### ISSUE THREAD

**Issue by iF2007** [PlayCover/PlayCover#338]
### Describe the bug

Device: M1 Pro Macbook Pro.
I updated to macOS 12.6 today and open an app in PlayCover prompts "PlayTools are not installed! Please move PlayCover.app into Applications!"
Works perfectly before update to macOS 12.6.
Also my Xcode updated to 14.
Version 1.1.1 (36)

### Steps to reproduce

Open PlayCover.app
Open an APp

### Expected behaviour

App runs perfectly

### What version of PlayCover are you using?

1.1.1

### What version of macOS are you using?

Monterey (macOS 12)

### Issue Language

- [X] Yes my issue is written in English

**Comment by iF2007** [comment]
<img width="559" alt="image" src="https://user-images.githubusercontent.com/4461848/189942122-447c5654-370c-4d30-b4a2-3de3ea0ffa25.png">

**Comment by amirsaam** [comment]
[Read this](https://github.com/PlayCover/PlayCover/discussions/336)

**Comment by ZhichGaming** [comment]
If @amirsaam's instructions do not work, please remove command line tools and update it with these two commands: 
```
sudo rm -rf /Library/Developer/CommandLineTools
xcode-select --install```

**Comment by amirsaam** [comment]
Btw, this can caused by CLT being updated, and it will not get update from `xcode-select --install`, you need to update it from Mac's System Preferences

**Comment by linfansh** [comment]
Go to Mac preferences > software updates and update xclt.
![521663179810_ pic](https://user-images.githubusercontent.com/62031885/190251583-8e847086-390e-42b3-9e7d-92880e38465b.jpg)
After that, open Xcode and accept Apple ToS (pops up when you open Xcode after update or install, a window that has an "agree" button.

**Comment by ZhichGaming** [comment]
Oh yeah, I forgot that that was the way to update command line tools.

**Comment by iF2007** [comment]
> [Read this](https://github.com/PlayCover/PlayCover/discussions/336)

Works perfectly. Thanks.
