### ISSUE TITLE
playcover tutorial?

### ISSUE THREAD

**Issue by osnapitzgiada** [PlayCover/PlayCover#34]
i just created this account bc i wanted to download genshin impact but playcover website is down and ppl on discord told me to use this website to download it, i looked at a few youtube tutorials but none is helping me. 
can someone please just tell me what do i have to click?😩

**Comment by JoseMoreville** [comment]
There's a section in code part that's says releases

**Comment by Depal1** [comment]
Right now 1.0.6 will require you to install Homebrew, which you can do by following the instructions at [brew.sh](https://brew.sh).
Once you have followed the instructions for installing it, do `brew install ldid`.
Download the 1.0.6 dmg, drag the the app into the Applications folder. You might need to press Control while clicking it to start it for the first time. You should be ready to go.

**Comment by JoseMoreville** [comment]
> I recommend installing 1.0.4 or 1.0.7, because both don't require the homebrew/ldid requirements

@zanderp25 1.0.7 is a pre-release so is recommended to downgrade before using pre releases unless you want to test new features

**Comment by zanderp25** [comment]
Can this issue be closed now?

**Comment by osnapitzgiada** [comment]
yes the issue can be closed, sorry i forgot to answer but thank u all so much!! i installed it everything was alright but genshin couldn’t work with the computer’s keyboard so i just gave up lol but thank u :)
