### ISSUE TITLE
[Bug]: "Tower of Fantasy"can run and log in normally, but it will return to the main menu when the loading progress reaches 99%

### ISSUE THREAD

**Issue by TaskeyLee** [PlayCover/PlayCover#340]
### Describe the bug

<img width="674" alt="image" src="https://user-images.githubusercontent.com/48666689/190083251-006774a1-f2df-4e28-acc7-27d2cd7e5489.png">

### Steps to reproduce

After opening the game, you can log in, enter the loading interface, and return to the main menu at 99%

### Expected behaviour

After loading, enter the game normally

### Crash log

```shell
-------------------------------------
Translated Report (Full Report Below)
-------------------------------------

Process:               QRSL [5198]
Path:                  /Users/USER/Library/Containers/io.playcover.PlayCover/QRSL.app/QRSL
Identifier:            com.pwrd.huanta
Version:               2.2.0 (0.17)
Code Type:             ARM-64 (Native)
Parent Process:        launchd [1]
User ID:               501

Date/Time:             2022-09-14 14:57:15.5680 +0800
OS Version:            macOS 12.5.1 (21G83)
Report Version:        12
Anonymous UUID:        FEA77BC4-5055-447A-D549-F296761A1964


Time Awake Since Boot: 1400 seconds

System Integrity Protection: disabled

Crashed Thread:        32  FAsyncLoadingThread

Exception Type:        EXC_BAD_ACCESS (SIGSEGV)
Exception Codes:       KERN_INVALID_ADDRESS at 0x0000000000000008
Exception Codes:       0x0000000000000001, 0x0000000000000008
Exception Note:        EXC_CORPSE_NOTIFY

Termination Reason:    Namespace SIGNAL, Code 11 Segmentation fault: 11
Terminating Process:   exc handler [5198]

VM Region Info: 0x8 is not in any region.  Bytes before following region: 105553518919672
      REGION TYPE                    START - END         [ VSIZE] PRT/MAX SHRMOD  REGION DETAIL
      UNUSED SPACE AT START
--->  
      MALLOC_NANO (reserved)   600018000000-600020000000 [128.0M] rw-/rwx SM=NUL  ...(unallocated)
```

### What version of PlayCover are you using?

1.1.1

### What version of macOS are you using?

Monterey (macOS 12)

### Issue Language

- [X] Yes my issue is written in English

**Comment by amirsaam** [comment]
ToF won't work on PlayCover because of the game's server end configurations.
It has been known and PlayCover devs cannot do anything about it.

**Comment by TaskeyLee** [comment]
> ToF won't work on PlayCover because of the game's server end configurations.
> It has been known and PlayCover devs cannot do anything about it.
Okay... Thank you.

**Comment by amirsaam** [comment]
No problem, consider closing this issue if you have no more questions.
