### ISSUE TITLE
[Bug]:  Nexxt Home - No stream Click to try again

### ISSUE THREAD

**Issue by silvercool2k** [PlayCover/PlayCover#341]
### Describe the bug

I am able to log in and get notifications however I am unable to retrieve video from the wifi cameras. I keep getting a "Failed to retrieve video stream. Click to try again". 

App is "Nexxt Home"
intcomex.app/intcomex
Identifier=com.intcomex.smart
Works fine on my iPhone 8 Plus.  

I will include a screenshot.   

<img width="583" alt="Screen Shot 2022-09-14 at 1 31 17 PM" src="https://user-images.githubusercontent.com/25691326/190226640-253fc25b-3df9-48f4-8ed2-c81b753d0578.png">

### Steps to reproduce

Open the App, Log in and view your cameras.

note: You need a Nexxt smart cameras.  

I am running playCover with SIP disabled. 

I also tried running it with lldb, same outcome. 

### Expected behaviour

It should start streaming the camera, and allow you to listen and or use the mic options. 

### Crash log

```shell
no Crash log since the app does not crashes. just getting a "unable to start stream" "Click to retry".
```

### What version of PlayCover are you using?

1.1.1

### What version of macOS are you using?

Monterey (macOS 12)

### Issue Language

- [X] Yes my issue is written in English

**Comment by IsaacMarovitz** [comment]
@silvercool2k Please try in latest nightly and with NVRAM args set

**Comment by silvercool2k** [comment]
Hi, just tried the nightly build, it works great! thank you! 

I didn't set NVRAM args (might've done in the past tho)

![1109984C-D88C-4799-A15C-564ECF09825C](https://user-images.githubusercontent.com/25691326/193411388-a900b510-9322-434f-b7ed-e3d73baa801a.jpg)

Thanks again,
you can close this one
