### ISSUE TITLE
[Bug]: command cp not found issue

### ISSUE THREAD

**Issue by bitweedx86** [PlayCover/PlayCover#343]
### Describe the bug

When PlayCover boot up, it pops up an alert shows below.

Clearly I already have CommandLineTool installed and cp is available.

I wonder if anything I can help with to diagnose this problem.

The Chinese in the popup means, "encountered a problem".

<img width="891" alt="CleanShot 2022-09-16 at 08 56 25@2x" src="https://user-images.githubusercontent.com/100564793/190533950-b0f2baec-603f-409e-b122-09bec9ee7ae4.png">

### Steps to reproduce

Install Playcover then boot it.

I'm using macOS Monterey 12.6 though. 

### Expected behaviour

To boot up normally.

### Crash log

```shell
No valuable log was found in console app.
```

### What version of PlayCover are you using?

1.1.1

### What version of macOS are you using?

Monterey (macOS 12)

### Issue Language

- [X] Yes my issue is written in English

**Comment by amirsaam** [comment]
Did you update your Xcode Command Line Tools to 14 through Mac's Preferences > Software Update?

**Comment by IsaacMarovitz** [comment]
This should be fixed in PlayCover 2.0.0

**Comment by bitweedx86** [comment]
> Did you update your Xcode Command Line Tools to 14 through Mac's Preferences > Software Update?

yep, I did. the CLI tools are the latest version
