### ISSUE TITLE
[Game Support]: 三国志无法正常连接

### ISSUE THREAD

**Issue by goodSlovenly** [PlayCover/PlayCover#346]
### App Store link

https://apps.apple.com/cn/app/%E4%B8%89%E5%9B%BD%E5%BF%97-%E6%88%98%E7%95%A5%E7%89%88/id1474572440

### Current issues

- [ ] Game fails to install
- [ ] Game fails to open
- [X] Game crashes randomly during gameplay
- [ ] Game does not work with keymapping
- [ ] Game experiences graphical issues or broken UI
- [X] Game fails to connect to servers or complete download

### More details

The game can't be loaded normally and the game crashes whenever it moves！

### Issue Language

- [X] Yes my issue is written in English

**Comment by TheMoonThatRises** [comment]
This issue has been fixed by using the latest nightly and enabling PlayChain (through the app's settings -> Bypasses).
