### ISSUE TITLE
[Feature]: Multiple app windows

### ISSUE THREAD

**Issue by hoobnn** [PlayCover/PlayCover#349]
### Is your feature request related to a problem?

yes

### Describe the solution you'd like

For a game, when I open more than one at the same time, and I am using the xbox handle to control, it will appear that the handle can operate all the games at the same time. I would like to add an isolation space so that I can choose independently whether the game window needs to be manipulated or not.

### Anything else?

Is it possible to add a function of application multi-opening, the current way of multi-opening is not convenient

### Issue Language

- [X] Yes my issue is written in English

**Comment by XuYicong** [comment]
By handle you mean controller（游戏手柄） right? Multi instance（多开） of the same application is not supported, because it affects game fairness. You can still open multi-instance of playcover don't you?

**Comment by TeaWu** [comment]
My problem is that the gamepad controls multiple instances of the application at the same time, regardless of which instance the application is focused on, but using the keyboard control does not control multiple instances at the same time, but only the instance that currently has the application focus

**Comment by hoobnn** [comment]
> By handle you mean controller（游戏手柄） right? Multi instance（多开） of the same application is not supported, because it affects game fairness. You can still open multi-instance of playcover don't you?

My problem is that the gamepad controls multiple instances of the application at the same time, regardless of which instance the application is focused on, but using the keyboard control does not control multiple instances at the same time, but only the instance that currently has the application focus

**Comment by XuYicong** [comment]
So this only happens to multiple instances of the same applications? How about if you open two instances of different applications?

**Comment by ohaiibuzzle** [comment]
Multiple parallel windows of any application is not supported at this time (and probably will never be) as that could provide ground for cheating in games.

**Comment by zanderp25** [comment]
That's true, however, it can be set up so that the game in the background can be controlled by a game controller and the game in the foreground is controlled by the keybind controls.

**Comment by hoobnn** [comment]
While playcover itself does not support multiple instances of the same application, there are still ways to launch multiple instances of the same application. The problem I described with the game controller controlling all instances of the foreground and background at the same time occurs with different instances of the same application, next I will try to open different applications at the same time and see if the game controller acts on these programs at the same time.

**Comment by TeaWu** [comment]
While playcover itself does not support multiple instances of the same application, there are still ways to launch multiple instances of the same application. The problem I described with the game controller controlling all instances of the foreground and background at the same time occurs with different instances of the same application, next I will try to open different applications at the same time and see if the game controller acts on these programs at the same time.

**Comment by zanderp25** [comment]
Yes, that's what i meant.

**Comment by Doooomizz** [comment]
@TrioTea Hi could u tell me how did u launch multiple instances of the same game with PlayCover plz ?

**Comment by makovez** [comment]
I'm also interested to this, how did u run it ? @TrioTea

**Comment by hoobnn** [comment]
> I'm also interested to this, how did u run it ? [@TrioTea](https://github.com/TrioTea)

You can try searching for methods to run multiple instances of any program on Mac, then use the same approach.

**Comment by GanZhiXiong** [comment]
> 我也对此很感兴趣，你是怎么运行的？@TrioTea

@makovez  Have you found a way? Looking forward to your reply. Thank you!
