### ISSUE TITLE
PlayCover switches the audio output on start

### ISSUE THREAD

**Issue by Depal1** [PlayCover/PlayCover#35]
PlayCover is changing default audio output on start. I have experienced this on a Mac Studio with a particular monitor.

Could anyone confirm if this happens on a MacBook with wireless headphones? The issue might not present itself in that case, since it might be triggered because the monitor I am using keeps asking to have the audio output. Normally, apps like Discord would open a prompt asking me if I would like to change the audio source; instead of switching on one go.

macOS version 12.4
This issue is present on PlayCover 1.0.6 and pre-release 1.0.7. It is not presenting itself on 1.0.0, so it is a regression.

**Comment by hayatofujii** [comment]
Couldn't repro with a MacBookPro18,2. Did:

1. Connected a Bluetooth audio device
2. Quit PlayCover and any playcover'ed apps
3. Open PlayCover and run anything

**Comment by Depal1** [comment]
Closing in favour of #79.
