### ISSUE TITLE
[错误]：After installation, do not display the download again

### ISSUE THREAD

**Issue by fugu88** [PlayCover/PlayCover#351]
### Describe the bug

1.1.1 If there is a problem with the installation list, there will be a download prompt after installation.

### Steps to reproduce

The installed items will still be prompted to download.

### Expected behaviour

After installation, do not display the download again

### What version of PlayCover are you using?

1.1.1

### What version of macOS are you using?

Monterey (macOS 12)

### Issue Language

- [X] Yes my issue is written in English

**Comment by ohaiibuzzle** [comment]
If you don't want to see them, simply press Option + Command + A.
