### ISSUE TITLE
[Feature]: 

### ISSUE THREAD

**Issue by 656747794** [PlayCover/PlayCover#353]
### Is your feature request related to a problem?

I hope the resolution can be automatically displayed in full screen as before.

### Describe the solution you'd like

Can automatically adapt to stretching full screen.

### Anything else?

No more

### Issue Language

- [X] Yes my issue is written in English

**Comment by ZhichGaming** [comment]
Do you mean in nightlies?

**Comment by 656747794** [comment]
<img width="1728" alt="截屏2022-09-17 22 05 13" src="https://user-images.githubusercontent.com/95347363/190861138-2adda5ea-74ed-4e64-bd9e-90b8730dd0e9.png">
No, I'm talking about iOS model，It's not full screen.

**Comment by ZhichGaming** [comment]
iPad model does not influence screen size. Did you enable auto screen resize/adaptive display? If you have those on, the app will fill the screen if you full screen it. If you disable it, there is custom resolution you can put. What version of PlayCover are you on?

**Comment by 656747794** [comment]
It is version 1.1.1.I've tried all these, and there are all kinds of problems.Can't perfect full screen.
<img width="500" alt="截屏2022-09-17 22 19 01" src="https://user-images.githubusercontent.com/95347363/190861897-4632ab8c-b9a0-47b6-95c1-f7d2859cf08d.png">
<img width="1728" alt="截屏2022-09-17 22 23 55" src="https://user
<img width="1728" alt="截屏2022-09-17 22 24 39" src="https://user-images.githubusercontent.com/95347363/190861949-c6143c4a-637a-4c04-bcbd-9f29cdea26a1.png">
-images.githubusercontent.com/95347363/190861923-49298ade-c085-4360-b4d6-d92195074b98.png">

**Comment by ZhichGaming** [comment]
What model MacBook are you using? 14 inch? If yes then uncheck adapt ive display and enter a custom resolution. This is not a feature request so I will be closing it.

**Comment by 656747794** [comment]
<img width="249" alt="截屏2022-09-17 22 31 08" src="https://user-images.githubusercontent.com/95347363/190862185-6dce5958-c26a-41a1-bf5f-de24e17971a4.png">
2021 MacBook 16inch

**Comment by ZhichGaming** [comment]
Please do the things mentioned above.

**Comment by 656747794** [comment]
https://user-images.githubusercontent.com/95347363/190863549-675515ab-82c5-4a92-a0e0-003a81b2c617.mp4

**Comment by JailbreakGentleman** [comment]
<img width="191" alt="Screen Shot 2022-09-17 at 23 08 37" src="https://user-images.githubusercontent.com/105794704/190863719-a93d60b2-9f51-4748-877a-9829796ba9fc.png">
这个你点一下试试?

**Comment by ZhichGaming** [comment]
<img width="182" alt="Screen Shot 2022-09-17 at 11 11 41" src="https://user-images.githubusercontent.com/93055907/190863821-d50b94a9-abdc-411d-b6b3-84aafe28510f.png">
He means please keep that box unchecked and also uncheck this box, you will be able to put custom resolution.

**Comment by 656747794** [comment]
https://user-images.githubusercontent.com/95347363/190863955-5ac6d3e1-3bfc-45c1-b34f-8b4e7cdf0e1f.mp4

**Comment by Araide** [comment]
刚才Zhich有提到你的电脑是14英寸的电脑。你先把“适配显示器”这个选项关掉，然后就可以在这里输入自定义分辨率。(见图二)

Zhich just mentioned that your computer is a 14 inch one. First, you wanna uncheck this "Adaptive resolution" box, then you can put in custom resolution values. (Check the second image)

或者... 你可以勾选这个"启用自动窗口大小调整"的选项。（见图一)

Or... you can click on this "Enable custom window size option" checkbox. (Check out the first image)
<img width="182" alt="Screen Shot 2022-09-17 at 23 21 05" src="https://user-images.githubusercontent.com/105794704/190864209-8c5005f9-dd39-4adc-b079-8d643edef395.png">

<img width="435" alt="Screen Shot 2022-09-17 at 23 17 14" src="https://user-images.githubusercontent.com/105794704/190864059-8277c832-82e9-4358-8594-3609cbd144d6.png">

**Comment by 656747794** [comment]
My mac is 1689241081 inch,After turning off the "Adaptive Display", I don't see that I can input a custom resolution.

**Comment by 656747794** [comment]
My mac is 16 inch,After turning off the "Adaptive Display", I don't see that I can input a custom resolution.

**Comment by Araide** [comment]
Ok, final try. Enable the Adaptive Display, and enable the "Enable custom window size option" checkbox.

**Comment by ZhichGaming** [comment]
I'm sorry, I got confused. You have to enable adaptive display and turn on custom window resize.

**Comment by 656747794** [comment]
https://user-images.githubusercontent.com/95347363/190864761-5cfad21c-1759-4003-9329-f3993e481169.mp4

**Comment by 656747794** [comment]
Sorry, I can't find anywhere to customize the window size.

**Comment by Araide** [comment]
<img width="522" alt="Screen Shot 2022-09-17 at 23 36 56" src="https://user-images.githubusercontent.com/105794704/190864827-81f30c3e-e987-478b-b51e-0c02c0f545a6.png">
Look what I am doing, and copy please. If there's any questions still, join the discord server.

**Comment by 656747794** [comment]
It's the same as yours, but it still doesn't work

https://user-images.githubusercontent.com/95347363/190865011-8badaf37-1688-466d-80a9-772975f4a37f.mp4

**Comment by ZhichGaming** [comment]
Use [this](https://nightly.link/PlayCover/PlayCover/actions/runs/3055580312/PlayCover_nightly_66.dmg.zip) build instead. Please be aware that bugs may occur and we do not support it.

**Comment by 656747794** [comment]
Thank you, There is no problem using this installation package.Although sometimes mistakes are reported.
<img width="904" alt="截屏2022-09-18 00 04 43" src="https://user-images.githubusercontent.com/95347363/190866059-92f72901-418b-4d6b-93bc-147542456e0
<img width="1728" alt="截屏2022-09-18 00 04 53" src="https://user-images.githubusercontent.com/95347363/190866083-bc8cdc9b-5403-40d7-b4ca-66373022b818.png">
e.png">
