### ISSUE TITLE
[Game Support]: Cytus 2 crashes right after the launching

### ISSUE THREAD

**Issue by Helloyunho** [PlayCover/PlayCover#354]
### App Store link

https://apps.apple.com/kr/app/cytus-ii/id1290687550?l=en

### Current issues

- [ ] Game fails to install
- [x] Game fails to open
- [ ] Game crashes randomly during gameplay
- [ ] Game does not work with keymapping
- [ ] Game experiences graphical issues or broken UI
- [ ] Game fails to connect to servers or complete download

### More details

Cytus 2 literally crashes right after I launch it.
It doesn't even show the screen. Just pop out to the Dock and disappear.

### Crash log

```shell
Check the thread
```

### Issue Language

- [X] Yes my issue is written in English

**Comment by Helloyunho** [comment]
[CytusII-2022-09-16-203451.txt](https://github.com/PlayCover/PlayCover/files/9592017/CytusII-2022-09-16-203451.txt)

**Comment by zanderp25** [comment]
This seems to be a common issue with certain apps and games and we are working to resolve this

**Comment by TheMoonThatRises** [comment]
This app is a paid, and so it would be hard to develop a fix for it.
