### ISSUE TITLE
[Bug]: Snapseed - Doesn't show the picture when I select an option.

### ISSUE THREAD

**Issue by notluquis** [PlayCover/PlayCover#355]
### Describe the bug

When I use Snapseed 2.2.0 (last version available) and select an option to edit the picture, Snapseed doesn't show the picture, instead it shows a black image.

### Steps to reproduce

1. Launch Snapseed 2.2.0 using PlayCover nightly 66.
2. Use Snapseed's native photo selector to choose a photo. 
3. The image is shown perfectly. 
4.When I select an option to edit (like Details), the image goes black.

### Expected behaviour

The expected behavior is that Snapseed shows the picture perfectly. 

### Crash log

```shell
There's no crash log, because there isn't a crash.
```

### What version of PlayCover are you using?

Nightly/beta

### What version of macOS are you using?

Monterey (macOS 12)

**Comment by ZhichGaming** [comment]
Did this app work on stable version of PlayCover?

**Comment by notluquis** [comment]
Here are images of the issue. 
<img width="1706" alt="Captura de Pantalla 2022-09-17 a la(s) 18 00 22" src="https://user-images.githubusercontent.com/51384279/190876450-522c37ee-c0eb-4494-b40f-d2ea553befe5.png">
<img width="1710" alt="Captura de Pantalla 2022-09-17 a la(s) 18 00 30" src="https://user-images.githubusercontent.com/51384279/190876417-55992cf2-bb28-4b4f-b6dd-353a34d57875.png">.

**Comment by notluquis** [comment]
> Did this app work on stable version of PlayCover?

It doesn't.

**Comment by ZhichGaming** [comment]
Please reopen the issue following the app support template.

**Comment by notluquis** [comment]
The app support template isn't available on the template's selector, only the yml file is available, but with an error.

**Comment by ZhichGaming** [comment]
Thank you for pointing that out, I have made a PR to fix it.

**Comment by ZhichGaming** [comment]
The issue with the app template has been fixed, please create an issue with that.
