### ISSUE TITLE
[App Support]: Snapseed - Black Image

### ISSUE THREAD

**Issue by notluquis** [PlayCover/PlayCover#357]
### App Store link

https://apps.apple.com/es/app/snapseed/id439438619

### Current issues

- [ ] App fails to install
- [ ] App fails to open
- [ ] App crashes randomly during usage
- [x] App experiences graphical issues or broken UI
- [ ] App fails to connect to servers
- [ ] Other

### More details

When I use Snapseed 2.2.0 (last version available) and select an option to edit the picture, Snapseed doesn't show the picture, instead it shows a black image.
<img width="1706" alt="Captura de Pantalla 2022-09-17 a la(s) 18 00 22" src="https://user-images.githubusercontent.com/51384279/190883832-0bc3f909-052b-4949-8ccf-cfd202a8ec69.png">
<img width="1710" alt="Captura de Pantalla 2022-09-17 a la(s) 18 00 30" src="https://user-images.githubusercontent.com/51384279/190883833-67ce4548-cce0-439d-90db-8c496fb32f6e.png">

### Crash log

```shell
There's no crash log, because there isn't a crash.
```

### Issue Language

- [ ] Yes my issue is written in English

**Comment by TheMoonThatRises** [comment]
Can you try on the latest build of PlayCover? The app works for me.
