### ISSUE TITLE
[Bug]: Nightly adaptive resolution is incompatible with older versions, causing old keymapping to shift

### ISSUE THREAD

**Issue by RigoLigoRLC** [PlayCover/PlayCover#360]
### Describe the bug

I have installed the nightly from https://github.com/PlayCover/PlayCover/issues/28#issuecomment-1250188365 for testing the bug in the original post. However, the adaptive resolution of the new nightly is incompatible with older versions', causing the key positions to shift.

I've manually changed the resolution to 1080p 16:10 and that will look the same as before.
![New adaptive display aspect ratio](https://user-images.githubusercontent.com/49363666/190973681-0f8b0d8c-0c11-480a-98ab-aa691ad02729.png)
![Manually set 1080p 16:10](https://user-images.githubusercontent.com/49363666/190973806-cdd7e9fb-457b-48fe-9561-f8a6cdadc3df.png)

My hardware is M1 MacBook Air 2020.

### Steps to reproduce

Just launch the previously installed game with the nightly build in the mentioned comment.

### Expected behaviour

The aspect ratio behavior should stay the same, otherwise the change should be warned.

### What version of PlayCover are you using?

Nightly/beta

### What version of macOS are you using?

Monterey (macOS 12)

### Issue Language

- [X] Yes my issue is written in English

**Comment by IsaacMarovitz** [comment]
Keymapping will already adapt to move to the same relative position. We cannot adapt properly for different aspect ratios as the UI from different games will scale differently.

**Comment by RigoLigoRLC** [comment]
I understand that the game UI may react unproportionally to the change of resolution, however the issue I’m reporting here is that the default behavior of “adaptive resolution” is inconsistent with previous version.
