### ISSUE TITLE
[Feature]: Deliver touchpad pinch gestures to mouse move areas when mouse cursor is captured

### ISSUE THREAD

**Issue by RigoLigoRLC** [PlayCover/PlayCover#361]
### Is your feature request related to a problem?

On MacBooks, pinch gestures will also work in PlayCover launched games. For example in Genshin you can zoom in and out with pinch gestures. The pinch gesture is usually delivered to the position of mouse cursor. However, when the mouse cursor is captured, it's still delivered to the cursor position -- while I am totally unaware of the cursor position. This can cause some issues like, when I wanted to zoom out the view, I would accidentally trigger a character's elemental burst (annoying).

### Describe the solution you'd like

Deliver the pinch actions to a mouse move area (I don't really know what it's called, but it's basically an area you can put on the screen in keymapping editor, so that the mouse moves will translate into touchscreen sliding) if the mouse is captured. If there isn't such an area, then still deliver to the cursor position.

### Anything else?

![Suggestions](https://user-images.githubusercontent.com/49363666/190975293-23f2a6ba-515e-4341-8b6f-c1e6816fd37f.png)

### Issue Language

- [X] Yes my issue is written in English

**Comment by IsaacMarovitz** [comment]
This might be achievable with https://developer.apple.com/documentation/coregraphics/1456387-cgwarpmousecursorposition

**Comment by FlyMeToTheMoonAndLetMePlayAmongTheStars** [comment]
I wonder if the problem described might be related to the random zooming in and out bug Genshin players have been reporting hmm

**Comment by RigoLigoRLC** [comment]
Zooming bug may be possible if the key mapping would actually trigger
zooming when keys are pressed. This one is only gonna happen if you pinch
on the touchpad, and with my experience in Genshin this is kinda unlikely
to happen.

FlyMeToTheMoonAndLetMePlayAmongTheStars ***@***.***> 于
2023年2月1日周三 上午6:24写道：

**Comment by TheMoonThatRises** [comment]
Try the latest nightly, since https://github.com/PlayCover/PlayTools/pull/73 was merged and may provide the feature you requested.
