### ISSUE TITLE
[Bug]: Keymapping doesn't register keystrokes in Genshin Impact

### ISSUE THREAD

**Issue by Anorak2009** [PlayCover/PlayCover#369]
### Describe the bug

When using a keymapping on Genshin Impact, the alt key just sends my mouse cursor to the center of the screen. After opening and closing the keymapping editor, my cursor is hidden but keystrokes don't register. Mouse clicks still register but nothing else does.

### Steps to reproduce

Open Genshin Impact with a keymapping. 
Try pressing the alt key or opening and closing the keymapping editor.

### Expected behaviour

Alt key hides mouse cursor and keystrokes are registered to where they are mapped.

### What version of PlayCover are you using?

1.1.1

### What version of macOS are you using?

Monterey (macOS 12)

### Issue Language

- [X] Yes my issue is written in English

**Comment by IsaacMarovitz** [comment]
Please try nightly build 85

**Comment by ECLuckyHe** [comment]
> Please try nightly build 85

Same problem on build 85, my device is MacBook Pro m2, macOS 12.6.
Before open key mapping editor, I can see and use the cursor, nothing happens when I press option key. And when I close the editor, the cursor disappears, and I cant control anything until I switch to other desktop and quit the game.
Only when the game window is active it happens.

**Comment by IsaacMarovitz** [comment]
Please try restarting and reinstalling PlayCover.
Delete folder `~/Library/Frameworks/PlayTools.framework`
Delete the app from the Applications folder
Remove `~/Library/Containers/PlayCover`
Remove `~/Library/Containers/Genshin Impact`

Reinstall PlayCover from latest nightly, reinstall Genshin Impact, reimport keymapping.

**Comment by elisezhu123** [comment]
it just a seldom happen bug you can just go like that and come back 

<img width="1728" alt="截屏2022-09-29 下午5 55 53" src="https://user-images.githubusercontent.com/68165050/193167250-5f5c4442-2f1c-4518-86b8-238fff666306.png">

then back to Geshin Impact and plus the option key for the mouse to show and then plus the option again it hides the key mapping work

**Comment by Bushuo** [comment]
I am experiencing this right now in Wild Rift. 
Mouse input works, but keyboard input does not.
I tried with the latest nightly and release, both to no avail.
What can I do to help you fix this?
