### ISSUE TITLE
[Bug]: it keeps asking me to install xcode command line tools 

### ISSUE THREAD

**Issue by uq6c** [PlayCover/PlayCover#372]
### Describe the bug

when i open playcover it asks me to install xcode command line, i wait, it installs, the app restarts, and it tells me to install it again.

### Steps to reproduce

1. open the app. 2. click install on Xcode command line. 3. input mac password for install. 4. wait for it to install. 5. restart the app, and it just asks to install it again

### Expected behaviour

it should download Xcode command line like it says

### What version of PlayCover are you using?

1.1.1

### What version of macOS are you using?

Monterey (macOS 12)

### Issue Language

- [X] Yes my issue is written in English

**Comment by ZhichGaming** [comment]
Just open Xcode and accept the licence.

**Comment by uq6c** [comment]
where do i find xcode?

**Comment by ZhichGaming** [comment]
<img width="518" alt="Screen Shot 2022-09-23 at 01 04 03" src="https://user-images.githubusercontent.com/93055907/191895225-67743dbd-3f19-4704-a689-0cd4412cd1f6.png">
Try the methods 1 and 4 if you don't have Xcode.

**Comment by uq6c** [comment]
nothing popped up when i installed it

**Comment by amirsaam** [comment]
did you try installing xclt with this command?
`xcode-select --install`

**Comment by elisezhu123** [comment]
it is just a component of Xcode you can go to the apple developer website in the develop categories click on Xcode and click the website. Then login to your Apple ID (of email phone id sometimes not ok you need to sign up a new one by email) and just download the Xcode command line tools for the version you have like the 14.1 beta 3 is the one that for macOS 13beta 9 
<img width="1482" alt="截屏2022-09-29 下午5 50 58" src="https://user-images.githubusercontent.com/68165050/193166929-68b5959c-5382-4f82-a5b1-d5cd5a275228.png">

also if you are under 13 macOS and  have never download the Xcode you can use terminal by xcode-select --install

if you download the past version before you can just go to your finder  library and find developer to delete the Xcode comaand line t
<img width="1230" alt="截屏2022-09-29 下午5 51 41" src="https://user-images.githubusercontent.com/68165050/193166900-0586b953-fee5-44df-973a-70793effdf60.png">
ools file

**Comment by woutervanwijk** [comment]
I get this error too. Tried everything. Ventura 13.1, Xcode 14.2 and commandline tools installed. Also tried all fixes mentioned here (xcrun, xcodebuild, etc). Keeps asking to install the tools

**Comment by elisezhu123** [comment]
Xcode 14 is not the suitable version for 13.1 you should have 14.1 or 14.0 xcode and it command lines not work

发件人: Wouter van Wijk ***@***.***>
日期: 星期二, 2023年1月3日 上午2:54
收件人: PlayCover/PlayCover ***@***.***>
抄送: elisezhu123 ***@***.***>, Comment ***@***.***>
主题: Re: [PlayCover/PlayCover] [Bug]: it keeps asking me to install xcode command line tools (Issue #372)

I get this error too. Tried everything. Ventura 13.1, Xcode 14, commandline tools installed

―

**Comment by woutervanwijk** [comment]
Sorry, I have Xcode 14.2

**Comment by vesper8** [comment]
I'm on Xcode 14.2, I already open Xcode and was not prompted to accept any license. I actually use Xcode for development on a daily basis.

If I try to run `xcode-select --install` it tells me I already have the latest version.

And every time I try to open PlayCover (latest non-nightly release) it tells me I need to install Xcode Tools.

**Comment by woutervanwijk** [comment]
> I'm on Xcode 14.2, I already open Xcode and was not prompted to accept any license. I actually use Xcode for development on a daily basis.
> 
> If I try to run `xcode-select --install` it tells me I already have the latest version.
> 
> And every time I try to open PlayCover (latest non-nightly release) it tells me I need to install Xcode Tools.

Exactly the same here

**Comment by elisezhu123** [comment]
sudo rm -rf /Library/Developer/CommandLineTools

xcode-select --install

发件人: Wouter van Wijk ***@***.***>
日期: 星期二, 2023年1月10日 上午12:37
收件人: PlayCover/PlayCover ***@***.***>
抄送: elisezhu123 ***@***.***>, Comment ***@***.***>
主题: Re: [PlayCover/PlayCover] [Bug]: it keeps asking me to install xcode command line tools (Issue #372)

I'm on Xcode 14.2, I already open Xcode and was not prompted to accept any license. I actually use Xcode for development on a daily basis.

If I try to run xcode-select --install it tells me I already have the latest version.

And every time I try to open PlayCover (latest non-nightly release) it tells me I need to install Xcode Tools.

Exactly the same here

―
