### ISSUE TITLE
[Feature]:Can you add a proxy switch to playcover? please.

### ISSUE THREAD

**Issue by youthyan** [PlayCover/PlayCover#373]
### Is your feature request related to a problem?

 I’m in China, and our network needs a proxy.
Even if I turn on the global proxy with crashx or v2rayU, some applications still can't connect to the network.
Can you add a proxy switch to playcover? please.

### Describe the solution you'd like

Add a separate http and socks proxy switch.
like this
<img width="1055" alt="截屏2022-09-24 08 29 53" src="https://user-images.githubusercontent.com/105373147/192072230-3b02af5e-3449-4549-9c8c-05089d75f044.png">
<img width="959" alt="截屏2022-09-24 08 30 06" src="https://user-images.githubusercontent.com/105373147/192072237-544c05b8-4a65-4c2f-8152-d8c6b9828d15.png">
<img width="511" alt="截屏2022-09-24 08 30 23" src="https://user-images.githubusercontent.com/105373147/192072386-f0800c78-050b-43a1-9ec9-68b0e20e7604.png">

### Anything else?

no. Thanks

### Issue Language

- [X] Yes my issue is written in English

**Comment by IsaacMarovitz** [comment]
These settings are already available in macOS System Preferences
