### ISSUE TITLE
[Feature]:can not perserve the rotation 

### ISSUE THREAD

**Issue by elisezhu123** [PlayCover/PlayCover#384]
### Is your feature request related to a problem?

I have an app it atomatic rotate 

when I open it. I can use command r to rotate it but next time when I open the app again  I need to rotate again

### Describe the solution you'd like

perceive the rotation in previous state 

### Anything else?

<img width="1590" alt="截屏2022-09-29 下午5 38 51" src="https://user-images.githubusercontent.com/68165050/193165649-b9d3817e-193d-48f5-81e8-bbbea8e9e0d4.png">

### Issue Language

- [X] Yes my issue is written in English

**Comment by amirsaam** [comment]
Which PlayCover version you're using?

**Comment by elisezhu123** [comment]
only the 2.0 beta version have that发自我的 iPhone在 2022年9月30日，下午12:29，Amir Mohammadi ***@***.***> 写道：﻿
Which PlayCover version you're using?

**Comment by JoseMoreville** [comment]
I think it can be added, but i don't promise anything.

**Comment by elisezhu123** [comment]
t hanks, I just desire but If not ok I still accept

**Comment by IsaacMarovitz** [comment]
Currently, rotation is not designed to be used permanently in this manner. It is also meant to be used for bug fixing purposes in instances where landscape apps open a portrait browser window or some other kind of rotation desync occurs.
