### ISSUE TITLE
Every (Appocalypse) IPA game (Like X-Plane Mobile) crashes right after opening

### ISSUE THREAD

**Issue by 25PM** [PlayCover/PlayCover#386]
### App Store link

https://apps.apple.com/ca/app/x-plane-flight-simulator/id566661426

### Current issues

- [ ] Game fails to install
- [X] Game fails to open
- [ ] Game crashes randomly during gameplay
- [ ] Game does not work with keymapping
- [ ] Game experiences graphical issues or broken UI
- [ ] Game fails to connect to servers or complete download

### More details

I followed the steps to disable SIP, and even after that, multiple games, such as X-Plane Mobile,  crashed not even a second after opening via PlayCover. All the apps that I’ve tested were downloaded from the Appocalypse server.

### Issue Language

- [X] Yes my issue is written in English

**Comment by ZhichGaming** [comment]
Have you tried enabling jailbreak bypass?

**Comment by IsaacMarovitz** [comment]
What version of PlayCover are you using
