### ISSUE TITLE
[Bug]: Camera not functioning after Q (ULT in Genshin Impact)

### ISSUE THREAD

**Issue by SherpGH** [PlayCover/PlayCover#388]
### Describe the bug

**Camera fails to function during/after the occurance of a cutscene caused by activating the ultimate attack.** Dragging mouse around doesn't do anything (doesn't turn/cant look around) while everything else functions perfectly fine**. Can only be fixed by going back into mouse mode and back into keymapping mode.** This **issue is prevalent and occurs in the most recent Nightly builds (#92) and stable (1.1.1) build.** 

### Steps to reproduce

1. Press Q while looking around/moving mouse around a bit (**Cutscene must be happening**).

### Expected behaviour

Camera/Mouse panning should be functioning just as fine as the other keys during/after ult cutscene.

### What version of PlayCover are you using?

Nightly/beta

### What version of macOS are you using?

Monterey (macOS 12)

### Issue Language

- [X] Yes my issue is written in English

**Comment by IsaacMarovitz** [comment]
Fixed
