### ISSUE TITLE
[Instagram]: Shows malicious if downloaded from private discord servers. 

### ISSUE THREAD

**Issue by alfyjam** [PlayCover/PlayCover#392]
### App Store link

https://apps.apple.com/us/app/instagram/id389801252

### Current issues

- [ ] App fails to install
- [X] App fails to open
- [ ] App crashes randomly during usage
- [ ] App experiences graphical issues or broken UI
- [ ] App fails to connect to servers
- [X] Other

### More details

<img width="379" alt="Screen Shot 2022-10-02 at 1 55 04 PM" src="https://user-images.githubusercontent.com/114854631/193446574-cecbb768-9449-41d4-872d-b64a0d9dd674.png">

If anyone knows where to get trusted IPA files or whats wrong with it and if can be fixed do let me know 

### Issue Language

- [X] Yes my issue is written in English

**Comment by zanderp25** [comment]
This is not an issue with PlayCover and is related to the IPA itself. You can bypass it by turning off the malware check: right click the app in finder, click get info, and check the checkbox that disables the malware check.
