### ISSUE TITLE
[Game Support]: Seven Knight 2

### ISSUE THREAD

**Issue by luantn1212** [PlayCover/PlayCover#394]
### App Store link

https://apps.apple.com/us/app/seven-knights-2/id1579464028

### Current issues

- [ ] Game fails to install
- [X] Game fails to open
- [ ] Game crashes randomly during gameplay
- [ ] Game does not work with keymapping
- [ ] Game experiences graphical issues or broken UI
- [ ] Game fails to connect to servers or complete download

### More details

App did not work when I clicked open and it asked me reopen all the time. Can somebody help me?
<img width="1167" alt="Screen Shot 2022-10-03 at 01 17 26" src="https://user-images.githubusercontent.com/91442960/193469846-d9f94291-1d46-4504-8a9f-d2af6daea7f5.png">

### Issue Language

- [X] Yes my issue is written in English

**Comment by IsaacMarovitz** [comment]
@luantn1212 Please try again in Pre-release 2.0.0

**Comment by TheMoonThatRises** [comment]
Closing in favor of #1052.
