### ISSUE TITLE
[Feature]: Shortcut keys to zoom screen size

### ISSUE THREAD

**Issue by linxxxxxxi** [PlayCover/PlayCover#395]
### Is your feature request related to a problem?

Some games need to zoom the screen after entering the scene to achieve the highest view
In the native program, you can also use the Mac touch pad to zoom to adjust the view
You cannot zoom the screen in 90 (the first time I use the beta version) - 94 beta version
No problem with the official version 1.1.1

### Describe the solution you'd like

need to set shortcut keys to zoom the screen size, such as kneading the screen and expanding the screen
Achieve the goal of game changing vision

### Anything else?

no

### Issue Language

- [ ] Yes my issue is written in English

**Comment by JoseMoreville** [comment]
Keep using stable build, nightlies are for testing new features, but they might be bugged

**Comment by linxxxxxxi** [comment]
> 

thank you!
The game I'm playing really needs buttons to simulate the view of zooming screen!
It can be zoomed in and out like the city skyline!
I hope to consider this key mapping to join!

**Comment by IsaacMarovitz** [comment]
Stale
