### ISSUE TITLE
[Bug]: Some apps open without a window

### ISSUE THREAD

**Issue by Mistyswirl** [PlayCover/PlayCover#397]
### Describe the bug

I've been playing on the old PlayCover build with my Genshin IPAs and everything's been working fine, but I just now tried to upgrade my PlayCover to the new version so I could have built-in keymapping. That all seemed to work fine, but then I tried uploading the Genshin 3.1 IPA I had been using and opening it.

The game seems to be open and there is sound playing, but I can't see the app anywhere on my computer. I was wondering if I need to try a different IPA (which I know are in the other server), or if maybe I did something wrong when downloading the new PC build.

### Steps to reproduce

1) Have older PlayCover build (I don't remember the version, guessing it's 1.1?)
2) Have Genshin 3.1 IPA downloaded & operational via PlayCover
3) Directly upgrade to PC 2.0.0; download the Command Line Tools to open the app
4) Import the same 3.1 IPA to PlayCover
5) Attempt to launch Genshin from PC

### Expected behaviour

I expect the game to launch fully and have a visible window to interact with.

### What version of PlayCover are you using?

Nightly/beta

### What version of macOS are you using?

Monterey (macOS 12)

### Issue Language

- [X] Yes my issue is written in English

**Comment by JoseMoreville** [comment]
Use latest, we can't provide support for nightlies but just import keymaps again, and it should work.

**Comment by Depal1** [comment]
There have been sparse reports of this happening with other apps allegedly starting with https://github.com/PlayCover/PlayCover/pull/342 and https://github.com/PlayCover/PlayTools/pull/38.

**Comment by Mistyswirl** [comment]
> Use latest, we can't provide support for nightlies but just import keymaps again, and it should work.

The keymapping isn't the problem. I just tried importing the keymap I've been using and there were no changes to Genshin being able to launch properly.

**Comment by Depal1** [comment]
> The game seems to be open and there is sound playing, but I can't see the app anywhere on my computer. I was wondering if I need to try a different IPA (which I know are in the other server), or if maybe I did something wrong when downloading the new PC build.

@JoseMoreville The second paragraph is the alleged issue.

**Comment by Depal1** [comment]
@ohaiibuzzle @IsaacMarovitz This is the issue someone informally reported the other day.

**Comment by ZhichGaming** [comment]
@Mistyswirl Could you please try temporarily downgrading to 1.1.1, installing genshin and going back to nightly?

**Comment by Depal1** [comment]
For anyone attempting to replicate this, delete all app related files as described in https://github.com/PlayCover/PlayCover/issues/155.

**Comment by Mistyswirl** [comment]
Okay, downgrading did fix it. PlayCover 1.1.0 opened with the same Genshin IPA still downloaded from the beta build and that didn't launch right, but then I deleted the Genshin app and dropped it back in and it seems to work now.

**Comment by Mistyswirl** [comment]
Oh, 1.1.1 is the most recent. I'll go download that, but I expect it to work the same. Will edit this comment with an update.

Edit: Seems fine on the older build.

**Comment by IsaacMarovitz** [comment]
@Mistyswirl PlayCover 1.1.0 was fundamentally broken, hence the need for 1.1.1. To return to the original issue, does opening the IPA installed in 1.1.1 in 2.0.0 cause the same no-window issue experienced before?

**Comment by IsaacMarovitz** [comment]
Reopening cause this issue has cropped up again.

1.1.1 -> Nightly 113
Game: Alchemy Stars 1.12.1
macOS Version: 12.4

Game would not install properly in 1.1.1, does install correctly in 2.0.0, but failed to open with window.

Attempting to install the same game on my machine in latest nightly running macOS Ventura, the game installed and ran as expected.

**Comment by the-jason-json** [comment]
Describe the bug:
The window for Honkai won't open even though the app icon shows in dock

Steps to reproduce:
tried to launch honkai
honkai not launching
I expect the game to launch fully and have a visible window to interact with.

No crash log i think

What version of PlayCover are you using?
2.0.0 alpha build

What version of macOS are you using?
Monterey (macOS 12)

Potential fix?
Uninstalling honkai and reinstalling in 1.1.1 allows it to run with a few errorsd
![image](https://user-images.githubusercontent.com/106799225/198784745-c8c907ab-d6e4-4458-acf0-96cf64aa9512.png)
![image](https://user-images.githubusercontent.com/106799225/198784796-edaddb31-95fb-4d2c-8eea-916919619369.png)
