### ISSUE TITLE
[Game Support]: Guardian Tales

### ISSUE THREAD

**Issue by j-fuxa** [PlayCover/PlayCover#404]
### App Store link

https://apps.apple.com/us/app/guardian-tales/id1485526957

### Current issues

- [ ] Game fails to install
- [ ] Game fails to open
- [x] Game crashes randomly during gameplay
- [ ] Game does not work with keymapping
- [ ] Game experiences graphical issues or broken UI
- [ ] Game fails to connect to servers or complete download

### More details

I'm unable to Sign in with my Apple or Google account into the game.
Also game randomly crashes aprox 30 secs after is opened. 
Sometimes when the games is launched only black screen is shown.

PD: I have to use pastebin for crashlog since maxium body is 65536 chars

### Crash log

```shell
https://pastebin.com/SX257JKR
```

### Issue Language

- [X] Yes my issue is written in English

**Comment by TheMoonThatRises** [comment]
Signing in with Google now works with the latest nightly version of PlayCover with PlayChain enabled (you can enable PlayChain through the app's settings -> Bypasses) (Note that signing in with Apple will not work and implementation that will be considered at some point in the future). Also, I have not experienced any crashes on the latest version.

**Comment by wlvrx** [comment]
@TheMoonThatRises does it still work for you? It keeps crashing for me after every 45 seconds or so
