### ISSUE TITLE
[Feature]: Improvements on import/export keymapping

### ISSUE THREAD

**Issue by 47thforce** [PlayCover/PlayCover#407]
### Is your feature request related to a problem?

Some games like Infinite Blade series or Noah's Heart only works via Sideloadly, and with PlayTools injected it is a life-saving tool to control the game without the controller. 

But the keymap will be deleted after closing the app and the players like me must take about 5 to 15 mins to setup keymapping before we can control the game.

### Describe the solution you'd like

So I think that how can we make Playtools can import/export keymapping directly on the menu bar for Sideloadly games. That will be a great improvement

### Anything else?

(just the keymap improvement request)

### Issue Language

- [X] Yes my issue is written in English

**Comment by a4840639** [comment]
Please also allow access to the app preference screen for exported app so users can, for example, toggle 'Gaming Mode' or select iOS device

**Comment by 47thforce** [comment]
> Please also allow access to the app preference screen for exported app so users can, for example, toggle 'Gaming Mode' or select iOS device

not that bruh. you can do that on Sideloadly???


That's the support request for PlayTools in Playtools-injected Sideloadly apps

**Comment by a4840639** [comment]
I am talking about this screen
<img width="522" alt="Screen Shot 2022-10-20 at 7 40 50 PM" src="https://user-images.githubusercontent.com/12200912/197098824-ccf89931-655b-4c9b-aae6-f0ecd1b40fb8.png">

Pretty sure it is related to your topic

**Comment by amirsaam** [comment]
@47thforce Gaming Mode is an option when toggled your mouse will be bind to keymap and in PlayCover you need to press Option key in-game to toggle in order to use the mouse pointer, what @a4840639 means is in your feature request devs make it possible to export this setting state to be used in Sideloadly, like when you toggled this option and export the game to Sideloadly, Gaming mode or Mouse Mapping state be exported too.

**Comment by 47thforce** [comment]
@a4840639 @amirsaam 
and your answer is not helpful at all. what I goddamn mean IS that we can import/export available keymapping while playing apps on Sideloadly IN THE MENU BAR. and before I created this enhancement request, I reported it to the mods in the discord 

<img width="290" alt="Ảnh chụp Màn hình 2022-10-21 lúc 18 26 53" src="https://user-images.githubusercontent.com/109323570/197185619-66e87170-17b0-4848-ad28-2927c07b0352.png">

**Comment by amirsaam** [comment]
Dude, that person meant that I asked to post it here was when dev wanna add your request consider that request too, what's the problem? Your request is already on devs todo list.

**Comment by JoseMoreville** [comment]
> @a4840639 @amirsaam and your answer is not helpful at all. what I goddamn mean IS that we can import/export available keymapping while playing apps on Sideloadly IN THE MENU BAR, and IN THE KEYMAPPING OPTION like the pic below. and before I created this enhancement request, I reported it to the mods in the discord
> 
> <img alt="Ảnh chụp Màn hình 2022-10-21 lúc 18 26 53" width="290" src="https://user-images.githubusercontent.com/109323570/197185619-66e87170-17b0-4848-ad28-2927c07b0352.png">
> 
> that thing I took from Noah's Heart

@47thforce Why so aggresive, i'm closing this post.
