### ISSUE TITLE
[Bug]: "Move to /Applications" Error with a Brew Installation

### ISSUE THREAD

**Issue by Moenupa** [PlayCover/PlayCover#412]
### Describe the bug

PlayCover version: 1.1.1
macOS version: 12.6

App Name: Genshin Impact
App Version: 3.1.0
What you have tried so far: Reinstalling PlayCover, reboot, Settings>Software Update
Xcode Version: 14.0.1

Description:
This happens after my upgrade of Xcode today, I have already go to settings > software update and shows 'up to date' (already installed command line tools update after xcode upgrade).

I have tried `brew reinstall playcover-community` and it keeps showing this when I open playcover again. There are sometimes prompt for installing cmdline update for `vtool` and `swift` during this process, and after finishing installation nothing is changed.

If I click on the prompted button, then playcover in `/Applications`  would be cracked and reduced to zero bytes.

I am very sure that before upgrading xcode playcover is working, and brew install playcover into the `/Application` folder.

Solution:
[My problem is already solved.] Downloading github distribution and replace the app in `/Applications`.

### Steps to reproduce

A originally working PlayCover brew installation, plus
an upgrade of Xcode along with cmdline tools.

### Expected behaviour

Something like this will show up.

<img width="777" alt="crash_prompt" src="https://user-images.githubusercontent.com/49304833/194906023-15c7eac4-a387-4fc0-a44d-2c715085ff67.png">

If you click the button, `/Applications/PlayCover.app` would be instantly shown as zero bytes and show a crack when opening again. There are no more prompt afterwards. You can not open the PlayCover any longer.

If you run `brew reinstall playcover-community` then it will repeat the same process.

### What version of PlayCover are you using?

1.1.1

### What version of macOS are you using?

Monterey (macOS 12)

### Issue Language

- [X] Yes my issue is written in English

**Comment by ohaiibuzzle** [comment]
Please launch a terminal, run `sudo xcrun cc`, agree to the terms and run PlayCover again
