### ISSUE TITLE
[Bug]: YouTube App's Login Status lost when close and restart.

### ISSUE THREAD

**Issue by caimofei** [PlayCover/PlayCover#418]
### Describe the bug

[Bug]: YouTube App's Login Status lost when close and restart.

### Steps to reproduce

[Bug]: YouTube App's Login Status lost when close and restart.

### Expected behaviour

[Bug]: YouTube App's Login Status lost when close and restart.

### What version of PlayCover are you using?

1.1.1

### What version of macOS are you using?

Monterey (macOS 12)

### Issue Language

- [X] Yes my issue is written in English

**Comment by ZhichGaming** [comment]
This is a known issue that happens with a lot of apps that require login.

**Comment by IsaacMarovitz** [comment]
@caimofei Try in nightly but otherwise there's likely not a lot we can do for this

**Comment by ZhichGaming** [comment]
> @caimofei Try in nightly but otherwise there's likely not a lot we can do for this

Would allowing access to group containers like Netflix change anything?

**Comment by IsaacMarovitz** [comment]
@ZhichGaming That's why I'm asking them to try nightly

**Comment by ZhichGaming** [comment]
Ah, I thought that the group containers change only affected Netflix specifically. My bad.

**Comment by aayushbhatia06** [comment]
How did you even get Youtube to work? I have tried so many IPAs and every single one of them crashes on start

**Comment by IsaacMarovitz** [comment]
Original issue is stale/presumed resolved
