### ISSUE TITLE
[Bug]: AudioMixerRenderThread

### ISSUE THREAD

**Issue by n-anantha** [PlayCover/PlayCover#422]
### Describe the bug

Whenever I open the Dislyte app, it works for a few seconds and then crashes. An error report window pops up saying I have an AudioMixerRenderThread numbered anywhere between 68 and 70. No idea what that means, have never done anything like this before either. Just trying to play a game I had on a phone I lost.

### Steps to reproduce

Download PlayCover, all the Xcode Command Line Tools, and download the Dislyte decrypted IPA from the discord.
Disable SIP and try to open: fails
Modify nvram boot-args: fails (the [sudo nvram boot-args="amfi_get_out_of_my_way=0x1 ipc_control_port_options=0"] version)
Modify nvram boot-args again: fails (the [sudo nvram boot-args="amfi_get_out_of_my_way=1"] version)
Look through discord for similar issues and asks for help: nothing
Come to github for help

### Expected behaviour

I expected the app to open and work without crashing in the first couple seconds.

### Crash log

```shell
Translated Report (Full Report Below)
-------------------------------------

Process:               XGame [1107]
Path:                  /Users/USER/Library/Containers/io.playcover.PlayCover/XGame.app/XGame
Identifier:            com.lilithgames.xgame.ios.global
Version:               3.1.0103 (0.1160)
Code Type:             ARM-64 (Native)
Parent Process:        launchd [1]
User ID:               501

Date/Time:             2022-10-14 16:09:20.6927 -0700
OS Version:            macOS 12.6 (21G115)
Report Version:        12
Anonymous UUID:        4473F6F5-CA07-71EF-44A8-38D1EEF331EB


Time Awake Since Boot: 780 seconds

System Integrity Protection: disabled

Crashed Thread:        70  AudioMixerRenderThread(1)

Exception Type:        EXC_BAD_ACCESS (SIGSEGV)
Exception Codes:       KERN_INVALID_ADDRESS at 0x0000000000000000
Exception Codes:       0x0000000000000001, 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFY

Termination Reason:    Namespace SIGNAL, Code 11 Segmentation fault: 11
Terminating Process:   exc handler [1107]

VM Region Info: 0 is not in any region.  Bytes before following region: 4310564864
      REGION TYPE                    START - END         [ VSIZE] PRT/MAX SHRMOD  REGION DETAIL
      UNUSED SPACE AT START
--->  
      __TEXT                      100ee0000-1046f0000    [ 56.1M] r-x/r-x SM=COW  ...ame.app/XGame
```

### What version of PlayCover are you using?

1.1.1

### What version of macOS are you using?

Monterey (macOS 12)

### Issue Language

- [X] Yes my issue is written in English

**Comment by n-anantha** [comment]
I just reenabled SIP, downloaded the latest Xcode thing from apple developer, tried the jailbreak bypass, and deleted and reinstalled the app data. Still not working, same error with different numbers (66, 68).
It looks like some kind of memory error. Maybe the Dislyte app package I downloaded is incomplete in some way and needs to be updated?

**Comment by TheMoonThatRises** [comment]
Unable to reproduce on the latest version. Works for me.
