### ISSUE TITLE
[Feature]: Borderless Gaming / Auto-Hide Title-Bar

### ISSUE THREAD

**Issue by Computron010** [PlayCover/PlayCover#423]
### Is your feature request related to a problem?

Not related to a problem

### Describe the solution you'd like

For a couple of reasons (PiP videos, Promotion not playing nice), I play games not in fullscreen exclusive mode. I use the window size setting to maximize the screen real-estate I can get, but there are a couple of additional vertical pixels we can take advantage of. 

Currently, the title bar of an app created by PlayCover is fixed and cannot be removed. Some macOS applications supports auto-hiding the title-bar when the mouse cursor is not active. One example of this is [IINA](https://github.com/iina/iina):

Title-bar is present when cursor is active:
<img width="363" alt="Screen Shot 2022-10-15 at 5 15 07 PM" src="https://user-images.githubusercontent.com/56774862/196007839-bd7b4493-694a-4868-977c-a214cc5b3744.png">

Title bar is absent when cursor is inactive:
<img width="368" alt="Screen Shot 2022-10-15 at 5 14 58 PM" src="https://user-images.githubusercontent.com/56774862/196007832-2ede6968-39da-4c47-83c8-dc02806d58b0.png">

The resolution of the window stays fixed.

### Anything else?

I'm not sure if it's possible to inject these changes into the app that is packaged, but perhaps one can start here:

https://developer.apple.com/documentation/appkit/nswindow/stylemask/1644698-borderless

Or how IINA implements it's fadeableViews: https://github.com/iina/iina/blob/42b19d59022ba6a2206806f26145ccece842155f/iina/MainWindowController.swift#L152

### Issue Language

- [X] Yes my issue is written in English

**Comment by JoseMoreville** [comment]
If I remember correctly, it is not possible to access style mask on catalyst apps yet as far as today. I'll take a look but so far is not priority

**Comment by IsaacMarovitz** [comment]
@JoseMoreville Catalyst limitations are not a concern as we have access to AppKit through AKInterface

**Comment by IsaacMarovitz** [comment]
Catalyst actually has a feature that can get us part of the way there: https://developer.apple.com/documentation/uikit/mac_catalyst/removing_the_title_bar_in_your_mac_app_built_with_mac_catalyst

**Comment by lushuyu** [comment]
@IsaacMarovitz Borderless mode is a solution to the frame drop bug in macOS Ventura (#462) If can not locate that full screen problem, a borderless mode can help.

**Comment by Computron010** [comment]
> Catalyst actually has a feature that can get us part of the way there: https://developer.apple.com/documentation/uikit/mac_catalyst/removing_the_title_bar_in_your_mac_app_built_with_mac_catalyst

There appears to be a bug related to this for Ventura and the solution appears to be building with Xcode 13.

https://developer.apple.com/forums/thread/716623

**Comment by IsaacMarovitz** [comment]
#481 will add this functionality.
