### ISSUE TITLE
[Game Support]: LifeAfter

### ISSUE THREAD

**Issue by perara-chen** [PlayCover/PlayCover#433]
### App Store link

https://apps.apple.com/us/app/lifeafter/id1441752845

### Current issues

- [ ] Game fails to install
- [X] Game fails to open
- [ ] Game crashes randomly during gameplay
- [ ] Game does not work with keymapping
- [ ] Game experiences graphical issues or broken UI
- [ ] Game fails to connect to servers or complete download

### More details

I tried to play LifeAfter with PlayCover. The game is installed with PlayCover and I can click the game icon. But after opening, a blank white window appears and it stacks forever. The ipa is from PlayCover's ipa repo and game version is 1.0.132. My macOS version is 12.6.

<img width="1480" alt="Screen Shot 2022-10-20 at 20 02 33" src="https://user-images.githubusercontent.com/104021043/196966199-8472d28a-9af2-4583-ace1-c329cf91c454.png">

### Issue Language

- [X] Yes my issue is written in English

**Comment by ZhichGaming** [comment]
Have you tried disabling SIP and nvram, as well as jailbreak detection bypass?

**Comment by perara-chen** [comment]
Yes, I tried everything mentioned in PlayCover docs. Also enabled jailbreak detection bypass.

**Comment by JoseMoreville** [comment]
Sorry not this one

**Comment by TheMoonThatRises** [comment]
Can you try the latest Nightly build with PlayChain enabled and see if that works (PlayChain is under the app's settings -> Bypasses)?

**Comment by TheMoonThatRises** [comment]
Closing in favor of #910.
