### ISSUE TITLE
[功能]：It is expected that keyboard mapping is enabled can also be disabled by Option (⌥).

### ISSUE THREAD

**Issue by zzz-one** [PlayCover/PlayCover#455]
### Is your feature request related to a problem?

When only keyboard mapping is enabled, using Option (⌥). cannot be disabled。Keyboard mapping can be disabled only after all mouse mapping is selected

### Describe the solution you'd like

It is expected that  keyboard mapping is enabled can also be disabled by Option (⌥).

### Anything else?

<img width="1198" alt="image" src="https://user-images.githubusercontent.com/78596294/198189682-00dd660a-4259-47b7-8fe7-881667b91e1a.png">

### Issue Language

- [X] Yes my issue is written in English

**Comment by gb-zh** [comment]
删除第三方输入法，改用系统自带的就没碰到过这个问题了

**Comment by zzz-one** [comment]
> 删除第三方输入法，改用系统自带的就没碰到过这个问题了

“输入法”只保留，简体拼音还是ABC，我把搜狗移除没卸载，仅开启键盘映射的时候还是不能option禁用

**Comment by IsaacMarovitz** [comment]
Stale/Its not entirely clear what this issue is referring to.
