### ISSUE TITLE
[Bug]: excessive CPU usage with playtools - swgoh

### ISSUE THREAD

**Issue by FrAcTi0N** [PlayCover/PlayCover#456]
### Describe the bug

While playing Start wars - galaxy of heroes, it is not possible to play it with playtools istalled. It uses too much cpu and mac is getting hot. If i uninstall playtools, cpu usage is much better and mac is not getting hot...
<img width="747" alt="swgoh-cpu-playtools" src="https://user-images.githubusercontent.com/26749550/198366975-639321af-1244-4f69-8324-3b37eb267adc.png">
<img width="747" alt="swgoh-cpu-noplaytools" src="https://user-images.githubusercontent.com/26749550/198366984-ff18a8b1-94a6-416c-add0-edd48c4087f1.png">

### Steps to reproduce

Install swgoh with playtools and run it

### Expected behaviour

Low CPU usage even with playtools installed and no overheating.

### What version of PlayCover are you using?

Nightly/beta

### What version of macOS are you using?

Ventura (macOS 13)

### Issue Language

- [X] Yes my issue is written in English

**Comment by IsaacMarovitz** [comment]
Should be fixed in 2.0.2
