### ISSUE TITLE
[Bug]: already signed in icloud message everytime focusing the game window

### ISSUE THREAD

**Issue by FrAcTi0N** [PlayCover/PlayCover#457]
### Describe the bug

While playing Start wars - galaxy of heroes, if focus is on any other window, then right after you focus the swgoh window, you get a message that you are already signed in. You can continue into the game by selecting "use my account", but it is really annoying.

<img width="477" alt="Screenshot 2022-10-27 at 20 17 54" src="https://user-images.githubusercontent.com/26749550/198369775-df0ca01e-cd49-4fb5-9cc4-6cb5ae5f6532.png">

### Steps to reproduce

Start SWGOH game, click on any other window and then click into the game window.

### Expected behaviour

After you focus SWGOH game window, you don't get icloud already logged in message window and you get straight into the game.

### What version of PlayCover are you using?

Nightly/beta

### What version of macOS are you using?

Ventura (macOS 13)

### Issue Language

- [X] Yes my issue is written in English

**Comment by IsaacMarovitz** [comment]
Game Center games don't work in PlayCover.

**Comment by FrAcTi0N** [comment]
well, the game works in playcover, it just display that anoying message window everytime you focus the game window...

**Comment by lewisxy** [comment]
I experienced the same issue in (PlayCover 2.0.2) another game-center-enabled game. Game Center doesn't work (which is fine for me). But the pop up (every time window is focused) is quite annoying. It's appreciated if this can be fixed.

**Comment by treyturner** [comment]
I'm also wishing something could be done about this. I don't think anyone expects Game Center to work, we're just wondering if it's possible to prevent the window from opening. I'm new to macOS, but am wondering if it'd be possible to automate something if it can't be addressed in PlayCover.

**Comment by ohaiibuzzle** [comment]
@treyturner Technically, yes!
You can make a shell script with a while loop that kill `gamed` every 5-10s
The issues is that Apple themselves no longer read the `Disabled` key in the Defaults database for Game Center, and you can't unload the service due to SIP
But since it's running as your user, not system, you can just kill it repeatedly
