### ISSUE TITLE
[Bug]: Failed to read data because it is not in the correct format

### ISSUE THREAD

**Issue by WaBiKong** [PlayCover/PlayCover#461]
### Describe the bug

When I open the paycover, the small window keeps showing up (problem encountered: Failed to read data because it's not in the correct format) and can't close

### Steps to reproduce

When I open the paycover, the small window keeps showing up (problem encountered: Failed to read data because it's not in the correct format) and can't close

### Expected behaviour

Similar small window displays no longer appear

### What version of PlayCover are you using?

1.1.1

### What version of macOS are you using?

Ventura (macOS 13)

### Issue Language

- [X] Yes my issue is written in English

**Comment by afdallah** [comment]
I also experience this issue

**Comment by Crowley-Yao** [comment]
yes i have same issues after upgrading to Ventura...

**Comment by ZhichGaming** [comment]
Please update to the prerelease.

**Comment by WaBiKong** [comment]
> I also experience this issue

do you know how to solve it?

**Comment by Crowley-Yao** [comment]
> > I also experience this issue
> 
> do you know how to solve it?

please try this pre-release version. https://github.com/PlayCover/PlayCover/releases/tag/2.0.0-alpha.2
