### ISSUE TITLE
[Bug] Virtual Touch “frame drop” in macOS Ventura in Full-screen Genshin

### ISSUE THREAD

**Issue by lushuyu** [PlayCover/PlayCover#462]
### Describe the bug

After updating to macOS Ventura, when playing Genshin, the Virtual Touch(Camera rotation) becomes stuck with frame drop. Both the latest and oldest versions have this problem.

- When using gamepad, all things work fine.
- (Interesting) When I try to record the screen with a software called iShot, the problem solved, it becomes fine.

Maybe there's a problem with the virtual touch component.

### Steps to reproduce

updating macOS Ventura 

### What version of PlayCover are you using?

Nightly/beta

### What version of macOS are you using?

Ventura (macOS 13)

### Issue Language

- [X] Yes my issue is written in English

**Comment by lushuyu** [comment]
Added: 60fps doesn't have this problem. The issue only occurs when 120fps is enabled, regardless of the quality options

**Comment by lushuyu** [comment]
<img width="1548" alt="image" src="https://user-images.githubusercontent.com/27007632/198589599-9325c1ef-0650-4703-a150-035d9eaef10b.png">
unusual frame drop

**Comment by ZhichGaming** [comment]
This has been a known issue for a long time but it has increased lately. We haven't gotten time to test it though.

**Comment by lushuyu** [comment]
> This has been a known issue for a long time but it has increased lately. We haven't gotten time to test it though.

so I am trying to degrade my Mac😂

**Comment by afdallah** [comment]
I'm experiencing the same in ventura. Setting is on 60 fps, when moving/combat can drop until 48 - 50 fps. 

[edit]: frame rate even drop when the graphic setting set to low

**Comment by lushuyu** [comment]
!important

This issue is resolved when playing in windowed mode, with only occasional and very slight frame drops. DO NOT play game in full-screen can temporarily avoid meeting this problem. 

> This has been a known issue for a long time but it has increased lately. We haven't gotten time to test it though.



> I'm experiencing the same in ventura. Setting is on 60 vps, when moving/combat can drop until 48 - 50 fps.
> 
> [edit]: frame rate even drop when the graphic setting set to low

**Comment by afdallah** [comment]
Reducing the screen and game resolution also help, I was able to play in 60 fps steadily. in my case, I use 1440 x 900

**Comment by IsaacMarovitz** [comment]
PlayTools has numerous performance and stability issues right now. Since the majority of Mac displays can only show up to 60 Hz anyway, I recommend leaving the 120 FPS option alone for now. We have future PlayTools refactors planned that should alleviate these performance issues.

**Comment by IsaacMarovitz** [comment]
Should be fixed or improved in 2.0.2 and macOS 13.1
