### ISSUE TITLE
[Bug]: Can't validate date in iOS datepicker

### ISSUE THREAD

**Issue by txreplay** [PlayCover/PlayCover#463]
### Describe the bug

When a datepicker is opened, I can scroll through days, months and years and click on "Cancel" but I can't click on "Done" to validate the date. 

Tested on 1.1.1 and 2.0.0 nightly

### Steps to reproduce

- Open a native iOS datepicker
- Select any date
- Click on "Done"
- Nothing happen

### Expected behaviour

When i click on "Done" it should validate my date and close the datepicker option

### What version of PlayCover are you using?

1.1.1

### What version of macOS are you using?

Monterey (macOS 12)

### Issue Language

- [x] Yes my issue is written in English

**Comment by TheMoonThatRises** [comment]
Could you provide an example app?

**Comment by txreplay** [comment]
I have this error on the "campfire" app (Niantic), who request a date of birth before acceding the app

**Comment by TheMoonThatRises** [comment]
Try install the app without injecting PlayTools, or remove PlayTools in settings (under Misc).

**Comment by TheMoonThatRises** [comment]
Try updating to the latest version of PlayCover and the advice above (stale).
