### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by yiluoegit** [PlayCover/PlayCover#465]
### Describe the bug

启动应用后循环提示这个错误。
This error is prompted circularly after the application is started.
<img width="1920" alt="截屏2022-10-30 10 24 56" src="https://user-images.githubusercontent.com/76962284/198859873-b1ce4994-ec8d-446b-b79c-7f11fe0b5a3c.png">

### Steps to reproduce

每次重新启动应用，即便我更新了版本。
Every time I restart the app, even if I update the version.

### Expected behaviour

它应该没有弹窗进而正确的运行。
It should run correctly without pop ups.

### What version of PlayCover are you using?

1.1.1

### What version of macOS are you using?

Monterey (macOS 12)

### Issue Language

- [X] Yes my issue is written in English

**Comment by aesophor** [comment]
I encountered this bug as well.

![Screenshot 2022-10-30 at 9 51 21 PM](https://user-images.githubusercontent.com/32998585/198882197-6526ef7a-657a-4b53-b3be-01e6aa5fcc20.png)

**Comment by xiaocheng-bili** [comment]
I encountered this bug as well.

<img width="515" alt="image" src="https://user-images.githubusercontent.com/74574034/199199368-da28d9fc-02c4-48a0-9ddc-27809d662f7f.png">

press OK 

<img width="522" alt="image" src="https://user-images.githubusercontent.com/74574034/199199921-53227f2a-6b85-480c-b23c-13be5e8319bc.png">

**Comment by xiaocheng-bili** [comment]
<img width="504" alt="image" src="https://user-images.githubusercontent.com/74574034/199199579-f99efebf-e2be-4dcd-a50c-0dfc40472565.png">
press OK

**Comment by IsaacMarovitz** [comment]
Update to PlayCover 2.0.0
