### ISSUE TITLE
[Bug]: PlayCover's Issue related to Mouse Keymapping

### ISSUE THREAD

**Issue by JunoNowOrNever** [PlayCover/PlayCover#466]
### Describe the bug

The Apps installed via PlayCover cannot unfocus and refocus 
After unfocusing, the Apps become not able to use the menu features such as fullscreen

### Steps to reproduce

1. Uncheck/disable the Mouse Keymapping for an App
2. Create any Keymapping
3. Save the Keymapping
4. Unfocus the App
5. Refocus the App

### Expected behaviour

Cannot refocus on the Apps
Only able to refocus after enabling the Mouse Keymapping

### What version of PlayCover are you using?

Nightly/beta

### What version of macOS are you using?

Ventura (macOS 13)

### Issue Language

- [X] Yes my issue is written in English

**Comment by IsaacMarovitz** [comment]
Stale/presumed fixed
