### ISSUE TITLE
[Bug]: Genshin Impact Unexpected exit in osx 13

### ISSUE THREAD

**Issue by shi1993911119** [PlayCover/PlayCover#468]
### Describe the bug

when I  start a dungeon or click some button, the game exit.

### Steps to reproduce

start a dungeon or click some button

### Expected behaviour

fix it pls

### What version of PlayCover are you using?

Nightly/beta

### What version of macOS are you using?

Ventura (macOS 13)

### Issue Language

- [X] Yes my issue is written in English

**Comment by ZhichGaming** [comment]
Try some other versions of playcover.

**Comment by shi1993911119** [comment]
just happen in 
[Pre-release 2.0.0-alpha.2](https://github.com/PlayCover/PlayCover/releases/tag/2.0.0-alpha.2)

**Comment by Depal1** [comment]
Could you provide some logs? Otherwise we are in the dark.

**Comment by shi1993911119** [comment]
how can I find logs

**Comment by shi1993911119** [comment]
hi，how can i get logs


在 2022年10月31日 ***@***.***> 写道：


Could you provide some logs? Otherwise we are in the dark.

**Comment by ESWZY** [comment]
@Depal1 I met the same problem. I can provide some logs.

At the startup of the PlayCover:

<img width="900" alt="image" src="https://user-images.githubusercontent.com/32200887/199018825-d6c3ab74-a79f-48b4-b564-2acf67f0cba6.png">

<img width="900" alt="image" src="https://user-images.githubusercontent.com/32200887/199019044-04597c74-dde8-4a0b-886e-bb048981342b.png">

After click applications just like Genshin Impact:

<img width="665" alt="image" src="https://user-images.githubusercontent.com/32200887/199019455-f27b49ab-db59-422c-88fa-b5801d29c2f2.png">

<img width="665" alt="image" src="https://user-images.githubusercontent.com/32200887/199019485-bf1b6a79-a2b0-4cb6-9386-c486f04d1087.png">

<img width="665" alt="image" src="https://user-images.githubusercontent.com/32200887/199019512-edfef5ea-2e88-467d-99b4-464d2d2cf657.png">

**Comment by shi1993911119** [comment]
hi bros,i know something about this bug:When I start game in  external monitor, and click some button or start a dungeon, the game Unexpected exist;When I start game in MacBook's monitor, the game all going well;When i start game in any monitor, and start dungeon in MacBook's monitor, the game all going well, and then I move game to external monitor and start dungeon again, the game all going well. I hope these things will help you。

**Comment by PascalTemel** [comment]
I'm having crashes as soon as I open my character menu on the 16' MacBook Pro, using [2.0.0-alpha.2]

**Comment by fruitcatt** [comment]
#  ##[](url)
<img width="873" alt="Снимок экрана 2022-11-06 в 01 29 01" src="https://user-images.githubusercontent.com/117546488/200143786-dd6e311a-b264-4a02-b89c-c325bebbaa3d.png">

**Comment by fruitcatt** [comment]
> ### Опишите ошибку
> когда я запускаю подземелье или нажимаю какую-либо кнопку, игра завершается.
> 
> ### Шаги для воспроизведения
> запустите подземелье или нажмите какую-нибудь кнопку
> 
> ### Ожидаемое поведение
> исправьте это, пожалуйста
> 
> ### Журнал сбоев
> _Ответа нет_
> 
> ### Какую версию PlayCover вы используете?
> Каждую ночь / бета-версия
> 
> ### Какую версию macOS вы используете?
> Ventura (macOS 13)
> 
> ### Issue Language
> * [x]  Yes my issue is written in English

![GenshinImpact-2022-11-06-011224](https://user-images.githubusercontent.com/117546488/200143822-03a7c7a1-3605-44eb-92db-5a3909a09d5d.jpeg)

**Comment by glimmercassidy** [comment]
Adding info here as per Zhich on discord, also this seems to be working fine now when I changed Aspect Ratio. Nevertheless, putting it here for visibility. 

• PlayCover version: 2.0.0 (118)
• :macos: macOS version: macOS Monterey 12.6

• App name: Genshin Impact
• App version: 3.2
• What you've tried so far: Reinstall Playcover and GI, Reboot mac, Change the Graphics and Resolution on GI settings (Tried: iPad Pro 3rd/5th, Aspect Ration 16.9)

• Issue description: Everytime I change party or team, the app crashes. (Paimon option -> Party Setup), reading through the past issues, Aspect Ratio 16:10 seems to work fine. Will update this thread if problem persists.

**Comment by ZhichGaming** [comment]
According to Chi#1739 on Discord, only 16:9 crashes.

**Comment by IsaacMarovitz** [comment]
Stale/presumed fixed
