### ISSUE TITLE
[Bug]: Is PlayTools Installed icon not updating

### ISSUE THREAD

**Issue by TheMoonThatRises** [PlayCover/PlayCover#470]
### Describe the bug

When installing an app that already exists in the library, the is PlayTools installed icon does not update if it is installed with/out PlayTools.

### Steps to reproduce

1. Have an app already installed
2. Re-install the app without PlayTools if it is already installed, or with if it doesn't

### Expected behaviour

The icon will update and correctly show if the app has or does not have PlayTools.

### What version of PlayCover are you using?

Nightly/beta

### What version of macOS are you using?

Ventura (macOS 13)

### Issue Language

- [X] Yes my issue is written in English

**Comment by IsaacMarovitz** [comment]
Fixed in #484
