### ISSUE TITLE
[App Support]: Genshin Impact

### ISSUE THREAD

**Issue by Khoinguyen119905** [PlayCover/PlayCover#477]
### App Store link

https://apps.apple.com/app/id1517783697

### Current issues

- [ ] App fails to install
- [X] App fails to open
- [ ] App crashes randomly during usage
- [ ] App experiences graphical issues or broken UI
- [ ] App fails to connect to servers
- [ ] Other

### More details

i downloaded the ipa but when i try to open it says its open but there are no windows showing its open

### Issue Language

- [X] Yes my issue is written in English

**Comment by IsaacMarovitz** [comment]
This is a different issue. Genshin is entirely supported. If you are experiencing no window update to the latest nightly version available to download from the `Actions` section.

Then delete `com.miHoYo.GenshinImpact.plist` in `~/Library/Containers/PlayCover/Entitlements`, uninstall Genshin Impact and re-install it.
