### ISSUE TITLE
[Bug]: Pop-ups when start PlayCover

### ISSUE THREAD

**Issue by ZhaoRibo** [PlayCover/PlayCover#478]
### Describe the bug

When I start PlayCover on my M1 MacBook Pro, a series of pop-ups appear immediately. The two pop-ups keep switching a lot of times before disappearing when I click the button on them.
<img width="284" alt="截屏2022-11-02 15 32 08" src="https://user-images.githubusercontent.com/44902865/199428953-94d23c0d-391d-4e69-927d-85c08a6621fb.png">
<img width="277" alt="截屏2022-11-02 15 32 16" src="https://user-images.githubusercontent.com/44902865/199429601-27368de9-3201-4575-ac56-9a7db059cca7.png">

### Steps to reproduce

easy to reproduce:
start PlayCover, or
click any game's icon to open it, or
click some other button may reproduce this bug

### Expected behaviour

no pop-ups

### What version of PlayCover are you using?

1.1.1

### What version of macOS are you using?

Ventura (macOS 13)

### Issue Language

- [X] Yes my issue is written in English

**Comment by IsaacMarovitz** [comment]
Update to 2.0.0
