### ISSUE TITLE
[Bug]: Playtools fail to install properly when spaces are present in the mac account name 

### ISSUE THREAD

**Issue by Hty-53** [PlayCover/PlayCover#479]
### Describe the bug

When installing an app, playtools fail to install, and requires manual injection. Upon manual injection, they successfully install, but they uninstall itself once playcover is closed, or if the Mac is restarted. This yields keymappings unusable as they require restarting of the Mac for them to start working, but playtools stop working after restart, causing an infinite loop.

### Steps to reproduce
Have an Mac account with at least one space in its name 

### Expected behaviour

Upon reopening of playcover, a warning mark will show up indicating that playtools are not installed. 

### Crash log

```shell
/
```

### What version of PlayCover are you using?

2.0.0 alpha 2 

### What version of macOS are you using?

Ventura (macOS 13)

### Issue Language

- [X] Yes my issue is written in English

**Comment by Depal1** [comment]
I can't replicate this issue, and my user name does have a space on it.

**Comment by TheMoonThatRises** [comment]
Can you try again with the latest version? Many things have changed since.

**Comment by Hty-53** [comment]
I probably wouldn't try it given that changing the name of an account on a mac is pretty annoying and risky, so let's just assume it has been fixed. Macos has been updated since i discovered this bug, so has playcover, it was alpha 1 but it is the official release now.

**Comment by IsaacMarovitz** [comment]
Fixed
