### ISSUE TITLE
[Bug]: VSCO app needs relogin everytime boots

### ISSUE THREAD

**Issue by Lorde627** [PlayCover/PlayCover#480]
### Describe the bug

I don't know why, VSCO needs me to log in every time when I close the app and reopen it.
https://decrypt.day/app/id588013838
Download link here~

### Steps to reproduce

1. open the playcover
2. open the VSCO app
3. the app needs me to log in everytime when I open it.

### Expected behaviour

can somebody help to fix the problem that every time I click the app and it requires me to log in? 

### Crash log

```shell
There's no log tho.
```

### What version of PlayCover are you using?

Nightly/beta

### What version of macOS are you using?

Ventura (macOS 13)

### Issue Language

- [X] Yes my issue is written in English

**Comment by TheMoonThatRises** [comment]
Should be fixed with the latest Nightly build with PlayChain enabled (under the app's settings -> Bypasses).
