### ISSUE TITLE
[Bug]: Genshin Impact crashes on in-app purchase related pages

### ISSUE THREAD

**Issue by greatoe** [PlayCover/PlayCover#482]
### Describe the bug

16" MacBook Pro M1 Max 2021, 64Gb RAM
macOS Ventura 13.0
PlayCover 2.0.0 alpha 2
Genshin Impact CN version - Yuanshen 3.2.0 - ipa downloaded from decrypt.day

The app crashes when I click/push the buttons to the following pages
- Wish
- Battle Pass

I realized that both the pages are in-app purchase  related.
No other page found will cause similar issue.

### Steps to reproduce

Click/push the Wish button/icons or the Battle Pass button/icon in the game.

### Expected behaviour

load the corresponding page

### What version of PlayCover are you using?

Nightly/beta

### What version of macOS are you using?

Ventura (macOS 13)

### Issue Language

- [X] Yes my issue is written in English

**Comment by IsaacMarovitz** [comment]
We do not and do not plan to support in-app purchases within PlayCover in any app. These must be completed on an actual device.

**Comment by greatoe** [comment]
It's fine not purchasing in the app, but could you please make the app don't crash?

**Comment by RarogCmex** [comment]
@greatoe I'm not playcover developer, but it seems requires a lot of work with creating Apple App store stubs. Feel free to contribute.
