### ISSUE TITLE
[Feature]: Allow custom path for app storage

### ISSUE THREAD

**Issue by ugzhu** [PlayCover/PlayCover#485]
### Is your feature request related to a problem?

Running out of storage on mac internal drive

### Describe the solution you'd like

I hope Playcover will allow saving app data into an external drive (SD card, for example)

### Anything else?

no

### Issue Language

- [X] Yes my issue is written in English

**Comment by ZhichGaming** [comment]
I don't think this is possible as most apps will store data in the original location, so in ~/Library/Application Support or something of the sort.

**Comment by ohaiibuzzle** [comment]
Sorry, but this would be near-impossible to manage.
Even if you manage to move the app files to an external disk, the app data cannot. They must stay in your user home directory, and moving these files out is not at all easy (See: #473)
And even if you manage all of the above stuff, well, there is no way for PlayCover to reliably keep track of your apps
