### ISSUE TITLE
[Bug]: Can‘t use playcover on MacOS 13

### ISSUE THREAD

**Issue by lumoshhx** [PlayCover/PlayCover#486]
### Describe the bug

When I open playcover, the error appears, the screenshot as below: 
<img width="296" alt="image" src="https://user-images.githubusercontent.com/36717399/199675629-dab81bc6-805b-4bfb-a0ec-d913ba253d81.png">
<img width="296" alt="image" src="https://user-images.githubusercontent.com/36717399/199675651-c1219bf6-9c69-4adb-af93-2c24fbc06e83.png">

### Steps to reproduce

Open playcover on MacOS 13

### Expected behaviour

Fix the error and can run the game.

### What version of PlayCover are you using?

1.1.1

### What version of macOS are you using?

Ventura (macOS 13)

### Issue Language

- [X] Yes my issue is written in English

**Comment by Hty-53** [comment]
1.1.1 is broken use 2.0.0 alpha

**Comment by lumoshhx** [comment]
where to get Version 2.0.0?

**Comment by IsaacMarovitz** [comment]
You can download the 2.0.0 Alpha from the release page.
