### ISSUE TITLE
[Bug]: Unstoppable prompts "Some error happened! The data couldn’t be read because it isn’t in the correct format." and "Unable to retrieve store!"

### ISSUE THREAD

**Issue by iF2007** [PlayCover/PlayCover#490]
### Describe the bug

The following two prompts keeps popping out and they are unstoppable. As soon as you click on one, the other one pops out and keeps going and going.

![image](https://user-images.githubusercontent.com/4461848/199867174-623a0e0c-d7f9-4464-aaed-4a20a3143b3b.png)

<img width="260" alt="image" src="https://user-images.githubusercontent.com/4461848/199867191-699a1221-63ed-4490-8b6e-27185d073b24.png">.

However, if you can somehow click on the sideloaded app despite that the prompts keep popping out, the app runs without any issues.

### Steps to reproduce

Open PlayCover and gives the above two prompts unstoppable

### Expected behaviour

No such prompts

### What version of PlayCover are you using?

1.1.1

### What version of macOS are you using?

Ventura (macOS 13)

### Issue Language

- [X] Yes my issue is written in English

**Comment by Candygoblen123** [comment]
Update your play cover

**Comment by iF2007** [comment]
> Update your play cover

It's the latest version @Candygoblen123 

<img width="284" alt="image" src="https://user-images.githubusercontent.com/4461848/199878324-5e5bf828-c647-4ba8-8232-23cb4e93b76a.png">

**Comment by iF2007** [comment]
Can confirm [Pre-release 2.0.0-alpha.2](https://github.com/PlayCover/PlayCover/releases/tag/2.0.0-alpha.2) solves the issue
