### ISSUE TITLE
[Bug]: Genshin on mac os 13, quit unexpectedly

### ISSUE THREAD

**Issue by loveaeen** [PlayCover/PlayCover#492]
### Describe the bug

The program can run, but when I click any button, such as backpack, settings, Genshin Impact will quit unexpectedly
[genshin crash.txt](https://github.com/PlayCover/PlayCover/files/9934723/genshin.crash.txt)

### Steps to reproduce

playcover 2.0.0
mac ventura

### Expected behaviour

can somebody help to fix the problem

### Crash log

```shell
There's no log.
```

### What version of PlayCover are you using?

Nightly/beta

### What version of macOS are you using?

Ventura (macOS 13)

### Issue Language

- [X] Yes my issue is written in English

**Comment by xdrond** [comment]
I have same problem. Workaround: change 4k resolution in app settings in playcover to something else(2560x1440 for example)🫠

**Comment by loveaeen** [comment]
@xdrond Thanks bro, I found problem , Because I set the screen of the mac to have more space.
