### ISSUE TITLE
[Game Support]: Taptitans2

### ISSUE THREAD

**Issue by jasonchxi** [PlayCover/PlayCover#497]
### App Store link

https://apps.apple.com/us/app/tap-titans-2-hero-legends/id1120294802

### Current issues

- [ ] Game fails to install
- [ ] Game fails to open
- [ ] Game crashes randomly during gameplay
- [ ] Game does not work with keymapping
- [ ] Game experiences graphical issues or broken UI
- [X] Game fails to connect to servers or complete download

### More details

Stuck in initializaing and wont load into the game

### Issue Language

- [X] Yes my issue is written in English

**Comment by TheMoonThatRises** [comment]
Tap Titans 2 only works with PlayTools removed. You can remove PlayTools by going to the app's Settings -> Misc -> Remove PlayTools.
