### ISSUE TITLE
[Game Support]: LEGO® Builder's Journey

### ISSUE THREAD

**Issue by HomeStarRunnerTron** [PlayCover/PlayCover#498]
### App Store link

https://apps.apple.com/us/app/lego-builders-journey/id1466965366

### Current issues

- [ ] Game fails to install
- [X] Game fails to open
- [ ] Game crashes randomly during gameplay
- [ ] Game does not work with keymapping
- [ ] Game experiences graphical issues or broken UI
- [ ] Game fails to connect to servers or complete download

### More details

This game actually worked before the last update, but now, when try to revert to an older version, it still doesn't work! Unsure of what changed. It could even just be a specifically-my-computer problem, but every other program and game I was using before still works! I install Builder's Journey now, and then immediately get this message:

<img width="372" alt="zasillyhahaha" src="https://user-images.githubusercontent.com/67088659/200106802-cb856f48-5cc3-40dc-8c37-e199b66932a5.png">

Should I, like, delete some preferences or something?

### Issue Language

- [X] Yes my issue is written in English

**Comment by aljustiet01** [comment]
The same issue

**Comment by TheMoonThatRises** [comment]
Fixed by PR #602. Besides that, the game is available on Mac through Apple Arcade.
