### ISSUE TITLE
Change logo

### ISSUE THREAD

**Issue by Depal1** [PlayCover/PlayCover#5]
I think we don't know who designed the original logo, so it would probably be better to change it. I have quickly designed a possible replacement, but I think there might be other avid designers that might want to propose something more sophisticated.

**Comment by Depal1** [comment]
![PlayCoverIcon](https://user-images.githubusercontent.com/47154119/178414684-d57571b9-3ff4-49b9-96d1-49a54483b1a4.png)
A not so barebones version.

**Comment by ZhichGaming** [comment]
![PlayCoverIconDepalv2](https://user-images.githubusercontent.com/93055907/178419951-3e8ae885-1df4-49b0-b7bd-845cb71201e8.png)
I thought this should have a little more padding so here ya go

**Comment by Depal1** [comment]
@ZhichGaming It does look better that way.

**Comment by JoseMoreville** [comment]
It looks great, although i think i'd look better without that outerglow.

**Comment by brylleobra** [comment]
Better without the outerglow

**Comment by DeviousM** [comment]
Can't this one be used tho? https://avatars.githubusercontent.com/u/108947908
I'd argue that it's cleaner, less retro-y and original enough (IMO proposition from this thread looks like a PS1/PS2 emulator logo 😅)

**Comment by ZhichGaming** [comment]
> Can't this one be used tho? ![PlayCover Github Logo](https://avatars.githubusercontent.com/u/108947908)
> 
> It's already used as a GH logo and I'd argue that it's cleaner, less retro-y and original enough (IMO proposition from this thread looks like a PS1/PS2 emulator logo 😅)

Yep, it has been decided already that the PlayCover community logo will be changed to this.

**Comment by Depal1** [comment]
Indeed, it was agreed upon to use the latter. This issue will remain open until such icon gets included on a stable build and on the readme.

**Comment by Animenosekai** [comment]
> Can't this one be used tho? ![PlayCover Github Logo](https://avatars.githubusercontent.com/u/108947908)

I think the vignette makes it less clear though, but it's just my opinion, and overall the logo is really good 👍
