### ISSUE TITLE
[Bug]: No sound after upgrading to beta version

### ISSUE THREAD

**Issue by hsuyelin** [PlayCover/PlayCover#507]
### Describe the bug

before version: 1.1.1
after version: 2.0.0-beta.1

after installing the app, no matter how I adjust the sound, the sound in the app is invalid

### Steps to reproduce

must-occur problem, occurred in version 1.1.1 upgrade to 2.0.0-beta.1

### Expected behaviour

sound can be played normally

### What version of PlayCover are you using?

Nightly/beta

### What version of macOS are you using?

Ventura (macOS 13)

### Issue Language

- [X] Yes my issue is written in English

**Comment by IsaacMarovitz** [comment]
No other reports of this in the final version of 2.0.0+, presumed fixed
