### ISSUE TITLE
[Game Support]: Pokémon Masters EX didnt work

### ISSUE THREAD

**Issue by jinny155359** [PlayCover/PlayCover#508]
### App Store link

https://apps.apple.com/tw/app/pokémon-masters-ex/id1442061397

### Current issues

- [ ] Game fails to install
- [X] Game fails to open
- [X] Game crashes randomly during gameplay
- [ ] Game does not work with keymapping
- [ ] Game experiences graphical issues or broken UI
- [ ] Game fails to connect to servers or complete download

### More details

•  PlayCover version: Playcover 2.0.0-beta.1 
•  macOS version: MacOs ventura 13.0.1

• App name: Pokémon Masters EX
• App version: 2.26.0
• What you've tried so far: everytime i open it tell me that time was wrong has to reopen the app and crash

### Issue Language

- [X] Yes my issue is written in English

**Comment by jinny155359** [comment]
![截圖 2022-11-15 下午4 22 26](https://user-images.githubusercontent.com/117734353/201870196-f10f1c86-f652-4f21-86a3-fe50b827c72e.png)

**Comment by jinny155359** [comment]
after I try SIP it does work. But the problem change to game crush easily

**Comment by TheMoonThatRises** [comment]
Closing in favour of #751.
