### ISSUE TITLE
[Bug]: About Keyboard Mapping Does Not Work

### ISSUE THREAD

**Issue by bakeXu** [PlayCover/PlayCover#519]
### Describe the bug

When playing Genshin Impact, the keyboard mapping will suddenly fail 。
Symptom：
1. Press command+k to open the mapping position, but press command+k again and it cannot be closed;
2. Press option and there is no response;

### Steps to reproduce

The triggering conditions do not seem fixed.

1. This will happen after playing for a period of time;

2. Switch window, but it may not be triggered immediately;

3. Close the display of the macbook, but it may not be triggered immediately

### Expected behaviour

I hope this situation can be controlled.

### Crash log

```shell
No log printing.
```

### What version of PlayCover are you using?

Nightly/beta

### What version of macOS are you using?

Ventura (macOS 13)

### Issue Language

- [X] Yes my issue is written in English

**Comment by IsaacMarovitz** [comment]
Presumed fixed in release 2.0.0+ and macOS 13.1
