### ISSUE TITLE
Install xTools button's color is not uniform with other buttons. 

### ISSUE THREAD

**Issue by ZhichGaming** [PlayCover/PlayCover#52]
It is not based on accent color.
<img width="1094" alt="Screen_Shot_2022-07-16_at_4 23 28_PM" src="https://user-images.githubusercontent.com/93055907/179371016-d92bbd37-334e-45ce-b273-d8d8c33fbd2a.png">

**Comment by JoseMoreville** [comment]
Thank you, will check it and fix it :)
