### ISSUE TITLE
[Bug]: The data cant be read after installed.

### ISSUE THREAD

**Issue by deergu** [PlayCover/PlayCover#523]
### Describe the bug

Cannot run playcover when first installed.
![471668774409_ pic](https://user-images.githubusercontent.com/118536184/202704915-28ae8694-9809-414d-a2fa-bcb7dfc73d67.jpg)
![481668774419_ pic](https://user-images.githubusercontent.com/118536184/202704918-10812609-4fb3-45d3-a40a-021aa09178cc.jpg)

### Steps to reproduce

Installed 1.1.1
Open the app and then showed the error.

My macbook pro is Apple M1 Pro MacOs 13.0

### Expected behaviour

Once opened Playcover, it will occur. 

### What version of PlayCover are you using?

1.1.1

### What version of macOS are you using?

Ventura (macOS 13)

### Issue Language

- [X] Yes my issue is written in English

**Comment by Candygoblen123** [comment]
Please download the 2.0 beta from our releases page. https://github.com/PlayCover/PlayCover/releases/tag/2.0.0-beta.1
