### ISSUE TITLE
[Bug]: Metal HUD preference not saved when closing PlayCover

### ISSUE THREAD

**Issue by FlyMeToTheMoonAndLetMePlayAmongTheStars** [PlayCover/PlayCover#526]
### Describe the bug

Metal HUD on/off toggle under game settings is not saved, happens for every game. 

Other toggles, like Enable Discord activity, disable display sleep, etc. are saved. 

So when you enable it and then close and reopen PlayCover, it defaults back to being disabled. 

### Steps to reproduce

1. open per-app/game settings
2. enable Metal HUD 
3. close app/game
4. close PlayCover
5. open PlayCover
6. check the toggle 

### Expected behaviour

The preference getting preserved on app close like all other options/toggles. 

### Crash log

```shell
N/A
```

### What version of PlayCover are you using?

Nightly/beta

### What version of macOS are you using?

Ventura (macOS 13)

### Issue Language

- [X] Yes my issue is written in English

**Comment by TheMoonThatRises** [comment]
For anyone interested, the reason why Metal HUD is not saved after each open of PlayCover is because it is saved only locally in the code. The way to have it saved is to add another option into the app's settings file.

**Comment by FlyMeToTheMoonAndLetMePlayAmongTheStars** [comment]
found a bug related to this setting, didn't feel the need to open up a new issue since i thought it could be related to what @TheMoonThatRises said above

if you enable metal HUD for an app, then click on IPA library and click back to the app library, and open the app settings, you'll see that the setting is also not saved in this scenario

**Comment by elisezhu123** [comment]
unfortunately, the metal in play cover is just a ui system its original method is just to use the metal api for us. the metal hud api itself can only be used when you use the code and it cannot be saved unless you forced it to add in the launcher environmental variable (but you still need to retype it in terminal after you close the mac). There is nothing to do of play cover to solve, it is just the way apple used to utilize the metalapi from its unix file each time and not preserved. If you really want  to force the metal hud used you can use /bin/launchctl setenv MTL_HUD_ENABLED 1 but this one is work for all the metal app so even the photoshop, Photo Booth it will all open metalhud as it used metal api
