### ISSUE TITLE
[Bug]: How to add a custom ContextMenuItem?

### ISSUE THREAD

**Issue by lstarboy** [PlayCover/PlayCover#529]
### Describe the bug

When I add a custom contextmenu item, I get a build error: Trailing closure passed to parameter of type 'ContextMenu<MenuItem>?' that does not accept a closure ( Generic parameter 'MenuItems' coudl not be inferred). But I only add a custom menuitem copyed from a existing one, I still get a error. The source code(In the file PlayAppView line 59) like:
                Button(action: {
                    app.showInFinder()
                }, label: {
                    Text("playapp.showInFinder")
                })
                Button(action: {
                    app.sign() // change here
                }, label: {
                    Text("playapp.showInFinder") // temp use the existing text
                })

### Steps to reproduce

Only add a custom menuitem at line 59 in PlayAppView  copyed from a existing one(line 54-58), and change the action to app.sign(),  save the file and build

### Expected behaviour

No build error

### What version of PlayCover are you using?

Nightly/beta

### What version of macOS are you using?

Monterey (macOS 12)

### Issue Language

- [X] Yes my issue is written in English

**Comment by IsaacMarovitz** [comment]
Issues are not a place to ask code-related questions.
