### ISSUE TITLE
[Bug]: "Unable to retrieve store!"when I open the playcover

### ISSUE THREAD

**Issue by Liziyu352** [PlayCover/PlayCover#533]
### Describe the bug

When I open the playcover , my mac pop out a issue window like this:
<img width="658" alt="截屏2022-11-21 11 01 33" src="https://user-images.githubusercontent.com/72553634/202954231-5e45fe2c-be1a-4d80-b494-b5b11663d653.png">

### Steps to reproduce

1:Make sure your Mac's system version is macOS Ventura.
2:use "brew install playcover"to install playcover.
3:install "genshin impact".
4:restart playcover and wait a few minute.
5:then the issue window will pop out.

### Expected behaviour

If you keep pressing enter ,the issue window will disappear.

### Crash log

```shell
......I do not have log......
```

### What version of PlayCover are you using?

1.1.1

### What version of macOS are you using?

Ventura (macOS 13)

### Issue Language

- [X] Yes my issue is written in English

**Comment by Liziyu352** [comment]
If anyone have the solution, please contact me:
BJ3158941721@icloud.com

**Comment by MinghongGao** [comment]
The same issue happened to me.

**Comment by MeloS7** [comment]
Same issue to me.

**Comment by ZhichGaming** [comment]
You can either update to 2.0 or spam the OK button.

**Comment by Liziyu352** [comment]
> You can either update to 2.0 or spam the OK button.
Thanks a lot.
I update to beta 2.0 and the problem is solves

**Comment by ZhichGaming** [comment]
This issue should have been fixed with this PR that just got merged: https://github.com/PlayCover/PlaySite/pull/32. Can you see if it still pops up and send a screenshot/video?

**Comment by IsaacMarovitz** [comment]
Fixed
