### ISSUE TITLE
[Bug]: Application quit when trying to open the application.

### ISSUE THREAD

**Issue by kevinle3212** [PlayCover/PlayCover#536]
### Describe the bug

The application quit unexpectedly. It happens after successfully uploading the IPA and trying to load the application.

### Steps to reproduce

1. Load IPA.
2. Launch the app.
3. Get error.

### Expected behaviour

I expected the application to open without any errors.

### Crash log

```shell
https://sourceb.in/c81EHgkNrA
```

### What version of PlayCover are you using?

Nightly/beta

### What version of macOS are you using?

Ventura (macOS 13)

### Issue Language

- [X] Yes my issue is written in English

**Comment by ZhichGaming** [comment]
To clarify, is PlayCover crashing or the app? What app did you try to run?

**Comment by kevinle3212** [comment]
> To clarify, is PlayCover crashing or the app? What app did you try to run?

The app is crashing, and PlayCover is still running. I tried loading a Minecraft IPA I exported and decrypted from my iOS device.

**Comment by ohaiibuzzle** [comment]
Have you tried reinstalling the app (using AppSync) on the same iOS device to verify that you have a good dump?

**Comment by ZhichGaming** [comment]
> > To clarify, is PlayCover crashing or the app? What app did you try to run?
> 
> The app is crashing, and PlayCover is still running. I tried loading a Minecraft IPA I exported and decrypted from my iOS device.

Then this issue does not have the necessary details and it is created under the Bug label instead of Game Support. Please edit your post to include these details: https://github.com/PlayCover/PlayCover/issues/new?assignees=&labels=game-support&template=GAME-SUPPORT.yml&title=%5BGame+Support%5D%3A+

**Comment by ZhichGaming** [comment]
Closed for #537.
