### ISSUE TITLE
[Game Support]: Minecraft IPA unexpectedly crashing.

### ISSUE THREAD

**Issue by kevinle3212** [PlayCover/PlayCover#537]
### App Store link

https://apps.apple.com/us/app/minecraft/id479516143

### Current issues

- [ ] Game fails to install
- [X] Game fails to open
- [ ] Game crashes randomly during gameplay
- [ ] Game does not work with keymapping
- [ ] Game experiences graphical issues or broken UI
- [ ] Game fails to connect to servers or complete download

### More details

When I open the Minecraft app, it doesn't open and the game crashes. 

### Crash log

```shell
https://sourceb.in/c81EHgkNrA
```

### Issue Language

- [X] Yes my issue is written in English

**Comment by ZhichGaming** [comment]
Where did you get your IPA from?

**Comment by kevinle3212** [comment]
> Where did you get your IPA from?

Well, on my first attempt I tried to dump it from my iOS device, I then checked and saw that it was damaged. I later searched for IPAs and got them from https://archive.org/details/minecraft-1.19.41

**Comment by Liziyu352** [comment]
> > Where did you get your IPA from?
> 
> Well, on my first attempt I tried to dump it from my iOS device, I then checked and saw that it was damaged. I later searched for IPAs and got them from https://archive.org/details/minecraft-1.19.41

Hey! the original system ipa file is encrypted! macOS installer and Playcover can't install the app. you can try this:https://decrypt.day/

**Comment by kevinle3212** [comment]
> > > Where did you get your IPA from?
> 
> > 
> 
> > Well, on my first attempt I tried to dump it from my iOS device, I then checked and saw that it was damaged. I later searched for IPAs and got them from https://archive.org/details/minecraft-1.19.41
> 
> 
> 
> Hey! the original system ipa file is encrypted! macOS installer and Playcover can't install the app. you can try this:https://decrypt.day/


I used that link and searched up the Minecraft IPA and the same issue still occurs with this error. https://sourceb.in/xZYuXxXblj

**Comment by ZhichGaming** [comment]
This issue is known to happen with some versions of Minecraft. The Minecraft IPA shouldn’t be on decrypt.day too since it is a paid app.

**Comment by amirsaam** [comment]
Minecraft requires SIP to be off in order to run.

**Comment by purpln** [comment]
Minecraft crashes on open due to NSInternalInconsistencyException 'Couldn't add the Keychain Item.'

Minecraft v1.19.50
PlayCover 2.0.0
MacOS 13.1

**Comment by ZhichGaming** [comment]
> Minecraft crashes on open due to NSInternalInconsistencyException 'Couldn't add the Keychain Item.'
> 
> Minecraft v1.19.50 downloaded from https://pdalife.to/minecraft-pocket-edition1-ios-a8721.html

PlayCover does not condone piracy.

**Comment by purpln** [comment]
> PlayCover does not condone piracy.

I've my minecraft purchase on different platforms (AppStore, PS Store and Microsoft Store). I've just provided game source to make opportunity for debugging

**Comment by TheMoonThatRises** [comment]
By the issue that is being described, the issue would probably be fixed by the latest nightly with PlayChain enabled. But regardless, Minecraft is a paid app. As Zhich said, we do not condone piracy.

**Comment by Shock9616** [comment]
Are there any workarounds/fixes for this crash? I've dumped a decrypted ipa from my iPad and it still crashes on PlayCover v3.0.0 (685)

**Comment by bleghj** [comment]
ive bought the game like 6 times, i just want to play minecraft on my mac.

microsoft could add bedrock to macs, but they dont. this seems like a great reason for piracy lmao

**Comment by s44237266-glitch** [comment]
Minecraft may crash on launch due to compatibility issues, a corrupted installation, or an outdated IPA version. Try reinstalling the app, ensuring your device meets the game's requirements, and using a properly signed IPA file.

For the latest Minecraft IPA versions, you can visit [Minecraft IPA](https://mincraftipa.com/) and download the most recent release for free. If the issue persists, please share your device model and iOS version for further troubleshooting.
