### ISSUE TITLE
[Bug]: Keyboard mapping not taking keyboard input

### ISSUE THREAD

**Issue by alanyan7** [PlayCover/PlayCover#541]
### Describe the bug

Game: Genshin Impact 3.2.0

* My mouse and keyboard works fine in all other applications
* Keyboard mapping editor can be opened with cmd + k
* Mouse can be unlocked with option key
* Keyboard mapping editor works fine with mouse input
* Keyboard mapping editor does not take keyboard input other than L/R shift and ctrl. No response when any other key is pushed.
* When in normal game mode, no keyboard input is taken other than L/R shift and ctrl.

Effort tried:
* Reinstalling playcover
* Switch between playcover nightly(2.0.0-beta.1) and 1.1.1

### Steps to reproduce

This might have started happening after I turned on the touch alternative and then off. 

### Expected behaviour

All keyboard keys work in normal game mode and keymap editor

### Crash log

```shell
N/A
```

### What version of PlayCover are you using?

1.1.1

### What version of macOS are you using?

Monterey (macOS 12)

### Issue Language

- [X] Yes my issue is written in English

**Comment by amirsaam** [comment]
try latest nightly build 
https://nightly.link/playcover/playcover/workflows/2.nightly_release/develop?status=completed

**Comment by IsaacMarovitz** [comment]
Presumed fixed in release 2.0.0+ and macOS 13.1

**Comment by alanyan7** [comment]
It stopped happening after several restarts, without any kind of upgrade/fix.

**Comment by Abedeen25** [comment]
The same is happening to me. I am using M2 MacBook Air with 16 GB RAM. After restarting genshin for 7-8 times only once did the keyboard inputs work. the mouse activity is being registered without any issues. My OS is 13.1 and Playcover v2.0.2
