### ISSUE TITLE
[Bug]: Being logged out after reenabling SIP

### ISSUE THREAD

**Issue by singhalrishi27** [PlayCover/PlayCover#543]
### Describe the bug

Apps Such as Hotstar and Reddit won't let you login after re-enabling SIP

### Steps to reproduce

Download Hotstar or Reddit IPA.
Disable SIP and add Boot args
Login as usual
app work just fine no matter what
enable SIP 
you will be logged out of SIP and can't log back in

### Expected behaviour

I should stay logged in even after SIP is enabled

### What version of PlayCover are you using?

Nightly/beta

### What version of macOS are you using?

Ventura (macOS 13)

### Issue Language

- [X] Yes my issue is written in English

**Comment by amirsaam** [comment]
Going through the troubleshoot login process doesn't guarantee logged in state for apps and game.
In fact some apps and games don't like to run on macOS environment that hard that won't accept that workaround.

**Comment by IsaacMarovitz** [comment]
Some apps will only work with SIP continuously disabled. Those instructions are designed primarily for Genshin and games like it and isn't guaranteed to work on all applications.

**Comment by singhalrishi27** [comment]
> Some apps will only work with SIP continuously disabled. Those instructions are designed primarily for Genshin and games like it and isn't guaranteed to work on all applications.

Hotstar previously worked fine on Monterey but now it logs you out I think after play cover update it started happening
