### ISSUE TITLE
[Bug]: Can't login to Immortal Diablo 

### ISSUE THREAD

**Issue by CodeMinerz** [PlayCover/PlayCover#545]
### Describe the bug

Hello, I want to play immortal diablo in my macbook but I can't log in in blizzard.net Im stuck in main page. : (

### Steps to reproduce

1. Open Play Cover.
2. Open Immortal Diablo
3. Login as Guest or Blizzard Account
4. Stuck in Main Screen.

### Expected behaviour

Connect to Blizzard.net

### What version of PlayCover are you using?

1.1.1

### What version of macOS are you using?

Ventura (macOS 13)

### Issue Language

- [X] Yes my issue is written in English

**Comment by amirsaam** [comment]
Please read docs before opening issues:
https://docs.playcover.io/getting_started/troubleshoot_login.html

**Comment by IsaacMarovitz** [comment]
Non-issue/stale
