### ISSUE TITLE
[Bug]:  Game Center prompt pops up when regaining focus on Umamusume

### ISSUE THREAD

**Issue by a4840639** [PlayCover/PlayCover#548]
### Describe the bug

Like the title suggests, Game Center prompt just pops up every time focus is regained on Umamusume.
[Example screenshot](https://imgur.com/a/JR4ZvWk)
It does not make the game unplayable but it is highly annoying because Umamusume is a game you tend to play in parallel with other tasks like looking for guide. 

Note that this behavior did not present on 0.9.2 and 0.9.5 may be the first version that has this behavior

### Steps to reproduce

1. Install any Playcover version newer than 0.9.2
2. Install any version of Umamusume (ウマ娘)
3. Launch the game
4. Switch to another window
5. Switch back to Umamusume

### Expected behaviour

There shoudl not be the pop-up

### What version of PlayCover are you using?

1.1.1

### What version of macOS are you using?

Monterey (macOS 12)

### Issue Language

- [X] Yes my issue is written in English

**Comment by amirsaam** [comment]
Games with Game Centre login will have this issue, you cannot login via GC because Apple doesn't allow it and it just keeps trying, there is no workaround for it.

**Comment by a4840639** [comment]
@amirsaam Why is not this an issue on 0.9.2, though? I was using 0.9.2 for this particular game because of this exact reason. However, 0.9.2 stopped with newly released IPAs in the recent weeks for some reason.
