### ISSUE TITLE
[Game Support]: Ragnarok Origin

### ISSUE THREAD

**Issue by mfg008** [PlayCover/PlayCover#552]
### App Store link

https://apps.apple.com/us/app/id1564896188

### Current issues

- [ ] Game fails to install
- [X] Game fails to open
- [ ] Game crashes randomly during gameplay
- [ ] Game does not work with keymapping
- [ ] Game experiences graphical issues or broken UI
- [ ] Game fails to connect to servers or complete download

### More details

Have followed all the instructions under Troubleshoot App Login Issues in the Playbook (including the alternative for modifying the nvram boot args) but still getting "Authorization Failed" error message when logging in on the app once I enable SIP.

### Issue Language

- [X] Yes my issue is written in English

**Comment by TheMoonThatRises** [comment]
The app is available on Mac's App Store. If you really need to use PlayCover, try with the latest nightly with PlayChain enabled (through the app's settings -> Bypasses).

**Comment by TheMoonThatRises** [comment]
Closing in favour of #955.
