### ISSUE TITLE
Changed code signature in version 2.0.0?

### ISSUE THREAD

**Issue by suschizu** [PlayCover/PlayCover#570]
### Describe the bug

version 1.1.1 was signed with: 
Andrew Glaze (RJNC97Y8QD) 

version 2.0.0 contains now
XIN LI (792V9HMJW3)

### Steps to reproduce

`codesign -dv --verbose=4 /Path/To/Application.app`

### Expected behaviour

can you confirm the changed code signature?

### What version of PlayCover are you using?

1.1.1

### What version of macOS are you using?

Monterey (macOS 12)

### Issue Language

- [X] Yes my issue is written in English

**Comment by Depal1** [comment]
Yes, I can confirm the changes.

**Comment by suschizu** [comment]
thanks!
