### ISSUE TITLE
[Bug]: FPS of Genshin is lower using 2.0.0 than 2.0.0-beta

### ISSUE THREAD

**Issue by krmst** [PlayCover/PlayCover#573]
### Describe the bug

2.0.0-beta can run Genshin at 120 fps.
I updated to 2.0.0 yesterday. but found Genshin run at 90 fps or lower.
If I reinstall 2.0.0-beta Genshin will run at 120 fps again. 
※ I didn't do any other changes except using different playcover version.

My pc spec:
Apple M1 Pro

|  😶‍🌫️  |  2.0.0-beta  |  2.0.0  |
| ---- | ---- | ---- |
|   |  ![image](https://user-images.githubusercontent.com/98016677/207310768-55231865-74d0-42a5-a8cc-e26f7440eaa4.png) | ![image](https://user-images.githubusercontent.com/98016677/207311382-faf0a6ff-7918-4f10-a980-97e54bda001f.png) |
|    |  ![image](https://user-images.githubusercontent.com/98016677/207310939-20fb2daa-4216-4f1b-b0a8-28880707320e.png)  | ![image](https://user-images.githubusercontent.com/98016677/207311238-09be0221-3088-45d1-a3e1-0ae57e3c395e.png) |
|    |  ![image](https://user-images.githubusercontent.com/98016677/207311062-44682230-9e34-40dc-9180-5173477f40f0.png)  |  ![image](https://user-images.githubusercontent.com/98016677/207311469-a25e13e1-068e-4120-aafa-564b641c59ea.png) |
|    |  ![image](https://user-images.githubusercontent.com/98016677/207311141-e30a1853-b60f-46d8-af01-857ed71b3688.png)  | ![image](https://user-images.githubusercontent.com/98016677/207311543-24e44a2b-1dbb-4b70-87ab-a264a374762c.png)  |
|  | ![image](https://user-images.githubusercontent.com/98016677/207313478-c8c4b5d0-f966-4f23-aaed-4bc3af69a8d4.png) | ![image](https://user-images.githubusercontent.com/98016677/207313282-e95c1682-64f4-43b9-83b0-328ec2691c27.png)
|  | 1.9x Composited | 1.8x Composited

### Steps to reproduce

1. Install 2.0.0-beta and install Genshin.
2. Set to 120 FPS.
3. Install 2.0.0

### Expected behaviour

2.0.0 should run at 120 fps

### What version of PlayCover are you using?

Nightly/beta

### What version of macOS are you using?

Ventura (macOS 13)

### Issue Language

- [X] Yes my issue is written in English

**Comment by ohaiibuzzle** [comment]
I don't see an issue here, they were built using the same configuration. You should probably look around to see if there is anything that may be using the GPU.
The fact that the framerate did go beyond 60 FPS is already a clear sign that PlayCover did not capped it in any way

**Comment by krmst** [comment]
> I don't see an issue here, they were built using the same configuration. You should probably look around to see if there is anything that may be using the GPU.
> The fact that the framerate did go beyond 60 FPS is already a clear sign that PlayCover did not capped it in any way

@ohaiibuzzle 
I closed all other application. But the problem still remains.
I just noticed something new which may help you investigate this.

😶‍🌫️  | real fps using 2.0.0 when game on focus | real fps using 2.0.0 when  game lose focus
-- | -- | --
 _60 fps setting_ | 55 fps  |  60fps
 _120 fps setting_ | approximately 90 fps  |  approximately 90 fps 

As you see, with only changing the setting of the game. my pc is not able to run at 60 fps even though it can ran at 90 fps.
If I focus on safari( I am wring this) the fps is higher than focus on. ⬅️This behavior is some how strange.

⬇️ _60 fps setting, 120 fps setting_ stands for the following setting in game.
![image](https://user-images.githubusercontent.com/98016677/207325123-3b28f037-5a26-40e8-8dd7-7362b74746b7.png)

**Comment by ashran** [comment]
> I don't see an issue here, they were built using the same configuration. You should probably look around to see if there is anything that may be using the GPU. The fact that the framerate did go beyond 60 FPS is already a clear sign that PlayCover did not capped it in any way

This issue started with a version of nightly build. I can see that the CPU time increases significantly, resulting in a lower frame rate. Even in some cases, it will drop from 110+ fps to 80 fps. In addition, I cannot get stable 120 fps as before. The fps fluctuates around 115. I'm M1 Max, macOS 13.1.

**Comment by macvip** [comment]
The same problem here.
To get a better performance, we could use newer playcover to install games, while older beta playcover to start games.

**Comment by macvip** [comment]
After almost every nightly build was tested, [PlayCover_nightly_168.dmg](https://github.com/PlayCover/PlayCover/suites/9705268361/artifacts/465182820) was found the first version caused "CPU time increases significantly, resulting in a lower frame rate". @ashran @ohaiibuzzle @krmst 
Just stay with [PlayCover_nightly_167.dmg](https://github.com/PlayCover/PlayCover/suites/9680374571/artifacts/463517955)

**Comment by ashran** [comment]
> After almost every nightly build was tested, [PlayCover_nightly_168.dmg](https://github.com/PlayCover/PlayCover/suites/9705268361/artifacts/465182820) was found the first version caused "CPU time increases significantly, resulting in a lower frame rate". @ashran @ohaiibuzzle @krmst
> Just stay with [PlayCover_nightly_167.dmg](https://github.com/PlayCover/PlayCover/suites/9680374571/artifacts/463517955)

Thank you. It works for me！

**Comment by krmst** [comment]
> After almost every nightly build was tested, [PlayCover_nightly_168.dmg](https://github.com/PlayCover/PlayCover/suites/9705268361/artifacts/465182820) was found the first version caused "CPU time increases significantly, resulting in a lower frame rate". @ashran @ohaiibuzzle @krmst
> Just stay with [PlayCover_nightly_167.dmg](https://github.com/PlayCover/PlayCover/suites/9680374571/artifacts/463517955)

Thank you for taking the time to do this. it works perfect for me.

**Comment by FlyMeToTheMoonAndLetMePlayAmongTheStars** [comment]
I downgraded from nightly 183 to 167, genshin (and i assume other games as well) runs noticeably better now. @macvip 
thank you so much for testing different builds and finding out where the issue started ❤️

**Comment by IsaacMarovitz** [comment]
Resolved in PlayCover 2.0.2
