### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by al0xe** [PlayCover/PlayCover#574]
### Describe the bug

Unable to log into genshin

### Steps to reproduce

Hello! So originally, I was installing playcover in order to download genshin impact. I went through all the necessary steps according to the play cover.io website EXCEPT the part where you don't enter the game because you need to enable SIP (step 3). Instead, I started playing genshin and after I realized my mistake, I quickly deleted Genshin and the keychain downloads in hopes of starting from zero. However, when I try to play genshin after going through the whole process correctly, it wont let me log in and it says "login has expired, please log in again"in order

### Expected behaviour

to be able to log into genshin.  

### What version of PlayCover are you using?

1.1.1

### What version of macOS are you using?

Ventura (macOS 13)

### Issue Language

- [X] Yes my issue is written in English

**Comment by IsaacMarovitz** [comment]
Not a bug just improper following of instructions
