### ISSUE TITLE
[Bug]: No Keymapping plugin while PlayTools is installed

### ISSUE THREAD

**Issue by amirsaam** [PlayCover/PlayCover#578]
### Describe the bug

In some games/apps while you have PlayTools installed correctly, you'll notice that Keymapping plugin is not available when you open the game or app and it doesn't have a MenuBar dropdown either.

### Steps to reproduce

1. Install latest stable release of PlayCover 2.0 (didn't test before versions but maybe it's there too)
2. Install Sonic the Hedgehog ([download link](https://repo.amrsm.ir/ipa/Sonic-The-Hedgehog-Classic_3.8.2.4.ipa))
3. Open the game, you'll notice the Keymapping plugin is not there even when PlayTools is installed and changed the resolution

### Expected behaviour

Games/Apps should have Keymapping plugin correctly installed when PlayTools is injected into them.

### Crash log

```shell
None
```

### What version of PlayCover are you using?

Nightly/beta

### What version of macOS are you using?

Ventura (macOS 13)

### Issue Language

- [X] Yes my issue is written in English

**Comment by ohaiibuzzle** [comment]
It does looks like PlayTools initialized (you can see the resolution and Discord IPC starting) 
I wonder if this is something the game intentionally does?

**Comment by amirsaam** [comment]
> It does looks like PlayTools initialized (you can see the resolution and Discord IPC starting)

Yeah I can confirm that PlayTools works.

> I wonder if this is something the game intentionally does?

It's possible, I've also tested JB Bypass. nothing showed up.
