### ISSUE TITLE
[Bug]: Genshin Impact game interface is offset

### ISSUE THREAD

**Issue by Luastonsu** [PlayCover/PlayCover#579]
### Describe the bug

The game interface of Genshin Impact is offset and cannot be restored after updating macOS 13.2 beta.I have tried reinstall the game application but the problem not be solved.
I think it may be a compatibility issue between the game and macOS 13.2 beta,but i am not sure
here are screenshot
<img width="895" alt="image" src="https://user-images.githubusercontent.com/70949583/207883993-9a7ea08c-2abd-4dbf-aef2-ae6fd7d4ce13.png">

### Steps to reproduce

1.update macOS 13.2 beta
2.open Genshin Impact in Playcover
3.problem will reproduce.(100%,every time)

### Expected behaviour

Game interface returns to normal

### What version of PlayCover are you using?

Nightly/beta

### What version of macOS are you using?

Ventura (macOS 13)

### Issue Language

- [X] Yes my issue is written in English

**Comment by Depal1** [comment]
You must `inject PlayTools` under `Settings > Misc`.

**Comment by Luastonsu** [comment]
> You must `inject PlayTools` under `Settings > Misc`.

it already installed.

**Comment by Luastonsu** [comment]
> You must `inject PlayTools` under `Settings > Misc`.

I uninstalled and inject playtools,but the problem still exists

**Comment by TheMoonThatRises** [comment]
I can confirm this issue exists only after upgrading to MacOS's latest beta 13.2. This issue seems to only occur to certain apps, regardless of if PlayTools is installed.

**Comment by Luastonsu** [comment]
> 



> I can confirm this issue exists only after upgrading to MacOS's latest beta 13.2. This issue seems to only occur to certain apps, regardless of if PlayTools is installed.

It seems that it should be a compatibility issue between macOS and the game.

**Comment by Normanyin** [comment]
Same problem with this    13.2 (a) Beta版(22D7750270d) and latest playcover

**Comment by FlyMeToTheMoonAndLetMePlayAmongTheStars** [comment]
issue caused by Apple, not PlayCover. current workaround is to downgrade back to macOS 13.1 which does not have any problems and keymaps work perfectly. 

at this point it's not certain if this is a temporary beta issue that will resolve on its own when Apple pushes out a new beta of macOS 13.2, or if it's something that will carry over to the final 13.2 release

**Comment by MR-UNI** [comment]
downgrade to macOS 13.1, the beta is being dumb
