### ISSUE TITLE
[Bug]: Genshin Impact crashing  

### ISSUE THREAD

**Issue by FlyMeToTheMoonAndLetMePlayAmongTheStars** [PlayCover/PlayCover#580]
### Describe the bug

Ventura 13.1 (22C65)
Playcover 2.0.0 (177)

Genshin Impact crashes occasionally, can happen during combat or while walking, sometimes even crashes for no apparent reason when my character is standing still in a city and not pressing anything. Hopefully the crash log can help pinpoint the issue?

### Steps to reproduce

Hard to reproduce these random crashes, but there is one kind of crash that happens often, which is when I close the game and a crash message pops up immediately after. 

### Expected behaviour

Not crashing lol

### Crash log
[click here for full crash log](https://gist.github.com/FlyMeToTheMoonAndLetMePlayAmongTheStars/24ca8121209b170cbbad602a8d86cf34)

### What version of PlayCover are you using?

2.0.1/build (185)

### What version of macOS are you using?

Ventura (macOS 13.1)

### Issue Language

- [X] Yes my issue is written in English

**Comment by FlyMeToTheMoonAndLetMePlayAmongTheStars** [comment]
[crash log from the game crashing immediately after closing](https://gist.github.com/FlyMeToTheMoonAndLetMePlayAmongTheStars/81c2b12eb6c4a48de8374674b07d3f5f)

**Comment by FlyMeToTheMoonAndLetMePlayAmongTheStars** [comment]
[crash log from game crashing randomly during open world exploration](https://gist.github.com/FlyMeToTheMoonAndLetMePlayAmongTheStars/f0199b90b0186aef4676d1a8d0273028)

**Comment by XuYicong** [comment]
The first crash should be fixed by https://github.com/PlayCover/PlayTools/pull/69. There was some contention in faketouch that wasn't handled correctly.

**Comment by TheMoonThatRises** [comment]
Should be fixed in the nightly builds.
