### ISSUE TITLE
Arknights does not work on versions other than 0.9.2. 

### ISSUE THREAD

**Issue by ZhichGaming** [PlayCover/PlayCover#59]
We should make Arknights work on the lastest version. I however do not know if there is a problem that is not fixable but we could maybe try seeing the differences between 0.9.2 and others? Sorry for my ignorance.

**Comment by dyc12389** [comment]
Would someone please tell me where can I get playcover with the verison 0.9.2?

**Comment by ZhichGaming** [comment]
> Would someone please tell me where can I get playcover with the verison 0.9.2? 
> 
> Or a build intstruction so that people can build the specific version from source. 

The archived PlayCover versions can be found here: https://github.com/PlayCover/playcover-archive

**How to open a legacy version of PlayCover** ﻿ 
[] - **Command + Space** on your keyboard 
﻿[] - Type `Terminal` ﻿
[] - Type or copy+paste the following commands: 
﻿```chmod -R +x /Applications/PlayCover.app ﻿xattr -cr /Applications/PlayCover.app codesign --force --deep --sign - /Applications/PlayCover.app ``` ﻿

**Comment by ruixingw** [comment]
Hi, can you share how you run Arknights on 0.9.2?  Even with 0.9.2 and SIP disabled, I was not able to run Arknights with the message _"明日方舟" cannot be opened because the developer did not intend for it to run on this Mac._ I'm on MacOS 12.5.1 btw.

**Comment by ZhichGaming** [comment]
Open the ipa with playcover.

**Comment by ruixingw** [comment]
> 

yes that's how I did. I click on "Add app" in playcover and select the IPA to import, and then click on the Arknights icon in playcover library but doesn't work

**Comment by ruixingw** [comment]
I can run it now. (I forgot to reboot after setting nvram, sry for bothering. )
