### ISSUE TITLE
[Bug]: OAuth Failure

### ISSUE THREAD

**Issue by emircanerkul** [PlayCover/PlayCover#593]
### Describe the bug

I install black desert mobile but facebook, google, and of course, apple's login failed.

I checked issues in this repo I think apple login is something that can not be accomplishable.

But other Facebook and google options should work. When I click, the app opens my browser and I am able to fill in and also create a connection. But after that game gives an error. Like Google login failed. But all successful. I think something was broken while the OAuth data transfer between the app and the browser.

I do not disable SIP, and I don't think. It's quite a big security concern.Facebook

### Steps to reproduce

> https://decrypt.day/app/id1477186880 Download IPA
> Install
> Click Login

![Uploading image.png…]()

### Expected behaviour

<img width="702" alt="image" src="https://user-images.githubusercontent.com/11430795/208251704-b8aac28b-3e68-48da-82e5-84b9168aac67.png">

### What version of PlayCover are you using?

1.1.1

### What version of macOS are you using?

Ventura (macOS 13)

### Issue Language

- [X] Yes my issue is written in English

**Comment by emircanerkul** [comment]
I disabled csrutil for a short time to log in-game, it was successful even with apple login. But each time the game asks for login. After enabling csrutil it keeps failing. Isn't there any other way? Or app-specific csrutil commands? 

Probably OAuth responses are blocked. I also tried the Gmail login method it was the same as the Apple login.

**Comment by TheMoonThatRises** [comment]
Can you try using the latest Nightly build and enable PlayChain (through the app's settings -> Bypasses) and see if that works?

**Comment by emircanerkul** [comment]
<img width="744" alt="image" src="https://user-images.githubusercontent.com/11430795/217441584-0e5f1bf8-849b-49d9-a1e0-f5e2e4f44272.png">

Gmail okay but Apple login still not working

**Comment by ohaiibuzzle** [comment]
Don't ever expect Apple ID logins to work with SIP on, really. That is another whole can of worm that we haven't really had time to figure out

**Comment by TheMoonThatRises** [comment]
For now, use Google to login. Apple ID login will be considered in the future.

**Comment by emircanerkul** [comment]
@TheMoonThatRises that would be good instead of closing this issue, you can put task list and mark it some of them done.

**Comment by hongyuehao** [comment]
is there any message now, after over half a year?
