### ISSUE TITLE
Change of copyright statement

### ISSUE THREAD

**Issue by Depal1** [PlayCover/PlayCover#6]
The Copyright in [PlayCover/Info.plist](https://github.com/PlayCover/PlayCover/blob/3341e911925a788cddcd16915bea652901e87225/PlayCover/Info.plist) should be bumped by a year and changed into something like "Playcover community" or "Playcover project" since this project is of joint authorship.

This might need to come along with [Issue #5 ](https://github.com/PlayCover/PlayCover/issues/5). I am not sure if a change of name would be required too.

**Comment by lixin9311** [comment]
I've changed to PlayCover Community Edition
