### ISSUE TITLE
[Game Support]: Survivor!.io won't open

### ISSUE THREAD

**Issue by MrDoggo911** [PlayCover/PlayCover#615]
### App Store link

https://apps.apple.com/us/app/survivor-io/id1528941310

### Current issues

- [ ] Game fails to install
- [x] Game fails to open
- [ ] Game crashes randomly during gameplay
- [ ] Game does not work with keymapping
- [ ] Game experiences graphical issues or broken UI
- [ ] Game fails to connect to servers or complete download

### More details

When I start downloaded from [decrypt.day](https://decrypt.day/). I added the game to Playcover, the install is perfectly normal but when I open the game, it not loaded the game instead it crash and show the crash log. I try to reinstall the game, restart computer, and reopen multiple times but it not fixed at all.

### Crash log

```shell
https://pastebin.com/BxM8Tfbj
```

### Issue Language

- [x] Yes my issue is written in English

**Comment by TheMoonThatRises** [comment]
Game now works on the latest nightly build with PlayChain enabled.
