### ISSUE TITLE
[Bug]: massive FPS drop in-game when clicking mouse

### ISSUE THREAD

**Issue by FlyMeToTheMoonAndLetMePlayAmongTheStars** [PlayCover/PlayCover#618]
### Describe the bug

PlayCover: `2.0.1 (188)`
macOS: `13.1`

[screen recording of the bug in action](https://files.catbox.moe/n1udnj.mov)

while the cursor is released, clicking mouse `LMB` causes huge FPS drop in-game. if the cursor is focused/using keymapping, no FPS drop occurs. The severity of framerate drop is kinda proportional to how much and how fast you're clicking in a short span of time. As you can see in the video at one point I clicked faster so the FPS dropped harder. 

Dunno if this happens with other games too since I mostly play Genshin, this has happened in previous playcover versions as well though I don't recall how far back. 

If it makes any difference I had Genshin open as a window on Desktop and was switching back and forth between Firefox which was open in full-screen.

sometimes the bug still happens after restarting the game, sometimes it goes away on its own

### Steps to reproduce

not able to reproduce this consistently, it just happens sometimes. i will update this when i figure out what 100% causes it

### Expected behaviour

no FPS drop when clicking mouse while cursor is 'released'

### Crash log

```shell
no crash
```

### What version of PlayCover are you using?

Nightly/beta

### What version of macOS are you using?

Ventura (macOS 13)

### Issue Language

- [X] Yes my issue is written in English

**Comment by moelmoo** [comment]
do you have multiple key elements set to lmb?
