### ISSUE TITLE
Keymaping & macros not working in Girls' Frontline

### ISSUE THREAD

**Issue by sheaahhoi1** [PlayCover/PlayCover#62]
Keymaping & macros not working in Girls' Frontline
https://apps.apple.com/us/app/girls-frontline/id1313126006
Keymaping cannot be displayed properly, add and delete
Macro cannot log any operations

**Comment by ohaiibuzzle** [comment]
Macro is known to not be working. Need some work on that. See #18 
As for keymapping, I suggest you re-read the instructions as they works for me

**Comment by sheaahhoi1** [comment]
https://youtu.be/ipOM_q7nNA8
@ohaiibuzzle I don't know which setting affects 2 game differences
Keymapping instructions not provided

**Comment by ZhichGaming** [comment]
@sheaahhoi1 You can find instructions for keymapping in discord by typing .keymapping in #bot-spam-here.
