### ISSUE TITLE
[Bug]: Terraria doesn't have PlayTools injected

### ISSUE THREAD

**Issue by kingbri1** [PlayCover/PlayCover#626]
### Describe the bug

In PlayCover v2.0.1, Terraria doesn't have PlayTools injected even though there were no errors when installing the ipa. It was concluded that switching to the Inject dependency broke this functionality after seeing that it worked in PlayCover v2.0.0.

### Steps to reproduce

1. Install Terraria's ipa in v2.0.1
2. An exclamation point should show up next to the Terraria app even though it said "Installing PlayTools" and didn't show an error.

### Expected behaviour

PlayTools should install in Terraria without problems

### What version of PlayCover are you using?

2.0.1

### What version of macOS are you using?

Ventura (macOS 13)

### Issue Language

- [X] Yes my issue is written in English

**Comment by IsaacMarovitz** [comment]
Fixed in #634
