### ISSUE TITLE
[Bug]: failed to inject playtools (PayBack2)

### ISSUE THREAD

**Issue by Kees-van-Beilen** [PlayCover/PlayCover#632]
### Describe the bug

When trying to inject playtools in some applications will fail, I suspect that it is an appname issue
The command line puts out the following text:
```bash
Please run 'lipo /Users/kbeilen/Library/Containers/io.playcover.PlayCover/Payback².app/Payback 2 Free -thin armv7 -output /Users/kbeilen/Library/Containers/io.playcover.PlayCover/Payback².app/Payback 2 Free_armv7' first
Inject /Users/kbeilen/Library/Frameworks/PlayTools.framework/PlayTools failed
```
The recommended lipo command fails when plainly copying over the command. Putting quotation-marks around the file names seems to work, but it still fails to inject playtools

### Steps to reproduce

I have been able to reproduce this on 2 devices using the payback 2 app

1. download and install `https://decrypt.day/app/id570426586`
2. run playcover from the commandline (to see any error messages)
3. try to inject playtools

### Expected behaviour

At the very least an error popup instead of having to read from the terminal, but obviously that playtools would install correctly

### What version of PlayCover are you using?

2.0.1

### What version of macOS are you using?

Monterey (macOS 12)

### Issue Language

- [X] Yes my issue is written in English

**Comment by IsaacMarovitz** [comment]
Fixed in #634
