### ISSUE TITLE
Keymaping not support in Girls' Frontline

### ISSUE THREAD

**Issue by sheaahhoi1** [PlayCover/PlayCover#64]
https://youtu.be/ipOM_q7nNA8
@ohaiibuzzle I don't know which setting affects 2 game differences
Keymapping instructions not provided

Keymaping **not support** in Girls' Frontline

**Comment by IsaacMarovitz** [comment]
Does this issue persist in PlayCover 1.1.1?

**Comment by sheaahhoi1** [comment]
@IsaacMarovitz Is still there in PlayCover 1.1.1

**Comment by XuYicong** [comment]
I think this is a consequence of the play tools UI not top enough in the UI stack. From the following video, it can be seen that, if I press on the survey link, then open keymapping editor before the link opens, the editor UI would be hidden by the survey page.

https://user-images.githubusercontent.com/16048758/187444593-ed0d1dfa-4d99-4db5-937a-5ea2c74a0424.mov


In ideal cases, editor UI should be always on the top. If a survey page can cover the editor UI, then normal gaming UI in other games such as Girl's Frontline can also easily cover the editor UI (plus the toast UI).
