### ISSUE TITLE
[Feature]: Add "Cancel downloading" button

### ISSUE THREAD

**Issue by 47thforce** [PlayCover/PlayCover#647]
### Is your feature request related to a problem?

no

### Describe the solution you'd like

Just add "Cancel download" button in the progress bar to cancel download apps from IPA library. It's way more convenient than force quit PlayCover or disconnect the internet. 

(Alice here)

### Anything else?

no

### Issue Language

- [X] Yes my issue is written in English

**Comment by amirsaam** [comment]
Already addressed in #622
