### ISSUE TITLE
[Game Support]: Tower Of Fantasy

### ISSUE THREAD

**Issue by LynoDesu** [PlayCover/PlayCover#649]
### App Store link

[https://apps.apple.com/us/app/tower-of-fantasy/id1601586278](https://apps.apple.com/us/app/tower-of-fantasy/id1601586278)

### Current issues

- [ ] Game fails to install
- [ ] Game fails to open
- [ ] Game crashes randomly during gameplay
- [X] Game does not work with keymapping
- [X] Game experiences graphical issues or broken UI
- [ ] Game fails to connect to servers or complete download

### More details

The game seems to have some pretty severe graphical glitches. Parts of certain models (such as the main character don't render and the overall textures and shaders don't seem to render correctly. Screenshot: [https://ibb.co/3vhDSBB](https://ibb.co/3vhDSBB)

Also selecting input elements such as dropdown options or text input fields don't work. Instead a white bar at the top of the screen displays for a split-second instead of focusing on the input. This prevents data from being entered into various UI forms.

### Issue Language

- [X] Yes my issue is written in English

**Comment by amirsaam** [comment]
ToF has a known issue that is not easy to fix.
Contributors currently trying to fix it but no ETA for the fix.

**Comment by LynoDesu** [comment]
I thought the issues were related to login/server issues rather than graphics rendering?

**Comment by amirsaam** [comment]
Logging into online servers and Graphical, both.

**Comment by jay0ma** [comment]
Are there any updates on this issue?

**Comment by s7v3n7** [comment]
I have no problem installing and updating, but can you even login?
