### ISSUE TITLE
[App Support]: DingTalk no notification and no sound

### ISSUE THREAD

**Issue by aaronysj** [PlayCover/PlayCover#655]
### App Store link

[DingTalk](https://apps.apple.com/cn/app/%E9%92%89%E9%92%89/id930368978)

### Current issues

- [ ] App fails to install
- [ ] App fails to open
- [ ] App crashes randomly during usage
- [ ] App experiences graphical issues or broken UI
- [ ] App fails to connect to servers
- [X] Other

### More details

I intalled this app yesterday, but there was **no notification** and **no sound**, please check it , plz.

### Issue Language

- [X] Yes my issue is written in English

**Comment by ohaiibuzzle** [comment]
Notifications is managed by the macOS system (System Prefs > Notifications). PlayCover has no control over this

**Comment by aaronysj** [comment]
> Notifications is managed by the macOS system (System Prefs > Notifications). PlayCover has no control over this

I know these notifications settings, but it does't work well. Maybe some app settings causes this. I'll try it later. Thanks .
