### ISSUE TITLE
[Feature]: Change Location of App Installs

### ISSUE THREAD

**Issue by MoPaMo** [PlayCover/PlayCover#667]
### Is your feature request related to a problem?

Genshin is taking up to much space on my Macs intern SSD

### Describe the solution you'd like

I would love to be able to store apps in different locations, e. g. my external SSD

### Anything else?

I think this would improve overall quality by a lot

### Issue Language

- [X] Yes my issue is written in English

**Comment by TheMoonThatRises** [comment]
The app itself probably could be manually moved to an external SSD, but the main bulk of Genshin's data is in it's game files, which cannot be moved. Discussed in this discussion: https://github.com/PlayCover/PlayCover/discussions/473.
