### ISSUE TITLE
[Bug]: Display Proportion Error after System Update

### ISSUE THREAD

**Issue by FlyCat0229** [PlayCover/PlayCover#669]
### Describe the bug

After updating to macOS 13.2 Beta, Genshin Impact won't display properly. It can only display half of the picture.
<img width="1440" alt="截屏2023-01-03 23 28 35" src="https://user-images.githubusercontent.com/47152641/210389270-79a7fa2f-a02f-4d06-b5ab-40481cc2fc00.png">

### Steps to reproduce

just update to the beta system 13.2

### Expected behaviour

hope to fix it

### What version of PlayCover are you using?

Nightly/beta

### What version of macOS are you using?

macOS beta (please state the specific version)

### Issue Language

- [X] Yes my issue is written in English

**Comment by IsaacMarovitz** [comment]
Known issue with macOS beta please downgrade to release 13.1
