### ISSUE TITLE
[Game Support]: Goose Goose Duck Run With Error!

### ISSUE THREAD

**Issue by zhinianyuxin0o0** [PlayCover/PlayCover#683]
### App Store link

https://apps.apple.com/us/app/goose-goose-duck/id1558248707

### Current issues

- [ ] Game fails to install
- [X] Game fails to open
- [ ] Game crashes randomly during gameplay
- [ ] Game does not work with keymapping
- [ ] Game experiences graphical issues or broken UI
- [ ] Game fails to connect to servers or complete download

### More details

When I opened the game, I got this error：
An error occurred when accessing the keychain. The NSLocalizedFailureReasonErrorKey field in the NSError.userinfo dictionary will contain more information about the error encountered。

<img width="867" alt="image" src="https://user-images.githubusercontent.com/73481491/210966974-4505b906-0089-4fcd-9548-e02b346ff0fb.png">

### Crash log

```shell
Temporarily absent Crash log
```

### Issue Language

- [X] Yes my issue is written in English

**Comment by TheMoonThatRises** [comment]
Goose Goose Duck is available on Steam, their website, and on the App Store. Besides that, this issue has been fixed on the latest nightly with KeyChain enabled.
