### ISSUE TITLE
[Feature]: Scripting and Automation

### ISSUE THREAD

**Issue by lewisxy** [PlayCover/PlayCover#687]
### Is your feature request related to a problem?

No

### Describe the solution you'd like

Scripting
- Provide API to simulate user input (using touch screen). This could be implemented as an RPC server opened at localhost, and user can send commands to it (similar to how Puppeteer operate Chrome browser through DevTool Protocol).
App Automation
- Allow user to programmatically start/manipulate/close a specific game. This could be implemented as AppleScript interface. This will be useful to automate certain games where there are things like daily login rewards.

### Anything else?

No

### Issue Language

- [X] Yes my issue is written in English

**Comment by FlyMeToTheMoonAndLetMePlayAmongTheStars** [comment]
i love this idea, sounds like it could violate the terms of service of many games

**Comment by Depal1** [comment]
This won’t be done, as it would enable input automation, which was removed permanently from PlayCover, and won’t be included in any form. Check https://github.com/PlayCover/PlayCover/issues/378 for more information.

As for the second one, AppleScripts to start and close PlayCover apps can already be done without even having to modify any PlayCover source code.
