### ISSUE TITLE
[Bug]: Crash pop-up after closing games

### ISSUE THREAD

**Issue by FlyMeToTheMoonAndLetMePlayAmongTheStars** [PlayCover/PlayCover#689]
### Describe the bug

PlayCover `2.0.2 (206)`
macOS `13.1`
Computer `M1 MacBook Air, 8 GB RAM, 7-core GPU`

Doesn't happen all the time but happens often enough to be annoying.

I noticed that if you're using the M1 identifier to play for example Genshin Impact or Honkai Impact 3rd, there's often a crash pop-up **after** you click on the little red dot to close the game after playing for awhile (~30 mins). Interestingly, this does not happen or happens far less frequently when using the A12Z identifier. 

### Steps to reproduce

Close the game with M1 identifier and do the same with A12Z (should play the game for awhile before closing it, closing on the start screen usually don't produce a crash message)

### Expected behaviour

No crash message 

### Crash log

```shell
crash log too long to fit all in here, but it's SIGSEGV related
```

### What version of PlayCover are you using?

Nightly/beta

### What version of macOS are you using?

Ventura (macOS 13)

### Issue Language

- [X] Yes my issue is written in English

**Comment by FlyMeToTheMoonAndLetMePlayAmongTheStars** [comment]
Doesn't seem to be exclusive to the M1 identifier. Also still getting these crash pop-ups from time to time when closing apps (more specifically Genshin Impact and Honkai Impact 3rd) on PlayCover 3.0.0 (244)/macOS 13.2 

Prior versions crash log indicated SIGSEGV, now it's SIGABRT. Here's the full[ crash log on newer PlayCover version.](https://gist.github.com/FlyMeToTheMoonAndLetMePlayAmongTheStars/596709499bba71e10807b09f6b4f8f36)

This is a minor issue since it happens after you exit the app/game, but I'll still track it here to make it known.

**Comment by ohaiibuzzle** [comment]
Probably because on iOS you never end up terminating the game completely and abruptly like Cmd + Q on macOS

**Comment by XuYicong** [comment]
Potential solution: post notifications like [did enter background](https://developer.apple.com/documentation/uikit/uiscene/3197922-didenterbackgroundnotification) or [will sleep](https://developer.apple.com/documentation/appkit/nsworkspace/1530075-willsleepnotification) on quiting the app. Normally iOS app would have cleanup triggers on these.

Or we can just follow [this sequence](https://developer.apple.com/documentation/uikit/app_and_environment/scenes/preparing_your_ui_to_run_in_the_background/about_the_background_execution_sequence#2928661)

**Comment by XuYicong** [comment]
I can reproduce this and this is indeed annoying and I have ideas to fix this

**Comment by nesk** [comment]
I also encounter this bug, what about merging the PR provided by @XuYicong? It seems to be a reasonable fix.
