### ISSUE TITLE
[Feature]: Support cleo for GTA SA

### ISSUE THREAD

**Issue by dacker97** [PlayCover/PlayCover#690]
### Is your feature request related to a problem?

No

### Describe the solution you'd like

Can you add support cleo for GTA SA?
I tried to inject cleo.deb in IPA file, but it doesn't work.

### Anything else?

No

### Issue Language

- [X] Yes my issue is written in English

**Comment by zanderp25** [comment]
I believe this isn't a playcover issue and an IPA issue. Have you successfully installed the same IPA on a real iOS device? Does GTA work normally without the mod?

**Comment by IsaacMarovitz** [comment]
`.deb` are intended to be used on Jailbroken iOS devices, not Mac Catalyst. This question is better directed to the team making this mod loader than here.
