### ISSUE TITLE
Nexon games pop-up shows illegal program has been detected and shut off the game

### ISSUE THREAD

**Issue by jadenism** [PlayCover/PlayCover#694]
Tried bypass jailbreak option, and turn on and off SIP and stuff.
But it keeps showing the illegal program has been detected and shut off the game.
The game I try to play is Kingdomwind or '바람의나라:연' from South Korea.

**Comment by FlyMeToTheMoonAndLetMePlayAmongTheStars** [comment]
PlayBook is for documentation, you should report this issue in the main [PlayCover repository](https://github.com/PlayCover/PlayCover/issues) instead.

**Comment by TheMoonThatRises** [comment]
See #57 and #296.
