### ISSUE TITLE
[App Support]: Butterfly iQ — Ultrasound

### ISSUE THREAD

**Issue by Wolforator** [PlayCover/PlayCover#695]
### App Store link

https://apps.apple.com/ua/app/butterfly-iq-ultrasound/id1183035589?l=ru

### Current issues

- [ ] App fails to install
- [ ] App fails to open
- [ ] App crashes randomly during usage
- [ ] App experiences graphical issues or broken UI
- [ ] App fails to connect to servers
- [X] Other

### More details

The application works, but when an ultrasound external device is connected, it does not see it. Is it possible to connect an external ultrasound device to the application?
<img width="1440" alt="Снимок экрана 2023-01-12 в 11 09 21" src="https://user-images.githubusercontent.com/40734946/212025157-10b3033b-3a9c-4b22-b62b-dc3f60becdc3.png">

### Issue Language

- [X] Yes my issue is written in English

**Comment by zanderp25** [comment]
I think iOS/iPadOS has a different communication method than macOS... I doubt it will work, unfortunately.

**Comment by IsaacMarovitz** [comment]
I don't think we can make this work
