### ISSUE TITLE
[feature request] [ux/ui] add #ipa-request and #decrypted-ipa into playcover.

### ISSUE THREAD

**Issue by IndiiSkies** [PlayCover/PlayCover#7]
What would be nice is if you add all the decrypted apps & requesting .ipa functionality into PlayCover and we can just directly use PlayCover instead of opening the discord client, going to the PlayCover server, then clicking on the channel for the decrypted apps and searching.

**Comment by AarnavSin** [comment]
I suspect that would require a completely different database to work with, currently the server does it with a bot.

**Comment by MrKai77** [comment]
I know this isn't directly related to the discord part, but we do know that all decrypted ipa files are stored [here](https://ipa.playcover.workers.dev/0:/). If we could somehow load this from within Playcover, it might be an effective solution.

**Comment by roeegh** [comment]
As of right now, all channels related to decryption will be deleted from the server. They will stay deleted until we can find a better solution to the decryption problem. As for integrating it into PlayCover, that is something on the roadmap.
