### ISSUE TITLE
[Bug]: Proton Mail app not working 

### ISSUE THREAD

**Issue by syryyndypyty** [PlayCover/PlayCover#700]
### Describe the bug

If somebody can help test `Proton Mail - Encrypted Email` version 4.2.2 with Apple M1. It installs perfectly and launches with PlayCover, but doesn't seem to allow login to account.

https://apps.apple.com/app/apple-store/id979659905

![](https://i.imgur.com/KLnBaND.jpg)

The operation couldn't be completed.
(ProtonMail.SignInCoordinator.FlowError error 3)

### Steps to reproduce

Get the decrypted app and install it.

### Expected behaviour

Should work.

### What version of PlayCover are you using?

2.0.2

### What version of macOS are you using?

Ventura (macOS 13)

### Issue Language

- [X] Yes my issue is written in English

**Comment by zanderp25** [comment]
Hello!

Have you tried following the method in the documentation here?
https://docs.playcover.io/getting_started/troubleshoot_login

**Comment by TheMoonThatRises** [comment]
Proton Mail works on the latest nightly of PlayCover with PlayChain enabled (through the app's settings -> Bypasses). Do note that if you want to install it, you would first need to install it on a stable version of PlayCover, and then upgrade to the nightly version.
