### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by ChristinaBarbosa** [PlayCover/PlayCover#701]
### Describe the bug

<img width="825" alt="Screen Shot 2023-01-14 at 1 13 48 PM" src="https://user-images.githubusercontent.com/106934125/212488869-174746f8-0578-4563-91b7-574ee7cc61ae.png">

Constantly pops up without a way to close it besides pressing use account.

### Steps to reproduce

Pop-up comes on every couple of seconds after opening game.

### Expected behaviour

Keep getting this popup if I want to stay signed in or use another icloud account. Even thought the icloud account is not needed I logged in through Facebook. Is there a way to make this pop up stop appearing? Game runs fine just the pop-up is annoying from reappearing.

### What version of PlayCover are you using?

2.0.2

### What version of macOS are you using?

Monterey (macOS 12)

### Issue Language

- [X] Yes my issue is written in English

**Comment by zanderp25** [comment]
This is a GameCenter prompt that seems to appear every time the app requests access to GameCenter. I'm not sure if there's a way around it.

**Comment by zanderp25** [comment]
I think that the iOS method of signing in with GameCenter is different than macOS, and it's saying that it can't sign into GameCenter when it's already signed in.

**Comment by IsaacMarovitz** [comment]
Press "Use another account" and then "Cancel" then it shouldn't pop up again until you move to a different window and come back.

**Comment by Trychlik** [comment]
> 

"cancel" works only shortly if you dont leave the window.. if you leave window to another app and came back it appears again, its very annoying if you play boardgames and leave the window often.

**Comment by Azyzraissi** [comment]
I've been battling against this problem since PlayCover launched. Anyone have any solution ?

**Comment by fusionx3** [comment]
I found that if I double click the game and quickly switch to another full-screen app using the three-finger swipe gesture BEFORE the game opens, it won't prompt for iCloud login.

Two things here:
- You need to be super quick and make a full window switch before the game opens.
- Sometimes you need to do it multiple times for it to work.

This is not a fix, but it works for me at least.

**Comment by Drakiat** [comment]
Same happening here on Mac M2, the message pops up every time I switch desktops or open another app.
