### ISSUE TITLE
[Bug]: Command line tools installation failed but mac detects the command line tools.

### ISSUE THREAD

**Issue by ThisIsHimaksh** [PlayCover/PlayCover#702]
### Describe the bug

I tried installing playcover but it said installation failed. But on opening terminal and writing xcode-select --install tells me that the command line tools are already installed.

### Steps to reproduce

<ul>
<li> Install playcover like usual </li>
<li> Command line installation failed </li>
<li> Open terminal </li>
<li> type xcode-select --install </li>
 </ul>

### Expected behaviour

Command line tools should not be there if installation was failed. Also installation should be succesful.

### What version of PlayCover are you using?

Playcover 2.0.2

### What version of macOS are you using?

Ventura (macOS 13)

### Issue Language

- [X] Yes my issue is written in English

**Comment by tiagoaosilveira** [comment]
same here, PlayCover doesn't detect my xcode-select at all even though it's there. Tried removing and reinstalling both PlayCover and XCode terminal tools but it just doesn't work

**Comment by ohaiibuzzle** [comment]
Can you check the output of `$(xcode-select -p)/usr/bin/notarytool` in the Terminal?

**Comment by tiagoaosilveira** [comment]
@ohaiibuzzle 

```
tiago@Tiagos-MacBook-Pro Codes % $(xcode-select -p)/usr/bin/notarytool
OVERVIEW: Manage submissions to the Apple notary service

USAGE: notarytool <subcommand>

OPTIONS:
  --version               Show the version.
  -h, --help              Show help information.

SUBCOMMANDS:
  store-credentials       Save Notary service credentials to the Keychain. Leave credential options not specified for interactive prompts.
  submit                  Submit an archive to the Notary service
  info                    Get status information for a submission
  wait                    Wait for completion of a previous submission
  history                 Get a list of previous submissions for your team
  log                     Retrieve notarization log for a single completed submission

  See 'notarytool help <subcommand>' for detailed help.
  ```

**Comment by tiagoaosilveira** [comment]
oh wow, this is embarrassing but I've managed to fix this...

- tried to run PlayCover directly from terminal and got the `xcode-select command not found error`
- noticed that PlayCover actually runs `zsh` before issuing the code
- when I tried `zsh` command, it gave me multiple errors of not finding stuff (locale, direnv, etc)
- then I checked my terminal rc files (~/.zprofile, ~/.zshenv, ~/.zshrc) and one of them was exporting PATH incorrectly (basically overriding the correct PATH)
- fixing the PATH inside of `~/.zshenv` did the trick for me :)

**Comment by zanderp25** [comment]
Weird. I don't think it should be depending on that.
