### ISSUE TITLE
[Bug]: Genshin Impact has UI problem after updated MacOS 13.2beta

### ISSUE THREAD

**Issue by Vuk018** [PlayCover/PlayCover#714]
### Describe the bug

After updating MacOs, Genshin Impact has UI problems, only one-third of the screen can appear, and the rest is black screen

### Steps to reproduce

Guessing that after I updated MacOS, Playcover asked me to download x-code without success, and there was a problem when I opened Genshin Impact directly.

### Expected behaviour

I hope that know how to reset everything because I tried delete all the apps and repeat the steps but Playcover still have the app Genshin Impact ，so maybe can I know how to reset all？

### What version of PlayCover are you using?

2.0.2

### What version of macOS are you using?

macOS beta (please state the specific version)

### Issue Language

- [X] Yes my issue is written in English

**Comment by ohaiibuzzle** [comment]
This has been mentioned many, many, many moons ago. It's an Apple bug on beta software. You can try downloading Among Us on the Mac App Store and you will run into the same exact issue.

TL,DR: Not a PlayCover Bug

**Comment by Vuk018** [comment]
ok
