### ISSUE TITLE
playcover可以越狱安装frida吗

### ISSUE THREAD

**Issue by wengxianxun** [PlayCover/PlayCover#72]
想要像真机越狱frida调试那样实现功能

**Comment by lixin9311** [comment]
取决于你想要做什么。
如果你想要解密IPA话，只能在iOS上做。

这个只是相当于在一个越狱过的手机上跑App一样。
关闭SIP之后，你可以使用frida动态分析mac上的所有程序，包括PlayCover运行的App。
具体参照 https://frida.re/docs/installation/
