### ISSUE TITLE
[Bug]: Wrong resolution while running landscape apps on macOS13.2 beta

### ISSUE THREAD

**Issue by SUNJY15** [PlayCover/PlayCover#722]
### Describe the bug

<img width="893" alt="截屏2023-01-19 09 14 08" src="https://user-images.githubusercontent.com/41618888/213332793-3351112d-2d7b-4e54-9f5f-912d8b839c1e.png">
macOS13.2 beta

### Steps to reproduce

open a landscape app

### Expected behaviour

open a landscape app

### What version of PlayCover are you using?

2.0.2

### What version of macOS are you using?

macOS beta (please state the specific version)

### Issue Language

- [X] Yes my issue is written in English

**Comment by SUNJY15** [comment]
I know that is a macOS issue but now on the latest beta I can run iOS app from AppStore without resolution wrong.

**Comment by IsaacMarovitz** [comment]
Fixed in https://github.com/PlayCover/PlayTools/pull/66

**Comment by lslqtz** [comment]
This fix may affect the accuracy of the keymapping.
