### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by Aeolus04** [PlayCover/PlayCover#723]
### Describe the bug

I'm trying to play Genshin but I keep running into this problem where every time I try to open up the app it closes immediately. And another screen would pop up showing "GenshinImpact quit unexpectedly". 

### Steps to reproduce

I've followed the play cover steps from downloading the play cover app to all the way of turning off csrutil and copy and pasting the text into terminal. This problem occurs when I'm supposed to log in into my account before shutting down everything to turn back on csrutil. 

### Expected behaviour

Before the Genshin update I would be able to login into the account, shut down and enable csrutil perfectly fine. 

### Crash log

```shell
System Integrity Protection: disabled

Crashed Thread:        0  Dispatch queue: com.apple.main-thread

Exception Type:        EXC_BREAKPOINT (SIGTRAP)
Exception Codes:       0x0000000000000001, 0x00000001b83e30e0
```

### What version of PlayCover are you using?

2.0.2

### What version of macOS are you using?

Ventura (macOS 13)

### Issue Language

- [X] Yes my issue is written in English

**Comment by IsaacMarovitz** [comment]
What resolution is your Genshin set at in App Settings? It can run into instability issues at very high or low resolutions. Try the 1440p preset.
