### ISSUE TITLE
[Feature Request] Multiple Instances of one app

### ISSUE THREAD

**Issue by Nyunyun** [PlayCover/PlayCover#73]
Add an option to start a single app multiple times, so we can manage multiple accounts at once.

This is useful, if you're sharing accounts with a friend and want to finish tasks fast while on different shifts.
Otherwise, some might want to play alt accounts at the same time. Like attacking a boss of acc#1 with acc#2 and acc#3.

Thanks

**Comment by JoseMoreville** [comment]
Thank you for your feedback

**Comment by JoseMoreville** [comment]
Hi, we're currently working on this feature, thank you!

**Comment by JoseMoreville** [comment]
Hello, we have to drop this feature, i'll be not included on this or future releases.

**Comment by Nyunyun** [comment]
May I ask why this has to be dropped?

**Comment by JoseMoreville** [comment]
That's been stated on discord.
