### ISSUE TITLE
[Bug]: Keymap doesn't work on 2.0.3/latest nightly build

### ISSUE THREAD

**Issue by MEMORIEmusic** [PlayCover/PlayCover#737]
### Describe the bug

The keymap is simple not working even though it is imported and present
<img width="1577" alt="Screenshot 2023-01-22 at 11 51 41" src="https://user-images.githubusercontent.com/79436281/213903429-9fe4e9b7-5bff-4672-a48b-90145df17dd9.png">

pressing option key doesnt do anything, and keyboards shortcuts like command + Q and command + K are not working either. I am also not able change previously assigned keymaps(like a sprint key is assigned to left shift, i cant seem to change it to anything else)

### Steps to reproduce

Opening genshin, i guess?

### Expected behaviour

Game should be able to be control with keys, and previously assigned keys in keymappings should be able to be changed. Keyboards shortcuts too should work.

### What version of PlayCover are you using?

Nightly/beta

### What version of macOS are you using?

Ventura (macOS 13)

### Issue Language

- [x] Yes my issue is written in English

**Comment by M0REKZ** [comment]
i remember something similar happening to me, ¿can you use the multitouch on other ios apps? (the ones installed directly from app store)

**Comment by elisezhu123** [comment]
it seems not work for 13.2 as apple change something with the Xcode command line tools
