### ISSUE TITLE
[Bug]: Genshin - Parameter error

### ISSUE THREAD

**Issue by mbs0ft** [PlayCover/PlayCover#741]
### Describe the bug

Parameter error

### Steps to reproduce

Try to login in another account

### Expected behaviour

Genshin captcha now working from [JoseMoreville:accountsFix](https://github.com/PlayCover/PlayCover/pull/664), but it's giving "Parameter error" while logging in with another account 

<img width="1405" alt="Screenshot 2023-01-23 at 9 53 45 am" src="https://user-images.githubusercontent.com/22106304/213990221-bf2e8da1-a436-4c52-8f5b-400222c68512.png">

"Parameter error" text in Russian
<img width="1405" alt="Screenshot 2023-01-23 at 9 53 52 am" src="https://user-images.githubusercontent.com/22106304/213990180-3be88584-6b0e-4c65-9040-9963ea3d3732.png">

### What version of PlayCover are you using?

2.0.3

### What version of macOS are you using?

Ventura (macOS 13)

### Issue Language

- [X] Yes my issue is written in English

**Comment by IsaacMarovitz** [comment]
This is fixed in latest nightly if you enable PlayChain in App Settings

**Comment by thekngsgambit** [comment]
It worked, Thank you!

**Comment by minpearl** [comment]
How to fix this error please give me a solution because mine also got this error

**Comment by MEMORIEmusic** [comment]
> How to fix this error please give me a solution because mine also got this error

Fix is written in the [docs. ](https://docs.playcover.io/getting_started/troubleshoot_login)

**Comment by AJ5735** [comment]
> This is fixed in latest nightly if you enable PlayChain in App Settings

How to fix it?
