### ISSUE TITLE
Diablo Immortal can't login when Enable SIP

### ISSUE THREAD

**Issue by xiaotuanyu120** [PlayCover/PlayCover#75]
I can login DI when disable SIP. But can't when enable SIP.

**Comment by JoseMoreville** [comment]
That's a known behaviour, please disable it, enable playsign and login

**Comment by wilbit** [comment]
What does it actually mean that it is a known behaviour?
Is it unsolvable (by what reason) or just not a priority?
I know that Sideloadly does not require disabling of SIP for Diablo Immortal, but has other limitations.

**Comment by ohaiibuzzle** [comment]
> What does it actually mean that it is a known behaviour?

Basically, we know that the software does this, we just have not worked out what to do to get it fixed so you need to just use the workaround
> Sideloadly 

If you want to compare PlayCover to Sideloadly, use Sideloadly in **Local** mode. PlayCover not at all rely on Apple's signing servers to work, so you can't compare them like so
