### ISSUE TITLE
[App Support]: 

### ISSUE THREAD

**Issue by DEVIREDDY-NIKHIL-REDDY** [PlayCover/PlayCover#758]
### App Store link

i am not getting verification code

### Current issues

- [ ] App fails to install
- [ ] App fails to open
- [ ] App crashes randomly during usage
- [ ] App experiences graphical issues or broken UI
- [ ] App fails to connect to servers
- [ ] Other

### More details

i disabled sip and ran the script in terminal then i open genshin i enterd email and password but iam not getting the verification code

### Issue Language

- [X] Yes my issue is written in English

**Comment by IsaacMarovitz** [comment]
Improper template use and bad following of instructions
