### ISSUE TITLE
Notices arrow is reversed

### ISSUE THREAD

**Issue by leomiglio02** [PlayCover/PlayCover#76]
The arrow should be to the up when closed and to the bottom when open
<img width="735" alt="Screenshot 2022-07-21 at 2 30 40 PM" src="https://user-images.githubusercontent.com/56474420/180213814-1426e08d-c984-4e37-9c72-289a562e718a.png">

**Comment by zanderp25** [comment]
This has already been fixed, and will be released in the next update.
