### ISSUE TITLE
[Bug]: Google Home app asks for login at every start-up

### ISSUE THREAD

**Issue by s1lviu** [PlayCover/PlayCover#768]
### Describe the bug

When I open the Google Home app, it puts me to log in and set-up every time. 

### Steps to reproduce

Open the Google Home app. 

### Expected behaviour

The app should persist the settings through sessions.

### What version of PlayCover are you using?

2.0.4

### What version of macOS are you using?

Ventura (macOS 13)

### Issue Language

- [X] Yes my issue is written in English

**Comment by ohaiibuzzle** [comment]
Simple really. Most Google apps uses Keychain to store their login information
And AMFI on = no Keychain access for unsigned apps

**Comment by s1lviu** [comment]
Got it. Thanks.

**Comment by ohaiibuzzle** [comment]
@s1lviu We are working on a fix on the 3.0.0 Beta. It may work, but we haven't tested every single apps yet. You can try and report the results here

**Comment by s1lviu** [comment]
Is there a 3.0.0 build? I didn't find one on releases.

**Comment by ohaiibuzzle** [comment]
It's in alpha right now, you will need to access it via the Nightly Actions or build the app yourself (how-to is in docs)

**Comment by s1lviu** [comment]
> It's in alpha right now, you will need to access it via the Nightly Actions or build the app yourself (how-to is in docs)

I've tried with this: https://github.com/PlayCover/PlayCover/suites/10721397037/artifacts/537390632

The issue is still present, thanks.

**Comment by electr1fy0** [comment]
Can reproduce the same with all Google apps as well

**Comment by huy-lv** [comment]
hope this problem will be resolved soon
