### ISSUE TITLE
[Bug]: All games do not support keyboard input

### ISSUE THREAD

**Issue by ZombiejsC** [PlayCover/PlayCover#772]
### Describe the bug

Computer:Macbook Air M2 chip,16GB memory 256GB Solid State Drive Ventura 13.2
Playcover version:2.0.4. Genshin Impact version:3.4.0
In the setting interface of playcover, I'm sure to open the keyboard mapping and mouse mapping. But in the game, I can't use the option key to switch the mouse mode, and I can't use the shortcut of command+k to open the keyboard mapping editing. But the original keyboard mapping can work. It can create a keyboard mapping, but it can't change the keys (no matter what key is pressed, the computer doesn't respond). Even command+q can't exit the game, You can only force the app to close

### Steps to reproduce

no more details, I do hope this bug can be solved

### Expected behaviour

The bug can be fixed

### What version of PlayCover are you using?

2.0.4

### What version of macOS are you using?

Ventura (macOS 13)

### Issue Language

- [X] Yes my issue is written in English

**Comment by FlyMeToTheMoonAndLetMePlayAmongTheStars** [comment]
Have you tried restarting your computer?

**Comment by ZombiejsC** [comment]
omg, it is quite weird, I have restart my computer several times ago, but this time the bug was fixed!Anyway,thx for ur idea!!XD

**Comment by AayushGTM6693** [comment]
I have the same issue. how to deal it with ??
