### ISSUE TITLE
[Bug]: 安装金铲铲时安装失败

### ISSUE THREAD

**Issue by zhxqc** [PlayCover/PlayCover#774]
### Describe the bug

安装金铲铲时进度条1秒钟跑完，看网速应该是没下载东西，过了一会儿报错
When installing the 金铲铲 the progress bar ran in one second. The network speed should be no download. After a while, an error was reported
<img width="260" alt="image" src="https://user-images.githubusercontent.com/35363368/216506693-e68cfad9-c85f-4c29-86ad-a23393ede306.png">

电脑M1 Mac 系统 Ventura 13.1
playCover版本 2.0.4
IPA源 https://decrypt.day/library

### Steps to reproduce

下载最新版本，安装金铲铲

### Expected behaviour

成功安装

### What version of PlayCover are you using?

2.0.4

### What version of macOS are you using?

Ventura (macOS 13)

### Issue Language

- [X] Yes my issue is written in English

**Comment by JoseMoreville** [comment]
Closing this since is it is not following the english template correctly
