### ISSUE TITLE
[Bug]: Kindle when SIP is on can not work well 

### ISSUE THREAD

**Issue by sunjishen** [PlayCover/PlayCover#780]
### Describe the bug

When I closed SIP, Kindle can login normally, but when I setting all the things, open the SIP protection, Kindle app always collapse directly when open up 

### Steps to reproduce

When I closed SIP, Kindle can login normally, but when I setting all the things, open the SIP protection, Kindle app always collapse directly when open up 

### Expected behaviour

When I closed SIP, Kindle can login normally, but when I setting all the things, open the SIP protection, Kindle app always collapse directly when open up 

### What version of PlayCover are you using?

2.0.4

### What version of macOS are you using?

Ventura (macOS 13)

### Issue Language

- [X] Yes my issue is written in English

**Comment by TheMoonThatRises** [comment]
After https://github.com/PlayCover/PlayTools/pull/80/ gets merged (and is compiled onto Nightly), you can run the Kindle app with SIP on and PlayChain enabled (make sure PlayChain debugging is off).
