### ISSUE TITLE
[App Support]: Udemy

### ISSUE THREAD

**Issue by BozsanyiArnold** [PlayCover/PlayCover#782]
### App Store link

https://apps.apple.com/us/app/udemy-online-video-courses/id562413829

### Current issues

- [ ] App fails to install
- [ ] App fails to open
- [ ] App crashes randomly during usage
- [ ] App experiences graphical issues or broken UI
- [ ] App fails to connect to servers
- [X] Other

### More details

App fails to log in.

### Issue Language

- [X] Yes my issue is written in English

**Comment by ohaiibuzzle** [comment]
Already fixed in PlayCover 3 alpha (using PlayChain)

**Comment by TheMoonThatRises** [comment]
Use Nightly version of PlayCover and enable PlayChain through the apps setting -> Bypasses. If the app is unable to open, install with the latest stable version of PlayCover, then upgrade to the Nightly version.

**Comment by BozsanyiArnold** [comment]
Thanks, much obliged!
