### ISSUE TITLE
[Bug]: Incorrect iOS device info

### ISSUE THREAD

**Issue by FlyMeToTheMoonAndLetMePlayAmongTheStars** [PlayCover/PlayCover#783]
### Describe the bug

<img width="320" src="https://user-images.githubusercontent.com/78054566/216861294-ba5437d8-4ee8-46f3-84a7-f62b86c79bbe.png">

3rd gen iPad Pro uses A12X not A12Z, Apple only started using A12Z with the 4th gen models and it has 6GB RAM 

so now the question is, where is the real error? Is it actually A12X or A12Z in PlayCover/PlayTools code?

### Steps to reproduce

just click on the iOS devices menu lol

### Expected behaviour

correct info

### Crash log

```shell
n/a
```

### What version of PlayCover are you using?

Nightly/beta

### What version of macOS are you using?

Ventura (macOS 13)

### Issue Language

- [X] Yes my issue is written in English

**Comment by FlyMeToTheMoonAndLetMePlayAmongTheStars** [comment]
Ok so I used PCTT to look up the actual model identifier, it says it's iPad8,6 which is indeed the 3rd gen iPad Pro, but it's A12X not A12Z, 4GB RAM is correct, 6GB is also correct but only applicable to 1TB storage models lol

**Comment by Depal1** [comment]
https://github.com/PlayCover/PlayCover/commit/461fa064fa6d324fa2254c6e9e1702b3d4db41b8
