### ISSUE TITLE
[Feature]: Support for more iOS device models

### ISSUE THREAD

**Issue by FlyMeToTheMoonAndLetMePlayAmongTheStars** [PlayCover/PlayCover#784]
### Is your feature request related to a problem?

<img width="343" alt="image" src="https://user-images.githubusercontent.com/78054566/216863209-7df7edb2-163a-4e15-af04-3e294eec8530.png">

as you can see there's not enough options here 

### Describe the solution you'd like

for 12.9" iPad Pro models add 2nd and 4th gen

for iPhones add 11 Pro Max and 12 Pro Max

also the RAM amount is not very helpful info, maybe it would be better to change that to the year the device was released or [MTLGPUFamily](https://developer.apple.com/documentation/metal/mtlgpufamily)

### Anything else?

the more the merrier?

### Issue Language

- [X] Yes my issue is written in English

**Comment by TheMoonThatRises** [comment]
There isn't much need for more devices since more options isn't always useful, and may confuse the user. The devices already listed are fine, as it covers a wide enough range.

**Comment by FlyMeToTheMoonAndLetMePlayAmongTheStars** [comment]
More options would allow more granular performance tuning for users, especially people with fanless MacBook Airs. The 4th gen A12Z iPad model that is not available might provide better graphical quality than the 3rd gen A12X one without a high performance cost as the M1 option. 

I don't think it would confuse users since they can simply consult the documentation to better understand its usage. Also if they are accessing and tinkering with app settings, it's safe to assume they know what they're doing. What's the worst thing that could happen? A curious user might experiment with older device models but realizes the graphics look worse than the default M1 model, and then switches back to M1.
