### ISSUE TITLE
[Bug]: MacOS 13.2 Lower Resolution than before

### ISSUE THREAD

**Issue by fubukishiro** [PlayCover/PlayCover#787]
### Describe the bug

Previous screenshot on MacOS 13.1
![5431675655746_ pic](https://user-images.githubusercontent.com/19640215/216880938-d13644b7-bd97-4df6-9cff-e240e6544cf7.jpg)

Current screenshot on MacOS 13.2
![WX20230206-115500@2x](https://user-images.githubusercontent.com/19640215/216880939-cf13ac3d-64a3-4156-b8ce-ce94c223fdc2.png)

Even though the issue reported in https://github.com/PlayCover/PlayTools/issues/64 has been fixed, when the resolution is set to [default], this offset bug still exists. 
![WX20230206-120852@2x](https://user-images.githubusercontent.com/19640215/216882149-df8ce74d-ced3-495d-8e02-3ca005b8081b.png)

### Steps to reproduce

For the offset bug,
![WX20230206-121426@2x](https://user-images.githubusercontent.com/19640215/216882323-448cbc25-b74b-468f-92ed-9b794d01d08c.png)

### Expected behaviour

(1) The resolution becomes better.
(2) The offset bug is fixed when the resolution is set to [default]

### What version of PlayCover are you using?

2.0.4

### What version of macOS are you using?

Ventura (macOS 13)

### Issue Language

- [X] Yes my issue is written in English

**Comment by TheMoonThatRises** [comment]
Games such as Genshin should not be set to default, but that issue is being address here: https://github.com/PlayCover/PlayTools/pull/77. As for the resolution issue, that is fixed in https://github.com/PlayCover/PlayTools/pull/75 and is out on nightly builds.

**Comment by JoseMoreville** [comment]
There is a fix for default, but its still work in progress
