### ISSUE TITLE
SoundDeviceService not working as intended and game crashes at high bitrate

### ISSUE THREAD

**Issue by IsaacMarovitz** [PlayCover/PlayCover#79]
**SoundDeviceService does not:**

- Notify the user of incorrect sound setup
- Automatically correct audio output bitrate as intended

**Game crashes at high bitrate (unknown cause).** If this issue were solved, SoundDeviceService and SimplyCoreAudio would no longer be required.

Steps to reproduce high-bitrate crash:

- Set MacBook Speakers output formate to '96,000 Hz' in Audio MIDI Setup
- Launch Genshin
- Start keymapping/lock cursor with Option
- Enter a combat scenario
- Audio will cut out, and a few seconds later, game will freeze

**Comment by Depal1** [comment]
Associated with issue #35.

**Comment by IsaacMarovitz** [comment]
Correction:
SoundDeviceService **WILL** display an alert if audio settings are wrong however the alert is formatted incorrectly, and it will not correct audio settings automatically.

Instructions presented by the dialogue are not clear.

**Comment by IsaacMarovitz** [comment]
Update:
I have a fix for SoundDeviceService in the pipeline will be arriving soon :)
