### ISSUE TITLE
[Game Support]:  

### ISSUE THREAD

**Issue by bagrishikashvili** [PlayCover/PlayCover#798]
### App Store link

hi how to fix it? try run alert popup
**Using this app through PlayCover will likely result in a ban!**

### Current issues

- [ ] Game fails to install
- [ ] Game fails to open
- [ ] Game crashes randomly during gameplay
- [ ] Game does not work with keymapping
- [ ] Game experiences graphical issues or broken UI
- [ ] Game fails to connect to servers or complete download

### More details

hi how to fix it? try run alert popup
**Using this app through PlayCover will likely result in a ban!**

### Issue Language

- [X] Yes my issue is written in English

**Comment by XuYicong** [comment]
duplicate of https://github.com/PlayCover/PlayCover/issues/238
