### ISSUE TITLE
[Bug]: Changing the resolution does not display correctly.

### ISSUE THREAD

**Issue by tellus1019** [PlayCover/PlayCover#801]
### Describe the bug

Vertical games do not display properly when the resolution is set to anything other than "Default" from the graphics settings.

### Steps to reproduce

* I used the following application to check.
https://apps.apple.com/us/app/destiny-child/id1416959016

You can check by installing the application on PlayCover (2.0.4) and following the steps below.

1. confirm activation of normal settings
Start up without modifying the graphics settings.
The application starts up in iPad resolution and can be played without any problems.

2. exit the application and change the graphics settings
First, exit the application that was normally launched.
Then open the application settings and go to the graphics settings.
Select anything other than "Default" from the resolution settings.

*Auto, 1080p, 4K, or custom. Any of these is acceptable.
*Enter a value that matches the monitor resolution to finalize the resolution setting.

3. When start the application, a window with a corrupted display opens.
When the application is launched, the window resizes but is not displayed correctly.
The game screen is stretched horizontally and much of the screen extends outside the window.

PlayCover 2.0.4
![PlayCover 2 0 4](https://user-images.githubusercontent.com/25951129/218659091-3b93a44a-4b06-40fc-83ec-d4440ef913b0.png)

PlayCover2.0.0
![PlayCover 2 0 0](https://user-images.githubusercontent.com/25951129/218659113-019ef5db-ac8d-490a-b645-664fca0d93ad.png)

### Expected behaviour

The application display should conform to the window size.
*Displayed correctly in PlayCover (2.0.0)
　There seems to be a problem with the changes made in the most recent update.

### What version of PlayCover are you using?

2.0.4

### What version of macOS are you using?

Ventura (macOS 13)

### Issue Language

- [X] Yes my issue is written in English

**Comment by DSPerson** [comment]
me tooooo!

**Comment by TheMoonThatRises** [comment]
Could potentially be fixed with https://github.com/PlayCover/PlayTools/pull/77, but is still a work in progress.

**Comment by Misterlonely1069** [comment]
Same problem, but everything works fine in Monterey

**Comment by TheMoonThatRises** [comment]
Can you try with the latest nightly to see if it is fixed for you?

**Comment by tellus1019** [comment]
I checked the latest nightly build and the problem has been resolved.
I sincerely hope this applies to mainstream.

**Comment by seggsyhoney** [comment]
I found a fix for me to display the content by changing the resolution to 9:16 ratio, but the touches are all wrong. Can someone help me?
