### ISSUE TITLE
[App Support]: Pleco Chinese Dictionary crashes instantly after starting with exit code 0

### ISSUE THREAD

**Issue by zqidev** [PlayCover/PlayCover#805]
### App Store link

https://apps.apple.com/us/app/pleco-chinese-dictionary/id341922306?ign-mpt=uo%3D4

### Current issues

- [ ] App fails to install
- [X] App fails to open
- [ ] App crashes randomly during usage
- [ ] App experiences graphical issues or broken UI
- [ ] App fails to connect to servers
- [ ] Other

### More details

Starting the app simply results in the icon showing on the dock and then the application instantly exiting with exit code 0.

### Crash log

```shell
n/a: exit code 0
```

### Issue Language

- [X] Yes my issue is written in English

**Comment by TheMoonThatRises** [comment]
Install the app without PlayTools (or go into settings -> Misc -> Remove PlayTools).
