### ISSUE TITLE
[Game Support]: Top Drives – Car Cards Racing

### ISSUE THREAD

**Issue by TheBigFishPlayz** [PlayCover/PlayCover#810]
### App Store link

https://apps.apple.com/au/app/top-drives-car-cards-racing/id1069370674

### Current issues

- [ ] Game fails to install
- [X] Game fails to open
- [ ] Game crashes randomly during gameplay
- [ ] Game does not work with keymapping
- [ ] Game experiences graphical issues or broken UI
- [ ] Game fails to connect to servers or complete download

### More details

The game successfully installs into the library in play cover. However, when I launch the game, I get stuck immediately on a frozen loading screen that never progresses. The game doesn't crash, it just stays frozen on this screen indefinitely. I would greatly appreciate your help with this! Thank you :)

### Issue Language

- [X] Yes my issue is written in English

**Comment by TheMoonThatRises** [comment]
What version of PlayCover are you using? I cannot replicate this issue on 2.0.4.

**Comment by TheBigFishPlayz** [comment]
> What version of PlayCover are you using? I cannot replicate this issue on 2.0.4.

I, too am on 2.0.4. How far did you get with the loading? I can only get to the first loading screen that says Hutch and evo, but I never progress pass that screen. I have followed all instructions to disable SIP and all the like, so I'm not quite sure what I've done incorrectly. Please let me know what to try next, thank you.

**Comment by TheMoonThatRises** [comment]
Try with SIP enabled. It worked for me like that.

**Comment by TheBigFishPlayz** [comment]
> Try with SIP enabled. It worked for me like that.

I have tried again with SIP enabled and still have the same outcome. I get stuck on the first loading screen that says Hutch and evo, but never progress further with the game loading.

What else do you suggest I try?

For reference, I am running on an M2 Macbook Pro with running Ventura 13.2

**Comment by TheMoonThatRises** [comment]
Are you using the latest version of the app (it should say 18.00.00 in PlayCover)?

**Comment by TheBigFishPlayz** [comment]
> Are you using the latest version of the app (it should say 18.00.00 in PlayCover)?

Yep, that's the version I'm using. Even when the previous version was current at that time, it also didn't work.

**Comment by TheMoonThatRises** [comment]
Hmm, that is very strange.

> I have followed all instructions to disable SIP and all the like

Did you make sure to reverse everything you did here?

**Comment by TheBigFishPlayz** [comment]
> Hmm, that is very strange.
> 
> > I have followed all instructions to disable SIP and all the like
> 
> Did you make sure to reverse everything you did here?

Yes, I 100% reversed everything.

**Comment by TheBigFishPlayz** [comment]
Any further suggestions about what to do?

**Comment by TheMoonThatRises** [comment]
Try using the latest nightly.

**Comment by TheBigFishPlayz** [comment]
> Try using the latest nightly.

Where do you download your decrypted IPA from? Perhaps that may be the source of the problem

**Comment by TheMoonThatRises** [comment]
I got my IPA from decrypt.day.

**Comment by TheBigFishPlayz** [comment]
That's also where I got mine from... did you download the IPA and then add it through PlayCover; or did you add it to the synced library on decrypt.day?

**Comment by TheBigFishPlayz** [comment]
Ok, I think I improperly installed the nightly build; I just redid it and the game launched perfectly. Thank you for all your help and patience.
