### ISSUE TITLE
[Feature]: remember last app window position

### ISSUE THREAD

**Issue by FlyMeToTheMoonAndLetMePlayAmongTheStars** [PlayCover/PlayCover#812]
### Is your feature request related to a problem?

yes, window positions of apps are reset when you re-open them

### Describe the solution you'd like

if you dragged the window to a certain spot, it should be in the same spot the next time you re-open the app

### Anything else?

 no

### Issue Language

- [X] Yes my issue is written in English

**Comment by JoseMoreville** [comment]
This is not at any priority level and is not really useful to be worked on. if someone wants to do it is welcome to PR.
