### ISSUE TITLE
[Feature]: Enable Disabling Keymapping while Mouse Mapping setting is turned off

### ISSUE THREAD

**Issue by devforey** [PlayCover/PlayCover#813]
### Is your feature request related to a problem?

Yes. While playing Ragnarok M, I can't chat while having Keyboard Mapping is turned on and Mouse Mapping turned off. I can, however, chat by toggling [Option] key but it requires me to turn on Mouse Mapping which is not an ideal setup for the game.

### Describe the solution you'd like

Enable Disabling Keymapping by toggling [Option] key while Mouse Mapping setting is turned off

### Anything else?

[Discord Chat Support](https://discord.com/channels/871829896492642387/1078266979003146320/1078266979003146320)

### Issue Language

- [X] Yes my issue is written in English

**Comment by XuYicong** [comment]
Working in progress here: https://github.com/PlayCover/PlayTools/pull/88

**Comment by XuYicong** [comment]
The PR above has been merged. This issue should have been resolved. You can try it in latest nightly.
