### ISSUE TITLE
[Bug]: Playcover The app threw an error during conversion !

### ISSUE THREAD

**Issue by zhugunick** [PlayCover/PlayCover#815]
### Describe the bug

genshin cannot be opened, perhaps because I repeatedly overwrote two different genshins, resulting in a confusion between files, at first it crashed, then I tried to delete, and started to re-import genshin.ipa, and this happened. Please tell me how to solve the problem.

### Steps to reproduce

Two different genshins:playcover genshin.ipa&genshin.dmg

### Expected behaviour

none

### Crash log
-------------------------------------
Translated Report (Full Report Below)
-------------------------------------

Process:               Yuanshen [3198]
Path:                  /Users/USER/Library/Containers/io.playcover.PlayCover/原神.app/Yuanshen
Identifier:            com.miHoYo.Yuanshen
Version:               3.4.0 (515)
Code Type:             ARM-64 (Native)
Parent Process:        launchd [1]
User ID:               501

Date/Time:             2023-02-25 15:44:07.1047 +0800
OS Version:            macOS 13.2.1 (22D68)
Report Version:        12
Anonymous UUID:        56816DDC-E756-AF10-0DE0-47805494D61A

Time Awake Since Boot: 3200 seconds

System Integrity Protection: enabled

Crashed Thread:        0

Exception Type:        EXC_CRASH (SIGABRT)
Exception Codes:       0x0000000000000000, 0x0000000000000000

Termination Reason:    Namespace DYLD, Code 1 Library missing
Library not loaded: /System/Library/Frameworks/AssetsLibrary.framework/AssetsLibrary
Referenced from: <9A1082FA-36C3-3570-AD2D-88D5182CAD5A> /Users/USER/Library/Containers/io.playcover.PlayCover/原神.app/Yuanshen
Reason: tried: '/System/Library/Frameworks/AssetsLibrary.framework/AssetsLibrary' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/System/Library/Frameworks/AssetsLibrary.framework/AssetsLibrary' (no such file), '/System/Library/Frameworks/AssetsLibrary.framework/AssetsLibrary' (no such file, not in dyld cache), '/Library/Frameworks/AssetsLibrary.framework/AssetsLibrary' (no such file)
(terminated at launch; ignore backtrace)

Thread 0 Crashed:
0   dyld                          	       0x1967ff190 __abort_with_payload + 8
1   dyld                          	       0x196809a00 abort_with_payload_wrapper_internal + 104
2   dyld                          	       0x196809a34 abort_with_payload + 16
3   dyld                          	       0x1967980a4 dyld4::halt(char const*) + 328
4   dyld                          	       0x196795098 dyld4::prepare(dyld4::APIs&, dyld3::MachOAnalyzer const*) + 4204
5   dyld                          	       0x196793dc4 start + 2404

Thread 0 crashed with ARM Thread State (64-bit):
    x0: 0x0000000000000006   x1: 0x0000000000000001   x2: 0x000000016db568f0   x3: 0x000000000000009f
    x4: 0x000000016db564f0   x5: 0x0000000000000000   x6: 0x0000000000000000   x7: 0x0000000000000a20
    x8: 0x0000000000000020   x9: 0x0000000000000009  x10: 0x0000000000000001  x11: 0x000000000000000a
   x12: 0x0000000000000000  x13: 0x0000000000000033  x14: 0x0000000233eec12a  x15: 0xffffffffffffffff
   x16: 0x0000000000000209  x17: 0x0000000196791344  x18: 0x0000000000000000  x19: 0x0000000000000000
   x20: 0x000000016db564f0  x21: 0x000000000000009f  x22: 0x000000016db568f0  x23: 0x0000000000000001
   x24: 0x0000000000000006  x25: 0x00000001f254f600  x26: 0x000000016db573b0  x27: 0x000000016db57218
   x28: 0x0000000000000000   fp: 0x000000016db564c0   lr: 0x0000000196809a00
    sp: 0x000000016db56480   pc: 0x00000001967ff190 cpsr: 0x00001000
   far: 0x0000000112974000  esr: 0x56000080  Address size fault

Binary Images:
       0x19678e000 -        0x196818ba3 dyld (*) <191e84f1-4b95-39c8-b253-1c1ef56c0fa8> /usr/lib/dyld

External Modification Summary:
  Calls made by other processes targeting this process:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0
  Calls made by this process:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0
  Calls made by all processes on this machine:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0

VM Region Summary:
ReadOnly portion of Libraries: Total=992.3M resident=0K(0%) swapped_out_or_unallocated=992.3M(100%)
Writable regions: Total=15.8M written=0K(0%) resident=0K(0%) swapped_out=0K(0%) unallocated=15.8M(100%)

                                VIRTUAL   REGION 
REGION TYPE                        SIZE    COUNT (non-coalesced) 
===========                     =======  ======= 
STACK GUARD                       56.0M        1 
Stack                             8176K        1 
VM_ALLOCATE                         16K        1 
__DATA                            38.3M        3 
__DATA_CONST                        22K        1 
__DATA_DIRTY                         7K        1 
__LINKEDIT                       773.8M        2 
__TEXT                           218.6M        2 
dyld private memory                512K        2 
===========                     =======  ======= 
TOTAL                              1.1G       14 

-----------
Full Report
-----------

{"app_name":"Yuanshen","timestamp":"2023-02-25 15:44:07.00 +0800","app_version":"3.4.0","slice_uuid":"9a1082fa-36c3-3570-ad2d-88d5182cad5a","build_version":"515","platform":1,"bundleID":"com.miHoYo.Yuanshen","share_with_app_devs":1,"is_first_party":0,"bug_type":"309","os_version":"macOS 13.2.1 (22D68)","roots_installed":0,"name":"Yuanshen","incident_id":"31B3BAB6-3459-4E50-A5D9-2192EFAEA15E"}
{
  "uptime" : 3200,
  "procRole" : "Background",
  "version" : 2,
  "userID" : 501,
  "deployVersion" : 210,
  "modelCode" : "MacBookPro18,1",
  "coalitionID" : 2174,
  "osVersion" : {
    "train" : "macOS 13.2.1",
    "build" : "22D68",
    "releaseType" : "User"
  },
  "captureTime" : "2023-02-25 15:44:07.1047 +0800",
  "incident" : "31B3BAB6-3459-4E50-A5D9-2192EFAEA15E",
  "pid" : 3198,
  "translated" : false,
  "cpuType" : "ARM-64",
  "roots_installed" : 0,
  "bug_type" : "309",
  "procLaunch" : "2023-02-25 15:44:02.8454 +0800",
  "procStartAbsTime" : 78402757186,
  "procExitAbsTime" : 78504619049,
  "procName" : "Yuanshen",
  "procPath" : "\/Users\/USER\/Library\/Containers\/io.playcover.PlayCover\/原神.app\/Yuanshen",
  "bundleInfo" : {"CFBundleShortVersionString":"3.4.0","CFBundleVersion":"515","CFBundleIdentifier":"com.miHoYo.Yuanshen","DTAppStoreToolsBuild":"14C17"},
  "storeInfo" : {"deviceIdentifierForVendor":"4712AEFA-62C1-54B4-94FC-D8B24E295E11","thirdParty":true},
  "parentProc" : "launchd",
  "parentPid" : 1,
  "coalitionName" : "com.miHoYo.Yuanshen",
  "crashReporterKey" : "56816DDC-E756-AF10-0DE0-47805494D61A",
  "throttleTimeout" : 2147483647,
  "sip" : "enabled",
  "exception" : {"codes":"0x0000000000000000, 0x0000000000000000","rawCodes":[0,0],"type":"EXC_CRASH","signal":"SIGABRT"},
  "termination" : {"code":1,"flags":518,"namespace":"DYLD","indicator":"Library missing","details":["(terminated at launch; ignore backtrace)"],"reasons":["Library not loaded: \/System\/Library\/Frameworks\/AssetsLibrary.framework\/AssetsLibrary","Referenced from: <9A1082FA-36C3-3570-AD2D-88D5182CAD5A> \/Users\/USER\/Library\/Containers\/io.playcover.PlayCover\/原神.app\/Yuanshen","Reason: tried: '\/System\/Library\/Frameworks\/AssetsLibrary.framework\/AssetsLibrary' (no such file), '\/System\/Volumes\/Preboot\/Cryptexes\/OS\/System\/Library\/Frameworks\/AssetsLibrary.framework\/AssetsLibrary' (no such file), '\/System\/Library\/Frameworks\/AssetsLibrary.framework\/AssetsLibrary' (no such file, not in dyld cache), '\/Library\/Frameworks\/AssetsLibrary.framework\/AssetsLibrary' (no such file)"]},
  "extMods" : {"caller":{"thread_create":0,"thread_set_state":0,"task_for_pid":0},"system":{"thread_create":0,"thread_set_state":0,"task_for_pid":0},"targeted":{"thread_create":0,"thread_set_state":0,"task_for_pid":0},"warnings":0},
  "faultingThread" : 0,
  "threads" : [{"triggered":true,"id":65584,"threadState":{"x":[{"value":6},{"value":1},{"value":6135572720},{"value":159},{"value":6135571696},{"value":0},{"value":0},{"value":2592},{"value":32},{"value":9},{"value":1},{"value":10},{"value":0},{"value":51},{"value":9461219626},{"value":18446744073709551615},{"value":521},{"value":6819484484,"symbolLocation":392,"symbol":"__simple_bprintf"},{"value":0},{"value":0},{"value":6135571696},{"value":159},{"value":6135572720},{"value":1},{"value":6},{"value":8360621568,"symbolLocation":0,"symbol":"gProcessInfo"},{"value":6135575472},{"value":6135575064},{"value":0}],"flavor":"ARM_THREAD_STATE64","lr":{"value":6819977728},"cpsr":{"value":4096},"fp":{"value":6135571648},"sp":{"value":6135571584},"esr":{"value":1442840704,"description":" Address size fault"},"pc":{"value":6819934608,"matchesCrashFrame":1},"far":{"value":4606869504}},"frames":[{"imageOffset":463248,"symbol":"__abort_with_payload","symbolLocation":8,"imageIndex":0},{"imageOffset":506368,"symbol":"abort_with_payload_wrapper_internal","symbolLocation":104,"imageIndex":0},{"imageOffset":506420,"symbol":"abort_with_payload","symbolLocation":16,"imageIndex":0},{"imageOffset":41124,"symbol":"dyld4::halt(char const*)","symbolLocation":328,"imageIndex":0},{"imageOffset":28824,"symbol":"dyld4::prepare(dyld4::APIs&, dyld3::MachOAnalyzer const*)","symbolLocation":4204,"imageIndex":0},{"imageOffset":24004,"symbol":"start","symbolLocation":2404,"imageIndex":0}]}],
  "usedImages" : [
  {
    "source" : "P",
    "arch" : "arm64e",
    "base" : 6819471360,
    "size" : 568228,
    "uuid" : "191e84f1-4b95-39c8-b253-1c1ef56c0fa8",
    "path" : "\/usr\/lib\/dyld",
    "name" : "dyld"
  }
],
  "sharedCache" : {
  "base" : 6818824192,
  "size" : 3447455744,
  "uuid" : "835716ae-b363-3187-b065-cf94139bfc85"
},
  "vmSummary" : "ReadOnly portion of Libraries: Total=992.3M resident=0K(0%) swapped_out_or_unallocated=992.3M(100%)\nWritable regions: Total=15.8M written=0K(0%) resident=0K(0%) swapped_out=0K(0%) unallocated=15.8M(100%)\n\n                                VIRTUAL   REGION \nREGION TYPE                        SIZE    COUNT (non-coalesced) \n===========                     =======  ======= \nSTACK GUARD                       56.0M        1 \nStack                             8176K        1 \nVM_ALLOCATE                         16K        1 \n__DATA                            38.3M        3 \n__DATA_CONST                        22K        1 \n__DATA_DIRTY                         7K        1 \n__LINKEDIT                       773.8M        2 \n__TEXT                           218.6M        2 \ndyld private memory                512K        2 \n===========                     =======  ======= \nTOTAL                              1.1G       14 \n",
  "legacyInfo" : {
  "threadTriggered" : {

  }
},
  "trialInfo" : {
  "rollouts" : [
    {
      "rolloutId" : "5ffde50ce2aacd000d47a95f",
      "factorPackIds" : {

      },
      "deploymentId" : 240000251
    },
    {
      "rolloutId" : "63a0a6cfd1cdb67d083006d0",
      "factorPackIds" : {

      },
      "deploymentId" : 240000003
    }
  ],
  "experiments" : [

  ]
}
}

Model: MacBookPro18,1, BootROM 8419.80.7, proc 10:8:2 processors, 16 GB, SMC 
Graphics: Apple M1 Pro, Apple M1 Pro, Built-In
Display: Color LCD, 3456 x 2234 Retina, Main, MirrorOff, Online
Memory Module: LPDDR5, Samsung
AirPort: spairport_wireless_card_type_wifi (0x14E4, 0x4387), wl0: Nov 30 2022 02:17:16 version 20.10.965.13.8.7.131 FWID 01-1251c18d
Bluetooth: Version (null), 0 services, 0 devices, 0 incoming serial ports
Network Service: Wi-Fi, AirPort, en0
Network Service: Shadowrocket, VPN (com.liguangming.Shadowrocket), utun3
USB Device: USB31Bus
USB Device: USB31Bus
USB Device: USB31Bus
Thunderbolt Bus: MacBook Pro, Apple Inc.
Thunderbolt Bus: MacBook Pro, Apple Inc.
Thunderbolt Bus: MacBook Pro, Apple Inc.

```shell
none
```

### What version of PlayCover are you using?

Nightly/beta

### What version of macOS are you using?

Ventura (macOS 13)

### Issue Language

- [X] Yes my issue is written in English

**Comment by TheMoonThatRises** [comment]
Install with a stable version of PlayCover. The nightly build is known to have an installer issue.
