### ISSUE TITLE
[Feature]: add support for 120Hz screen refresh rate

### ISSUE THREAD

**Issue by QuentinFung** [PlayCover/PlayCover#816]
### Is your feature request related to a problem?

No

### Describe the solution you'd like

Would like to add back the 120Hz screen refresh rate option provided in version 1.1.1.

### Anything else?

No

### Issue Language

- [X] Yes my issue is written in English

**Comment by JoseMoreville** [comment]
That feature never worked. we allow 120hz games to play at 120 if the game supports it
