### ISSUE TITLE
[App Support]: cms.app[招商证券]

### ISSUE THREAD

**Issue by skill7899** [PlayCover/PlayCover#822]
### App Store link

https://apps.apple.com/cn/app/%E6%8B%9B%E5%95%86%E8%AF%81%E5%88%B8-%E7%82%92%E8%82%A1%E7%90%86%E8%B4%A2%E5%B9%B3%E5%8F%B0/id1042567321

### Current issues

- [ ] App fails to install
- [X] App fails to open
- [ ] App crashes randomly during usage
- [ ] App experiences graphical issues or broken UI
- [ ] App fails to connect to servers
- [ ] Other

### More details

someone  test it can run in macos 12, but my mbp is macos 13, it can not to open.

### Issue Language

- [X] Yes my issue is written in English

**Comment by skill7899** [comment]
[open-detail.log](https://github.com/PlayCover/PlayCover/files/10846271/open-detail.log)

**Comment by XuYicong** [comment]
PlayCover does not support banking or financial/investment related APPs. These APPs usually require clean execution environment which cannot and should not be bypassed. Otherwise your money would be in danger.
