### ISSUE TITLE
[Game Support]: 

### ISSUE THREAD

**Issue by shubibin** [PlayCover/PlayCover#831]
### App Store link

https://apps.apple.com/cn/app/%E9%95%BF%E7%94%9F%E8%AF%80-%E5%94%AF%E7%BE%8E%E5%9B%BD%E9%A3%8E%E5%AF%BB%E4%BB%99%E6%83%85%E7%BC%98%E4%B9%8B%E6%97%85/id1208081593

### Current issues

- [ ] Game fails to install
- [X] Game fails to open
- [ ] Game crashes randomly during gameplay
- [ ] Game does not work with keymapping
- [ ] Game experiences graphical issues or broken UI
- [ ] Game fails to connect to servers or complete download

### More details

此应用已被加密！请使用未加密的 ipa文件。现已不再支持来自iMazing 的ipa！
This application is encrypted! Use an unencrypted ipa file. ipa from iMazing is no longer supported!

### Issue Language

- [X] Yes my issue is written in English

**Comment by TheMoonThatRises** [comment]
Get the IPA from an IPA decrypter, such as decrypt.day or armconverter.
