### ISSUE TITLE
[Feature]: Install applications along path `/Applications`

### ISSUE THREAD

**Issue by rakleed** [PlayCover/PlayCover#833]
### Is your feature request related to a problem?

To open an installed application, you need to launch PlayCover every time or manually create an alias and add it to `/Applications`, which is very inconvenient.

### Describe the solution you'd like

Install applications in `/Applications` as Sideloadly. Or automatically create an application alias in `/Applications`, although this is not the best option, since it is not in Spotlight anyway.

### Anything else?

N/A

### Issue Language

- [X] Yes my issue is written in English

**Comment by TheMoonThatRises** [comment]
Already has been implemented in #740 as an option to add app alias to ~/Applications in settings. Also, an alias in the Applications directory will appear in Spotlight.

**Comment by rakleed** [comment]
@TheMoonThatRises could you please add the feature to directly install in `/Applications` like Sideloadly does?

**Comment by TheMoonThatRises** [comment]
Is there any specific reason why it needs to be in `/Applications`? The reason why we don't do it is because it will be hard to keep track of apps that are installed through PlayCover.

**Comment by rakleed** [comment]
When I manually created an alias in `/Applications`, then for some reason when searching in Raycast (similar to Spotlight), the name of the app is displayed in Russian instead of the system language (English). If your implementation does not have such a problem, then great. (Or maybe this is a problem with Raycats.)

**Comment by TheMoonThatRises** [comment]
Try searching for the app in Russian. If it displays correctly there, then it is a Raycast issue. All that is currently implemented on the `develop` branch is the ability to add an alias to `~/Applications/PlayCover/` which Spotlight and Launchpad can pick up.

**Comment by rakleed** [comment]
Indeed, this was a problem either with the system (the Russian language was duplicated in the macOS settings), or Raycast.
