### ISSUE TITLE
[App Support]: Yandex Music is not displayed in landscape orientation

### ISSUE THREAD

**Issue by rakleed** [PlayCover/PlayCover#834]
### App Store link

https://apps.apple.com/app/yandex-music-books-podcasts/id520797969

### Current issues

- [ ] App fails to install
- [ ] App fails to open
- [ ] App crashes randomly during usage
- [X] App experiences graphical issues or broken UI
- [ ] App fails to connect to servers
- [X] Other

### More details

Yandex Music is not displayed in landscape orientation when trying to change it through the View menu.

### Issue Language

- [X] Yes my issue is written in English

**Comment by ohaiibuzzle** [comment]
You can try using App Default Mode. This is a native windowed iPad app so it may support native resizable windows

**Comment by TheMoonThatRises** [comment]
Can you give a screenshot of what the app looks like?

**Comment by rakleed** [comment]
> You can try using App Default Mode.

I just use it, since it only has the correct scale of the application interface elements.

Here is a screen recording of the problems: https://share.cleanshot.com/Rp1C9kK3

**Comment by ohaiibuzzle** [comment]
@rakleed When using App Default mode, PlayCover apps behaves exactly like macOS apps (meaning you can move your mouse to one side of the window and drag to resize)

Also, I was able to flip the app just fine 
<img width="1031" alt="image" src="https://user-images.githubusercontent.com/23693150/222971677-41d6bb02-2a5e-41aa-8d36-7b273b81d603.png">

**Comment by rakleed** [comment]
@ohaiibuzzle I deleted my version with all the data, downloaded the latest version 6.07 from the site https://armconverter.com/decryptedappstore/us, installed it, but the problems are still the same, and dragging the edge of the window does not work for me either: https://share.cleanshot.com/4sK3p9LD

**Comment by TheMoonThatRises** [comment]
Having the resolution set to auto works fine for me. Try using the latest nightly.

![Screenshot 2023-05-14 at 18 23 17](https://github.com/PlayCover/PlayCover/assets/58153205/67320dfa-e7c9-4aee-83eb-dd901617ff92)

**Comment by rakleed** [comment]
How can I download the nightly version? I did not find such an opportunity either in Releases or in GitHub Actions. Is there only an option for me to build the app myself?

**Comment by TheMoonThatRises** [comment]
https://github.com/PlayCover/PlayCover/actions/workflows/2.nightly_release.yml, or direct artifact download https://github.com/PlayCover/PlayCover/suites/12911904608/artifacts/697195756

**Comment by rakleed** [comment]
@TheMoonThatRises now the app is displayed only in landscape orientation, both in Auto and App Default resolution. Through the App Menu, changing the view to portrait orientation does not work, and when I try to stretch the window with the mouse, nothing happens either.

**Comment by TheMoonThatRises** [comment]
You can change the window to portrait by setting the resolution to `App Default`, ticking the `Fix window display issue`, and selecting `Alternate` from the drop down.

**Comment by rakleed** [comment]
In this case, half of the app content is simply cut off:
<details><summary>Screenshot:</summary>

![Screenshot 2023-05-16 at 22 13 23](https://github.com/PlayCover/PlayCover/assets/19418601/600a4bab-7f81-4fb0-8800-47d07b7404f8)

</details>

And why can't I change the orientation while the app is running?

**Comment by TheMoonThatRises** [comment]
> In this case, half of the app content is simply cut off:

My bad, its not `Alternate`, it should be `Normal`.

> And why can't I change the orientation while the app is running?

It could be possible, I don't know. I would ask @ohaiibuzzle.

**Comment by rakleed** [comment]
> My bad, its not `Alternate`, it should be `Normal`.

Still half of the app content is cut off:

<details><summary>Screenshot:</summary>

![Screenshot 2023-05-17 at 01 26 40](https://github.com/PlayCover/PlayCover/assets/19418601/b6cc7f2a-eb38-4cfa-9379-8800c79a5b00)

</details>

**Comment by TheMoonThatRises** [comment]
Do you have these settings?
<img width="995" alt="Screenshot 2023-05-16 at 16 32 09" src="https://github.com/PlayCover/PlayCover/assets/58153205/84e14c79-62f4-4606-aa62-f2bcc2b6cd20">

**Comment by rakleed** [comment]
Yes, exactly the same settings.

**Comment by ohaiibuzzle** [comment]
@rakleed You can kinda do it like this (specify a **square resolution** for more consistency)
<img width="1680" alt="image" src="https://github.com/PlayCover/PlayCover/assets/23693150/87524071-0bb0-4639-8722-ad27554808d2">
I think it is some kind of bugs in the display engine still :/

**Comment by rakleed** [comment]
> Do you have these settings? <img alt="Screenshot 2023-05-16 at 16 32 09" width="995" src="https://user-images.githubusercontent.com/58153205/238785901-84e14c79-62f4-4606-aa62-f2bcc2b6cd20.png">

Now, after changing the Graphics settings many times, the app finally displays normally with these settings.

---

> @rakleed You can kinda do it like this (specify a **square resolution** for more consistency) <img alt="image" width="1680" src="https://user-images.githubusercontent.com/23693150/238848114-87524071-0bb0-4639-8722-ad27554808d2.png"> I think it is some kind of bugs in the display engine still :/

Yep, that helped. But in the process, I noticed that sometimes the settings are correctly applied only after 2 launches of the app. And also if I change the custom resolution to App Default or Auto, then either there will be a black screen, or just most of the content will not be visible. So there are definitely problems with the rendering engine.

**Comment by ohaiibuzzle** [comment]
>Yep, that helped. But in the process, I noticed that sometimes the settings are correctly applied only after 2 launches of the app. And also if I change the custom resolution to App Default or Auto, then either there will be a black screen, or just most of the content will not be visible. So there are definitely problems with the rendering engine.

As I mentioned, use a **square** resolution for more consistency (eg. 1000 x 1001 so that height is larger than width and counts as vertical). It's gonna look a but quirky, but it will work

**Comment by rakleed** [comment]
What do you mean by consistency? With the proposed settings, I still cannot change the orientation of the app through the View menu, and also do not stretch the window with the mouse.
