### ISSUE TITLE
[Bug]: Crash occurs on Genshin Impact after updating the game to 3.5

### ISSUE THREAD

**Issue by hyh0220** [PlayCover/PlayCover#835]
### Describe the bug

Crash occurs after I updated the game to 3.5. It worked fine with 3.4.

### Steps to reproduce

Downloaded Genshin Impact 3.5 ipa file from decrypt.day
Imported the downloaded IPA file in PlayCover
Open Genshin Impact and logo showed up
Game crashed

I tried re-install PlayCover, re-install the game, re-download the game from a different source, clear game data, but nothing works. 

After I un-install the game and cleared the game data, the game crash immediately after I double click the app and pop up a message "An error occurred"

### Expected behaviour

The game opens normally 

### What version of PlayCover are you using?

Nightly/beta

### What version of macOS are you using?

Monterey (macOS 12)

### Issue Language

- [X] Yes my issue is written in English

**Comment by TheMoonThatRises** [comment]
Install using a stable version of PlayCover.
