### ISSUE TITLE
[Feature]:  hey, can you support  open multiple applications ？ thanks

### ISSUE THREAD

**Issue by liuqijie6** [PlayCover/PlayCover#836]
hey, can you support  open multiple applications ？ thanks

Like the Android emulator, it supports multiple applications

### Issue Language

- [X] Yes my issue is written in English

**Comment by ohaiibuzzle** [comment]
Multiple applications can be opened at the same time. 
Multiple instances of one application **will not be supported**. This is due to various technical reasons, as well as preventing PlayCover from being used as for bots.
