### ISSUE TITLE
[Feature]: unified app/ipa library 

### ISSUE THREAD

**Issue by FlyMeToTheMoonAndLetMePlayAmongTheStars** [PlayCover/PlayCover#848]
### Is your feature request related to a problem?

writing all this down asap before i forget 

right now the user experience is this (assuming playchain & xclt-less are already implemented btw):
1. download playcover
2. ask on the playcover discord for where to find IPA, since both the app and ipa libraries are empty out of the box
3. get told to read the docs which most ppl dont bother reading much (myself included even tho i wrote the docs lol) 
4. eventually find genshin, or any other app u want on decryptday or decryptkit or a gdrive link somewhere
5. download the ipa then add/drag it into playcover
6. go ask on the playcover discord again for keymaps or if ur adventurous enough, use the bot commands in the keymap channel
7. import keymap
8. now you can finally go play!

oh yea and most ppl dont even use/dont know how to use the ipa library 

### Describe the solution you'd like

the solution to this clunky user experience? combine app library and ipa library into one (incl. fancy ipa details) + auto import keymaps + include popular app detail pages out of the box. this would be an epic feature that will probably require a lot of coding and testing 

for starters, playcover would need to somehow know which apps are the most popular, maybe we can ask ipa source providers if they have this data 

imagine this: 

you heard about playcover from a friend or a youtube vid, and you heard it can run genshin on your mac, how cool is that? now u wanna give it a try yourself

when you first install playcover, theres only 1 unified library and its not empty, but there are icons/detail pages already for the most popular apps/games. none of these are pre-installed ofc, just have detailed/fancy pages where you can click on install and choose from ipa sources. you left click on the genshin icon in the grid/list and you see a detailed page with compatibility info, and available sources to install from, all you have to do is u click on install and choose from a source you want. apps that are verified to work really well on playcover (no crashes, fully working keymaps, etc.) can have a "verified by playcover" badge/tag in this detailed page 

instead of having to go find and import keymaps on ur own, playcover auto detects your resolution and matches it with an available one from the keymap repository, so after installing the app you can go ahead and open it to play right away

in this new unified library, headers will separate locally installed apps on ur mac and apps available for install from your sources, the interaction to open an app will be the same, double left click on the app to open it. however, single clicking the installed app will now take you to the detailed/fancy page, where you can click on open (essentially still 2 clicks to open). 

for installed apps, in the details page you can access app settings, uninstall, or switch between keymaps. if you changed your resolution/aspect ratio and the prev keymap no longer applies, playcover will auto download the appropriate keymap file when you next launch the game (should be fast, it's a tiny file anyway), so you'll never run into issues where the keymap is not aligned with in-game controls 

in the unified library view, there will also be sorting options (sorted by source/popularity by default), you can also sort by name, date added, size, etc. there would also be a filter to show only favorited apps that u have installed, all installed non-fave apps, and apps available for install from ipa sources

ofc the good ol list view and grid view options, add ipa button, and search will still be present 

### Anything else?

rly busy with school rn so i'll post some wireframes/mockups later 

### Issue Language

- [X] Yes my issue is written in English

**Comment by FlyMeToTheMoonAndLetMePlayAmongTheStars** [comment]
Quick sketch of how this could look like, the dotted lines indicates that part is 'floating', it stays there consistently as you scroll down the list of apps. Instead of 2 separate sections on the left side with a whole lotta empty space, the app library and ipa library are merged into one and differentiated by headers. These headers can be subject to filtering, sorting would apply universally, and you can click on the `>` to collapse/show all the apps part of that header. 

<img width="901" alt="image" src="https://user-images.githubusercontent.com/78054566/223599882-5b7e48c2-cdcb-4a4a-b088-a2a91ec09656.png">

The add button will stand out more from the rest of the buttons, clicking it will show a bubble that asks the user to choose between adding an app from IPA file or adding a new IPA source.

**Comment by ohaiibuzzle** [comment]
This is just 1.x over again. The main problem being that while we **can** do this, the whole reason why Sources are not included by default is that, legally speaking, dumping an IPA of even a free app is considered piracy and we don't want the project to have any kind of association with that front.

Sources are provided so users can easily provide their own IPA as it is a pretty *bad* idea if we starts doing what you suggest. We may add a default source of PlayCover's homegrown apps (eg. the PlayBug debugging tools) where we own the app
