### ISSUE TITLE
Prevent display from turning off while playing

### ISSUE THREAD

**Issue by kamui545** [PlayCover/PlayCover#85]
It would be nice if there is any way to prevent display from turning off while playing.

I have very strict settings: 1-2 min before showing screen saver to avoid screen burn.
The screen saver often shows up during dialogues and cut-scenes.

Thank you!

**Comment by ohaiibuzzle** [comment]
Will try to implement it. In the meantime, you can run `caffeinate` in your terminal when you launch your game which will disable all power saving features
