### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by Bonnenuit0** [PlayCover/PlayCover#864]
### Describe the bug

It is blank when you open the Flutter'page.

### Steps to reproduce

My project is native and flutter.  It is blank when you open the Flutter'page on PlayCover.

### Expected behaviour

Hopefully the flutter page will open properly.

### Crash log

```shell
There is no
```

### What version of PlayCover are you using?

2.0.4

### What version of macOS are you using?

Monterey (macOS 12)

### Issue Language

- [X] Yes my issue is written in English

**Comment by Bonnenuit0** [comment]
Log is "Could not signal service com.apple.WebKit.WebContent: 113: Could not find specified service.

**Comment by ohaiibuzzle** [comment]
> Log is "Could not signal service com.apple.WebKit.WebContent: 113: Could not find specified service.

We need the full logs. This is nothing we can go by
Also keep in mind that if you are developing an app you should use Xcode's Simulator

**Comment by IsaacMarovitz** [comment]
If you're developing your own app in Flutter, you should use Flutter's existing macOS support. If you're developing for only mobile devices as OHaii said, use Xcode's Simulator.
