### ISSUE TITLE
[Bug Report]: can't install games from IPA library -- MBP 14" M2 Pro

### ISSUE THREAD

**Issue by jinhui76** [PlayCover/PlayCover#874]
### Describe the bug

I cannot install any game from the IPA library with source URL //decrypt.day. I can see all the games in the library. But when I want to install any of them, it will start showing "Downloading" then says "An error occurred, forbidden".

My laptop is a Macbook Pro 14" with M2 Pro chip. Playcover latest version 2.0.5

Please help on this.

### Steps to reproduce

![Screenshot 2023-03-17 at 15 29 16](https://user-images.githubusercontent.com/55421648/225841034-47b27021-cfbb-4a48-9821-61876744ef4b.png)

### Expected behaviour

Please help me on this issue.

### What version of PlayCover are you using?

Nightly/beta

### What version of macOS are you using?

Ventura (macOS 13)

### Issue Language

- [X] Yes my issue is written in English

**Comment by TheMoonThatRises** [comment]
This is a problem with IPA library provider, not us. Download directly from the website or wait a bit.
