### ISSUE TITLE
[Bug]: Parameter error - Genshin Impact

### ISSUE THREAD

**Issue by Imnhan** [PlayCover/PlayCover#877]
### Describe the bug

parameter error

### Steps to reproduce

<img width="1590" alt="Screenshot 2023-03-19 at 16 10 41" src="https://user-images.githubusercontent.com/94832314/226165237-4b61121a-de29-4955-8bf4-7474f9b05d73.png">

### Expected behaviour

<img width="1590" alt="Screenshot 2023-03-19 at 16 02 39" src="https://user-images.githubusercontent.com/94832314/226165216-f269c3c5-d31b-4667-a212-c4819298c064.png">

### What version of PlayCover are you using?

Nightly/beta

### What version of macOS are you using?

Ventura (macOS 13)

### Issue Language

- [X] Yes my issue is written in English

**Comment by ohaiibuzzle** [comment]
Not a bug. Please read the docs.

**Comment by Imnhan** [comment]
Sorry, but where's the docs?
