### ISSUE TITLE
[Feature]: Add Library management function

### ISSUE THREAD

**Issue by Edward-Holmes** [PlayCover/PlayCover#883]
### Is your feature request related to a problem?

Add Library management functionality so that users can freely edit and delete unwanted or out-of-date library urls.

### Describe the solution you'd like

Make a simple UI that displays the Library URL(s) currently in use on this page. Each URL can be edited and deleted.

### Anything else?

The above description should be clear. I would appreciate it if this feature could be added.

### Issue Language

- [X] Yes my issue is written in English

**Comment by ohaiibuzzle** [comment]
Uhm, yes, it is already in the app?
<img width="712" alt="image" src="https://user-images.githubusercontent.com/23693150/226864612-8f64af86-0394-4f99-858a-cf778594865c.png">

**Comment by Edward-Holmes** [comment]
> 嗯，是的，它已經在應用程序中了？ <img alt="圖像" width="712" src="https://user-images.githubusercontent.com/23693150/226864612-8f64af86-0394-4f99-858a-cf778594865c.png">

I'm sorry, but my playcover doesn't have this function, so I may need to reinstall it. Thank you for your information.

**Comment by Edward-Holmes** [comment]
> Uhm, yes, it is already in the app? <img alt="image" width="712" src="https://user-images.githubusercontent.com/23693150/226864612-8f64af86-0394-4f99-858a-cf778594865c.png">

I'm sorry, but my playcover doesn't have this function, so I may need to reinstall it. Thank you for your information.
