### ISSUE TITLE
[Bug]: Recurrence of bug #801 Changing the resolution does not display correctly.

### ISSUE THREAD

**Issue by tellus1019** [PlayCover/PlayCover#888]
### Describe the bug

Vertical games do not display properly when the resolution is set to anything other than "Default" from the graphics settings.

### Steps to reproduce

I used the following application to check.
https://apps.apple.com/us/app/destiny-child/id1416959016
You can check by installing the application on PlayCover (2.0.4) and following the steps below.

confirm activation of normal settings
Start up without modifying the graphics settings.
The application starts up in iPad resolution and can be played without any problems.

exit the application and change the graphics settings
First, exit the application that was normally launched.
Then open the application settings and go to the graphics settings.
Select anything other than "Default" from the resolution settings.

*Auto, 1080p, 4K, or custom. Any of these is acceptable.
*Enter a value that matches the monitor resolution to finalize the resolution setting.

When start the application, a window with a corrupted display opens.
When the application is launched, the window resizes but is not displayed correctly.
The game screen is stretched horizontally and much of the screen extends outside the window.

PlayCover 2.0.5
![ScreenShot 2023-03-24 14 31 23](https://user-images.githubusercontent.com/25951129/227432941-2cf8cad9-2fa1-4e8e-b685-087dd1a5d60d.png)

PlayCover 2.0.0
![ScreenShot 2023-03-24 14 33 43](https://user-images.githubusercontent.com/25951129/227433212-72666acb-5381-42d9-bde6-0b26ae2cbccb.png)

### Expected behaviour

The application display should conform to the window size.
*Displayed correctly in PlayCover (2.0.0)
　Once resolved with a nightly build, the problem still exists in both the latest Ver 2.0.5 and the latest nightly build.

### What version of PlayCover are you using?

Nightly/beta

### What version of macOS are you using?

Ventura (macOS 13)

### Issue Language

- [X] Yes my issue is written in English

**Comment by JoseMoreville** [comment]
Please use 2.0.5 or latest nightly and select the new dropdown option normal with default settings enabled or it can be a chekbox.
it works i just tested

**Comment by tellus1019** [comment]
What are you saying?
You have closed my report, but the problem has not been resolved.
You don't understand that I am not talking about not being able to play with the default resolution, do you?

This is a problem with cases where the image is not displayed correctly when the resolution is changed even if Ver. 2.0.5 is used.
This is a problem that did not occur in Ver 2.0.0 and is clearly a glitch.
Please unclose my report and put it back on the Issue list.
Re-submitting is tedious.

**Comment by tellus1019** [comment]
Does this look normal to your eyes?
It does not look quite right to me.

Nightly 3.0.0(306)
<img width="666" alt="スクリーンショット 2023-03-27 16 31 27" src="https://user-images.githubusercontent.com/25951129/227871951-1ab614b1-ffb6-48ae-b090-6dcd31269a93.png">
<img width="396" alt="スクリーンショット 2023-03-27 16 31 36" src="https://user-images.githubusercontent.com/25951129/227871991-1d14a71c-2921-483e-9f72-7a78e68c4012.png">

Ver2.0.0(174)
<img width="666" alt="スクリーンショット 2023-03-27 16 34 46" src="https://user-images.githubusercontent.com/25951129/227872270-597ba404-e462-4f73-8323-3718ae3c0fe9.png">
<img width="396" alt="スクリーンショット 2023-03-27 16 34 55" src="https://user-images.githubusercontent.com/25951129/227872378-94cb37cf-690f-4700-a54d-c836c3277058.png">

**Comment by JoseMoreville** [comment]
hello @tellus1019 there are way better ways, to speak. I'll reopen your issue, but please do not say things that way

**Comment by IsaacMarovitz** [comment]
@tellus1019 Have a little respect. Your issue reports don't need to be so curt and inflammatory. Your conduct violates our [Code of Conduct](https://github.com/PlayCover/PlayCover/blob/b92a8139d694aefa08b267018bd3295c8faeea61/CODE_OF_CONDUCT.md). I suggest you read it.

**Comment by XuYicong** [comment]
@tellus1019  If you're not good at English and don't know how to be polite, one simple way is trying to use fewer words to describe things, and avoid expressing things in the form of a question. If you continue being rude as before, I'm afraid people will not be willing to respond to you.

**Comment by tellus1019** [comment]
Sorry, guys.
I won't deny that I was a little hot. I reflect on it.

**Comment by TheMoonThatRises** [comment]
This bug will most likely not be fixed, as the app is meant to be played in portrait mode, and setting the correct graphic settings (`App Default` with `Fix display window issues`) will fix the issue. There is no need (or is there probably a way) to fix the issue with other "custom" resolutions.

**Comment by tongjiann** [comment]
> This bug will most likely not be fixed, as the app is meant to be played in portrait mode, and setting the correct graphic settings (`App Default` with `Fix display window issues`) will fix the issue. There is no need (or is there probably a way) to fix the issue with other "custom" resolutions.

it did work, but i could not change the resolution in this way. is there a better way to change this like `iPhone Mirroring`?
btw, this app full my scrren.
![image](https://github.com/user-attachments/assets/2ba45357-3b9a-4be6-917f-731186d52926)
