### ISSUE TITLE
[Bug]: New scroll feature issue 

### ISSUE THREAD

**Issue by JJAEKY** [PlayCover/PlayCover#892]
### Describe the bug

*I've attached the recorded clip in youtube for better understanding
*Since there's no option to choose 2.0.5 from the provided selection, selected 2.0.4 for PlayCover version option

https://youtu.be/fPpvL42q7Mc

-Description for clip
~00:02 full control on angle
~00:04 Scrolling with mouse
~ issue happening

Happening with Genshin Impact

I just updated my playcover to 2.0.5 and was thrilled that mouse scroll finally works to zoom, but whenever I zoom out by max, loading message pops up and the entire screen fades black. It comes back right away but once that happens I lose full control over camera and some of keymapping functions. The only way to change the camera angle is to open Paimon page(main menu), use skills and eventually re-start. 

I'm not sure if this has to do with my mouse(I use mx master 3s with infinite scroll) but can't confirm as I don't have any other mouse than this.

### Steps to reproduce

Infinite scroll when using keymapping

### Expected behaviour

Simply zoom in and out by maximum

### Crash log

```shell
N/A
```

### What version of PlayCover are you using?

2.0.4

### What version of macOS are you using?

Ventura (macOS 13)

### Issue Language

- [X] Yes my issue is written in English

**Comment by TheMoonThatRises** [comment]
Unable to reproduce. Try updating to latest version of PlayCover (stale).
