### ISSUE TITLE
Instagram can not sign in

### ISSUE THREAD

**Issue by Specialtemp** [PlayCover/PlayCover#90]
It is the last version 244..
<img width="285" alt="截屏2022-07-23 17 28 06" src="https://user-images.githubusercontent.com/77627559/180599614-e69219c5-11c9-4a1a-9c6b-b348c1e190e7.png">
.

**Comment by zanderp25** [comment]
I can confirm that this is an issue
<img width="487" alt="Instagram screenshot" src="https://user-images.githubusercontent.com/13000207/180616985-afe51118-ad32-4cb6-b6b3-4f12e56f0e09.png">

**Comment by ohaiibuzzle** [comment]
Is this with PlaySign enabled or disabled?

**Comment by zanderp25** [comment]
Disabled.

**Comment by parth1241** [comment]
same issue

**Comment by singhalrishi27** [comment]
same issue

**Comment by alexij1997** [comment]
I have same problem.

**Comment by Frankyyeah** [comment]
I also have the same issue

**Comment by ohaiibuzzle** [comment]
This is probably caused by Instagram checking the hash of the app executable, which, was modified (due to decryption) and doesn't match the original version hash that it may be using to check against

**Comment by Frankyyeah** [comment]
Is there any ways to fix this issue?

**Comment by zanderp25** [comment]
not that i know of

**Comment by alanzchen** [comment]
Does anyone know what's the latest version that works?

I was using Version 169.0 (261791898) when Mac still allows IPAs to be sideloaded directly.

**Comment by humanperzeus** [comment]
any workaround?

**Comment by singhalrishi27** [comment]
For now there is none

**Comment by mooosmad** [comment]
i have same probleme

**Comment by Soooda** [comment]
Confirm still not working in Instagram ver. 272.0

**Comment by mehr-zarathustra** [comment]
Still not working, anybody found a solution?

**Comment by turnipsforme** [comment]
i know this is closed, but would be suuuper useful if not too hard to fix!

**Comment by jpransxdev** [comment]
Hi everyone. It is now possible to run latest instagram with the help of sideloadly. everything works no problem but when u close the app it logs out... Ok edit:: it ran fine the first few tries now doesn't show messages etc.

**Comment by TheRouletteBoi** [comment]
> Hi everyone. It is now possible to run latest instagram with the help of sideloadly. everything works no problem but when u close the app it logs out... Ok edit:: it ran fine the first few tries now doesn't show messages etc.

what IPA did you end up using? also would I have to change any settins in PlayCover?
