### ISSUE TITLE
[App Support]:  Alipay

### ISSUE THREAD

**Issue by olegarhn** [PlayCover/PlayCover#901]
### App Store link

id333206289

### Current issues

- [ ] App fails to install
- [ ] App fails to open
- [ ] App crashes randomly during usage
- [ ] App experiences graphical issues or broken UI
- [ ] App fails to connect to servers
- [X] Other

### More details

When you try to sign in or sign up, you can see the following error in the app -- "you've made too many attempts please try again later"
It seems like Alipay see Device ID (as I understand its undefined or universal) and a lot of users tried to log in through PlayCover bundle and Alipay banned this ID.

I hope there is some way to spoof the features or make them unique and use the Alipay app.

Also interested in the possibility of duplicating applications, that is, using multiple copies of the same application on the same device

### Issue Language

- [X] Yes my issue is written in English

**Comment by ohaiibuzzle** [comment]
Device ID should not be the same (App Tracking Transparency on develop is set to `Not Determined`) and the Serial/IDFV are actually passed through of your actual Mac

**Comment by lslqtz** [comment]
You can log in with Taobao, but Touch ID is not available

**Comment by IsaacMarovitz** [comment]
PlayCover does not support and does not plan to support financial apps. It is not recommended that you use financial apps with PlayCover.
