### ISSUE TITLE
[App Support]: Busuu

### ISSUE THREAD

**Issue by thomasync** [PlayCover/PlayCover#908]
### App Store link

https://apps.apple.com/fr/app/busuu-apprendre-une-langue/id379968583

### Current issues

- [ ] App fails to install
- [ ] App fails to open
- [ ] App crashes randomly during usage
- [ ] App experiences graphical issues or broken UI
- [X] App fails to connect to servers
- [ ] Other

### More details

I followed the tutorial (https://docs.playcover.io/getting_started/troubleshoot_login)

But when I get to step 5 after putting the SIP back, I am logged out of the app.

### Issue Language

- [X] Yes my issue is written in English

**Comment by TheMoonThatRises** [comment]
Fixed in the nighty build by enabling PlayChains (left click app in PlayCover -> Bypasses) (Note that this feature is still in beta and that you may experience bugs with the nightly version if you decide to use that version).
