### ISSUE TITLE
[Feature]: resize app window

### ISSUE THREAD

**Issue by yangliu-1995** [PlayCover/PlayCover#918]
### Is your feature request related to a problem?

hi is there any way to resize app window? Some applications have an incomplete UI display and the window is not resizable, making it unusable

### Describe the solution you'd like

resize app window

### Anything else?

resize app window

### Issue Language

- [X] Yes my issue is written in English

**Comment by ohaiibuzzle** [comment]
Switch the resolution mode to App Default. Then they act just like macOS apps
