### ISSUE TITLE
Parameter Error [Bug]: 

### ISSUE THREAD

**Issue by CrashingBootcamp** [PlayCover/PlayCover#919]
### Describe the bug

I had Genshin working fine for over a year on playcover until recently when I reset and updated my 2021 m1 macbook pro, now I'm getting this parameter error issue when I try to log in. Any insight into how to fix? 

<img width="1042" alt="Screenshot 2023-04-20 at 1 05 25 PM 1" src="https://user-images.githubusercontent.com/95519446/233477713-d7257969-7dd1-4d4f-92bf-cb76e26e4973.png">

### Steps to reproduce

Tried to login to genshin. 

### Expected behaviour

I expected to get reCaptcha or to log in. 

### What version of PlayCover are you using?

Nightly/beta

### What version of macOS are you using?

Ventura (macOS 13)

### Issue Language

- [X] Yes my issue is written in English

**Comment by ohaiibuzzle** [comment]
Please read the documentation. We've already clearly document how to work around this issue
