### ISSUE TITLE
Feature Request: Transfer iOS apps/games from iPhone/iPad

### ISSUE THREAD

**Issue by CollinsVakayil** [PlayCover/PlayCover#92]
Would it be possible to add a feature where when the iPhone/iPad is tethered to the Mac, apps/games could be transferred or dragged to the Mac and used on PlayCover?

**Comment by ohaiibuzzle** [comment]
This would only be possible with a jailbroken iOS device. Essentially what you need to use for PlayCover isn't just any IPA but an IPA with Apple's asymmetric encryption removed (see [here](https://apple.stackexchange.com/questions/42992/how-does-ios-app-drm-work-exactly)). 

So basically, complicaions.

**Comment by CollinsVakayil** [comment]
> This would only be possible with a jailbroken iOS device. Essentially what you need to use for PlayCover isn't just any IPA but an IPA with Apple's asymmetric encryption removed (see [here](https://apple.stackexchange.com/a/48236)).
> 
> So basically, complicaions.

Understood, thank you for the clarification.
