### ISSUE TITLE
[Feature]: Hotkey to disable Mouse Mapping

### ISSUE THREAD

**Issue by DeathImmortal** [PlayCover/PlayCover#920]
### Is your feature request related to a problem?

With this key, playing Mobile Legends would be so much easier. Right now, I need to keep switching between Mouse Mapping on and off in settings, I have to relaunch the game each time.

### Describe the solution you'd like

Press a key to disable the Mouse Mapping

### Anything else?

Nope

### Issue Language

- [X] Yes my issue is written in English

**Comment by amirsaam** [comment]
Press `Option` Key on your Keyboard. I've already sent this doc link to you in Discord.
https://docs.playcover.io/keymapping/using_making_keymaps
