### ISSUE TITLE
[Game Support]: Honkai Star Rail

### ISSUE THREAD

**Issue by taumasyang** [PlayCover/PlayCover#921]
### App Store link

https://apps.apple.com/cn/app/%E5%B4%A9%E5%9D%8F-%E6%98%9F%E7%A9%B9%E9%93%81%E9%81%93/id1523037824

### Current issues

- [ ] Game fails to install
- [ ] Game fails to open
- [ ] Game crashes randomly during gameplay
- [ ] Game does not work with keymapping
- [ ] Game experiences graphical issues or broken UI
- [ ] Game fails to connect to servers or complete download

### More details

- Game freezes (cannot enter) after downloading complete data.
- No sound.

### Issue Language

- [X] Yes my issue is written in English

**Comment by XuYicong** [comment]
Change the app name to something pure English letters, like `hks.app`, instead of `崩坏：星穹铁道.app`. This issue is also known for Honkai 3. You may have to do this for each version update until this got fixed.

**Comment by taumasyang** [comment]
It works, thanks a lot!
By the way, for someone who may be interested, the package name is `com.miHoYo.hkrpg`, so `hkrpg.app` might be a good workaround name.

**Comment by caiisen** [comment]
Which file name should I change? An .app file I saw in /Users/MYNAME/Library/Containers/io.playcover.PlayCover is already in English, but there is still a problem opening it

**Comment by taumasyang** [comment]
In my case, it's `~/Library/Containers/io.playcover.PlayCover/崩坏:星穹铁道.app` that should be renamed.
I guess it's the colon that causes the problem, as I tried to rename the app to `Honkai: Star Rail.app`, Finder warned me that filename is not accepted, while `Honkai Star Rail.app` is acceptable. Maybe a full colon would work? Try `崩坏：星穹铁道.app`. I don't know if it works, as I'm satisfied with the full English name.

**Comment by taumasyang** [comment]
I'm sorry, wrong guess. `崩坏：星穹铁道.app` doesn't work. Use `Honkai Star Rail.app` instead. Full path is `~/Library/Containers/io.playcover.PlayCover/Honkai\ Star\ Rail.app`.

**Comment by caiisen** [comment]
It works, but something different.
My mac display languange is English, I have chang app display language to simple chinese in Honkai Star Rail when I first time open. In Finder, it will show Honkai: Star Rail.app, but in terminal it show 崩坏:星穹铁道.app. So I `mv 崩坏:星穹铁道.app hkrpg.app`, it works. Thanks

**Comment by taumasyang** [comment]
Why close this issue? That's a workaround, not a solution.

**Comment by TheMoonThatRises** [comment]
A similar problem is being tracked in #668.

**Comment by Psilym** [comment]
I change the name of app in "Containers/". However, the name in playcover is still "崩坏3:星穹铁道", which is not changed. And the setting of this app in playcover is still origin and cannot be changed. Is there a way to settle this problem perfectly?
