### ISSUE TITLE
[Game Support]: ブルーアーカイブnot work on maa.2 version.

### ISSUE THREAD

**Issue by RyanWangxr** [PlayCover/PlayCover#923]
### App Store link

https://apps.apple.com/jp/app/%E3%83%96%E3%83%AB%E3%83%BC%E3%82%A2%E3%83%BC%E3%82%AB%E3%82%A4%E3%83%96/id1515877221?l=en&uo=4

### Current issues

- [ ] Game fails to install
- [X] Game fails to open
- [ ] Game crashes randomly during gameplay
- [ ] Game does not work with keymapping
- [ ] Game experiences graphical issues or broken UI
- [ ] Game fails to connect to servers or complete download

### More details

when start game it will say that there is illegal app running and shut the game automaticlly
![5eb3bbe5f52cf981e392a8778d978f16](https://user-images.githubusercontent.com/122590418/233918598-abbfd710-ad3a-4486-b868-49721e5a228f.png)

### Issue Language

- [X] Yes my issue is written in English

**Comment by ohaiibuzzle** [comment]
The maa.2 version is not built by us, rather, by the CN Arknights community for their game, so we can't provide support for it.

**Comment by RyanWangxr** [comment]
Thanks!
