### ISSUE TITLE
[Bug]: I had installed command line tools 14.3, but the interface is still blank

### ISSUE THREAD

**Issue by C01day** [PlayCover/PlayCover#924]
### Describe the bug

I had installed the command line tools 14.3
<img width="279" alt="截屏2023-04-25 02 07 39" src="https://user-images.githubusercontent.com/45281615/234082716-b328a3f1-da81-4478-ad96-4a6fd5974380.png">

### Steps to reproduce

When I first install PlayCover, it hints me to install command line tools, but reporting an error. 
So, I type `xcode-select --install` in terminal, it says that i have installed.
<img width="570" alt="截屏2023-04-25 02 22 40" src="https://user-images.githubusercontent.com/45281615/234083158-ba6a9a01-cb9b-4061-acb5-33f1e7c6e01d.png">

I also install CLT from official website, then I open PlayCover, the interface is still blank
<img width="903" alt="截屏2023-04-25 02 24 25" src="https://user-images.githubusercontent.com/45281615/234083917-f8c86d73-1642-4127-afe2-ad7d1d0d52c5.png">

### Expected behaviour

.

### What version of PlayCover are you using?

Nightly/beta

### What version of macOS are you using?

Ventura (macOS 13)

### Issue Language

- [X] Yes my issue is written in English

**Comment by IsaacMarovitz** [comment]
This is not a bug. You just don't have anything installed.
