### ISSUE TITLE
[Game Support]: Honkai: Star Rail (崩坏：星穹铁道)

### ISSUE THREAD

**Issue by AnotiaWang** [PlayCover/PlayCover#926]
### App Store link

https://apps.apple.com/cn/app/id1523037824

Decrypt IPA Store link: https://decrypt.day/app/id1523037824

### Current issues

- [ ] Game fails to install
- [ ] Game fails to open
- [ ] Game crashes randomly during gameplay
- [ ] Game does not work with keymapping
- [ ] Game experiences graphical issues or broken UI
- [ ] Game fails to connect to servers or complete download

### More details

Game experiences sound issues: 
- There's no audio when the game launches and when in game
- Sound feedback of some UI components can be played normally (for example, open the upper right "News" menu in the login screen and click the articles there, you should hear the sound effect)

### Issue Language

- [X] Yes my issue is written in English

**Comment by ohaiibuzzle** [comment]
Closed as duplicates of #921
