### ISSUE TITLE
[Game Support]: Unable to use Xbox controller for Honkai Star Rail

### ISSUE THREAD

**Issue by dzy1997** [PlayCover/PlayCover#927]
### App Store link

https://apps.apple.com/us/app/honkai-star-rail/id1599719154

### Current issues

- [ ] Game fails to install
- [ ] Game fails to open
- [ ] Game crashes randomly during gameplay
- [ ] Game does not work with keymapping
- [ ] Game experiences graphical issues or broken UI
- [ ] Game fails to connect to servers or complete download

### More details

I connect my Xbox controller to my M2 Mac and launched the game in PlayCover, but was unable to use the controller. Since on mobile the game has controller support, I guess this is an issue with PlayCover compatibility. 

### Issue Language

- [X] Yes my issue is written in English

**Comment by ohaiibuzzle** [comment]
Can you show me where controller support even is on iOS? Because if it exist, I am not seeing it in-game.

**Comment by dzy1997** [comment]
It does not have a UI item in-game (like in Genshin), but on iOS devices it automatically detects the controller and switch UI prompts

**Comment by ohaiibuzzle** [comment]
> It does not have a UI item in-game (like in Genshin), but on iOS devices it automatically detects the controller and switch UI prompts

Can you screenshot how that looks like in game?
The game running under PlayCover have full access to Apple's GameController API calls. If it can support a controller, it will just work like on iOS

**Comment by dzy1997** [comment]
Ah my bad... I previously watched a gameplay video using controllers, I just went back to it and fount it to be the PC version. The iOS version doesn't seem to support controllers at this time. Sorry for the confusion!
