### ISSUE TITLE
[Bug]: Cannot bind num pad keys in nightly

### ISSUE THREAD

**Issue by moelmoo** [PlayCover/PlayCover#928]
### Describe the bug

Num pad keys not recognized in nightly, work fine in 2.0.5

### Steps to reproduce

Try using num keybinds in any app

### Expected behaviour

In 2.0.5 the keys are recognized and map correctly

### What version of PlayCover are you using?

Nightly/beta

### What version of macOS are you using?

Ventura (macOS 13)

### Issue Language

- [X] Yes my issue is written in English

**Comment by Depal1** [comment]
Solved in PlayCover 3.0.0.
