### ISSUE TITLE
[Bug]: Honkai Impact 3 crashed korea version

### ISSUE THREAD

**Issue by ghdic** [PlayCover/PlayCover#929]
### Describe the bug

you can download here [korea version](https://decrypt.day/app/id1286705196) Honkai Impact3 after login

<img width="484" alt="image" src="https://user-images.githubusercontent.com/28496724/234834589-e2c849e7-ef22-4793-885f-edba6264a2b3.png">

The app crashes while playing Honkai Impact3 with Play Cover. It seems to be an issue that occurs when Korean is entered in the title, as it seems to work well when proceeding with the English version. Please check if there is a crash when the app name is in a language other than English, and if it is difficult to fix the bug, please support me to change the name to English.

### Steps to reproduce

1. download ipa & install app
2. download additional resource until show login page
3. then app crashed!!(always)

### Expected behaviour

app crashed after download additional resource

### Crash log
Log is so Long.. so i can't pasted it
```shell
-------------------------------------
Translated Report (Full Report Below)
-------------------------------------

Process:               bh3korea [3425]
Path:                  /Users/USER/Library/Containers/io.playcover.PlayCover/붕괴3rd.app/bh3korea
Identifier:            com.miHoYo.bh3korea
Version:               6.5.0 (550)
Code Type:             ARM-64 (Native)
Parent Process:        launchd [1]
User ID:               501

Date/Time:             2023-04-27 19:27:24.4888 +0900
OS Version:            macOS 13.3.1 (22E261)
Report Version:        12
Anonymous UUID:        44B9367B-A3AA-A4A3-1E23-3154AC4F6B38


Time Awake Since Boot: 2000 seconds

System Integrity Protection: disabled

Crashed Thread:        72  KSCrash Exception Handler (Primary)

Exception Type:        EXC_GUARD (SIGKILL)
Exception Codes:       GUARD_TYPE_MACH_PORT
Exception Codes:       0x000000000003f907, 0x0100000000000000

Termination Reason:    Namespace GUARD, Code 2305843017803888903 

Thread 0::  Dispatch queue: com.apple.main-thread
```

### What version of PlayCover are you using?

Nightly/beta

### What version of macOS are you using?

Monterey (macOS 12)

### Issue Language

- [X] Yes my issue is written in English

**Comment by amirsaam** [comment]
update to latest nightly build and make sure to not use 4k resolution
https://github.com/PlayCover/PlayCover/actions/runs/4840446405

**Comment by ririnto** [comment]
I cannot play this game with nightly 341 version.
After resource download, verify, App Crashed.

**Comment by amirsaam** [comment]
Are you using 4k resolution?

**Comment by ghdic** [comment]
@amirsaam still crashed app 🥹
i'm using 1080p from latest nightly build app

<img width="537" alt="image" src="https://user-images.githubusercontent.com/28496724/235603392-903958bf-8426-4f59-9bc8-246a9d4daf8e.png">

**Comment by ghdic** [comment]
[Kapture 2023-05-02 at 16.17.21.webm](https://user-images.githubusercontent.com/28496724/235604454-b5bfdfdd-c434-4afd-8281-2ee498ac14d1.webm)

**Comment by ohaiibuzzle** [comment]
I hate how silly this is going to be, but simply right click the app, choose Show in Finder
Then rename it to something like hk3kr.app
And then restart PlayCover

**Comment by ghdic** [comment]
> 

If I change the name of the app, playcover cannot find the app path, and even if directly run the renamed app, it crashes.

**Comment by ohaiibuzzle** [comment]
You need to **restart** PlayCover after renaming. Otherwise it will keep the old cache and do nothing

**Comment by ghdic** [comment]
oh! Thanks for enlightening me on my ignorance. As you said, I changed the name to English and it works fine.

I confirmed that it works well released version, too. 😁
