### ISSUE TITLE
[Bug]: Window is to small to  show the full game content

### ISSUE THREAD

**Issue by Orange-W** [PlayCover/PlayCover#931]
### Describe the bug

![image](https://user-images.githubusercontent.com/9405186/235350875-d6013538-c7f6-4896-b553-4f2eba74fac6.png)
it only can show a small part of the full game.

### Steps to reproduce

use the newest M2 Macbook to  play all the normal ios games like “世界弹射物语”

### Expected behaviour

the window can contain all the content of the game

### What version of PlayCover are you using?

Nightly/beta

### What version of macOS are you using?

Ventura (macOS 13)

### Issue Language

- [X] Yes my issue is written in English

**Comment by amirsaam** [comment]
What build number of nightly you using? Update to latest build https://github.com/PlayCover/PlayCover/actions/runs/4840446405

**Comment by Orange-W** [comment]
It is the same. My Mac is M2. The version is  3.0.0 (340). The blank is due to the windows being too small to show Privacy Agreement.
![image](https://github.com/PlayCover/PlayCover/assets/9405186/3e13bb54-186f-4256-8af2-cc0d656ddbce)

**Comment by TheMoonThatRises** [comment]
Using the nightly build, you can go to the app's graphical settings in PlayCover, set the resolution to `App Default` and tick the box that says `Fix window display issues`. This will put the app into portrait mode and fixes the window being cut off.
