### ISSUE TITLE
[Game Support]: HOKAI: STAR RAIL

### ISSUE THREAD

**Issue by fuyusui** [PlayCover/PlayCover#934]
### App Store link

https://apps.apple.com/cn/app/id1523037824

### Current issues

- [ ] Game fails to install
- [ ] Game fails to open
- [ ] Game crashes randomly during gameplay
- [ ] Game does not work with keymapping
- [ ] Game experiences graphical issues or broken UI
- [ ] Game fails to connect to servers or complete download

### More details

Unable to login, and shows "parameter error" Same error on Genshin, but there is no play chain option in the app setting.

![WeChatb2aaecd309f2c1da921b202102cd2516](https://user-images.githubusercontent.com/132262754/235438399-d4a1fc5a-20c6-443b-a39b-673217ebe141.jpg)

### Issue Language

- [X] Yes my issue is written in English

**Comment by MEMORIEmusic** [comment]
You need to use a nightly build for PlayChain option to show up. https://nightly.link/PlayCover/PlayCover/workflows/2.nightly_release/develop/PlayCover_nightly_341.dmg

**Comment by ohaiibuzzle** [comment]
Please read whatever you are using as reference again. PlayChain is not in 2.0.5
