### ISSUE TITLE
[Feature]: select microphone devices

### ISSUE THREAD

**Issue by clin366** [PlayCover/PlayCover#936]
### Is your feature request related to a problem?

Problem: Usually, the user's laptop has multiple input devices, such as a built-in microphone, external microphone, and virtual devices from loopback, etc. Current PlayCover does not allow the selection of input devices but uses the system-default microphone.

### Describe the solution you'd like

Solution: Add the feature to let the user select input devices in the settings or before launching the app from PlayCover.

### Anything else?

N/A

### Issue Language

- [X] Yes my issue is written in English

**Comment by amirsaam** [comment]
That feature is not related to PlayCover at all.
You need to use apps like SoundSource and etc for it.
Closing this.

Remember that PlayCover is just a Launcher and runs apps/games as they are.
