### ISSUE TITLE
[Feature]: can i use keyboard map and mouse click together

### ISSUE THREAD

**Issue by cmdedj** [PlayCover/PlayCover#937]
### Is your feature request related to a problem?

keymapper and mouse

### Describe the solution you'd like

like when you play a  moba game, left hand user keyboard, right hand use mouse. now i have to user option change mode, Or you can only use the keyboard and mouse mapping, or you can only use the mouse to click. Can I use keyboard mapping and mouse click at the same time?

### Anything else?

no

### Issue Language

- [X] Yes my issue is written in English

**Comment by TheMoonThatRises** [comment]
You can turn off mouse mapping by going into the app's PlayCover settings and unticking the "Mouse mapping" option. Is that what you are looking for?

**Comment by shzycat** [comment]
> You can turn off mouse mapping by going into the app's PlayCover settings and unticking the "Mouse mapping" option. Is that what you are looking for?

this could cause some problems, such as you can not input any character into to one label. But this is not the biggest reason i gave up this setting, the biggest issue is while playing some games, such as the recent HonKai Star Rail, if some view (personally I think) which is not renderd directly by the game engine (Unity) itself, but as a web page, you just can't use you mouse (controlled by playtools) to click that web view anymore in anyway, instead, your mouse clicking is all captured by the game view or game menus/ui which is under the web page. 
One thing maybe useful for your team I have discovered is that: while mouse with playtools can't click that web page, i switched to the macOS's native control tools for ios apps, called `Touch Alternatives`, and then i use two fingers touch the trackpad with a very little move just for simulate a likely click at the screen, i succeed and be able to scroll or click that web page, and easily close that web page then bring myself back to the game view. is that an known issue? I have seen your team working on some big change with playtools the other repo, so i wish all I know can bring you some thoughts.

**Comment by XuYicong** [comment]
FIxed by https://github.com/PlayCover/PlayTools/pull/88. You can try it in today's nightly version. @TheMoonThatRises can you close this issue?

**Comment by cmdedj** [comment]
> You can turn off mouse mapping by going into the app's PlayCover settings and unticking the "Mouse mapping" option. Is that what you are looking for?

yes thank you very much
