### ISSUE TITLE
[Game Support]: 

### ISSUE THREAD

**Issue by MidKnightXI** [PlayCover/PlayCover#938]
### App Store link

https://apps.apple.com/us/app/honkai-star-rail/id1599719154?platform=ipad

### Current issues

- [ ] Game fails to install
- [ ] Game fails to open
- [ ] Game crashes randomly during gameplay
- [ ] Game does not work with keymapping
- [ ] Game experiences graphical issues or broken UI
- [X] Game fails to connect to servers or complete download

### More details

When I try to connect, I do the captcha then the game display `Configuration Error` when the captcha is done and I've to try to login again.

### Issue Language

- [X] Yes my issue is written in English

**Comment by ohaiibuzzle** [comment]
The login issues have already been documented, please read the PlayCover documentations for more info.

**Comment by MidKnightXI** [comment]
Mb sorry for the inconvenience
