### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by david52pp** [PlayCover/PlayCover#939]
### Describe the bug

I really need help to help me fix this: I have downloaded Genshin Impact on Playcover, and my account is login by my email, but after I put the password and username inside the box and after it analyse me if I am a robot, it shows parameter error on the screen and I tried many times but it still gave me the same result, I can only login with the twitter but I don't have an account on twitter ,so how to fix it
<img width="1280" alt="截屏2023-05-03 19 55 05" src="https://user-images.githubusercontent.com/128602612/235922077-dd8b4b88-a645-4c10-9711-7c7f18fa9a55.png">
<img width="1280" alt="截屏2023-05-03 19 56 08" src="https://user-images.githubusercontent.com/128602612/235922337-ac91b073-98a3-4a03-9a2a-1e7bd3e56580.png">

### Steps to reproduce

1.click the genshin's icon to enter the game
2.it make me to login to my own account
3.I type the correct username and password
4.I done the robotic analysing
5.it shows parameter error and doesn't make me login

### Expected behaviour

I hope that I can successfully login to my account, and doesn't shows parameter error

### What version of PlayCover are you using?

2.0.4

### What version of macOS are you using?

Monterey (macOS 12)

### Issue Language

- [X] Yes my issue is written in English

**Comment by ohaiibuzzle** [comment]
Please read the documentations, which extensively explains this process.

**Comment by david52pp** [comment]
where can i see the documentations?
\

**Comment by david52pp** [comment]
sorry where can i read the documentation?

**Comment by MEMORIEmusic** [comment]
> sorry where can i read the documentation?

https://docs.playcover.io
