### ISSUE TITLE
Profile Error, there was an issue selecting this profile (Netflix)

### ISSUE THREAD

**Issue by Natalect** [PlayCover/PlayCover#94]

**Comment by ohaiibuzzle** [comment]
Is PlaySign on or off?

**Comment by birdmichael** [comment]
Playb:10008;CHD:1005;

**Comment by miloatsale** [comment]
same, how to solve?

**Comment by ZhichGaming** [comment]
Netflix apparently only works with the first profile created.

**Comment by ileeric** [comment]
@ZhichGaming In my case the first profile displayed among 3 profiles can not log in too

**Comment by albcc** [comment]
Same.

**Comment by CRooi** [comment]
same

**Comment by Depal1** [comment]
Closed in favor of https://github.com/PlayCover/PlayCover/issues/251.
