### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by fanvcz934n** [PlayCover/PlayCover#941]
### Describe the bug

can not click the "同意" button

### Steps to reproduce

1.
<img width="1478" alt="image" src="https://user-images.githubusercontent.com/97324295/236470997-95a04d35-23bf-4626-b168-c52ee4b99245.png">
2.
<img width="1478" alt="image" src="https://user-images.githubusercontent.com/97324295/236471173-182c4f68-db37-4961-b932-ce6da95dc095.png">

### Expected behaviour

pls 

### What version of PlayCover are you using?

Nightly/beta

### What version of macOS are you using?

Monterey (macOS 12)

### Issue Language

- [X] Yes my issue is written in English

**Comment by fanvcz934n** [comment]
game link:https://decrypt.day/app/id1305599559

**Comment by ohaiibuzzle** [comment]
I am sorry, but this issue doesn't follow any of our templates or provide useful troubleshooting information.
