### ISSUE TITLE
[Bug]: can't open the game

### ISSUE THREAD

**Issue by david52pp** [PlayCover/PlayCover#945]
### Describe the bug

I can open Honkai:star rail, sky, and Genshin Impact but when I click on"第五人格“ and ”蛋仔派对“(identity V and Eggy Party) and It will not open it which flashed quickly and I tried it again and again I still cannot open it, how to fix it?

### Steps to reproduce

1.download the ipa of "第五人格“（identity V)
2.install it on playcover
3.click the icon of the game
4.flashed
5.didn't open the game

### Expected behaviour

I want to open "第五人格“（Identity V) in playcover

### What version of PlayCover are you using?

2.0.4

### What version of macOS are you using?

Monterey (macOS 12)

### Issue Language

- [X] Yes my issue is written in English

**Comment by aiden-leong** [comment]
Same issue with 蛋仔派对 downloaded from https://decrypt.day/app/id1544884479 version 1.0.59

**Comment by TheMoonThatRises** [comment]
Try renaming the app to a name without special characters (like all english characters). You can find the app by left clicking it in PlayCover and selecting `Show in Finder`.

**Comment by xpellidamilk** [comment]
same issue here i also cant open identity v

**Comment by josepheiba** [comment]
same, this has been going for a while now, can't open Master Duel so I went back to steam version

**Comment by josepheiba** [comment]
> same issue here i also cant open identity v

try this, I have no idea what this even means:

disable keyboead mapping
disable playchain
change applicationCategoryType to public.app-category.games

source:
https://github.com/PlayCover/PlayCover/issues/1283

**Comment by sanamadapaka** [comment]
> > same issue here i also cant open identity v
> 
> try this, I have no idea what this even means:
> 
> disable keyboead mapping disable playchain change applicationCategoryType to public.app-category.games
> 
> source: #1283

Me too I can't open IDV. I seem to have the latest version of IDV and playcover but whenever I press it nothing happens. It doesn't even open. @josepheiba s solution didn't work for me idk why. But if theres other solution please tell me! thank you!
