### ISSUE TITLE
(TikTok) Question: This thing, last time I ran it, did this with no question asked (along with a bunch of other stuff)

### ISSUE THREAD

**Issue by KirinVittel** [PlayCover/PlayCover#950]
Why does it do this? Is it Tiktok being malicious or the people cracking it or just happens to be a side effect of how the app is built? 

This thing, last time I ran it, did this with no question asked (along with a bunch of other stuff)
![image](https://user-images.githubusercontent.com/23693150/209562294-6b50e04d-da6e-49a9-bb3b-977b9f7e1f93.png)
(That's the least of its problems, btw. Just use the web version if you don't want your Home folder to potentially be absolutely nuked)

_Originally posted by @ohaiibuzzle in https://github.com/PlayCover/PlayCover/discussions/628#discussioncomment-4498200_

**Comment by ohaiibuzzle** [comment]
Fun fact: on normal iOS devices, this file is protected and apps can't access it. (Obviously you don't just get to read the user's call history)
So this is more than likely TikTok's own behavior upon detecting a jailbroken device (which PlayCover technically is) to read these files for its own usage

**Comment by KirinVittel** [comment]
Interesting thanks, do you have any idea if it affects the iPhone jailbreaker? Don't see it talked about

**Comment by ohaiibuzzle** [comment]
I mean jailbreaking does also smash the app sandbox so... Technically?
Although again they could, like the clipboard access fiasco, say that it's debugging or SDK-related stuff. Hard to tell
The only way we can know for sure is to debug the app on iOS to see what it does there

**Comment by jakeyounglol** [comment]
>  So this is more than likely TikTok's own behavior upon detecting a jailbroken device (which PlayCover technically is) to read these files for its own usage

or it could just be tiktok's mechanism of detecting jailbreaks because on jailbroken devices without any bypassing it just refuses to run. trying to access folders like that is a way that apps use to detect jailbreaks
