### ISSUE TITLE
[Game Support]: Honkai Star rail

### ISSUE THREAD

**Issue by sammyhui911** [PlayCover/PlayCover#951]
### App Store link

https://decrypt.day/app/id1599719154

### Current issues

- [ ] Game fails to install
- [ ] Game fails to open
- [ ] Game crashes randomly during gameplay
- [ ] Game does not work with keymapping
- [ ] Game experiences graphical issues or broken UI
- [X] Game fails to connect to servers or complete download

### More details

Parameter error

### Issue Language

- [X] Yes my issue is written in English

**Comment by ohaiibuzzle** [comment]
Please read the docs. We clearly documented this behavior with login. Thanks
