### ISSUE TITLE
[Game Support]: can’t play

### ISSUE THREAD

**Issue by arS1N1c** [PlayCover/PlayCover#954]
### App Store link

https://apps.apple.com/gb/app/life-makeover/id1619100281

### Current issues

- [ ] Game fails to install
- [X] Game fails to open
- [ ] Game crashes randomly during gameplay
- [ ] Game does not work with keymapping
- [ ] Game experiences graphical issues or broken UI
- [ ] Game fails to connect to servers or complete download

### More details

I cannot play on server as it pops up with a message saying I need better configuration does that mean I need a better phone cos I’ve updated my phone but still isn’t working I’ve currently got the iPhone 6s please help.

### Issue Language

- [X] Yes my issue is written in English

**Comment by TheMoonThatRises** [comment]
Phone? PlayCover is for Macs.
