### ISSUE TITLE
[App Support]: can't login

### ISSUE THREAD

**Issue by tharitrot** [PlayCover/PlayCover#955]
### App Store link

ragnarok origin global

### Current issues

- [ ] App fails to install
- [ ] App fails to open
- [ ] App crashes randomly during usage
- [ ] App experiences graphical issues or broken UI
- [X] App fails to connect to servers
- [ ] Other

### More details

i can't login ragnarok origin global "login fail"

### Issue Language

- [X] Yes my issue is written in English

**Comment by TheMoonThatRises** [comment]
Have you tried using the nightly version?

**Comment by tharitrot** [comment]
i try using the nightly version and open config follow 552 case , it work.
Thank you for your help
