### ISSUE TITLE
[Game Support]: 

### ISSUE THREAD

**Issue by HHui123** [PlayCover/PlayCover#957]
### App Store link

Genshin in PlayCover

### Current issues

- [ ] Game fails to install
- [X] Game fails to open
- [ ] Game crashes randomly during gameplay
- [ ] Game does not work with keymapping
- [ ] Game experiences graphical issues or broken UI
- [ ] Game fails to connect to servers or complete download

### More details

Open Genshin Impact and exit unexpectedly
Pop up problem report

### Issue Language

- [X] Yes my issue is written in English

**Comment by MEMORIEmusic** [comment]
Are you running the game at 4K?(To check, right click genshin -> settings -> graphics). If you are, please try setting the resolution to Auto(Based on display) or 1080p.

**Comment by HHui123** [comment]
Thank you for your reply. I have been using automatic mode all along.
