### ISSUE TITLE
[Bug]: ARK MOBILE CANT LOGIN GAME CENTER

### ISSUE THREAD

**Issue by Ducmanhvn** [PlayCover/PlayCover#960]
### Describe the bug

Open game it ask for using icloud account i choose it,but when i  touch multi play stil said need login game center 

### Steps to reproduce

Open game it ask for using icloud account i choose it,but when i  touch multi play stil said need login game center 

### Expected behaviour

.

### Crash log

```shell
no crash
```

### What version of PlayCover are you using?

Nightly/beta

### What version of macOS are you using?

Monterey (macOS 12)

### Issue Language

- [X] Yes my issue is written in English

**Comment by MEMORIEmusic** [comment]
Game Centre login does not work. This issue is probably **not** fixable.
