### ISSUE TITLE
[Game Support]: blue archive

### ISSUE THREAD

**Issue by COBBNELSON** [PlayCover/PlayCover#966]
### App Store link

https://apps.apple.com/us/app/blue-archive/id1571873795

### Current issues

- [ ] Game fails to install
- [x] Game fails to open
- [ ] Game crashes randomly during gameplay
- [ ] Game does not work with keymapping
- [ ] Game experiences graphical issues or broken UI
- [ ] Game fails to connect to servers or complete download

### More details

Can't access the game, even if it's turned on to bypass the jailbreak detection, the game is detected as illegal

### Issue Language

- [X] Yes my issue is written in English

**Comment by MEMORIEmusic** [comment]
Fixed on latest nightly. However you still won’t be able to login.
