### ISSUE TITLE
[App Support]: Seal M

### ISSUE THREAD

**Issue by rennols** [PlayCover/PlayCover#969]
### App Store link

https://apps.apple.com/id/app/seal-m/id6444637840?l=id

### Current issues

- [ ] App fails to install
- [ ] App fails to open
- [ ] App crashes randomly during usage
- [ ] App experiences graphical issues or broken UI
- [ ] App fails to connect to servers
- [X] Other

### More details

Apps run perfectly but there is problem in login.
After following this guide https://docs.playcover.io/getting_started/troubleshoot_login.html#troubleshoot-app-login-issues, I can login normally, but it doesn't work again after Re-enable SIP
Somehow there is prompt to login again even though we already logged in before

### Issue Language

- [X] Yes my issue is written in English

**Comment by ohaiibuzzle** [comment]
Could you perhaps get the latest automated nightly build and test if it works there?
If it does, it will work when we release 3.0

**Comment by rennols** [comment]
Tested and it worked on latest nightly build
@ohaiibuzzle thank you for your reply
