### ISSUE TITLE
Apps glitch and turn sideways when switching between portrait and landscape

### ISSUE THREAD

**Issue by num1swedishfishfan** [PlayCover/PlayCover#97]
Whenever you switch from portrait and landscape, the app will turn sideways and become basically unuseable. This is especially bad for apps like Rec Room that immediatly break when opening because of it.
![image](https://user-images.githubusercontent.com/98643731/180667304-1615d246-7027-4f8c-a37c-8f7e2a8ebb9b.png)

**Comment by ohaiibuzzle** [comment]
You can try turning Adaptive Display off in the app's settings and see if that helps with this issue.

**Comment by num1swedishfishfan** [comment]
> You can try turning Adaptive Display off in the app's settings and see if that helps with this issue.

i tried that an it doesnt work

**Comment by IsaacMarovitz** [comment]
Does this issue persist in PlayCover 1.1.1?

**Comment by dedf1sj** [comment]
> Does this issue persist in PlayCover 1.1.1?

yes

**Comment by XuYicong** [comment]
https://user-images.githubusercontent.com/16048758/187448311-c301da22-c5df-46d2-b87d-7177967e962b.mov

confirmed in Genshin

**Comment by zanderp25** [comment]
This should be fixed in the upcoming 2.0 update.

**Comment by kunalduttagit** [comment]
Removing playcover tools helped me to fix this issue, especially with apps for video streaming.
Right click on app (in app library) -> Go to settings -> Under Misc -> Remove PlayTools.
