### ISSUE TITLE
[Feature]: Network Management Module

### ISSUE THREAD

**Issue by Ran-Xing** [PlayCover/PlayCover#973]
### Is your feature request related to a problem?

I am from China, we need to use a proxy to download many apps, such as [decrypt.day](https://decrypt.day/), software update
It will be much more convenient if you can set the use of proxy permissions for the software

Apps also need this option, such as YouTube, Facebook

### Network Management:

- [ ] Software update
- [ ] software download

### Network Management:

- [ ] use proxy

### Describe the solution you'd like

I believe PlayCover should have related config files
Just use the proxy when requesting and downloading the app
But I think it is really a headache to use a proxy when using software

### Anything else?

no

### Issue Language

- [X] Yes my issue is written in English

**Comment by ohaiibuzzle** [comment]
PlayCover and its apps respect the system's proxy settings, so you can globally set it there. 
Implementing separate a proxy setting for PlayCover itself is easy, but for the apps running from PC... I don't think so. PlayCover is a lot more hands off about its apps than you think it is

**Comment by Ran-Xing** [comment]
yes, but it would be nice to be able to add a proxy for the playcover settings separately

**Comment by Ran-Xing** [comment]
Also, I like to configure the proxy individually for each software

**Comment by ohaiibuzzle** [comment]
That would mean major modifications to PlayTools which I'm not sure is possible. PlayCover apps don't use a VM approach like most Android emulators, so we don't get to just set one settings and have everything works

**Comment by Ran-Xing** [comment]
@ohaiibuzzle Can we only design a proxy option for software?
It is only optional when updating, and when downloading software

**Comment by Ran-Xing** [comment]
Add another note, this proxy option is only for software updates and software downloads

**Comment by ohaiibuzzle** [comment]
Well for that you can technically just have a simple service that proxy your requests. We may add it later but definitely not quite the priority (which is to get apps running) right now

**Comment by Ran-Xing** [comment]
ok，tks
