### ISSUE TITLE
[App Support]: Propellerhead Rebirth not rotating

### ISSUE THREAD

**Issue by dkjo3** [PlayCover/PlayCover#979]
### App Store link

discontinued app

### Current issues

- [ ] App fails to install
- [ ] App fails to open
- [ ] App crashes randomly during usage
- [X] App experiences graphical issues or broken UI
- [ ] App fails to connect to servers
- [ ] Other

### More details

hello all

super new here, my first post on github in-fact

i am trying to run a legacy music synthesiser 

Propellerhead Rebirth RB 338
macos: 12.6.1 
Playcover: Version 2.0.5 (291)

i was delighted to find out i could run this 90's synth on my M1Pro. it has been taken down form the app store around 2017. I managed to get myself the IPA and it installed perfectly.

For reasons unknown to me i am unable to rotate the screen. CMD+R does nothing. the option under keymappings is greyed out and not selectable. i have attached a photo.

Kindly advise,
Best Regards.

<img width="1800" alt="Screenshot 2023-06-01 at 4 40 52 PM" src="https://github.com/PlayCover/PlayCover/assets/135237957/c5607af2-feae-4fc2-a555-46c5acad88de">

### Issue Language

- [X] Yes my issue is written in English

**Comment by ohaiibuzzle** [comment]
Try removing PlayTools from the app. It may resolve your issue. The option is available when right clicking the app from PlayCover > Settings > Misc > Remove PlayTools

**Comment by dkjo3** [comment]
@ohaiibuzzle thank you so much for that prompt reply. that worked perfectly. bless you.
