### ISSUE TITLE
[虫子]：Installation error

### ISSUE THREAD

**Issue by Mrwangzh2022** [PlayCover/PlayCover#985]
### Describe the bug

![Uploading WX20230605-154532@2x.p
![WX20230605-154551@2x](https://github.com/PlayCover/PlayCover/assets/111833329/976b497d-335a-4fbd-a3da-020bed31af84)
ng…]()

### Steps to reproduce

Fail to install correctly

### Expected behaviour

Fail to install correctly

### What version of PlayCover are you using?

Nightly/beta

### What version of macOS are you using?

Monterey (macOS 12)

### Issue Language

- [X] Yes my issue is written in English

**Comment by Mrwangzh2022** [comment]
您无法打开应用程序“PlayCover”，因为这台Mac不支持此应用程序。

**Comment by ohaiibuzzle** [comment]
Your Mac is not an M1 or M2 based device and thus not supported.

**Comment by Mrwangzh2022** [comment]
好的 知道了  非常感谢
