### ISSUE TITLE
[Bug]: PlayCover 3.0.0 is described as Beta but marked as latest (stable) release

### ISSUE THREAD

**Issue by suschizu** [PlayCover/PlayCover#988]
### Describe the bug

it's a bit confusing … is version 3.0.0 a beta release or a stable release?

### Steps to reproduce

download 3.0.0 

### Expected behaviour

to be stable

### What version of PlayCover are you using?

2.0.4

### What version of macOS are you using?

Monterey (macOS 12)

### Issue Language

- [X] Yes my issue is written in English

**Comment by JoseMoreville** [comment]
It's beta not stable, it was marked as release since there will be users who won't find it otherwise
