### ISSUE TITLE
[Question] Geshin Impact doesn't support 120hz natively?

### ISSUE THREAD

**Issue by HuayuZhangJager** [PlayCover/PlayCover#99]
Hey~ Thanks for your wonderful works!

I can see the 120hz can be enabled in the App settings inside Playcover. However, the Geshin Impact doesn't support 120hz like Ipad Pro inside the 'game graphic settings'.

Do we have any chance make improvement of it?

**Comment by ohaiibuzzle** [comment]
It might be checking the iPad Model Identifier which as of now is hardcoded to the iPad8,6 which is the iPad 8th Gen, due to reports of graphics being blurry. Someone is working on a patch to allow the identifier to be swapped per-app which may solve the issue

**Comment by Depal1** [comment]
The game won't show an option to toggle 120Hz, but the game does output it with the current model identifier.
