### ISSUE TITLE
[Bug]: When I install 3.0 beta and restart my Mac, the version of my App changes to 2.0.5

### ISSUE THREAD

**Issue by Lucas04-nhr** [PlayCover/PlayCover#990]
### Describe the bug

Just as the title:
When I install 3.0 beta and restart my Mac, the version of my App changes to 2.0.5
And all of the games cannot open as usual. They jumps in the dock for a few times and then quit.

### Steps to reproduce

Upgrade the app via the dmg file downloaded in the release, and then restart the Mac.

### Expected behaviour

The app downgraded to version 2.0.5

### What version of PlayCover are you using?

Nightly/beta

### What version of macOS are you using?

Ventura (macOS 13)

### Issue Language

- [X] Yes my issue is written in English

**Comment by Lucas04-nhr** [comment]
Here's the error reported by the system:
[Genshin Impact.txt](https://github.com/PlayCover/PlayCover/files/11685346/Genshin.Impact.txt)
[Honkai Star Rail.txt](https://github.com/PlayCover/PlayCover/files/11685354/Honkai.Star.Rail.txt)

**Comment by Lucas04-nhr** [comment]
The only way to fix this issue now is reinstall the PlayCover app.

**Comment by Lucas04-nhr** [comment]
I've found the reason why this bug appears:
It's because I've opened the "Automatically Update", and the default newest version of PlayCover is 2.0.5. So the app itself downloaded ver. 2.0.5 and "upgrade" my app.

**Comment by JoseMoreville** [comment]
We didn't update the sparkle version since this is technically not a stable release but a beta release, 3.0.0 is not released yet.
