### ISSUE TITLE
[Bug]: Crash on macOS 14 when dragging game window across monitors (Honkai: Star Rail)

### ISSUE THREAD

**Issue by AnotiaWang** [PlayCover/PlayCover#995]
### Describe the bug

As the title says, I experienced crashes when I was trying to drag my game window from my MacBook's internal display to external display.

PlayCover version: 3.0.0 Beta
macOS version: 14 (developer preview)
Device: MacBook Air M2

### Steps to reproduce

1. Open the game from PlayCover
2. Drag the game window to another monitor

> I was only able to reproduce this issue twice, then it became normal

### Expected behaviour

Window should be dragged to another display without crashing.

### Crash log

The log was too long to submit, so I pasted it to Pastebin: https://pastebin.com/AQa8X3wB

### What version of PlayCover are you using?

Nightly/beta

### What version of macOS are you using?

macOS beta (please state the specific version)

### Issue Language

- [X] Yes my issue is written in English

**Comment by AnotiaWang** [comment]
Somehow managed to repro this issue again: https://pastebin.com/kfKx9TrQ

**Comment by TheMoonThatRises** [comment]
Unable to reproduce on latest MacOS beta.
