### ISSUE TITLE
[Feature]: Microphone Support in PlayCover.

### ISSUE THREAD

**Issue by ajstars1** [PlayCover/PlayCover#996]
###  I'm not able to use a Microphone in PUBG
While I'm playing **BGMI / PUBG** with the help of **Playcover**, I can't use my microphone to connect with other players. When I tried to unmute myself in Pubg / BGMI it showed me the error _Correct permissions required._ 

### Microphone support in Playcover 
**I love to have Microphone support in Playcover and that makes it a complete gaming setup for us. ❤️**

<img width="1440" alt="Screenshot 2023-06-11 at 10 00 32 PM" src="https://github.com/PlayCover/PlayCover/assets/53529358/df1c0711-54f8-4503-8444-60d87a3af43f">

### Issue Language

- [X] Yes my issue is written in English

**Comment by TheMoonThatRises** [comment]
Closing in favour of #385.

**Comment by difkye247** [comment]
I also wish it could support the microphone. It's October 2025, and it still doesn't support the microphone.

**Comment by viatearz** [comment]
> I also wish it could support the microphone. It's October 2025, and it still doesn't support the microphone.

Most apps should already support the microphone.
If it doesn’t work on your side, you can open a new issue.

**Comment by Jatinsaini90500** [comment]
> I also wish it could support the microphone. It's October 2025, and it still doesn't support the microphone.

it support microphone, you remember we have to disable our system integrity security when installing playcover 
csrutil disable......you just have to re-enable it by crustil enable and then microphone can be used in pubg mobile playcover
